/* ============================================================
   FILE: 13_intelligence_query_engine.js
   IDE-170 Intelligence Platform
   Release: Version Manifest / Module: Version Manifest
   Phase 7: Evidence-Grounded Query Engine with Confidence and Independent Validation
   Architecture Decision: IDE-170-007 / IDE-170-008
   ============================================================ */
(function (global) {
  "use strict";
  const namespace=global.IDE170Intelligence, VERSION_MANIFEST=global.IDE170VersionManifest;
  if(!namespace||!namespace.__internal||!VERSION_MANIFEST)return;
  const internal=namespace.__internal,state=internal.state;
  const MODULE_VERSION=VERSION_MANIFEST.getModuleVersion("queryEngine");
  const RELEASE_VERSION=VERSION_MANIFEST.release.version;
  const CAPABILITY_ID="IDE-170-QUERY-ENGINE";
  const CAPABILITY_VERSION=VERSION_MANIFEST.getCapabilityVersion(CAPABILITY_ID);
  const INTERNAL_MINIMUM_VERSION=VERSION_MANIFEST.compatibility.minimumInternalCapabilityVersion;
  const schemaVersion=VERSION_MANIFEST.getSchemaVersion, artifactVersion=VERSION_MANIFEST.getArtifactVersion, datasetVersion=VERSION_MANIFEST.getDatasetVersion;
  const DATASET_ID="IDE-170-DATASET-PHASE6-QUERY-EXPLANATION";
  if(!(state.queryResults instanceof Map))state.queryResults=new Map();
  if(!(state.explainableEnvelopes instanceof Map))state.explainableEnvelopes=new Map();
  if(!Object.prototype.hasOwnProperty.call(state,"latestQueryResultId"))state.latestQueryResultId=null;
  if(!Object.prototype.hasOwnProperty.call(state,"latestExplainableEnvelopeId"))state.latestExplainableEnvelopeId=null;
  if(!Object.prototype.hasOwnProperty.call(state,"lastQueryValidation"))state.lastQueryValidation=null;

  function recordsOf(snapshot){return internal.asArray(snapshot&&snapshot.records);}
  function getRecord(snapshot,id){return recordsOf(snapshot).find(function(r){return r&&r.identity&&r.identity.canonicalId===id;})||null;}
  function latestContext(options){
    const o=internal.isPlainObject(options)?options:{};
    const canonical=o.canonicalSnapshot || (o.snapshotId&&namespace.getCanonicalSnapshot&&namespace.getCanonicalSnapshot(o.snapshotId)) || (state.latestCanonicalSnapshotId&&namespace.getCanonicalSnapshot&&namespace.getCanonicalSnapshot(state.latestCanonicalSnapshotId)) || null;
    const graph=o.graph || (o.graphId&&namespace.getEvidenceGraph&&namespace.getEvidenceGraph(o.graphId)) || (state.latestEvidenceGraphSnapshotId&&namespace.getEvidenceGraph&&namespace.getEvidenceGraph(state.latestEvidenceGraphSnapshotId)) || null;
    const repo=o.repositorySnapshot || (o.repositorySnapshotId&&namespace.getRepositorySnapshot&&namespace.getRepositorySnapshot(o.repositorySnapshotId)) || (state.latestRepositorySnapshotId&&namespace.getRepositorySnapshot&&namespace.getRepositorySnapshot(state.latestRepositorySnapshotId)) || null;
    const understanding=o.understanding || (o.understandingId&&namespace.getUnderstandingResult&&namespace.getUnderstandingResult(o.understandingId)) || (state.latestUnderstandingResultId&&namespace.getUnderstandingResult&&namespace.getUnderstandingResult(state.latestUnderstandingResultId)) || null;
    return {canonicalSnapshot:canonical,graph:graph,repositorySnapshot:repo,understanding:understanding,records:o.records||recordsOf(canonical)};
  }
  function sourceRef(record){const s=record&&record.source||{};return{sourceType:s.sourceType||"",sourceId:s.sourceId||"",sourceVersion:s.sourceVersion||"",adapterId:s.adapterId||"",sourceRecordId:s.sourceRecordId||""};}
  function recordFact(record,context){return{resultClass:"fact",canonicalId:record.identity.canonicalId,recordType:record.recordType,name:record.identity.name||record.identity.qualifiedName||record.identity.canonicalId,statement:(record.identity.name||record.identity.canonicalId)+" is present in the selected Canonical Snapshot.",sourceReference:sourceRef(record),snapshotReference:context.canonicalSnapshot&&context.canonicalSnapshot.snapshotId||"",evidenceReference:record.recordId||""};}
  function edgeFact(edge,context){return{resultClass:"fact",relationshipType:edge.relationshipType,source:edge.sourceNode,target:edge.targetNode,layer:edge.layer||"fact",graphReference:context.graph&&context.graph.graphId||"",evidenceReferences:internal.asArray(edge.evidence).map(function(x){return x.evidenceId;})};}
  function evidenceFromEdge(graph,edge){const idx=graph&&graph.evidenceIndex||{};return internal.asArray(edge&&edge.evidence).map(function(x){return idx[x.evidenceId]||x;}).filter(Boolean);}
  function relevantEdges(graph,targetId,direction,types,includeCandidates){
    const allowed=new Set(types||[]),edges=internal.asArray(graph&&graph.factEdges).concat(includeCandidates?internal.asArray(graph&&graph.candidateEdges):[]);
    return edges.filter(function(e){if(allowed.size&&!allowed.has(e.relationshipType))return false;if(direction==="incoming")return e.targetNode&&e.targetNode.canonicalId===targetId;if(direction==="outgoing")return e.sourceNode&&e.sourceNode.canonicalId===targetId;return(e.sourceNode&&e.sourceNode.canonicalId===targetId)||(e.targetNode&&e.targetNode.canonicalId===targetId);});
  }
  function sourceCoverageLimitations(query,context){
    const coverage=context.understanding&&context.understanding.scope&&context.understanding.scope.sourceCoverage;
    const limitations=[],missing=internal.asArray(coverage&&coverage.missingSources);
    const functionSensitive=["member-list","dependency-analysis","reverse-dependency-analysis","entity-search"].includes(query.queryType)||(query.target&&query.target.recordType==="function");
    const moduleSensitive=(query.target&&query.target.recordType==="module")||["dependency-analysis","reverse-dependency-analysis","relationship-path","relationship-search"].includes(query.queryType);
    const workflowSensitive=/workflow|decision|approval|execution|rollback|deployment/.test(query.queryType);
    if(query.queryType==="missing-information-search"){
      limitations.push.apply(limitations,internal.asArray(coverage&&coverage.limitations));
      limitations.push.apply(limitations,internal.asArray(context.understanding&&context.understanding.quality&&context.understanding.quality.warnings));
    }
    if(functionSensitive&&missing.includes("IDE-170-ADAPTER-FUNCTION"))limitations.push("Function Adapter is Partial; absence of Function results must not be interpreted as proof of non-existence.");
    if(moduleSensitive&&missing.includes("IDE-170-ADAPTER-MODULE"))limitations.push("Module Adapter is Partial; absence of Module relationships must not be interpreted as proof of non-existence.");
    if(["dependency-analysis","reverse-dependency-analysis"].includes(query.queryType)&&query.target&&query.target.recordType==="function")limitations.push("Dynamic references, string-based invocation, generated code and external entry points may not be fully represented by static relationship evidence.");
    if(workflowSensitive&&(!context.understanding||internal.asArray(context.understanding.facts).every(function(x){return !/workflow/i.test(JSON.stringify(x));})))limitations.push("Workflow evidence is unavailable or incomplete in the selected Understanding Result.");
    return internal.unique(limitations);
  }

  function executeEntityQuery(query,context){const r=query.target&&getRecord(context.canonicalSnapshot,query.target.canonicalId);if(!r)return{facts:[],derived:[],insights:[],paths:[],evidence:[],missing:["Resolved target is not present in the selected Canonical Snapshot."],summary:"対象Entityを現在のSnapshotで確認できませんでした。"};return{facts:[recordFact(r,context)],derived:[],insights:[],paths:[],evidence:[],missing:[],summary:(r.identity.name||r.identity.canonicalId)+" をCanonical Factとして確認しました。"};}
  function executeMemberList(query,context){const edges=relevantEdges(context.graph,query.target.canonicalId,"outgoing",["defines","contains"],query.scope.includeCandidates);return{facts:edges.map(function(e){return edgeFact(e,context);}),derived:[],insights:[],paths:edges.map(function(e){return{relationshipType:e.relationshipType,sourceCanonicalId:e.sourceNode.canonicalId,targetCanonicalId:e.targetNode.canonicalId};}),evidence:edges.reduce(function(a,e){return a.concat(evidenceFromEdge(context.graph,e));},[]),missing:[],summary:edges.length?edges.length+"件の所属Entityを確認しました。":"所属Entityは現在のEvidenceでは確認できませんでした。"};}
  function executeDependency(query,context,reverse){const types=["calls","depends-on","references","imports","consumes-interface","depends-on-component"],direction=reverse?"incoming":"outgoing",edges=relevantEdges(context.graph,query.target.canonicalId,direction,types,query.scope.includeCandidates);return{facts:edges.map(function(e){return edgeFact(e,context);}),derived:[],insights:[],paths:edges.map(function(e){return{relationshipType:e.relationshipType,sourceCanonicalId:e.sourceNode.canonicalId,targetCanonicalId:e.targetNode.canonicalId,direction:direction};}),evidence:edges.reduce(function(a,e){return a.concat(evidenceFromEdge(context.graph,e));},[]),missing:[],summary:edges.length?(reverse?"逆依存":"依存")+"を"+edges.length+"件確認しました。":"現在のEvidenceでは対象Relationshipを確認できませんでした。"};}
  function executeEntitySearch(query,context){const q=query.normalizedInput.toLowerCase().replace(/似た名前の|検索して|探して|関数|ファイル|モジュール/g," ").trim();const found=recordsOf(context.canonicalSnapshot).filter(function(r){const i=r.identity||{};return q&&[i.name,i.qualifiedName].concat(i.aliases||[]).some(function(v){return String(v||"").toLowerCase().includes(q);});}).slice(0,50);return{facts:found.map(function(r){return recordFact(r,context);}),derived:[],insights:[],paths:[],evidence:[],missing:[],summary:found.length+"件の候補をCanonical Snapshotから取得しました。"};}
  function executeSnapshot(query,context){const repo=context.repositorySnapshot;if(!repo)return{facts:[],derived:[],insights:[],paths:[],evidence:[],missing:["Repository Snapshot is unavailable."],summary:"Repository Snapshotを確認できませんでした。"};const changes=internal.asArray(repo.changes||repo.changeRecords||repo.state&&repo.state.changes);return{facts:changes.map(function(c){return{resultClass:"fact",changeType:c.changeType||c.type||"Unknown",canonicalId:c.canonicalId||c.recordId||"",change:c,repositorySnapshotId:repo.snapshotId||""};}),derived:[],insights:[],paths:[],evidence:[],missing:[],summary:changes.length+"件のSnapshot Changeを確認しました。"};}
  function executeUnderstandingTrace(query,context,regex){const u=context.understanding;if(!u)return{facts:[],derived:[],insights:[],paths:[],evidence:[],missing:["Understanding Result is unavailable."],summary:"Understanding Resultを確認できませんでした。"};const facts=internal.asArray(u.facts).filter(function(x){return regex.test(JSON.stringify(x));});const derived=internal.asArray(u.derivedResults).filter(function(x){return regex.test(JSON.stringify(x));});const insights=internal.asArray(u.insights).filter(function(x){return regex.test(JSON.stringify(x));});return{facts:facts,derived:derived,insights:insights,paths:[],evidence:internal.asArray(u.evidence).filter(function(x){return regex.test(JSON.stringify(x));}),missing:[],summary:(facts.length+derived.length+insights.length)+"件のUnderstanding Traceを確認しました。"};}
  function executeEvidence(query,context){const edges=relevantEdges(context.graph,query.target.canonicalId,"both",[],query.scope.includeCandidates);return{facts:edges.map(function(e){return edgeFact(e,context);}),derived:[],insights:[],paths:edges.map(function(e){return{relationshipType:e.relationshipType,sourceCanonicalId:e.sourceNode.canonicalId,targetCanonicalId:e.targetNode.canonicalId};}),evidence:edges.reduce(function(a,e){return a.concat(evidenceFromEdge(context.graph,e));},[]),missing:[],summary:edges.length?"対象Entityに紐づくEvidenceを取得しました。":"対象EntityのEvidence Relationshipを確認できませんでした。"};}
  function executeByType(query,context){switch(query.queryType){case"entity-lookup":case"entity-summary":return executeEntityQuery(query,context);case"entity-search":return executeEntitySearch(query,context);case"member-list":case"ownership-trace":return executeMemberList(query,context);case"dependency-analysis":return executeDependency(query,context,false);case"reverse-dependency-analysis":return executeDependency(query,context,true);case"relationship-path":case"relationship-search":return executeEvidence(query,context);case"change-analysis":case"snapshot-diff":case"change-history":return executeSnapshot(query,context);case"workflow-trace":return executeUnderstandingTrace(query,context,/workflow|change|completion/i);case"decision-trace":return executeUnderstandingTrace(query,context,/decision/i);case"approval-trace":return executeUnderstandingTrace(query,context,/approval/i);case"execution-trace":return executeUnderstandingTrace(query,context,/execution/i);case"rollback-trace":return executeUnderstandingTrace(query,context,/rollback/i);case"deployment-trace":return executeUnderstandingTrace(query,context,/deployment/i);case"validation-trace":return executeUnderstandingTrace(query,context,/validation|test|failure|failed/i);case"diagnostic-trace":return executeUnderstandingTrace(query,context,/diagnostic/i);case"evidence-trace":case"explanation-request":return executeEvidence(query,context);case"insight-search":return{facts:[],derived:[],insights:internal.asArray(context.understanding&&context.understanding.insights),paths:[],evidence:internal.asArray(context.understanding&&context.understanding.evidence),missing:[],summary:"Insight Candidateを取得しました。"};case"missing-information-search":return{facts:[],derived:[],insights:[],paths:[],evidence:[],missing:sourceCoverageLimitations(query,context),summary:"現在明示されている不足情報を返します。"};default:return{facts:[],derived:[],insights:[],paths:[],evidence:[],missing:["Query Type is registered but execution is not implemented in Phase 6."],summary:"このQuery TypeはPhase 6実行対象外です。"};}}

  function validateExplainableEnvelope(e){const errors=[];if(!e||typeof e!=="object")errors.push("Envelope missing");else{if(!e.queryId)errors.push("queryId missing");if(!Array.isArray(e.factResults)||!Array.isArray(e.derivedResults)||!Array.isArray(e.insightCandidates))errors.push("Result classes not separated");if(!e.explanation||!Array.isArray(e.explanation.limitations)||!Array.isArray(e.explanation.missingInformation))errors.push("Explanation incomplete");if(!e.policy||e.policy.repositoryMutationAllowed!==false||e.policy.candidateFactPromotionAllowed!==false||e.policy.missingInformationInferenceAllowed!==false)errors.push("Policy boundary invalid");if(!e.interpretationConfidence||!Object.prototype.hasOwnProperty.call(e.interpretationConfidence,"score"))errors.push("Interpretation Confidence missing");if(!e.confidence||!e.confidence.modelId||e.confidence.deferredToPhase7===true)errors.push("Phase 7 Confidence missing");if(!e.quality||!e.quality.dimensions)errors.push("Quality assessment missing");if(!e.integrity||!e.integrity.payloadHash)errors.push("Integrity payload Hash missing");}return{valid:errors.length===0,status:errors.length?"Invalid":"Valid",errors:errors,validatedAt:internal.nowIso()};}
  function executeQuery(queryOrInput,options){
    const settings=internal.isPlainObject(options)?options:{};
    let query=queryOrInput;
    if(typeof queryOrInput==="string"){const interpreted=namespace.interpretQuery(queryOrInput,settings);if(!interpreted.ok)return interpreted;query=interpreted.data.query;}
    else if(query&&query.queryId&&namespace.validateTypedQuery&&!namespace.validateTypedQuery(query).valid)return internal.buildResult(false,"QUERY_INVALID","Invalid",{query:query});
    if(!query||!query.queryType)return internal.buildResult(false,"QUERY_REQUIRED","Invalid",null,{error:{message:"Typed Query is required.",category:"Validation Failure"}});
    const context=latestContext(settings);
    if(!context.canonicalSnapshot)return internal.buildResult(false,"QUERY_SNAPSHOT_UNAVAILABLE","Blocked",{query:query},{error:{message:"Canonical Snapshot is unavailable.",category:"Source Failure"}});
    const execution=executeByType(query,context);
    const limitations=internal.unique(sourceCoverageLimitations(query,context).concat(internal.asArray(execution.missing)));
    const evidence=internal.asArray(execution.evidence);
    const requiredEvidence=query.requirements&&query.requirements.evidenceRequired!==false;
    const evidenceInsufficient=requiredEvidence && ["dependency-analysis","reverse-dependency-analysis","relationship-path","relationship-search","evidence-trace","explanation-request"].includes(query.queryType) && evidence.length===0 && internal.asArray(execution.facts).length===0;
    if(evidenceInsufficient)limitations.push("Required Evidence was not found for this Query in the selected scope.");
    const initialStatus=limitations.length?"Partial":"Completed";
    const now=internal.nowIso();
    const rulesApplied=internal.unique(internal.asArray(execution.derived).map(function(x){return x&&x.ruleId;}).concat(internal.asArray(execution.insights).reduce(function(a,x){return a.concat(internal.asArray(x&&x.generatedBy&&x.generatedBy.ruleIds));},[])));
    const reasoningEngines=internal.unique(internal.asArray(execution.insights).reduce(function(a,x){return a.concat(internal.asArray(x&&x.generatedBy&&x.generatedBy.engineIds));},[]));
    const envelope={envelopeId:internal.nextId("IDE-170-ANSWER"),artifactVersion:artifactVersion("explainableInsightEnvelope"),schemaVersion:schemaVersion("IDE-170-SCHEMA-EXPLAINABLE-INSIGHT-ENVELOPE"),queryId:query.queryId,queryType:query.queryType,status:initialStatus,answerSummary:{statement:execution.summary,answerType:"evidence-grounded"},factResults:internal.clone(execution.facts||[]),derivedResults:internal.clone(execution.derived||[]),insightCandidates:internal.clone(execution.insights||[]),evidence:internal.clone(evidence),relationshipPaths:internal.clone(execution.paths||[]),interpretationConfidence:null,confidence:null,quality:null,explanation:{summary:execution.summary,evidenceUsed:evidence.map(function(x){return x.evidenceId||x.recordId||"";}).filter(Boolean),relationshipPaths:internal.clone(execution.paths||[]),rulesApplied:rulesApplied,enginesUsed:internal.unique([CAPABILITY_ID].concat(reasoningEngines)),limitations:internal.unique(limitations),missingInformation:internal.unique(limitations),alternativeInterpretations:internal.asArray(query.interpretation&&query.interpretation.alternativeIntents)},scope:internal.clone(query.scope),snapshotReference:{canonicalSnapshotId:context.canonicalSnapshot&&context.canonicalSnapshot.snapshotId||"",repositorySnapshotId:context.repositorySnapshot&&context.repositorySnapshot.snapshotId||"",evidenceGraphId:context.graph&&context.graph.graphId||"",understandingId:context.understanding&&context.understanding.understandingId||""},validation:{status:"Validating"},policy:{repositoryMutationAllowed:false,workflowExecutionAllowed:false,candidateFactPromotionAllowed:false,missingInformationInferenceAllowed:false,naturalLanguageDirectReasoningAllowed:false},integrity:null,createdAt:now,frozenAt:null,immutable:false};

    if(settings.phase6Compatibility===true){
      envelope.interpretationConfidence={score:null,level:"Not Assessable",deferredToPhase7:true,explanation:"Historical Phase 6 compatibility validation."};
      envelope.confidence={score:null,level:"Not Assessable",method:null,deferredToPhase7:true,explanation:"Multi-Factor Confidence is implemented in Phase 7."};
      envelope.quality={dimensions:{},overall:null,deferredToPhase7:true};
      envelope.integrity={algorithm:"SHA-256",payloadHash:"phase6-compatibility",generatedAt:internal.nowIso()};
      envelope.validation={valid:true,status:"Valid",errors:[],phase6Compatibility:true,validatedAt:internal.nowIso()};
      envelope.frozenAt=internal.nowIso();envelope.immutable=true;
    }else{
      if(typeof namespace.assessInterpretationConfidence!=="function"||typeof namespace.assessConfidence!=="function"||typeof namespace.assessQuality!=="function"||typeof namespace.validateIntelligenceResult!=="function"||typeof namespace.computeIntelligencePayloadHash!=="function")return internal.buildResult(false,"QUERY_PHASE7_DEPENDENCY_MISSING","Blocked",{query:query,envelope:envelope},{error:{message:"Phase 7 Confidence/Validation APIs are unavailable.",category:"Dependency Failure"}});
      envelope.interpretationConfidence=namespace.assessInterpretationConfidence(query);
      envelope.confidence=namespace.assessConfidence(envelope,{query:query,context:context,sourceCoverage:context.understanding&&context.understanding.scope&&context.understanding.scope.sourceCoverage,reasoningEngineIds:reasoningEngines,partialSnapshot:Boolean(context.understanding&&context.understanding.quality&&context.understanding.quality.partialScope===true)});
      envelope.quality=namespace.assessQuality(envelope,{confidence:envelope.confidence,context:context});
      envelope.integrity={algorithm:"SHA-256",payloadHash:null,generatedAt:internal.nowIso()};
      envelope.integrity.payloadHash=namespace.computeIntelligencePayloadHash(envelope);
      const structural=validateExplainableEnvelope(envelope);if(!structural.valid)return internal.buildResult(false,"QUERY_ENVELOPE_INVALID","Invalid",{query:query,envelope:envelope},{error:{message:structural.errors.join("; "),category:"Validation Failure"}});
      const independent=namespace.validateIntelligenceResult(envelope,{query:query,context:context,schemaId:"IDE-170-SCHEMA-EXPLAINABLE-INSIGHT-ENVELOPE",targetType:"query-envelope",currentStateRequired:!/history|previous|前回/.test(String(query.queryType)+" "+String(query.normalizedInput||""))});
      envelope.validation=independent;
      if(!independent.gate||independent.gate.allowed!==true)return internal.buildResult(false,"QUERY_INDEPENDENT_VALIDATION_BLOCKED",independent.status,{query:query,envelope:envelope},{warnings:limitations,error:{message:independent.gate&&independent.gate.reason||"Independent Validation Gate blocked the Result.",category:"Validation Failure"}});
      envelope.status=independent.gate.status==="Conditionally Allowed"||limitations.length?"Partial":"Completed";
      envelope.frozenAt=internal.nowIso();envelope.immutable=true;
      if(typeof namespace.validateFrozenIntelligenceResult==="function"){const frozenCheck=namespace.validateFrozenIntelligenceResult(envelope);if(!frozenCheck.valid)return internal.buildResult(false,"QUERY_FREEZE_VALIDATION_FAILED","Invalid",{query:query,envelope:envelope,frozenValidation:frozenCheck},{error:{message:"Frozen Result validation failed.",category:"Integrity Failure"}});}
    }
    const status=envelope.status;
    const queryResult={queryResultId:internal.nextId("IDE-170-QUERY-RESULT"),artifactVersion:artifactVersion("queryResult"),schemaVersion:schemaVersion("IDE-170-SCHEMA-QUERY-RESULT"),queryId:query.queryId,queryType:query.queryType,status:status,envelopeId:envelope.envelopeId,counts:{facts:envelope.factResults.length,derived:envelope.derivedResults.length,insights:envelope.insightCandidates.length,evidence:envelope.evidence.length,limitations:envelope.explanation.limitations.length},confidenceLevel:envelope.confidence&&envelope.confidence.level||"Not Assessable",validationGate:envelope.validation&&envelope.validation.gate&&envelope.validation.gate.status||envelope.validation&&envelope.validation.status||"Valid",createdAt:now,frozenAt:internal.nowIso(),immutable:true};
    const fe=internal.deepFreeze(internal.clone(envelope)),fr=internal.deepFreeze(internal.clone(queryResult));state.explainableEnvelopes.set(envelope.envelopeId,fe);state.queryResults.set(queryResult.queryResultId,fr);state.latestExplainableEnvelopeId=envelope.envelopeId;state.latestQueryResultId=queryResult.queryResultId;internal.touch();
    return internal.buildResult(true,"QUERY_EXECUTED",status,{query:internal.clone(query),queryResult:internal.clone(fr),envelope:internal.clone(fe)},{warnings:limitations});
  }

  function getQueryResult(id){return internal.clone(state.queryResults.get(internal.text(id,""))||null);}function listQueryResults(){return[...state.queryResults.values()].map(internal.clone);}function getExplainableEnvelope(id){return internal.clone(state.explainableEnvelopes.get(internal.text(id,""))||null);}function getInsight(id){for(const e of state.explainableEnvelopes.values()){const x=internal.asArray(e.insightCandidates).find(function(i){return i&&i.insightId===id;});if(x)return internal.clone(x);}return null;}

  function buildPhase6Fixture(){
    const records=[
      {recordId:"R-PROJECT",recordType:"project",identity:{canonicalId:"project:ai-prompt-os",name:"AI Prompt OS",qualifiedName:"AI Prompt OS",aliases:["AIプロンプト生成Pro"]},classification:{domain:"repository"},source:{sourceType:"fixture",sourceId:"project",sourceVersion:"1.0.0",adapterId:"IDE-170-ADAPTER-PROJECT",sourceRecordId:"P1"},payload:{}},
      {recordId:"R-FILE",recordType:"file",identity:{canonicalId:"file:02_prompt.js",name:"02_prompt.js",qualifiedName:"02_prompt.js",aliases:[]},classification:{domain:"repository"},source:{sourceType:"fixture",sourceId:"02_prompt.js",sourceVersion:"1.0.0",adapterId:"IDE-170-ADAPTER-REPOSITORY",sourceRecordId:"F1"},payload:{}},
      {recordId:"R-FUNC1",recordType:"function",identity:{canonicalId:"function:02_prompt.js::buildPrompt",name:"buildPrompt",qualifiedName:"02_prompt.js::buildPrompt",aliases:[]},classification:{domain:"repository"},source:{sourceType:"fixture",sourceId:"buildPrompt",sourceVersion:"1.0.0",adapterId:"IDE-170-ADAPTER-FUNCTION",sourceRecordId:"FN1"},payload:{}},
      {recordId:"R-FUNC2",recordType:"function",identity:{canonicalId:"function:04_tools.js::callBuildPrompt",name:"callBuildPrompt",qualifiedName:"04_tools.js::callBuildPrompt",aliases:[]},classification:{domain:"repository"},source:{sourceType:"fixture",sourceId:"callBuildPrompt",sourceVersion:"1.0.0",adapterId:"IDE-170-ADAPTER-FUNCTION",sourceRecordId:"FN2"},payload:{}},
      {recordId:"R-IDE170",recordType:"module",identity:{canonicalId:"module:IDE-170",name:"IDE-170",qualifiedName:"IDE-170 Intelligence Platform",aliases:["IDE170"]},classification:{domain:"architecture"},source:{sourceType:"fixture",sourceId:"IDE-170",sourceVersion:RELEASE_VERSION,adapterId:"IDE-170-ADAPTER-MODULE",sourceRecordId:"M1"},payload:{status:"Ready"}}
    ];
    const evidence={"E-DEFINES":{evidenceId:"E-DEFINES",evidenceType:"source-reference",strength:"direct",recordId:"R-FUNC1"},"E-CALLS":{evidenceId:"E-CALLS",evidenceType:"source-reference",strength:"direct",recordId:"R-FUNC2"}};
    const graph={graphId:"IDE-170-PHASE6-FIXTURE-GRAPH",status:"Frozen",nodes:records.map(function(r){return{canonicalId:r.identity.canonicalId,recordType:r.recordType,name:r.identity.name,qualifiedName:r.identity.qualifiedName};}),factEdges:[{relationshipType:"defines",layer:"fact",sourceNode:{canonicalId:"file:02_prompt.js",recordType:"file"},targetNode:{canonicalId:"function:02_prompt.js::buildPrompt",recordType:"function"},evidence:[{evidenceId:"E-DEFINES"}]},{relationshipType:"calls",layer:"fact",sourceNode:{canonicalId:"function:04_tools.js::callBuildPrompt",recordType:"function"},targetNode:{canonicalId:"function:02_prompt.js::buildPrompt",recordType:"function"},evidence:[{evidenceId:"E-CALLS"}]}],candidateEdges:[],evidenceIndex:evidence};
    const canonicalSnapshot={snapshotId:"IDE-170-PHASE6-FIXTURE-SNAPSHOT",status:"Frozen",records:records,summary:{recordCount:records.length}};
    const repositorySnapshot={snapshotId:"IDE-170-PHASE6-FIXTURE-REPOSITORY",snapshotType:"baseline",status:"Frozen",changes:[]};
    const understanding={understandingId:"IDE-170-PHASE6-FIXTURE-UNDERSTANDING",status:"Frozen",facts:[],derivedResults:[],insights:[],evidence:[],scope:{sourceCoverage:{status:"Ready",missingSources:[],limitations:[]}}};
    return{canonicalSnapshot:canonicalSnapshot,graph:graph,repositorySnapshot:repositorySnapshot,understanding:understanding,records:records,phase6Compatibility:true};
  }

  function runQueryPhaseValidation(options){
    const settings=internal.isPlainObject(options)?options:{},fixture=buildPhase6Fixture(),checks=[];function check(name,passed,detail,group,severity){checks.push({name:name,passed:passed===true,detail:internal.clone(detail),group:group||"Phase 6",severity:severity||"High"});}
    try{
      const normalization=namespace.normalizeJapaneseQuery("ＩＤＥ１７０ の 状態");check("NFKC / IDE notation normalization",normalization.includes("IDE-170"),normalization,"Japanese Normalization");
      const q1=namespace.interpretQuery("buildPromptを呼び出している関数は？",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records,graphId:fixture.graph.graphId});check("Reverse dependency intent",q1.ok&&q1.data.query.queryType==="reverse-dependency-analysis",q1.data&&q1.data.query&&q1.data.query.queryType,"Intent");check("Function entity resolution",q1.ok&&q1.data.query.target.canonicalId==="function:02_prompt.js::buildPrompt",q1.data&&q1.data.query&&q1.data.query.target,"Entity Resolution");
      const q2=namespace.interpretQuery("02_prompt.jsの関数一覧",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});check("Member list intent",q2.ok&&q2.data.query.queryType==="member-list",q2.data&&q2.data.query&&q2.data.query.queryType,"Intent");
      const q3=namespace.interpretQuery("IDE１７０の状態",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});check("Full-width IDE entity normalization",q3.ok&&q3.data.query.queryType==="entity-summary"&&q3.data.query.target.canonicalId==="module:IDE-170",q3.data&&q3.data.query&&q3.data.query.target,"Normalization");
      const duplicateModule={recordId:"R-MODULE-FILE",recordType:"module",identity:{canonicalId:"module:02_prompt.js",name:"02_prompt.js",qualifiedName:"02_prompt.js",aliases:[]},classification:{domain:"repository"},source:{sourceType:"fixture",sourceId:"02_prompt.js",sourceVersion:RELEASE_VERSION,adapterId:"IDE-170-ADAPTER-MODULE",sourceRecordId:"M-FILE"},payload:{}};
      const duplicateRecords=fixture.records.concat([duplicateModule]);
      const duplicateSnapshot=Object.assign({},fixture.canonicalSnapshot,{records:duplicateRecords,summary:{recordCount:duplicateRecords.length}});
      const exactFile=namespace.interpretQuery("02_prompt.jsとは？",{canonicalSnapshot:duplicateSnapshot,records:duplicateRecords});check("Exact file name resolves File across File/Module duplicate",exactFile.ok&&exactFile.data.query.target.recordType==="file"&&exactFile.data.query.target.canonicalId==="file:02_prompt.js",exactFile.data&&exactFile.data.query&&exactFile.data.query.target,"Entity Resolution","Critical");
      const exactMember=namespace.interpretQuery("02_prompt.jsの関数一覧",{canonicalSnapshot:duplicateSnapshot,records:duplicateRecords});check("Member list resolves File across File/Module duplicate",exactMember.ok&&exactMember.data.query.target.recordType==="file"&&exactMember.data.query.target.canonicalId==="file:02_prompt.js",exactMember.data&&exactMember.data.query&&exactMember.data.query.target,"Entity Resolution","Critical");
      const q4=namespace.interpretQuery("これに関係するファイル",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});check("Unresolved pronoun does not silently resolve",q4.ok===false&&q4.status==="Needs Resolution",{ok:q4.ok,status:q4.status,code:q4.code},"Ambiguity","Critical");
      const q5=namespace.interpretQuery("この関数は使われている？",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records,contextTarget:{canonicalId:"function:02_prompt.js::buildPrompt",recordType:"function",name:"buildPrompt"}});check("Conversation context can resolve explicit pronoun",q5.data&&q5.data.query&&q5.data.query.target.canonicalId==="function:02_prompt.js::buildPrompt",q5.data&&q5.data.query&&q5.data.query.target,"Context");check("Usage question maps to dependency analysis",q5.data&&q5.data.query&&q5.data.query.queryType==="dependency-analysis",q5.data&&q5.data.query&&q5.data.query.queryType,"Intent");
      const q6=namespace.interpretQuery("IDE-160で変更されたファイル",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});check("IDE workflow change question maps to workflow trace",q6.ok&&q6.data.query.queryType==="workflow-trace",q6.data&&q6.data.query&&q6.data.query.queryType,"Intent","Critical");
      const q7=namespace.interpretQuery("前回から変わったファイル",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});check("Previous snapshot change question maps to snapshot diff",q7.ok&&q7.data.query.queryType==="snapshot-diff",q7.data&&q7.data.query&&q7.data.query.queryType,"Intent");
      const q8=namespace.interpretQuery("検証に失敗した理由",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});check("Validation failure question maps to validation trace",q8.ok&&q8.data.query.queryType==="validation-trace",q8.data&&q8.data.query&&q8.data.query.queryType,"Intent");
      const q9=namespace.interpretQuery("この結果の根拠は？",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records,contextTarget:{canonicalId:"function:02_prompt.js::buildPrompt",recordType:"function",name:"buildPrompt"}});check("Evidence request uses context and maps to evidence trace",q9.ok&&q9.data.query.queryType==="evidence-trace"&&q9.data.query.target.canonicalId==="function:02_prompt.js::buildPrompt",q9.data&&q9.data.query,"Intent");
      const q10=namespace.interpretQuery("似た名前のbuild関数",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});check("Similar-name question maps to entity search",q10.ok&&q10.data.query.queryType==="entity-search",q10.data&&q10.data.query&&q10.data.query.queryType,"Intent");
      const executed=executeQuery(q1.data.query,fixture);check("Reverse dependency execution succeeds",executed.ok===true,executed.code,"Execution","Critical");check("Reverse dependency returns caller Fact",executed.ok&&executed.data.envelope.factResults.some(function(f){return f.source&&f.source.canonicalId==="function:04_tools.js::callBuildPrompt";}),executed.ok&&executed.data.envelope.factResults,"Execution");check("Evidence is attached",executed.ok&&executed.data.envelope.evidence.some(function(e){return e.evidenceId==="E-CALLS";}),executed.ok&&executed.data.envelope.evidence,"Evidence","Critical");check("Fact / Derived / Candidate are separated",executed.ok&&Array.isArray(executed.data.envelope.factResults)&&Array.isArray(executed.data.envelope.derivedResults)&&Array.isArray(executed.data.envelope.insightCandidates),executed.ok&&executed.data.envelope,"Envelope","Critical");check("Confidence is deferred rather than fabricated",executed.ok&&executed.data.envelope.confidence.score===null&&executed.data.envelope.confidence.deferredToPhase7===true,executed.ok&&executed.data.envelope.confidence,"Confidence Boundary","Critical");check("Explanation exists",executed.ok&&Boolean(executed.data.envelope.explanation.summary),executed.ok&&executed.data.envelope.explanation,"Explanation");check("Repository mutation prohibited",executed.ok&&executed.data.envelope.policy.repositoryMutationAllowed===false,executed.ok&&executed.data.envelope.policy,"Governance","Critical");
      const member=executeQuery(q2.data.query,fixture);check("Member list finds defined Function",member.ok&&member.data.envelope.factResults.some(function(f){return f.target&&f.target.canonicalId==="function:02_prompt.js::buildPrompt";}),member.ok&&member.data.envelope.factResults,"Execution");
      const lookup=executeQuery(q3.data.query,fixture);check("Entity summary returns Canonical Fact",lookup.ok&&lookup.data.envelope.factResults[0]&&lookup.data.envelope.factResults[0].canonicalId==="module:IDE-170",lookup.ok&&lookup.data.envelope.factResults[0],"Execution");
      const copy=getExplainableEnvelope(executed.data.envelope.envelopeId);if(copy)copy.answerSummary.statement="MUTATED";const protectedCopy=getExplainableEnvelope(executed.data.envelope.envelopeId);check("Frozen Envelope external clone is mutation-protected",protectedCopy&&protectedCopy.answerSummary.statement!=="MUTATED",protectedCopy&&protectedCopy.answerSummary.statement,"Immutability","Critical");
      const partialUnderstanding=internal.clone(fixture.understanding);partialUnderstanding.scope.sourceCoverage={status:"Partial",missingSources:["IDE-170-ADAPTER-FUNCTION"],limitations:["Source Adapter is not Ready: IDE-170-ADAPTER-FUNCTION"]};const partial=executeQuery(q1.data.query,Object.assign({},fixture,{understanding:partialUnderstanding}));check("Missing Function Source is disclosed as Partial",partial.ok&&partial.status==="Partial"&&partial.data.envelope.explanation.missingInformation.length>0,partial.ok&&partial.data.envelope.explanation.missingInformation,"No Silent Completion","Critical");
      const qualityWarningUnderstanding=internal.clone(fixture.understanding);qualityWarningUnderstanding.quality={status:"Partial",warnings:["IDE-160 Workflow Package is unavailable in the current Canonical Snapshot."],errors:[],partialScope:true,missingSources:[]};const missingQuery=namespace.interpretQuery("何が足りない？",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});const missingResult=executeQuery(missingQuery.data.query,Object.assign({},fixture,{understanding:qualityWarningUnderstanding}));check("Missing-information Query exposes Understanding quality warnings",missingResult.ok&&missingResult.status==="Partial"&&missingResult.data.envelope.explanation.missingInformation.some(function(x){return /Workflow Package is unavailable/.test(x);}),missingResult.ok&&missingResult.data.envelope.explanation.missingInformation,"No Silent Completion","Critical");
      const dependencyFromContext=executeQuery(q5.data.query,fixture);check("Function dependency explanation discloses dynamic-reference limitation",dependencyFromContext.ok&&dependencyFromContext.data.envelope.explanation.limitations.some(function(x){return /Dynamic references/.test(x);}),dependencyFromContext.ok&&dependencyFromContext.data.envelope.explanation.limitations,"Explanation","Critical");
      const fileQuery=namespace.interpretQuery("02_prompt.jsとは？",{canonicalSnapshot:fixture.canonicalSnapshot,records:fixture.records});const filePartial=executeQuery(fileQuery.data.query,Object.assign({},fixture,{understanding:partialUnderstanding}));check("Unrelated Function source gap does not degrade direct File lookup",filePartial.ok&&filePartial.status==="Completed"&&filePartial.data.envelope.explanation.limitations.length===0,filePartial.ok&&{status:filePartial.status,limitations:filePartial.data.envelope.explanation.limitations},"Scope Coverage","Critical");
      check("Typed Query schema validates",q1.data&&namespace.validateAgainstSchema("IDE-170-SCHEMA-TYPED-QUERY",q1.data.query).valid===true,q1.data&&q1.data.query.queryId,"Schema");check("Explainable Envelope schema validates",executed.ok&&namespace.validateAgainstSchema("IDE-170-SCHEMA-EXPLAINABLE-INSIGHT-ENVELOPE",executed.data.envelope).valid===true,executed.ok&&executed.data.envelope.envelopeId,"Schema");check("Query Result schema validates",executed.ok&&namespace.validateAgainstSchema("IDE-170-SCHEMA-QUERY-RESULT",executed.data.queryResult).valid===true,executed.ok&&executed.data.queryResult.queryResultId,"Schema");check("All Query Types are governed",namespace.getQueryTypes().length>=20,namespace.getQueryTypes().length,"Registry");check("Terminology Registry is populated",namespace.listTerminology().length>=15,namespace.listTerminology().length,"Registry");check("Natural language direct Reasoning is disabled",namespace.modules.queryInterpreter.naturalLanguageDirectReasoningAllowed===false,namespace.modules.queryInterpreter,"Governance","Critical");check("Candidate automatic Fact promotion disabled",executed.ok&&executed.data.envelope.policy.candidateFactPromotionAllowed===false,executed.ok&&executed.data.envelope.policy,"Governance","Critical");
    }catch(error){check("Phase 6 validation completed without exception",false,error&&error.message||String(error),"Runtime","Critical");}
    const passed=checks.filter(function(x){return x.passed;}).length,total=checks.length;const result={id:internal.nextId("IDE-170-PHASE6-VALIDATION"),componentId:namespace.componentId,name:"IDE-170 Phase 6 Insight, Query and Explanation Validation",version:RELEASE_VERSION,valid:passed===total,passed:passed,failed:total-passed,total:total,health:total?Number(((passed/total)*100).toFixed(2)):0,status:passed===total?"Passed":"Failed",checks:checks,phase6Gate:"Passed - Phase 5 Release Frozen",phase7Gate:passed===total&&settings.androidRealDevicePassed===true?"Passed":"Blocked",androidRealDeviceValidation:{required:true,passed:settings.androidRealDevicePassed===true,device:internal.text(settings.device,settings.androidRealDevicePassed===true?"Android Chrome":""),evidence:internal.text(settings.androidEvidence,""),validatedAt:settings.androidRealDevicePassed===true?internal.nowIso():null},confidencePhaseBoundary:"Deferred to Phase 7",executedAt:internal.nowIso()};state.lastQueryValidation=internal.clone(result);internal.touch();if(typeof internal.registerExternalIntegration==="function")internal.registerExternalIntegration();if(typeof namespace.getReleaseStatus==="function")result.releaseStatus=namespace.getReleaseStatus();state.lastQueryValidation=internal.clone(result);return internal.clone(result);
  }

  function registerSchemas(){const defs=[{schemaId:"IDE-170-SCHEMA-QUERY-RESULT",name:"Query Result",required:["queryResultId","queryId","queryType","status","counts","createdAt","immutable"]},{schemaId:"IDE-170-SCHEMA-EXPLAINABLE-INSIGHT-ENVELOPE",name:"Explainable Insight Envelope",required:["envelopeId","queryId","status","answerSummary","factResults","derivedResults","insightCandidates","evidence","relationshipPaths","interpretationConfidence","confidence","quality","explanation","scope","validation","policy","integrity","createdAt","immutable"]}];return defs.map(function(item){const existing=namespace.getSchema(item.schemaId);if(existing&&existing.version===schemaVersion(item.schemaId))return{schemaId:item.schemaId,registered:true,existing:true};if(existing&&internal.removeSchemaForValidation)internal.removeSchemaForValidation(item.schemaId);const objectFields=new Set(["answerSummary","interpretationConfidence","confidence","quality","explanation","scope","validation","policy","integrity","counts"]),arrayFields=new Set(["factResults","derivedResults","insightCandidates","evidence","relationshipPaths"]);const props={};item.required.forEach(function(f){props[f]=arrayFields.has(f)?{type:"array"}:objectFields.has(f)?{type:"object"}:f==="immutable"?{type:"boolean"}:{type:"string"};});const r=namespace.registerSchema({schemaId:item.schemaId,name:item.name,version:schemaVersion(item.schemaId),type:"object",required:item.required,properties:props,additionalProperties:true,owner:"IDE-170",source:"Architecture Decision 007 + IDE-170-008"});return{schemaId:item.schemaId,registered:r.ok===true,code:r.code};});}
  function registerCapability(){const existing=namespace.getCapability(CAPABILITY_ID);if(existing&&existing.version===CAPABILITY_VERSION)return internal.buildResult(true,"CAPABILITY_EXISTS","Ready",{capability:existing});if(existing&&internal.removeCapabilityForValidation)internal.removeCapabilityForValidation(CAPABILITY_ID);return namespace.registerCapability({capabilityId:CAPABILITY_ID,name:"Evidence-Grounded Query Engine",version:CAPABILITY_VERSION,type:"Query",status:"Active",owner:"IDE-170",dependencies:[{capabilityId:"IDE-170-QUERY-INTERPRETER",minimumVersion:INTERNAL_MINIMUM_VERSION,optional:false},{capabilityId:"IDE-170-EVIDENCE-GRAPH",minimumVersion:INTERNAL_MINIMUM_VERSION,optional:false},{capabilityId:"IDE-170-UNDERSTANDING-PIPELINE",minimumVersion:INTERNAL_MINIMUM_VERSION,optional:false},{capabilityId:"IDE-170-CONFIDENCE-ASSESSMENT",minimumVersion:INTERNAL_MINIMUM_VERSION,optional:false},{capabilityId:"IDE-170-INDEPENDENT-VALIDATION",minimumVersion:INTERNAL_MINIMUM_VERSION,optional:false}],schemas:["IDE-170-SCHEMA-QUERY-RESULT","IDE-170-SCHEMA-EXPLAINABLE-INSIGHT-ENVELOPE"],provides:["Typed Query Execution","Evidence Retrieval","Explainable Insight Envelope","Fact/Derived/Candidate Separation","Missing Information Disclosure","Multi-Factor Confidence Integration","Independent Validation Gate","Quality Assessment"],source:"Architecture Decision 007"});}
  function registerPhase6ValidationAssets(){const results={targets:[],dataset:null};if(typeof namespace.registerValidationTarget==="function"){const targets=[["IDE-170-TARGET-PHASE6-NORMALIZE","Phase 6 Normalize",function(input){return{normalized:namespace.normalizeJapaneseQuery(input.query)};}],["IDE-170-TARGET-PHASE6-INTERPRET","Phase 6 Interpret",function(input){const f=buildPhase6Fixture(),r=namespace.interpretQuery(input.query,{canonicalSnapshot:f.canonicalSnapshot,records:f.records,contextTarget:input.contextTarget});return{ok:r.ok,status:r.status,queryType:r.data&&r.data.query&&r.data.query.queryType,targetCanonicalId:r.data&&r.data.query&&r.data.query.target&&r.data.query.target.canonicalId};}],["IDE-170-TARGET-PHASE6-EXECUTE","Phase 6 Execute",function(input){const f=buildPhase6Fixture(),r=executeQuery(input.query,f);return{ok:r.ok,status:r.status,factCount:r.data&&r.data.envelope&&r.data.envelope.factResults.length,evidenceCount:r.data&&r.data.envelope&&r.data.envelope.evidence.length,confidenceDeferred:Boolean(r.data&&r.data.envelope&&r.data.envelope.confidence.deferredToPhase7)};}]];targets.forEach(function(item){const existing=namespace.getValidationTarget&&namespace.getValidationTarget(item[0]);if(existing){results.targets.push({targetId:item[0],registered:true,existing:true});return;}const r=namespace.registerValidationTarget({targetId:item[0],name:item[1],executionTypes:["Function"]},item[2]);results.targets.push({targetId:item[0],registered:r.ok===true,code:r.code});});}
    if(typeof namespace.registerTestDataset==="function"){if(namespace.getTestDataset&&namespace.getTestDataset(DATASET_ID))results.dataset={datasetId:DATASET_ID,registered:true,existing:true};else{const cases=[
      ["001","Reverse dependency query","buildPromptを呼び出している関数は？",{ok:true,queryType:"reverse-dependency-analysis",targetCanonicalId:"function:02_prompt.js::buildPrompt"}],
      ["002","File member list query","02_prompt.jsの関数一覧",{ok:true,queryType:"member-list",targetCanonicalId:"file:02_prompt.js"}],
      ["003","IDE workflow changed files query","IDE-160で変更されたファイル",{ok:true,queryType:"workflow-trace"}],
      ["004","Previous snapshot diff query","前回から変わったファイル",{ok:true,queryType:"snapshot-diff"}],
      ["006","Validation failure reason query","検証に失敗した理由",{ok:true,queryType:"validation-trace"}],
      ["008","Similar build function search","似た名前のbuild関数",{ok:true,queryType:"entity-search"}],
      ["009","Unresolved pronoun blocks execution","これに関係するファイル",{ok:false,status:"Needs Resolution"}],
      ["010","Full-width IDE status query","IDE１７０の状態",{ok:true,queryType:"entity-summary",targetCanonicalId:"module:IDE-170"}]
    ].map(function(x){return{caseId:"IDE-170-P6-GOLDEN-"+x[0],name:x[1],category:"Japanese Query",severity:"High",target:"IDE-170-TARGET-PHASE6-INTERPRET",executionType:"Function",input:{query:x[2]},expected:{comparator:"Partial Object",value:x[3]}};});cases.splice(4,0,{caseId:"IDE-170-P6-GOLDEN-005",name:"Contextual function usage query",category:"Japanese Query",severity:"High",target:"IDE-170-TARGET-PHASE6-INTERPRET",executionType:"Function",input:{query:"この関数は使われている？",contextTarget:{canonicalId:"function:02_prompt.js::buildPrompt",recordType:"function",name:"buildPrompt"}},expected:{comparator:"Partial Object",value:{ok:true,queryType:"dependency-analysis",targetCanonicalId:"function:02_prompt.js::buildPrompt"}}});cases.splice(6,0,{caseId:"IDE-170-P6-GOLDEN-007",name:"Contextual evidence trace query",category:"Japanese Query",severity:"High",target:"IDE-170-TARGET-PHASE6-INTERPRET",executionType:"Function",input:{query:"この結果の根拠は？",contextTarget:{canonicalId:"function:02_prompt.js::buildPrompt",recordType:"function",name:"buildPrompt"}},expected:{comparator:"Partial Object",value:{ok:true,queryType:"evidence-trace",targetCanonicalId:"function:02_prompt.js::buildPrompt"}}});const ds={datasetId:DATASET_ID,name:"IDE-170 Phase 6 Japanese Query and Explanation Dataset",version:datasetVersion("phase6QueryExplanation"),componentId:"IDE-170",targetPhase:"Phase 6 Insight, Query and Explanation",status:"Frozen",description:"Decision 007 deterministic Japanese Query validation dataset.",testCases:cases,metadata:{architectureDecision:"IDE-170-007",noAutomaticExecution:true,confidencePhase:"Deferred to Phase 7"}};const r=namespace.registerTestDataset(ds,{actor:"IDE-170 Phase 6 Bootstrap"});results.dataset={datasetId:DATASET_ID,registered:r.ok===true,code:r.code};}}
    return results;}
  function initializeQueryEngine(){const sr=registerSchemas(),cr=registerCapability(),va=registerPhase6ValidationAssets(),ready=sr.every(function(x){return x.registered;})&&cr.ok===true;namespace.modules.queryEngine.status=ready?"Ready":"Blocked";return internal.buildResult(ready,ready?"QUERY_ENGINE_INITIALIZED":"QUERY_ENGINE_INITIALIZATION_FAILED",ready?"Ready":"Blocked",{schemaResults:sr,capabilityResult:cr,validationAssets:va});}
  function getQueryEngineStatus(){return{id:"IDE-170-QUERY-ENGINE-STATUS",version:MODULE_VERSION,capabilityVersion:CAPABILITY_VERSION,status:namespace.getCapability(CAPABILITY_ID)?"Ready":"Loaded",ready:Boolean(namespace.getCapability(CAPABILITY_ID)),queryResultCount:state.queryResults.size,explainableEnvelopeCount:state.explainableEnvelopes.size,latestQueryResultId:state.latestQueryResultId,latestEnvelopeId:state.latestExplainableEnvelopeId,confidencePhase:"Phase 7 Active"};}

  Object.assign(namespace.api,{initializeQueryEngine,executeQuery,getQueryResult,listQueryResults,getExplainableEnvelope,getInsight,validateExplainableEnvelope,runQueryPhaseValidation,getQueryEngineStatus,registerPhase6ValidationAssets});Object.assign(namespace,namespace.api);
  namespace.modules.queryEngine={id:CAPABILITY_ID,version:MODULE_VERSION,capabilityVersion:CAPABILITY_VERSION,status:"Loaded",evidenceRetrieval:true,explainableEnvelope:true,factDerivedCandidateSeparation:true,confidenceDeferredToPhase7:false,confidenceModelActive:true,independentValidationGate:true,repositoryMutationAllowed:false,workflowExecutionAllowed:false,candidateFactPromotionAllowed:false,loadedAt:internal.nowIso()};
  global.validateIntelligenceQueryExplanation=runQueryPhaseValidation;
})(typeof window!=="undefined"?window:globalThis);
