/* ============================================================
   FILE: 13_knowledge_navigator_validation_provider.js
   IDE-180 Knowledge Navigator
   Release: Version Manifest / Module: Validation Provider 1.0.0
   Phase 6: Federation / Conflict
   ============================================================ */
(function (global) {
  "use strict";
  const namespace=global.IDE180KnowledgeNavigator; const VERSION_MANIFEST=global.IDE180VersionManifest;
  if(!namespace||!namespace.__internal||!VERSION_MANIFEST){console.warn("IDE-180 Validation Provider blocked.");return;}
  const internal=namespace.__internal; const MODULE_VERSION=VERSION_MANIFEST.getModuleVersion("validationProvider"); const PROVIDER_ID="IDE-180-PROVIDER-VALIDATION-RESULTS"; const SOURCE_TYPE="validation-result-repository";
  function text(v,f){return internal.text(v,f);} function lower(v){return text(v,"").normalize("NFKC").toLowerCase();} function arr(v){return Array.isArray(v)?v:[];}
  function raw(){try{return typeof global.getValidationResults==="function"?arr(global.getValidationResults({limit:100})).map(internal.clone):[];}catch(_){return[];}}
  function normalize(r,i){const id=text(r&&r.id||r&&r.recordId,"VALIDATION-"+i); const target=text(r&&r.targetComponent||r&&r.sourceComponent,""); const lifecycle=r&&r.official===true?"validated-official":"active"; const validationState=lower(r&&r.status)==="passed"?"validated":(lower(r&&r.status)==="failed"?"failed":"unknown"); return internal.deepFreeze({recordId:"IDE180-VALIDATION:"+text(r&&r.recordId,id),canonicalEntityId:target?(target.includes(":")?target:"entity:"+target):("validation:"+id),providerId:PROVIDER_ID,sourceId:id,sourceType:SOURCE_TYPE,recordType:"validation",title:text(r&&r.payload&&r.payload.title,id),summary:text(r&&r.payload&&r.payload.summary||r&&r.payload&&r.payload.report&&r.payload.report.executiveSummary,""),contentReference:{validationRecordId:text(r&&r.recordId,id),validationId:id,readOnly:true},version:text(r&&r.resultVersion||r&&r.payload&&r.payload.version,""),lifecycle:lifecycle,officialState:r&&r.official===true?"official":"non-official",validationState:validationState,scope:target?{targetComponent:target}:null,relationships:[],lineage:[],evidenceReferences:arr(r&&r.evidenceReferences).map(function(e){return typeof e==="string"?{evidenceId:e}:internal.clone(e);}),trust:"not-applicable",timestamps:{completedAt:r&&r.completedAt||null,savedAt:r&&r.savedAt||null,updatedAt:r&&r.updatedAt||null},sourceMetadata:{status:text(r&&r.status,""),releaseAllowed:r&&r.releaseAllowed===true,implementationReady:r&&r.implementationReady===true,health:Number.isFinite(Number(r&&r.health))?Number(r.health):null,sourceComponent:text(r&&r.sourceComponent,""),targetComponent:target,comparable:{}},immutable:true});}
  function all(){return raw().map(normalize);} function describe(){const list=all(); return {providerId:PROVIDER_ID,providerVersion:MODULE_VERSION,sourceType:SOURCE_TYPE,readMode:"read-only",availability:typeof global.getValidationResults!=="function"?"unavailable":(list.length?"available":"partial"),capabilities:["validation-navigation","validation-facet","federation-source"],recordCount:list.length,mutationAllowed:false};}
  function supports(c){return describe().capabilities.includes(text(c,""));} function list(){return all().map(internal.clone);} function get(selector){const s=internal.isPlainObject(selector)?selector:{id:selector}; const id=text(s.recordId||s.canonicalEntityId||s.sourceId||s.id,""); return internal.clone(all().find(function(x){return [x.recordId,x.canonicalEntityId,x.sourceId].includes(id);})||null);} function search(query){const q=lower(query); if(!q)return list(); return all().filter(function(x){return [x.recordId,x.canonicalEntityId,x.sourceId,x.title,x.summary,x.sourceMetadata.sourceComponent,x.sourceMetadata.targetComponent,x.sourceMetadata.status].map(lower).join(" ").includes(q);}).map(internal.clone);}
  const providerDefinition={providerId:PROVIDER_ID,providerVersion:MODULE_VERSION,sourceType:SOURCE_TYPE,readMode:"read-only",availability:"not-loaded",capabilities:["validation-navigation","validation-facet","federation-source"],supports:supports,describe:describe,get:get,search:search,list:list};
  function initializeValidationProvider(){providerDefinition.availability=describe().availability; const existing=namespace.getProviderDefinition&&namespace.getProviderDefinition(PROVIDER_ID); const registration=existing?internal.buildResult(true,"IDE180_PROVIDER_EXISTS","Ready",{providerId:PROVIDER_ID}):namespace.registerProviderDefinition(providerDefinition); namespace.modules.validationProvider.status=registration&&registration.ok===true?"Ready":"Blocked"; return internal.buildResult(registration&&registration.ok===true,registration&&registration.ok===true?"IDE180_VALIDATION_PROVIDER_INITIALIZED":"IDE180_VALIDATION_PROVIDER_INITIALIZATION_FAILED",registration&&registration.ok===true?"Ready":"Blocked",{registration:registration,provider:describe()});}
  Object.assign(namespace.api,{initializeValidationProvider:initializeValidationProvider,getValidationProviderStatus:describe,listValidationSourceRecords:list,searchValidationSourceRecords:search,getValidationSourceRecord:get}); Object.assign(namespace,namespace.api); namespace.modules.validationProvider={id:"IDE-180-VALIDATION-PROVIDER",version:MODULE_VERSION,status:"Loaded",phase:6,providerId:PROVIDER_ID,sourceType:SOURCE_TYPE,readOnly:true,loadedAt:internal.nowIso()};
})(typeof window!=="undefined"?window:globalThis);