/* ============================================================
   FILE: 17_external_intelligence_social_narrative.js
   EXTERNAL-010 External Intelligence Platform
   Release: 1.12.0
   Phase 13: Social Narrative / Propagation / Decision 032-033 Hooks
   Primary Decision: 034
   ============================================================ */
(function (global) {
  "use strict";
  const namespace = global.EXTERNAL010ExternalIntelligence;
  const VERSION_MANIFEST = global.EXTERNAL010VersionManifest;
  if (!namespace || !namespace.__internal || !VERSION_MANIFEST) return;
  const internal = namespace.__internal, state = internal.state;
  const MODULE_VERSION = VERSION_MANIFEST.getModuleVersion("socialNarrative");
  const NARRATIVE_STATES = new Set(VERSION_MANIFEST.socialIntelligence.narrativeStates || []);
  ["socialNarratives", "socialNarrativeVersions", "socialNarrativeShifts", "socialPropagationRecords", "socialCoordinationCandidates", "socialAccountClusters", "socialAmplificationAssessments", "socialPumpPatternCandidates"].forEach(function (key) { if (!(state[key] instanceof Map)) state[key] = new Map(); });

  function validateRecord(contractKey, schemaId, record) { const c = namespace.validateExternalIntelligenceContract(contractKey, record), s = namespace.validateExternalIntelligenceRecord(schemaId, record); return c.valid && s.valid ? null : { contract: c, schema: s }; }
  function linkLineage(refs, output, relation) {
    const list = internal.unique(refs || []).filter(Boolean);
    if (!list.length || typeof namespace.createExternalIntelligenceLineageRecord !== "function") return { ok: true, lineageRecords: [] };
    const results = list.map(function (ref) { return namespace.createExternalIntelligenceLineageRecord({ inputReferenceId: ref, outputReferenceId: output, relationType: relation || "DERIVED_FROM", lineageState: "ACTIVE" }); });
    return { ok: results.every(function (x) { return x && x.ok === true; }), lineageRecords: results.map(function (x) { return x && x.data && x.data.lineageRecord; }).filter(Boolean), results: results };
  }

  function recordExternalIntelligenceSocialNarrative(input) {
    const source = internal.isPlainObject(input) ? input : {}, id = internal.text(source.narrativeId, "") || internal.nextId("EXTERNAL-010-NARRATIVE"), previous = state.socialNarratives.get(id);
    const version = previous ? previous.version + 1 : Math.max(1, Number(source.version) || 1), narrativeState = internal.text(source.narrativeState, "EMERGING").toUpperCase();
    if (!NARRATIVE_STATES.has(narrativeState)) return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_STATE_INVALID", "Blocked", { narrativeState: narrativeState });
    const observations = internal.unique(source.supportingSocialObservationIds || []);
    if (observations.some(function (key) { return !state.socialObservations.has(key); })) return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_OBSERVATION_MISSING", "Blocked", { supportingSocialObservationIds: observations });
    const record = internal.deepFreeze({ narrativeId: id, version: version, narrativeRecordId: id + "-V" + version, topic: internal.text(source.topic, "UNSPECIFIED"), relatedEntityIds: internal.unique(source.relatedEntityIds || []), firstObservedAt: internal.text(source.firstObservedAt, previous && previous.firstObservedAt || internal.nowIso()), lastObservedAt: internal.text(source.lastObservedAt, internal.nowIso()), mentionVolume: Number.isFinite(source.mentionVolume) ? source.mentionVolume : observations.length, mentionVelocity: Number.isFinite(source.mentionVelocity) ? source.mentionVelocity : null, sentimentProfile: internal.isPlainObject(source.sentimentProfile) ? internal.clone(source.sentimentProfile) : {}, reachEstimate: Number.isFinite(source.reachEstimate) ? source.reachEstimate : null, supportingSocialObservationIds: observations, narrativeState: narrativeState, confidence: internal.text(source.confidence, "UNKNOWN").toUpperCase(), candidateOnly: true, truthConfirmed: false, createdAt: internal.nowIso(), immutable: true });
    const invalid = validateRecord("socialNarrative", "EXTERNAL-010-SCHEMA-SOCIAL-NARRATIVE", record); if (invalid) return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_INVALID", "Blocked", invalid);
    state.socialNarratives.set(id, record); state.socialNarrativeVersions.set(record.narrativeRecordId, record);
    const lineage = linkLineage(observations, record.narrativeRecordId, "AGGREGATED_FROM");
    if (!lineage.ok) { state.socialNarratives.delete(id); state.socialNarrativeVersions.delete(record.narrativeRecordId); return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_LINEAGE_FAILED", "Blocked", lineage); }
    internal.touch(); return internal.buildResult(true, "EXTERNAL010_SOCIAL_NARRATIVE_RECORDED", "Candidate", { narrative: internal.clone(record), lineageRecords: internal.clone(lineage.lineageRecords) });
  }

  function recordExternalIntelligenceSocialNarrativeShift(input) {
    const source = internal.isPlainObject(input) ? input : {}, current = state.socialNarratives.get(internal.text(source.narrativeId, ""));
    if (!current) return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_REQUIRED", "Blocked", null);
    const toState = internal.text(source.toState, current.narrativeState).toUpperCase(); if (!NARRATIVE_STATES.has(toState)) return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_STATE_INVALID", "Blocked", { toState: toState });
    const id = internal.text(source.narrativeShiftId, "") || internal.nextId("EXTERNAL-010-NARRATIVE-SHIFT");
    const record = internal.deepFreeze({ narrativeShiftId: id, narrativeId: current.narrativeId, fromState: internal.text(source.fromState, current.narrativeState).toUpperCase(), toState: toState, previousTopic: internal.text(source.previousTopic, current.topic) || null, currentTopic: internal.text(source.currentTopic, current.topic), detectedAt: internal.text(source.detectedAt, internal.nowIso()), signalCandidate: true, eventConfirmed: false, createdAt: internal.nowIso(), immutable: true });
    const invalid = validateRecord("socialNarrativeShift", "EXTERNAL-010-SCHEMA-SOCIAL-NARRATIVE-SHIFT", record); if (invalid) return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_SHIFT_INVALID", "Blocked", invalid);
    state.socialNarrativeShifts.set(id, record); const lineage = linkLineage([current.narrativeRecordId], id, "DERIVED_FROM"); if (!lineage.ok) { state.socialNarrativeShifts.delete(id); return internal.buildResult(false, "EXTERNAL010_SOCIAL_NARRATIVE_SHIFT_LINEAGE_FAILED", "Blocked", lineage); }
    internal.touch(); return internal.buildResult(true, "EXTERNAL010_SOCIAL_NARRATIVE_SHIFT_RECORDED", "Candidate", { narrativeShift: internal.clone(record), lineageRecords: internal.clone(lineage.lineageRecords) });
  }

  function recordExternalIntelligenceSocialPropagation(input) {
    const source = internal.isPlainObject(input) ? input : {}, id = internal.text(source.propagationRecordId, "") || internal.nextId("EXTERNAL-010-SOCIAL-PROPAGATION");
    const mentionCount = Math.max(0, Number(source.mentionCount) || 0), origins = Number.isFinite(source.estimatedIndependentOrigins) ? Math.max(0, source.estimatedIndependentOrigins) : null;
    const record = internal.deepFreeze({ propagationRecordId: id, subjectType: internal.text(source.subjectType, "NARRATIVE").toUpperCase(), subjectId: internal.text(source.subjectId, ""), windowStart: internal.text(source.windowStart, internal.nowIso()), windowEnd: internal.text(source.windowEnd, internal.nowIso()), mentionCount: mentionCount, mentionVelocity: Number.isFinite(source.mentionVelocity) ? source.mentionVelocity : null, propagationVelocity: Number.isFinite(source.propagationVelocity) ? source.propagationVelocity : null, engagementMetrics: internal.isPlainObject(source.engagementMetrics) ? internal.clone(source.engagementMetrics) : {}, communitySourceIds: internal.unique(source.communitySourceIds || []), crossCommunitySpreadCount: internal.unique(source.communitySourceIds || []).length, estimatedIndependentOrigins: origins, rawMentionCountEqualsIndependentOpinions: false, createdAt: internal.nowIso(), immutable: true });
    if (!record.subjectId) return internal.buildResult(false, "EXTERNAL010_SOCIAL_PROPAGATION_SUBJECT_REQUIRED", "Blocked", null);
    const invalid = validateRecord("socialPropagationRecord", "EXTERNAL-010-SCHEMA-SOCIAL-PROPAGATION", record); if (invalid) return internal.buildResult(false, "EXTERNAL010_SOCIAL_PROPAGATION_INVALID", "Blocked", invalid);
    state.socialPropagationRecords.set(id, record); const lineage = linkLineage([record.subjectId], id, "DERIVED_FROM"); if (!lineage.ok) { state.socialPropagationRecords.delete(id); return internal.buildResult(false, "EXTERNAL010_SOCIAL_PROPAGATION_LINEAGE_FAILED", "Blocked", lineage); }
    internal.touch(); return internal.buildResult(true, "EXTERNAL010_SOCIAL_PROPAGATION_RECORDED", "Ready", { propagation: internal.clone(record), lineageRecords: internal.clone(lineage.lineageRecords) });
  }

  function recordExternalIntelligenceSocialCoordinationCandidate(input) { const source = internal.isPlainObject(input) ? input : {}, ids = internal.unique(source.accountIds || []); if (ids.length < 2) return internal.buildResult(false, "EXTERNAL010_SOCIAL_COORDINATION_ACCOUNTS_REQUIRED", "Blocked", null); const id = internal.text(source.coordinationCandidateId, "") || internal.nextId("EXTERNAL-010-COORDINATION-CANDIDATE"), record = internal.deepFreeze({ coordinationCandidateId: id, accountIds: ids, evidenceRefs: internal.unique(source.evidenceRefs || []), coordinationInputs: internal.isPlainObject(source.coordinationInputs) ? internal.clone(source.coordinationInputs) : {}, coordinationConfidence: internal.text(source.coordinationConfidence, "UNKNOWN").toUpperCase(), samePersonConfirmed: false, illegalManipulationProven: false, createdAt: internal.nowIso(), immutable: true }); const invalid = validateRecord("socialCoordinationCandidate", "EXTERNAL-010-SCHEMA-SOCIAL-COORDINATION-CANDIDATE", record); if (invalid) return internal.buildResult(false, "EXTERNAL010_SOCIAL_COORDINATION_INVALID", "Blocked", invalid); state.socialCoordinationCandidates.set(id, record); const lineage = linkLineage(record.evidenceRefs, id, "DERIVED_FROM"); if (!lineage.ok) { state.socialCoordinationCandidates.delete(id); return internal.buildResult(false, "EXTERNAL010_SOCIAL_COORDINATION_LINEAGE_FAILED", "Blocked", lineage); } internal.touch(); return internal.buildResult(true, "EXTERNAL010_SOCIAL_COORDINATION_CANDIDATE_RECORDED", "Candidate", { coordinationCandidate: internal.clone(record), lineageRecords: internal.clone(lineage.lineageRecords) }); }
  function recordExternalIntelligenceSocialAccountCluster(input) { const source = internal.isPlainObject(input) ? input : {}, ids = internal.unique(source.memberAccountIds || []); if (ids.length < 2) return internal.buildResult(false, "EXTERNAL010_SOCIAL_CLUSTER_ACCOUNTS_REQUIRED", "Blocked", null); const id = internal.text(source.accountClusterId, "") || internal.nextId("EXTERNAL-010-ACCOUNT-CLUSTER"), record = internal.deepFreeze({ accountClusterId: id, memberAccountIds: ids, behaviorSimilarity: Number.isFinite(source.behaviorSimilarity) ? source.behaviorSimilarity : null, timingSimilarity: Number.isFinite(source.timingSimilarity) ? source.timingSimilarity : null, contentSimilarity: Number.isFinite(source.contentSimilarity) ? source.contentSimilarity : null, networkSimilarity: Number.isFinite(source.networkSimilarity) ? source.networkSimilarity : null, coordinationConfidence: internal.text(source.coordinationConfidence, "UNKNOWN").toUpperCase(), samePersonConfirmed: false, realPersonIdentityResolved: false, createdAt: internal.nowIso(), immutable: true }); const invalid = validateRecord("socialAccountCluster", "EXTERNAL-010-SCHEMA-SOCIAL-ACCOUNT-CLUSTER", record); if (invalid) return internal.buildResult(false, "EXTERNAL010_SOCIAL_ACCOUNT_CLUSTER_INVALID", "Blocked", invalid); state.socialAccountClusters.set(id, record); internal.touch(); return internal.buildResult(true, "EXTERNAL010_SOCIAL_ACCOUNT_CLUSTER_RECORDED", "Candidate", { accountCluster: internal.clone(record) }); }
  function recordExternalIntelligenceSocialAmplificationAssessment(input) { const source = internal.isPlainObject(input) ? input : {}, id = internal.text(source.amplificationAssessmentId, "") || internal.nextId("EXTERNAL-010-AMPLIFICATION"), record = internal.deepFreeze({ amplificationAssessmentId: id, subjectId: internal.text(source.subjectId, ""), organicInfluence: Number.isFinite(source.organicInfluence) ? source.organicInfluence : null, artificialAmplification: Number.isFinite(source.artificialAmplification) ? source.artificialAmplification : null, botProbability: Number.isFinite(source.botProbability) ? source.botProbability : null, aiGeneratedProbability: Number.isFinite(source.aiGeneratedProbability) ? source.aiGeneratedProbability : null, advertisingShare: Number.isFinite(source.advertisingShare) ? source.advertisingShare : null, marketImpactEligible: true, botIdentityProven: false, createdAt: internal.nowIso(), immutable: true }); if (!record.subjectId) return internal.buildResult(false, "EXTERNAL010_SOCIAL_AMPLIFICATION_SUBJECT_REQUIRED", "Blocked", null); const invalid = validateRecord("socialAmplificationAssessment", "EXTERNAL-010-SCHEMA-SOCIAL-AMPLIFICATION-ASSESSMENT", record); if (invalid) return internal.buildResult(false, "EXTERNAL010_SOCIAL_AMPLIFICATION_INVALID", "Blocked", invalid); state.socialAmplificationAssessments.set(id, record); const lineage = linkLineage([record.subjectId], id, "DERIVED_FROM"); if (!lineage.ok) { state.socialAmplificationAssessments.delete(id); return internal.buildResult(false, "EXTERNAL010_SOCIAL_AMPLIFICATION_LINEAGE_FAILED", "Blocked", lineage); } internal.touch(); return internal.buildResult(true, "EXTERNAL010_SOCIAL_AMPLIFICATION_RECORDED", "Candidate", { amplificationAssessment: internal.clone(record), lineageRecords: internal.clone(lineage.lineageRecords) }); }
  function recordExternalIntelligenceSocialPumpPatternCandidate(input) { const source = internal.isPlainObject(input) ? input : {}, id = internal.text(source.pumpPatternCandidateId, "") || internal.nextId("EXTERNAL-010-PUMP-PATTERN"), record = internal.deepFreeze({ pumpPatternCandidateId: id, subjectEntityId: internal.text(source.subjectEntityId, "") || null, signalRefs: internal.unique(source.signalRefs || []), patternInputs: internal.isPlainObject(source.patternInputs) ? internal.clone(source.patternInputs) : {}, patternSimilarity: Number.isFinite(source.patternSimilarity) ? source.patternSimilarity : null, marketManipulationRisk: internal.text(source.marketManipulationRisk, "UNKNOWN").toUpperCase(), candidateOnly: true, illegalManipulationProven: false, legalConclusionReached: false, tradingAuthorityGranted: false, createdAt: internal.nowIso(), immutable: true }); const invalid = validateRecord("socialPumpPatternCandidate", "EXTERNAL-010-SCHEMA-SOCIAL-PUMP-PATTERN-CANDIDATE", record); if (invalid) return internal.buildResult(false, "EXTERNAL010_SOCIAL_PUMP_PATTERN_INVALID", "Blocked", invalid); state.socialPumpPatternCandidates.set(id, record); const lineage = linkLineage(record.signalRefs, id, "DERIVED_FROM"); if (!lineage.ok) { state.socialPumpPatternCandidates.delete(id); return internal.buildResult(false, "EXTERNAL010_SOCIAL_PUMP_PATTERN_LINEAGE_FAILED", "Blocked", lineage); } internal.touch(); return internal.buildResult(true, "EXTERNAL010_SOCIAL_PUMP_PATTERN_CANDIDATE_RECORDED", "Candidate", { pumpPatternCandidate: internal.clone(record), lineageRecords: internal.clone(lineage.lineageRecords) }); }

  function createExternalIntelligenceSocialSignalHook(input) {
    const source = internal.isPlainObject(input) ? input : {};
    const observationRefs = internal.unique(source.socialObservationIds || source.observationRefs || []);
    if (!observationRefs.length || observationRefs.some(function (id) { return !state.socialObservations.has(id); })) return internal.buildResult(false, "EXTERNAL010_SOCIAL_SIGNAL_OBSERVATIONS_REQUIRED", "Blocked", { observationRefs: observationRefs });
    if (typeof namespace.recordExternalIntelligenceSignalCandidate !== "function" || typeof namespace.recordExternalIntelligenceSignalCluster !== "function") return internal.buildResult(false, "EXTERNAL010_SOCIAL_SIGNAL_PLATFORM_UNAVAILABLE", "Blocked", null);
    const signal = namespace.recordExternalIntelligenceSignalCandidate({ signalId: source.signalId, signalType: internal.text(source.signalType, "SOCIAL_NARRATIVE_SHIFT"), baselineId: source.baselineId, observationRefs: observationRefs, anomalyStrength: source.anomalyStrength, novelty: source.novelty, persistence: source.persistence, confidence: internal.text(source.confidence, "UNKNOWN"), signalState: "CANDIDATE" });
    if (!signal || signal.ok !== true) return signal;
    const cluster = namespace.recordExternalIntelligenceSignalCluster({ signalClusterId: source.signalClusterId, memberSignalIds: [signal.data.signal.signalId], clusterConfidence: internal.text(source.clusterConfidence, source.confidence || "UNKNOWN") });
    return internal.buildResult(cluster && cluster.ok === true, cluster && cluster.ok ? "EXTERNAL010_SOCIAL_SIGNAL_HOOK_CREATED" : "EXTERNAL010_SOCIAL_SIGNAL_CLUSTER_FAILED", cluster && cluster.ok ? "Candidate" : "Blocked", { signal: signal.data.signal, signalCluster: cluster && cluster.data && cluster.data.signalCluster, decision032Integrated: cluster && cluster.ok === true });
  }

  function createExternalIntelligenceSocialResearchHook(input) {
    const source = internal.isPlainObject(input) ? input : {}, signalIds = internal.unique(source.signalIds || []), hypotheses = Array.isArray(source.hypotheses) ? source.hypotheses : [];
    if (!signalIds.length || hypotheses.length < 2) return internal.buildResult(false, "EXTERNAL010_SOCIAL_COMPETING_HYPOTHESES_REQUIRED", "Blocked", { signalIds: signalIds, hypothesisCount: hypotheses.length });
    if (typeof namespace.recordExternalIntelligenceResearchQuestion !== "function" || typeof namespace.recordExternalIntelligenceHypothesis !== "function") return internal.buildResult(false, "EXTERNAL010_SOCIAL_RESEARCH_PLATFORM_UNAVAILABLE", "Blocked", null);
    const question = namespace.recordExternalIntelligenceResearchQuestion({ researchQuestionId: source.researchQuestionId, question: internal.text(source.question, "What explains this social propagation signal?"), triggerSignalIds: signalIds });
    if (!question || question.ok !== true) return question;
    const records = hypotheses.map(function (h, index) { const item = internal.isPlainObject(h) ? h : {}; return namespace.recordExternalIntelligenceHypothesis({ hypothesisId: item.hypothesisId, researchQuestionId: question.data.researchQuestion.researchQuestionId, hypothesisType: internal.text(item.hypothesisType, "ALTERNATIVE"), statement: internal.text(item.statement, "Alternative social propagation explanation " + (index + 1)), relatedSignalIds: signalIds, supportingEvidenceIds: internal.unique(item.supportingEvidenceIds || []), contradictingEvidenceIds: internal.unique(item.contradictingEvidenceIds || []), missingEvidence: Array.isArray(item.missingEvidence) ? item.missingEvidence : [], expectedObservations: Array.isArray(item.expectedObservations) ? item.expectedObservations : [], falsificationCriteria: Array.isArray(item.falsificationCriteria) ? item.falsificationCriteria : [], hypothesisState: internal.text(item.hypothesisState, "INCONCLUSIVE"), confidenceProfile: internal.isPlainObject(item.confidenceProfile) ? item.confidenceProfile : { state: "UNKNOWN" } }); });
    const ok = records.every(function (item) { return item && item.ok === true; });
    return internal.buildResult(ok, ok ? "EXTERNAL010_SOCIAL_RESEARCH_HOOK_CREATED" : "EXTERNAL010_SOCIAL_RESEARCH_HYPOTHESIS_FAILED", ok ? "Candidate" : "Blocked", { researchQuestion: question.data.researchQuestion, hypotheses: records.map(function (x) { return x && x.data && x.data.hypothesis; }).filter(Boolean), competingHypothesesPreserved: ok, decision033Integrated: ok });
  }

  function listExternalIntelligenceSocialNarrativeHistory(id) { return Array.from(state.socialNarrativeVersions.values()).filter(function (r) { return r.narrativeId === id; }).sort(function (a, b) { return a.version - b.version; }).map(internal.clone); }
  Object.assign(namespace.api, { recordExternalIntelligenceSocialNarrative, recordExternalIntelligenceSocialNarrativeShift, recordExternalIntelligenceSocialPropagation, recordExternalIntelligenceSocialCoordinationCandidate, recordExternalIntelligenceSocialAccountCluster, recordExternalIntelligenceSocialAmplificationAssessment, recordExternalIntelligenceSocialPumpPatternCandidate, createExternalIntelligenceSocialSignalHook, createExternalIntelligenceSocialResearchHook, listExternalIntelligenceSocialNarrativeHistory });
  Object.assign(namespace, namespace.api);
  namespace.modules.socialNarrative = { id: "EXTERNAL-010-SOCIAL-NARRATIVE", version: MODULE_VERSION, status: "Ready", phase: 13, decisions: ["034"], decision032SignalHook: true, decision033ResearchHook: true, lineageIntegration: true, loadedAt: internal.nowIso() };
})(typeof window !== "undefined" ? window : globalThis);
