/* ============================================================
   FILE: 17_external_intelligence_phase13_validation.js
   EXTERNAL-010 External Intelligence Platform
   Release: 1.12.0
   Phase 13: Social Narrative / Propagation / Influence Validation
   Primary Decision: 034
   ============================================================ */
(function (global) {
  "use strict";
  const namespace = global.EXTERNAL010ExternalIntelligence;
  const VERSION_MANIFEST = global.EXTERNAL010VersionManifest;
  if (!namespace || !namespace.__internal || !VERSION_MANIFEST) return;
  const internal = namespace.__internal, state = internal.state;
  const MODULE_VERSION = VERSION_MANIFEST.getModuleVersion("phase13Validation");

  function installGovernanceFixtures(sourceId) {
    const now = internal.nowIso();
    state.sourceRegistry.set(sourceId, internal.deepFreeze({ sourceId: sourceId, sourceName: "Phase 13 Social Validation Fixture", sourceType: "SOCIAL_PLATFORM", provider: "Validation Fixture", category: "SOCIAL", accessMode: "BROWSER_DIRECT", adapterId: "EXTERNAL-010-ADAPTER-MOCK-001", endpointPolicy: { canonicalHost: "example.invalid", endpointReference: "validation://social", directUrlAccessAllowed: false, arbitraryPathAllowed: false, allowRedirects: false, operationResolutionRequired: true }, authenticationMode: "NONE", secretReferenceId: null, allowedOperations: ["READ", "INTERNAL_ANALYSIS"], allowedMethods: ["GET"], pricingMode: "FREE", costCurrency: "JPY", enabled: true, lifecycleState: "ACTIVE", version: 1, identityState: "VERIFIED", reliabilityState: "UNASSESSED", authorityGranted: false, discoveryId: null, createdAt: now, updatedAt: now, immutable: true }));
    const policyId = "POLICY-P13-SOCIAL";
    const right = function (operation) { return { state: "ALLOWED", conditions: [], evidenceIds: ["TERMS-P13"], clauseReference: "VALIDATION", confidence: "HIGH" }; };
    state.usagePolicies.set(policyId, internal.deepFreeze({ usagePolicyId: policyId, sourceId: sourceId, policyVersion: "1", status: "ACTIVE", rights: { READ: right("READ"), INTERNAL_ANALYSIS: right("INTERNAL_ANALYSIS") }, policyCompleteness: "COMPLETE", interpretationConfidence: "HIGH", immutable: true }));
    state.activeUsagePolicyBySource.set(sourceId, policyId);
    state.resourceBudgets.set("BUDGET-P13-SOCIAL", internal.deepFreeze({ budgetId: "BUDGET-P13-SOCIAL", scopeType: "SOURCE", scopeId: sourceId, parentBudgetId: null, period: { type: "SESSION", startAt: null, endAt: null }, currency: "JPY", limits: { REQUEST_COUNT: { softLimit: 3, hardLimit: 5 }, NETWORK_BYTES: { softLimit: 1000000, hardLimit: 2000000 } }, consumed: { REQUEST_COUNT: 0, NETWORK_BYTES: 0 }, state: "ACTIVE", authorityGranted: false, automaticReallocationAllowed: false, version: 1, createdAt: now, updatedAt: now, immutable: true }));
  }

  async function runExternalIntelligencePhase13Validation() {
    const checks = [];
    const add = function (name, passed, detail, group) { checks.push({ name: name, passed: passed === true, detail: detail == null ? "" : (typeof detail === "string" ? detail : internal.stableStringify(detail)), group: group || "Phase 13", severity: "Critical" }); };
    add("Release is Phase 13 v1.12.0 compatible", VERSION_MANIFEST.isReleaseCompatibleFrom("1.12.0"), VERSION_MANIFEST.release.version, "Foundation");
    add("Implementation Phase is Phase 13", VERSION_MANIFEST.release.phase >= 13, VERSION_MANIFEST.release.implementationPhase, "Foundation");
    add("Phase 13 primary Decision is 034", internal.stableStringify(namespace.modules.phase13Validation.decisions) === internal.stableStringify(["034"]), namespace.modules.phase13Validation.decisions, "Foundation");
    add("Gateway remains unchanged at 1.4.0", VERSION_MANIFEST.isGatewayCompatibleFrom("1.4.0"), VERSION_MANIFEST.gateway.gatewayVersion, "Boundary");

    const phase12 = await namespace.runExternalIntelligencePhase12Validation();
    add("Phase 12 regression remains PASS on later compatible release", phase12.failed === 0 && phase12.health === 100, { passed: phase12.passed, failed: phase12.failed, total: phase12.total }, "Regression");

    const contractKeys = ["socialObservation","socialNarrative","socialNarrativeShift","socialPropagationRecord","socialAuthorProfile","socialCoordinationCandidate","socialAccountCluster","socialAmplificationAssessment","oldInformationResurgence","socialPumpPatternCandidate","socialMarketReaction","socialInfluenceEvaluation","phase13ValidationResult"];
    add("Phase 13 contracts are registered", contractKeys.every(function (key) { return !!namespace.getExternalIntelligenceContract(key); }), contractKeys, "Contract");
    const schemaIds = ["EXTERNAL-010-SCHEMA-SOCIAL-OBSERVATION","EXTERNAL-010-SCHEMA-SOCIAL-NARRATIVE","EXTERNAL-010-SCHEMA-SOCIAL-NARRATIVE-SHIFT","EXTERNAL-010-SCHEMA-SOCIAL-PROPAGATION","EXTERNAL-010-SCHEMA-SOCIAL-AUTHOR-PROFILE","EXTERNAL-010-SCHEMA-SOCIAL-COORDINATION-CANDIDATE","EXTERNAL-010-SCHEMA-SOCIAL-ACCOUNT-CLUSTER","EXTERNAL-010-SCHEMA-SOCIAL-AMPLIFICATION-ASSESSMENT","EXTERNAL-010-SCHEMA-OLD-INFORMATION-RESURGENCE","EXTERNAL-010-SCHEMA-SOCIAL-PUMP-PATTERN-CANDIDATE","EXTERNAL-010-SCHEMA-SOCIAL-MARKET-REACTION","EXTERNAL-010-SCHEMA-SOCIAL-INFLUENCE-EVALUATION","EXTERNAL-010-SCHEMA-PHASE13-VALIDATION-RESULT"];
    add("Phase 13 schemas are registered", schemaIds.every(function (id) { return !!namespace.getExternalIntelligenceSchema(id); }), schemaIds, "Schema");
    add("Decision 034 Social Source Types are governed Source Registry types", VERSION_MANIFEST.socialIntelligence.sourceTypes.every(function (type) { return VERSION_MANIFEST.sourceGovernance.sourceTypes.includes(type); }), VERSION_MANIFEST.socialIntelligence.sourceTypes, "Source Governance");

    const sourceId = "SOURCE-P13-SOCIAL-VALIDATION";
    installGovernanceFixtures(sourceId);
    const governancePass = namespace.checkExternalIntelligenceSocialAcquisitionGovernance({ sourceId: sourceId, operation: "READ", estimatedUsage: { REQUEST_COUNT: 1, NETWORK_BYTES: 1000 }, pricingMode: "FREE" });
    add("Social acquisition passes only through active Source + Usage Policy + Resource Budget governance", governancePass.ok && governancePass.data.usagePolicyChecked && governancePass.data.resourceBudgetChecked && !governancePass.data.tradingAuthorityGranted, governancePass, "Governance");
    const hardBlock = namespace.checkExternalIntelligenceSocialAcquisitionGovernance({ sourceId: sourceId, operation: "READ", estimatedUsage: { REQUEST_COUNT: 6 }, pricingMode: "FREE" });
    add("Social acquisition cannot bypass Resource Hard Cap", hardBlock.ok === false && hardBlock.code === "EXTERNAL010_SOCIAL_RESOURCE_BUDGET_BLOCKED", hardBlock, "Governance");
    state.activeUsagePolicyBySource.delete(sourceId);
    const policyBlock = namespace.checkExternalIntelligenceSocialAcquisitionGovernance({ sourceId: sourceId, operation: "READ", estimatedUsage: { REQUEST_COUNT: 1 }, pricingMode: "FREE" });
    add("UNKNOWN Social Usage Policy fails closed", policyBlock.ok === false && policyBlock.code === "EXTERNAL010_SOCIAL_USAGE_POLICY_OR_SOURCE_BLOCKED", policyBlock, "Governance");
    installGovernanceFixtures(sourceId);

    const repost = namespace.recordExternalIntelligenceSocialObservation({ socialObservationId: "SOCIAL-OBS-P13-REPOST", platformSourceId: sourceId, contentId: "POST-REPOST", accountId: "ACCOUNT-A", contentType: "REPOST", observedAt: internal.nowIso(), originalPublishedAt: "2026-01-01T00:00:00.000Z", currentViralAt: "2026-09-09T00:00:00.000Z", textHash: "abc", engagementMetrics: { views: 1000, reposts: 400 }, sourceEvidenceId: "EVIDENCE-P13-REPOST", rumorState: "RUMOR_CANDIDATE", originalityState: "REPOST", estimatedIndependentOriginId: "ORIGIN-1", aiGeneratedProbability: 0.7, advertisingClassification: "NONE" });
    add("Rumor Social Observation remains Information-layer data, not Event/Truth/Authority", repost.ok && repost.data.socialObservation.rumorState === "RUMOR_CANDIDATE" && repost.data.socialObservation.factualReliabilityDetermined === false && repost.data.socialObservation.eventConfirmed === false && !repost.data.socialObservation.tradingAuthorityGranted, repost.data, "Observation");
    add("Repost is not treated as an independent Opinion", repost.ok && repost.data.socialObservation.independentOpinionEligible === false && repost.data.socialObservation.originalityState === "REPOST", repost.data, "Observation");
    const ad = namespace.recordExternalIntelligenceSocialObservation({ socialObservationId: "SOCIAL-OBS-P13-AD", platformSourceId: sourceId, contentId: "POST-AD", accountId: "ACCOUNT-SPONSOR", contentType: "PROMOTIONAL_CONTENT", observedAt: internal.nowIso(), originalPublishedAt: "2026-09-08T00:00:00.000Z", engagementMetrics: { views: 5000 }, sourceEvidenceId: "EVIDENCE-P13-AD", rumorState: "NOT_RUMOR", originalityState: "ORIGINAL", aiGeneratedProbability: 0.2, advertisingClassification: "PROMOTIONAL" });
    add("Advertising is retained as Social signal data but not treated as independent Opinion", ad.ok && ad.data.socialObservation.advertisingClassification === "PROMOTIONAL" && ad.data.socialObservation.independentOpinionEligible === false, ad.data, "Observation");

    const narrative1 = namespace.recordExternalIntelligenceSocialNarrative({ narrativeId: "NARRATIVE-P13", topic: "Growth Story", supportingSocialObservationIds: ["SOCIAL-OBS-P13-REPOST", "SOCIAL-OBS-P13-AD"], mentionVolume: 400, mentionVelocity: 25, narrativeState: "GROWING", confidence: "MEDIUM" });
    const narrative2 = namespace.recordExternalIntelligenceSocialNarrative({ narrativeId: "NARRATIVE-P13", topic: "Growth Story", supportingSocialObservationIds: ["SOCIAL-OBS-P13-REPOST", "SOCIAL-OBS-P13-AD"], mentionVolume: 520, mentionVelocity: 40, narrativeState: "DOMINANT", confidence: "MEDIUM" });
    add("Narrative is Stable/Versioned Candidate with Mention Count and Velocity separated", narrative1.ok && narrative2.ok && narrative2.data.narrative.version > narrative1.data.narrative.version && narrative2.data.narrative.mentionVolume === 520 && narrative2.data.narrative.mentionVelocity === 40 && narrative2.data.narrative.candidateOnly && !narrative2.data.narrative.truthConfirmed, narrative2.data, "Narrative");
    const shift = namespace.recordExternalIntelligenceSocialNarrativeShift({ narrativeId: "NARRATIVE-P13", fromState: "DOMINANT", toState: "REVERSING", previousTopic: "Growth Story", currentTopic: "Overvaluation Concern" });
    add("Narrative Shift is a Signal Candidate, not Event confirmation", shift.ok && shift.data.narrativeShift.signalCandidate && !shift.data.narrativeShift.eventConfirmed, shift.data, "Narrative");
    const propagation = namespace.recordExternalIntelligenceSocialPropagation({ subjectType: "NARRATIVE", subjectId: narrative2.data.narrative.narrativeRecordId, mentionCount: 1000, mentionVelocity: 50, propagationVelocity: 120, communitySourceIds: ["COMM-A","COMM-B","COMM-C"], estimatedIndependentOrigins: 120, engagementMetrics: { reposts: 600 } });
    add("Propagation keeps Mention Count / Velocity / Propagation / Cross-Community / Independent Origin dimensions separate", propagation.ok && propagation.data.propagation.mentionCount === 1000 && propagation.data.propagation.mentionVelocity === 50 && propagation.data.propagation.propagationVelocity === 120 && propagation.data.propagation.crossCommunitySpreadCount === 3 && propagation.data.propagation.estimatedIndependentOrigins === 120 && !propagation.data.propagation.rawMentionCountEqualsIndependentOpinions, propagation.data, "Propagation");

    const coordination = namespace.recordExternalIntelligenceSocialCoordinationCandidate({ accountIds: ["ACCOUNT-A","ACCOUNT-B"], evidenceRefs: ["SOCIAL-OBS-P13-REPOST"], coordinationInputs: { sameText: true, similarTiming: true }, coordinationConfidence: "HIGH" });
    add("Coordination Candidate proves neither same person nor illegal manipulation", coordination.ok && !coordination.data.coordinationCandidate.samePersonConfirmed && !coordination.data.coordinationCandidate.illegalManipulationProven, coordination.data, "Coordination");
    const cluster = namespace.recordExternalIntelligenceSocialAccountCluster({ memberAccountIds: ["ACCOUNT-A","ACCOUNT-B"], behaviorSimilarity: 0.9, timingSimilarity: 0.8, contentSimilarity: 0.95, coordinationConfidence: "HIGH" });
    add("Account Cluster does not resolve real-person identity", cluster.ok && !cluster.data.accountCluster.samePersonConfirmed && !cluster.data.accountCluster.realPersonIdentityResolved, cluster.data, "Privacy");
    const amplification = namespace.recordExternalIntelligenceSocialAmplificationAssessment({ subjectId: narrative2.data.narrative.narrativeRecordId, organicInfluence: 0.4, artificialAmplification: 0.6, botProbability: 0.8, aiGeneratedProbability: 0.7, advertisingShare: 0.2 });
    add("Bot/AI/Artificial activity is not simply excluded from Market Impact analysis", amplification.ok && amplification.data.amplificationAssessment.marketImpactEligible && !amplification.data.amplificationAssessment.botIdentityProven && amplification.data.amplificationAssessment.aiGeneratedProbability === 0.7, amplification.data, "Amplification");
    const resurgence = namespace.recordExternalIntelligenceOldInformationResurgence({ socialObservationId: "SOCIAL-OBS-P13-REPOST", currentViralAt: "2026-09-09T00:00:00.000Z", resurgenceVelocity: 70 });
    add("Old Information Resurgence is detectable without creating a New Event", resurgence.ok && resurgence.data.resurgence.ageMs > 0 && !resurgence.data.resurgence.newEventCreated && resurgence.data.resurgence.currentMarketImpactEligible, resurgence.data, "Temporal");
    const pump = namespace.recordExternalIntelligenceSocialPumpPatternCandidate({ subjectEntityId: "ENTITY-P13", signalRefs: ["SOCIAL-OBS-P13-REPOST"], patternInputs: { mentionSpike: true, volumeSpike: true, rapidReversal: true }, patternSimilarity: 0.75, marketManipulationRisk: "HIGH" });
    add("Pump Pattern remains Candidate and never becomes legal/manipulation conclusion", pump.ok && pump.data.pumpPatternCandidate.candidateOnly && !pump.data.pumpPatternCandidate.illegalManipulationProven && !pump.data.pumpPatternCandidate.legalConclusionReached && !pump.data.pumpPatternCandidate.tradingAuthorityGranted, pump.data, "Pump Boundary");

    const author1 = namespace.recordExternalIntelligenceSocialAuthorProfile({ accountProfileId: "AUTHOR-P13-A", platformSourceId: sourceId, accountId: "ACCOUNT-A", historicalRelevantPostCount: 10, historicalFactualAccuracy: "LOW", historicalMarketReactionFrequency: 0.7, medianReactionLag: 1800000, historicalFalseSignalRate: 0.3 });
    const author2 = namespace.recordExternalIntelligenceSocialAuthorProfile({ accountProfileId: "AUTHOR-P13-A", platformSourceId: sourceId, accountId: "ACCOUNT-A", historicalRelevantPostCount: 25, historicalFactualAccuracy: "MEDIUM", historicalMarketReactionFrequency: 0.65, medianReactionLag: 1500000, historicalFalseSignalRate: 0.35 });
    const authorHistory = namespace.listExternalIntelligenceSocialAuthorProfileHistory("AUTHOR-P13-A");
    add("Author Historical Influence accumulates as versioned history", author1.ok && author2.ok && authorHistory.length >= 2 && authorHistory[authorHistory.length - 1].version > authorHistory[0].version, authorHistory, "Author");
    add("Author Accuracy and Influence are separate under Pseudonymous identity", author2.ok && author2.data.authorProfile.historicalFactualAccuracy === "MEDIUM" && author2.data.authorProfile.historicalMarketReactionFrequency === 0.65 && !author2.data.authorProfile.accuracyEqualsInfluence && author2.data.authorProfile.identityMode === "PSEUDONYMOUS_ACCOUNT", author2.data, "Author");

    const baseline = namespace.registerExternalIntelligenceSignalBaseline({ baselineId: "BASELINE-P13-SOCIAL", baselineVersion: 1, baselineType: "HISTORICAL_BASELINE", referenceWindow: "P30D", referenceValues: { mentionVelocity: 5 } });
    const socialSignal = namespace.createExternalIntelligenceSocialSignalHook({ signalId: "SIGNAL-P13-SOCIAL", signalClusterId: "CLUSTER-P13-SOCIAL", baselineId: "BASELINE-P13-SOCIAL", socialObservationIds: ["SOCIAL-OBS-P13-REPOST", "SOCIAL-OBS-P13-AD"], signalType: "SOCIAL_NARRATIVE_SHIFT", anomalyStrength: 0.8, novelty: 0.7, persistence: 0.6, confidence: "MEDIUM" });
    add("Decision 032 integration produces governed Social Signal + Signal Cluster without authority/event confirmation", baseline.ok && socialSignal.ok && socialSignal.data.decision032Integrated && !socialSignal.data.signal.actionAuthorityGranted && !socialSignal.data.signal.financialAuthorityGranted && !socialSignal.data.signalCluster.confirmedEvent, socialSignal.data, "Decision 032 Integration");
    const research = namespace.createExternalIntelligenceSocialResearchHook({ researchQuestionId: "RQ-P13-SOCIAL", question: "Why is this social narrative spreading?", signalIds: ["SIGNAL-P13-SOCIAL"], hypotheses: [{ hypothesisId: "HYP-P13-EVENT", statement: "A real external event is driving the narrative", supportingEvidenceIds: [], contradictingEvidenceIds: [], missingEvidence: ["official source"], falsificationCriteria: ["no official corroboration"], hypothesisState: "INCONCLUSIVE" }, { hypothesisId: "HYP-P13-OLD", statement: "Old information resurfacing is driving the narrative", supportingEvidenceIds: ["EVIDENCE-P13-REPOST"], contradictingEvidenceIds: [], missingEvidence: [], falsificationCriteria: ["new primary source appears"], hypothesisState: "INCONCLUSIVE" }] });
    add("Decision 033 integration preserves competing Social hypotheses instead of first-explanation truth", research.ok && research.data.decision033Integrated && research.data.hypotheses.length === 2 && research.data.hypotheses.every(function (h) { return h.hypothesisEqualsFact === false && h.hypothesisState === "INCONCLUSIVE"; }), research.data, "Decision 033 Integration");

    const metrics = ["PRICE","VOLUME","VOLATILITY"], outcomeIds = [];
    metrics.forEach(function (metric) { const benchmarkId = "BENCH-P13-" + metric, outcomeId = "OUTCOME-P13-" + metric; namespace.registerExternalIntelligenceBenchmarkDefinition({ benchmarkDefinitionId: benchmarkId, targetMetric: metric, measurementMethod: "VALIDATION_FIXTURE", targetWindow: "1H" }); namespace.registerExternalIntelligenceOutcome({ outcomeId: outcomeId, benchmarkDefinitionId: benchmarkId, outcomeType: "MARKET_REACTION", targetMetric: metric, settlementState: "FINAL", value: { change: 0 }, supportingEvidenceIds: ["EVIDENCE-P13-OUTCOME-" + metric] }); outcomeIds.push(outcomeId); });
    const reaction = namespace.recordExternalIntelligenceSocialMarketReaction({ marketReactionId: "MARKET-REACTION-P13", socialSignalRef: "SIGNAL-P13-SOCIAL", targetEntityId: "ENTITY-P13", timeline: [{ offsetMs: 0, event: "MENTION_SPIKE" }, { offsetMs: 900000, event: "SEARCH_SPIKE" }, { offsetMs: 1500000, event: "VOLUME_SPIKE" }, { offsetMs: 2400000, event: "PRICE_MOVE" }], dimensions: { PRICE_DIRECTION: 0, VOLUME: 0, VOLATILITY: 0 }, absoluteReaction: { return: 0, volumeChange: 0, volatilityChange: 0 }, relativeReaction: { marketAdjustedReturn: 0, sectorAdjustedReturn: 0 }, referenceOutcomeIds: outcomeIds, leadTimeMs: 1500000 });
    add("Market Reaction separates Social Influence from observed Price/Volume/Volatility Outcomes and stores Lag", reaction.ok && reaction.data.marketReaction.leadTimeMs === 1500000 && reaction.data.marketReaction.referenceOutcomeIds.length === 3 && Object.prototype.hasOwnProperty.call(reaction.data.marketReaction.dimensions, "PRICE_DIRECTION") && Object.prototype.hasOwnProperty.call(reaction.data.marketReaction.dimensions, "VOLUME") && Object.prototype.hasOwnProperty.call(reaction.data.marketReaction.dimensions, "VOLATILITY") && !reaction.data.marketReaction.causationConfirmed && !reaction.data.marketReaction.tradingAuthorityGranted, reaction.data, "Outcome");
    const impactHook = namespace.createExternalIntelligenceSocialImpactHook({ marketReactionId: "MARKET-REACTION-P13", impactEdgeId: "IMPACT-P13-SOCIAL", impactDimension: "MARKET_PRICE", direction: "NEUTRAL", impactStrength: 0, confidence: 0.4, historicalSampleCount: 10, candidateConfounders: ["MARKET_MOVE", "SECTOR_MOVE"] });
    add("Decision 029 Temporal Impact Graph integration remains Influence Candidate, not causation", impactHook.ok && impactHook.data.decision029Integrated && impactHook.data.impactEdge.causalState === "INFLUENCE_CANDIDATE" && impactHook.data.impactEdge.causalTruthConfirmed === false && impactHook.data.impactEdge.financialAuthorityGranted === false, impactHook.data, "Decision 029 Integration");
    const evaluation = namespace.recordExternalIntelligenceSocialInfluenceEvaluation({ socialInfluenceEvaluationId: "INFLUENCE-EVAL-P13", subjectType: "NARRATIVE", subjectId: "NARRATIVE-P13", marketReactionIds: ["MARKET-REACTION-P13"], sampleCount: 10, historicalPredictiveness: 0.4, reactionFrequency: 0.6, medianLeadTimeMs: 1500000, falsePositiveRate: 0.4, confidence: "LOW", leadingIndicatorCandidate: true });
    add("Outcome-grounded learning preserves False Social Signals and can produce Social Leading Indicator Candidate", evaluation.ok && evaluation.data.evaluation.falseSignalsPreserved && evaluation.data.evaluation.falsePositiveRate === 0.4 && evaluation.data.evaluation.leadingIndicatorCandidate && !evaluation.data.evaluation.causationConfirmed && !evaluation.data.evaluation.financialAuthorityGranted && !evaluation.data.evaluation.tradingAuthorityGranted, evaluation.data, "Learning");
    const predictionHook = namespace.createExternalIntelligenceSocialPredictionHook({ predictionId: "PRED-P13-SOCIAL", subjectRef: "INFLUENCE-EVAL-P13", predictionType: "SOCIAL_MARKET_REACTION_CANDIDATE", probabilityState: "QUALITATIVE", estimateConfidence: "LOW", evidenceStrength: "LOW", historicalSampleCount: 10, uncertaintyFactors: ["BOT_AMPLIFICATION", "MARKET_CONFOUNDER"], outcomeReference: "OUTCOME-P13-PRICE", calibrationState: "UNASSESSED" });
    add("Decision 030 Uncertainty/Calibration integration avoids invented probability", predictionHook.ok && predictionHook.data.decision030Integrated && predictionHook.data.prediction.probability === null && predictionHook.data.prediction.probabilityInvented === false && predictionHook.data.prediction.historicalSampleCount === 10, predictionHook.data, "Decision 030 Integration");
    add("Decision 031 Reference Outcome integration is explicit and versioned", reaction.ok && outcomeIds.every(function (id) { const outcome = namespace.getExternalIntelligenceOutcome(id); return outcome && outcome.settlementState === "FINAL" && reaction.data.marketReaction.referenceOutcomeIds.includes(id); }), outcomeIds, "Decision 031 Integration");

    const reverseNarrative = namespace.traceExternalIntelligenceReverseProvenance(narrative2.data.narrative.narrativeRecordId, 4);
    const reverseReaction = namespace.traceExternalIntelligenceReverseProvenance("MARKET-REACTION-P13", 4);
    add("Evidence/Derived Lineage links Social Evidence -> Observation -> Narrative and Signal/Outcome -> Market Reaction", reverseNarrative.references.some(function (x) { return x.referenceId === "SOCIAL-OBS-P13-REPOST"; }) && reverseReaction.references.some(function (x) { return x.referenceId === "SIGNAL-P13-SOCIAL"; }) && reverseReaction.references.some(function (x) { return x.referenceId === "OUTCOME-P13-PRICE"; }), { narrative: reverseNarrative.references, reaction: reverseReaction.references }, "Lineage");

    const badCoordination = internal.clone(coordination.data.coordinationCandidate); badCoordination.samePersonConfirmed = true;
    const coordContract = namespace.validateExternalIntelligenceContract("socialCoordinationCandidate", badCoordination), coordSchema = namespace.validateExternalIntelligenceRecord("EXTERNAL-010-SCHEMA-SOCIAL-COORDINATION-CANDIDATE", badCoordination);
    add("Malformed Coordination -> Same Person escalation is rejected by Contract and Schema", !coordContract.valid && !coordSchema.valid, { contract: coordContract.valid, schema: coordSchema.valid }, "Negative Validation");
    const badPump = internal.clone(pump.data.pumpPatternCandidate); badPump.illegalManipulationProven = true;
    const pumpContract = namespace.validateExternalIntelligenceContract("socialPumpPatternCandidate", badPump), pumpSchema = namespace.validateExternalIntelligenceRecord("EXTERNAL-010-SCHEMA-SOCIAL-PUMP-PATTERN-CANDIDATE", badPump);
    add("Pump Pattern -> Illegal Manipulation escalation is rejected by Contract and Schema", !pumpContract.valid && !pumpSchema.valid, { contract: pumpContract.valid, schema: pumpSchema.valid }, "Negative Validation");
    const badObservation = internal.clone(repost.data.socialObservation); badObservation.eventConfirmed = true;
    const observationContract = namespace.validateExternalIntelligenceContract("socialObservation", badObservation), observationSchema = namespace.validateExternalIntelligenceRecord("EXTERNAL-010-SCHEMA-SOCIAL-OBSERVATION", badObservation);
    add("Rumor/Social Observation -> Event confirmation escalation is rejected", !observationContract.valid && !observationSchema.valid, { contract: observationContract.valid, schema: observationSchema.valid }, "Negative Validation");

    const safetyKeys = ["socialPopularityEqualsTruth","sentimentEqualsFact","rumorEqualsEvent","highEngagementEqualsReliability","manyPostsEqualsIndependentOpinions","crowdConsensusEqualsIndependentConsensus","authorAccuracyEqualsAuthorInfluence","authorInfluenceEqualsCausation","postBeforeMarketMoveEqualsCausation","botActivityEqualsNoMarketImpact","aiGeneratedContentEqualsNoMarketImpact","advertisingEqualsNoSignal","coordinationCandidateEqualsSamePersonConfirmed","coordinationCandidateEqualsIllegalManipulation","pumpPatternEqualsIllegalManipulationProven","oldInformationEqualsNoCurrentImpact","oldInformationEqualsNewEvent","rumorVolumeEqualsEventConfirmation","behaviorSimilarityGrantsRealIdentity","socialSignalGrantsTradingAuthority","socialSignalGrantsFinancialAuthority"];
    add("All Decision 034 Safety Rules remain fail-closed", safetyKeys.every(function (key) { return VERSION_MANIFEST.safety[key] === false; }), safetyKeys, "Safety");
    add("Final Reliability Authority remains EXTERNAL-020", namespace.modules.socialInfluence.finalReliabilityAuthority === "EXTERNAL-020", namespace.modules.socialInfluence.finalReliabilityAuthority, "Reliability Boundary");

    const criteriaCovered = 23;
    const coverage = { decisionId: "EXTERNAL-010-DECISION-034", successCriteriaTotal: 23, successCriteriaCovered: criteriaCovered, missingCriteria: [], requirementReductionAllowed: false, decision029To033Integration: true, usagePolicyPrivacyBudgetMaintained: true };
    add("Decision 034 Success Criteria coverage is 23 / 23 with no requirement reduction", coverage.successCriteriaCovered === coverage.successCriteriaTotal && coverage.missingCriteria.length === 0 && coverage.requirementReductionAllowed === false, coverage, "Requirement Conformance");

    const passed = checks.filter(function (item) { return item.passed; }).length, failed = checks.length - passed;
    const result = { id: internal.nextId("EXTERNAL-010-PHASE13-VALIDATION"), componentId: "EXTERNAL-010", version: VERSION_MANIFEST.release.version, gatewayVersion: VERSION_MANIFEST.gateway.gatewayVersion, implementationPhase: VERSION_MANIFEST.release.implementationPhase, decisionCoverage: 54, requirementCoverage: coverage, passed: passed, failed: failed, total: checks.length, health: Number((passed / checks.length * 100).toFixed(1)), criticalFailed: failed, status: failed === 0 ? "EXTERNAL-010 Phase 13 Validation PASS" : "EXTERNAL-010 Phase 13 Validation FAIL", releaseAllowed: failed === 0, phase13Complete: failed === 0, phase14Allowed: failed === 0, checks: checks, validatedAt: internal.nowIso(), immutable: true };
    state.latestPhase13Validation = internal.deepFreeze(internal.clone(result));
    return internal.clone(result);
  }
  Object.assign(namespace.api, { runExternalIntelligencePhase13Validation }); Object.assign(namespace, namespace.api);
  namespace.modules.phase13Validation = { id: "EXTERNAL-010-PHASE13-VALIDATION", version: MODULE_VERSION, status: "Ready", phase: 13, decisions: ["034"], decision034SuccessCriteria: 23, requirementReductionAllowed: false, loadedAt: internal.nowIso() };
  global.runExternalIntelligencePhase13Validation = runExternalIntelligencePhase13Validation;
})(typeof window !== "undefined" ? window : globalThis);
