/* ============================================================
   FILE: 17_external_intelligence_phase8_validation.js
   EXTERNAL-010 External Intelligence Platform
   Release: 1.7.0
   Phase 08 Validation: Analytical Capability Registry / Unified Lineage
   Primary Decisions: 036 / 037
   ============================================================ */
(function (global) {
  "use strict";
  const namespace = global.EXTERNAL010ExternalIntelligence;
  const VERSION_MANIFEST = global.EXTERNAL010VersionManifest;
  if (!namespace || !namespace.__internal || !VERSION_MANIFEST) { console.warn("EXTERNAL-010 Phase 08 validation blocked: dependencies missing."); return; }
  const internal = namespace.__internal, state = internal.state;
  const MODULE_VERSION = VERSION_MANIFEST.getModuleVersion("phase8Validation");
  function collector(){const checks=[];return{checks,check(name,passed,detail,group,severity){checks.push({name,passed:passed===true,detail:detail==null?"":(typeof detail==="string"?detail:internal.stableStringify(detail)),group:group||"General",severity:severity||"Critical"});}};}
  function summarize(checks){const passed=checks.filter(x=>x.passed).length,failed=checks.length-passed,criticalFailed=checks.filter(x=>!x.passed&&x.severity==="Critical").length;return{passed,failed,total:checks.length,criticalFailed,health:checks.length?Math.round(passed/checks.length*1000)/10:0};}

  async function runExternalIntelligencePhase8Validation(){
    const c=collector(),check=c.check; let localCap=null,externalCap=null,reviewerCap=null,routing=null,snapshot=null,transform=null,lineage1=null,lineage2=null;
    try {
      check("Release Version is 1.7.0",VERSION_MANIFEST.release.version==="1.7.0",VERSION_MANIFEST.release.version,"Foundation");
      check("Implementation Phase is Phase 08",VERSION_MANIFEST.release.phase===8&&VERSION_MANIFEST.release.implementationPhase.indexOf("Phase 08")===0,VERSION_MANIFEST.release.implementationPhase,"Foundation");
      check("Phase 08 primary Decisions are 036/037",internal.stableStringify(namespace.modules.phase8Validation.decisions)===internal.stableStringify(["036","037"]),namespace.modules.phase8Validation,"Foundation");
      check("Gateway remains unchanged at 1.4.0",VERSION_MANIFEST.gateway.gatewayVersion==="1.4.0",VERSION_MANIFEST.gateway.gatewayVersion,"Boundary");

      const init=await namespace.initializeExternalIntelligenceFoundation(); check("Phase 08 foundation initializes",init&&init.ok===true,init&&init.code,"Initialization");
      const p7=await namespace.runExternalIntelligencePhase7Validation(); check("Phase 07 regression remains PASS",p7.failed===0&&p7.health===100&&p7.phase7Complete===true,{passed:p7.passed,failed:p7.failed,total:p7.total},"Regression");

      const contractKeys=["analyticalCapability","capabilityPerformanceProfile","capabilityRoutingCandidate","analysisExecutionRecord","independentReviewPlan","shadowEvaluationRecord","capabilityFallbackRecord","snapshotManifest","transformationRecord","lineageRecord","recomputeCandidate","phase8ValidationResult"];
      contractKeys.forEach(key=>check("Contract "+key+" is registered",Boolean(namespace.getExternalIntelligenceContract(key)),key,"Contracts"));
      const schemaIds=["EXTERNAL-010-SCHEMA-ANALYTICAL-CAPABILITY","EXTERNAL-010-SCHEMA-CAPABILITY-PERFORMANCE-PROFILE","EXTERNAL-010-SCHEMA-CAPABILITY-ROUTING-CANDIDATE","EXTERNAL-010-SCHEMA-ANALYSIS-EXECUTION-RECORD","EXTERNAL-010-SCHEMA-INDEPENDENT-REVIEW-PLAN","EXTERNAL-010-SCHEMA-SHADOW-EVALUATION-RECORD","EXTERNAL-010-SCHEMA-CAPABILITY-FALLBACK-RECORD","EXTERNAL-010-SCHEMA-SNAPSHOT-MANIFEST","EXTERNAL-010-SCHEMA-TRANSFORMATION-RECORD","EXTERNAL-010-SCHEMA-LINEAGE-RECORD","EXTERNAL-010-SCHEMA-RECOMPUTE-CANDIDATE","EXTERNAL-010-SCHEMA-PHASE8-VALIDATION-RESULT"];
      schemaIds.forEach(id=>check("Schema "+id+" is registered",Boolean(namespace.getExternalIntelligenceSchema(id)),id,"Schemas"));

      localCap=namespace.registerExternalIntelligenceAnalyticalCapability({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",recordVersion:"1.0.0",capabilityType:"RULE_ENGINE",providerId:"LOCAL",modelFamily:"DETERMINISTIC_RULE",modelVersion:"N/A",algorithmVersion:"1.0.0",supportedTasks:["CLAIM_REVIEW","GENERAL_ANALYSIS"],supportedDomains:["GENERAL","MARKET"],supportedHorizons:["ANY","SHORT"],supportedInputTypes:["TEXT","JSON"],costProfile:{pricingMode:"FREE",estimatedCost:0,currency:"JPY"},latencyProfile:{class:"LOW",estimatedMs:5},availabilityState:"READY",executionLocation:"BROWSER",dataHandlingPolicy:{externalTransmissionAllowed:false,allowedDataClasses:["ANY"]},roles:["PRIMARY"],outputClassifications:["MODEL_ANALYSIS","CLASSIFICATION"]});
      check("Stable local Analytical Capability registers",localCap.ok===true&&localCap.data.analyticalCapability.capabilityId==="EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",localCap.data||localCap.code,"Capability Registry");
      externalCap=namespace.registerExternalIntelligenceAnalyticalCapability({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-OPENAI-CANDIDATE",recordVersion:"1.0.0",capabilityType:"EXTERNAL_AI_SERVICE",providerId:"OPENAI",modelFamily:"OPENAI_API",modelVersion:"UNBOUND",algorithmVersion:"N/A",supportedTasks:["GENERAL_ANALYSIS","CLAIM_REVIEW"],supportedDomains:["GENERAL","MARKET"],supportedHorizons:["ANY","SHORT"],supportedInputTypes:["TEXT","JSON"],costProfile:{pricingMode:"PAID",estimatedCost:0.01,currency:"USD"},latencyProfile:{class:"NETWORK",estimatedMs:null},availabilityState:"EXPERIMENTAL",executionLocation:"LOCAL_GATEWAY",dataHandlingPolicy:{externalTransmissionAllowed:true,allowedDataClasses:["PUBLIC","DERIVED"]},secretReferenceId:"SECRET-OPENAI-PHASE8-REFERENCE-CANDIDATE",roles:["SHADOW","EXPERIMENTAL"],outputClassifications:["MODEL_ANALYSIS","SUMMARY"]});
      check("External AI Capability stores Secret reference only",externalCap.ok===true&&externalCap.data.analyticalCapability.secretReferenceId==="SECRET-OPENAI-PHASE8-REFERENCE-CANDIDATE"&&externalCap.data.analyticalCapability.secretValueStored===false,externalCap.data||externalCap.code,"Secret Boundary");
      const secretReject=namespace.registerExternalIntelligenceAnalyticalCapability({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-SECRET-REJECT",capabilityType:"EXTERNAL_AI_SERVICE",availabilityState:"READY",apiKey:"sk-phase8-should-never-store"});
      check("Provider Secret value in Capability registration is rejected",secretReject.ok===false&&secretReject.code==="EXTERNAL010_CAPABILITY_SECRET_VALUE_REJECTED",secretReject,"Secret Boundary");
      reviewerCap=namespace.registerExternalIntelligenceAnalyticalCapability({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-REVIEWER",recordVersion:"1.0.0",capabilityType:"ALGORITHM",providerId:"LOCAL",modelFamily:"INDEPENDENT_REVIEW",modelVersion:"N/A",algorithmVersion:"1.0.0",supportedTasks:["CLAIM_REVIEW"],supportedDomains:["GENERAL"],supportedHorizons:["ANY"],supportedInputTypes:["TEXT"],costProfile:{pricingMode:"FREE",estimatedCost:0,currency:"JPY"},latencyProfile:{class:"LOW",estimatedMs:10},availabilityState:"READY",executionLocation:"BROWSER",dataHandlingPolicy:{externalTransmissionAllowed:false,allowedDataClasses:["ANY"]},roles:["REVIEWER","FALSIFICATION_REVIEWER"],outputClassifications:["MODEL_ANALYSIS"]});
      check("Independent Reviewer Capability registers separately",reviewerCap.ok===true&&reviewerCap.data.analyticalCapability.roles.includes("REVIEWER"),reviewerCap.data||reviewerCap.code,"Capability Registry");

      const v2=namespace.registerExternalIntelligenceAnalyticalCapability({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",recordVersion:"1.1.0",capabilityType:"RULE_ENGINE",providerId:"LOCAL",modelFamily:"DETERMINISTIC_RULE",modelVersion:"N/A",algorithmVersion:"1.1.0",supportedTasks:["CLAIM_REVIEW","GENERAL_ANALYSIS"],supportedDomains:["GENERAL","MARKET"],supportedHorizons:["ANY","SHORT"],supportedInputTypes:["TEXT","JSON"],costProfile:{pricingMode:"FREE",estimatedCost:0,currency:"JPY"},latencyProfile:{class:"LOW",estimatedMs:4},availabilityState:"READY",executionLocation:"BROWSER",dataHandlingPolicy:{externalTransmissionAllowed:false,allowedDataClasses:["ANY"]},roles:["PRIMARY"],outputClassifications:["MODEL_ANALYSIS","CLASSIFICATION"]});
      check("Stable Capability ID preserves versioned history",v2.ok===true&&namespace.getExternalIntelligenceAnalyticalCapability("EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE","1.0.0").recordVersion==="1.0.0"&&namespace.getExternalIntelligenceAnalyticalCapability("EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE").recordVersion==="1.1.0",v2.data||v2.code,"Capability Versioning");
      const perf=namespace.recordExternalIntelligenceCapabilityPerformanceProfile({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",taskType:"CLAIM_REVIEW",domain:"GENERAL",horizon:"SHORT",evaluationType:"HISTORICAL",sampleCount:20,metrics:{accuracy:0.85},outcomeGrounded:true,evaluationEvidenceRefs:["EVIDENCE-PHASE8-PERFORMANCE"]});
      check("Outcome-grounded Performance is evidence record, not authority",perf.ok===true&&perf.data.performanceProfile.outcomeGrounded===true&&perf.data.performanceProfile.performanceGrantsActionAuthority===false,perf.data||perf.code,"Capability Performance");

      routing=namespace.createExternalIntelligenceCapabilityRoutingCandidate({taskType:"CLAIM_REVIEW",domain:"GENERAL",horizon:"SHORT",inputType:"TEXT",dataClass:"PUBLIC",requiresExternalTransmission:false,maxEstimatedCost:1});
      check("Task/Domain/Horizon-aware routing returns Candidate set",routing.ok===true&&routing.data.routingCandidate.eligibleCapabilityIds.includes("EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE")&&routing.data.routingCandidate.automaticWinnerSelected===false,routing.data||routing.code,"Routing");
      const sensitiveRoute=namespace.createExternalIntelligenceCapabilityRoutingCandidate({taskType:"CLAIM_REVIEW",domain:"GENERAL",horizon:"SHORT",inputType:"TEXT",dataClass:"SENSITIVE",requiresExternalTransmission:true,maxEstimatedCost:1});
      const extDetail=sensitiveRoute.data&&sensitiveRoute.data.routingCandidate&&sensitiveRoute.data.routingCandidate.candidateDetails.find(x=>x.capabilityId==="EXTERNAL-010-CAPABILITY-PHASE8-OPENAI-CANDIDATE");
      check("External transmission obeys Data Policy instead of model capability alone",Boolean(extDetail&&extDetail.eligible===false&&extDetail.reasons.includes("DATA_POLICY_BLOCKED")),extDetail,"Routing Policy");
      const review=namespace.createExternalIntelligenceIndependentReviewPlan({primaryCapabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",reviewerCapabilityIds:["EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE","EXTERNAL-010-CAPABILITY-PHASE8-REVIEWER"],purpose:"FALSIFICATION_REVIEW"});
      check("Independent Review excludes Primary Capability",review.ok===true&&review.data.reviewPlan.primaryExcludedFromReviewerSet===true&&!review.data.reviewPlan.reviewerCapabilityIds.includes("EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE"),review.data||review.code,"Independent Review");
      const shadow=namespace.createExternalIntelligenceShadowEvaluationRecord({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-OPENAI-CANDIDATE",comparedWithCapabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",taskType:"CLAIM_REVIEW",domain:"GENERAL",horizon:"SHORT",metrics:{agreement:0.9},shadowSuccess:true,evaluationEvidenceRefs:["EVIDENCE-PHASE8-SHADOW"]});
      check("Shadow success never auto-promotes Capability",shadow.ok===true&&shadow.data.shadowEvaluation.shadowSuccess===true&&shadow.data.shadowEvaluation.automaticPromotionPerformed===false,shadow.data||shadow.code,"Shadow Evaluation");
      const fallback=namespace.createExternalIntelligenceCapabilityFallbackRecord({requestedCapabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-OPENAI-CANDIDATE",executedCapabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",reason:"UNAVAILABLE",policyRevalidated:true,costRevalidated:true,dataPolicyRevalidated:true});
      check("Fallback is explicit and cannot silently bypass policy",fallback.ok===true&&fallback.data.fallbackRecord.silentFallback===false&&fallback.data.fallbackRecord.fallbackCanBypassPolicy===false,fallback.data||fallback.code,"Fallback");
      const execution=namespace.createExternalIntelligenceAnalysisExecutionRecord({capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",taskType:"CLAIM_REVIEW",domain:"GENERAL",horizon:"SHORT",inputReferenceIds:["CLAIM-PHASE8-INPUT"],outputReferenceIds:["ANALYSIS-PHASE8-OUTPUT"],outputClassification:"MODEL_ANALYSIS",executionState:"RECORDED",externalTransmissionPerformed:false,externalTransmissionPolicyValidated:true});
      check("Analysis Output classification preserves Evidence/Authority boundary",execution.ok===true&&execution.data.analysisExecution.aiAnalysisEqualsPrimaryEvidence===false&&execution.data.analysisExecution.repositoryAuthorityGranted===false&&execution.data.analysisExecution.financialAuthorityGranted===false,execution.data||execution.code,"Analysis Output");

      snapshot=namespace.createExternalIntelligenceSnapshotManifest({purpose:"PHASE8_VALIDATION",references:[{referenceId:"CLAIM-PHASE8-INPUT",recordType:"CLAIM_CANDIDATE",versionId:"1.0.0",contentHash:"hash-input"},{referenceId:"ANALYSIS-PHASE8-OUTPUT",recordType:"MODEL_ANALYSIS",versionId:"1.0.0",contentHash:"hash-output"}],configurationVersion:"1.0.0"});
      check("Snapshot Manifest captures historical input versions",snapshot.ok===true&&snapshot.data.snapshotManifest.snapshotBasedReproducibility===true&&snapshot.data.snapshotManifest.references.length===2,snapshot.data||snapshot.code,"Lineage Snapshot");
      transform=namespace.createExternalIntelligenceTransformationRecord({transformationType:"REVIEW",transformationVersion:"1.0.0",capabilityId:"EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE",inputReferenceIds:["CLAIM-PHASE8-INPUT"],outputReferenceIds:["ANALYSIS-PHASE8-OUTPUT"],snapshotManifestId:snapshot.data.snapshotManifest.snapshotManifestId,status:"SUCCESS",configurationVersion:"1.0.0"});
      check("Transformation Record binds Capability + Versioned Snapshot",transform.ok===true&&transform.data.transformationRecord.capabilityId==="EXTERNAL-010-CAPABILITY-PHASE8-LOCAL-RULE"&&transform.data.transformationRecord.snapshotManifestId===snapshot.data.snapshotManifest.snapshotManifestId,transform.data||transform.code,"Transformation Lineage");
      lineage1=namespace.createExternalIntelligenceLineageRecord({inputReferenceId:"CLAIM-PHASE8-INPUT",outputReferenceId:"ANALYSIS-PHASE8-OUTPUT",relationType:"REVIEWED_FROM",transformationId:transform.data.transformationRecord.transformationId,lineageState:"ACTIVE"});
      lineage2=namespace.createExternalIntelligenceLineageRecord({inputReferenceId:"ANALYSIS-PHASE8-OUTPUT",outputReferenceId:"INTELLIGENCE-PHASE8-PACKAGE",relationType:"DERIVED_FROM",lineageState:"ACTIVE"});
      check("Unified Lineage stores derivation edges",lineage1.ok===true&&lineage2.ok===true&&state.lineageRecords.size>=2,{lineageCount:state.lineageRecords.size},"Lineage Graph");
      const forward=namespace.traceExternalIntelligenceForwardDependencies("CLAIM-PHASE8-INPUT",8), reverse=namespace.traceExternalIntelligenceReverseProvenance("INTELLIGENCE-PHASE8-PACKAGE",8);
      check("Forward Dependency query traces blast path",forward.references.some(x=>x.referenceId==="INTELLIGENCE-PHASE8-PACKAGE"),forward,"Lineage Query");
      check("Reverse Provenance query traces source path",reverse.references.some(x=>x.referenceId==="CLAIM-PHASE8-INPUT"),reverse,"Lineage Query");
      const cycle=namespace.createExternalIntelligenceLineageRecord({inputReferenceId:"INTELLIGENCE-PHASE8-PACKAGE",outputReferenceId:"CLAIM-PHASE8-INPUT",relationType:"DERIVED_FROM",lineageState:"ACTIVE"});
      check("Derivation cycle is fail-closed",cycle.ok===false&&cycle.code==="EXTERNAL010_DERIVATION_CYCLE_REJECTED",cycle,"Lineage Safety");
      const blast=namespace.analyzeExternalIntelligenceBlastRadius({referenceId:"CLAIM-PHASE8-INPUT",maxDepth:8});
      check("Blast Radius marks affected without declaring invalid",blast.ok===true&&blast.data.affectedReferences.length>=2&&blast.data.affectedEqualsInvalid===false&&blast.data.automaticInvalidationPerformed===false,blast.data||blast.code,"Blast Radius");
      const recompute=namespace.createExternalIntelligenceRecomputeCandidate({outputReferenceId:"INTELLIGENCE-PHASE8-PACKAGE",reason:"INPUT_REVISION",triggerReferenceIds:["CLAIM-PHASE8-INPUT"]});
      check("Recompute remains Candidate-only",recompute.ok===true&&recompute.data.recomputeCandidate.automaticRecomputePerformed===false&&recompute.data.recomputeCandidate.approvalGranted===false,recompute.data||recompute.code,"Recompute");
      const revision=namespace.createExternalIntelligenceRevisionLineage({previousRecordId:"CLAIM-PHASE8-V1",newRecordId:"CLAIM-PHASE8-V2"});
      check("Revision Lineage preserves historical record",revision.ok===true&&revision.data.lineageRecord.relationType==="SUPERSEDES"&&revision.data.lineageRecord.historicalRecordSilentlyRewritten===false,revision.data||revision.code,"Revision Lineage");
      const emergency=namespace.createExternalIntelligenceEmergencyDecisionLineageHook({decisionReferenceId:"EMERGENCY-DECISION-PHASE8",evidenceReferenceIds:["EVIDENCE-PHASE8"],intelligenceReferenceIds:["INTELLIGENCE-PHASE8-PACKAGE"],reasoningReferenceIds:["REASONING-PHASE8"]});
      check("Emergency Decision Lineage cannot bypass Authority",emergency.ok===true&&emergency.data.emergencyLineageHook.lineageBypassAllowed===false&&emergency.data.emergencyLineageHook.actionAuthorityGranted===false,emergency.data||emergency.code,"Emergency Lineage");

      const s=VERSION_MANIFEST.safety;
      check("Phase 08 Capability safety is fail-closed",s.modelAgreementEqualsTruth===false&&s.aiAnalysisEqualsPrimaryEvidence===false&&s.modelCanAnalyzeEqualsDataMayBeSent===false&&s.shadowSuccessEqualsAutomaticPromotion===false&&s.modelFailureAllowsSilentFallback===false&&s.highModelPerformanceGrantsActionAuthority===false&&s.capabilityRoutingGrantsBusinessAuthority===false,s,"Safety");
      check("Phase 08 Lineage safety is non-destructive",s.sourceProvenanceEqualsAnalyticalLineage===false&&s.auditEqualsLineage===false&&s.affectedEqualsInvalid===false&&s.recomputeRequiredEqualsKnownIncorrect===false&&s.historicalRecordMayBeSilentlyRewritten===false&&s.automaticRecomputeAllowed===false,s,"Safety");
      ["capabilityRegistry","capabilityRouting","lineage","phase8Validation"].forEach(name=>check("Module "+name+" is loaded",Boolean(namespace.modules[name]),namespace.modules[name]&&namespace.modules[name].status,"Modules"));
      const auditEvent=await namespace.appendExternalIntelligenceAuditEvent({eventType:"PHASE8_VALIDATION_CAPABILITY_LINEAGE",actor:"EXTERNAL-010 Phase 08 Validation",outcome:"Recorded",details:{capabilityCount:state.analyticalCapabilities.size,lineageCount:state.lineageRecords.size,secretValueStored:false,automaticPromotionPerformed:false,automaticRecomputePerformed:false},references:[localCap.data.analyticalCapability.capabilityId,transform.data.transformationRecord.transformationId]});
      check("Phase 08 operations integrate with append-only Audit",auditEvent.ok===true,auditEvent.data||auditEvent.code,"Audit");
      const audit=await namespace.verifyExternalIntelligenceAuditChain(); check("Phase 08 audit chain remains valid",audit.valid===true,{valid:audit.valid,eventCount:audit.eventCount},"Audit");
    } catch(error) { check("Phase 08 validation execution completes without exception",false,{message:error&&error.message||String(error),stack:error&&error.stack||null},"Validation"); }

    const summary=summarize(c.checks),gate=summary.failed===0&&summary.criticalFailed===0;
    const result={id:internal.nextId("EXTERNAL-010-PHASE8-VALIDATION"),componentId:"EXTERNAL-010",version:VERSION_MANIFEST.release.version,implementationPhase:VERSION_MANIFEST.release.implementationPhase,designFreezeId:VERSION_MANIFEST.release.designFreezeId,roadmapId:VERSION_MANIFEST.release.implementationRoadmapId,decisionCoverage:VERSION_MANIFEST.release.decisionCount,passed:summary.passed,failed:summary.failed,total:summary.total,health:summary.health,criticalFailed:summary.criticalFailed,status:gate?"EXTERNAL-010 Phase 08 Validation PASS":"EXTERNAL-010 Phase 08 Validation FAIL",releaseAllowed:gate,phase8Complete:gate,phase9Allowed:gate,checks:c.checks,safety:internal.clone(VERSION_MANIFEST.safety),validatedAt:internal.nowIso()};
    const cv=namespace.validateExternalIntelligenceContract("phase8ValidationResult",result),sv=namespace.validateExternalIntelligenceRecord("EXTERNAL-010-SCHEMA-PHASE8-VALIDATION-RESULT",result);
    if(!cv.valid||!sv.valid){result.failed+=1;result.total+=1;result.criticalFailed+=1;result.health=Math.round(result.passed/result.total*1000)/10;result.status="EXTERNAL-010 Phase 08 Validation FAIL";result.releaseAllowed=false;result.phase8Complete=false;result.phase9Allowed=false;result.checks.push({name:"Phase 08 result validates against contract and schema",passed:false,detail:internal.stableStringify({contract:cv,schema:sv}),group:"Validation",severity:"Critical"});}
    else{result.checks.push({name:"Phase 08 result validates against contract and schema",passed:true,detail:"valid",group:"Validation",severity:"Critical"});result.passed+=1;result.total+=1;result.health=Math.round(result.passed/result.total*1000)/10;}
    state.latestPhase8Validation=internal.deepFreeze(internal.clone(result)); namespace.modules.phase8Validation.status=result.failed===0?"Passed":"Failed"; internal.touch(); return internal.clone(result);
  }
  function getLatestExternalIntelligencePhase8Validation(){return state.latestPhase8Validation?internal.clone(state.latestPhase8Validation):null;}
  Object.assign(namespace.api,{runExternalIntelligencePhase8Validation,getLatestExternalIntelligencePhase8Validation});Object.assign(namespace,namespace.api);
  namespace.modules.phase8Validation={id:"EXTERNAL-010-PHASE8-VALIDATION",version:MODULE_VERSION,status:"Loaded",phase:8,decisions:["036","037"],gatewayChangeRequired:false,loadedAt:internal.nowIso()};
  global.runExternalIntelligencePhase8Validation=runExternalIntelligencePhase8Validation;
})(typeof window!=="undefined"?window:globalThis);
