/* ============================================================
   FILE: 17_external_intelligence_version_manifest.js
   EXTERNAL-010 External Intelligence Platform
   Release: 1.9.1
   Phase 10: Reliability Signals / Uncertainty / Outcome Foundation
   Design Freeze: EXTERNAL-010-DESIGN-FREEZE-1.0.0
   ============================================================ */
(function (global) {
  "use strict";

  const RELEASE_VERSION = "1.10.0";
  const PHASE1_VERSION = "1.0.0";
  const PHASE2_VERSION = "1.1.0";
  const PHASE3_VERSION = "1.2.0";
  const PHASE4_VERSION = "1.3.0";
  const PHASE5_VERSION = "1.4.0";
  const PHASE6_VERSION = "1.5.0";
  const PHASE7_VERSION = "1.6.0";
  const PHASE8_VERSION = "1.7.3";
  const PHASE9_VERSION = "1.8.0";
  const PHASE10_VERSION = "1.9.1";
  const PHASE11_VERSION = "1.10.0";
  const GATEWAY_PHASE4_VERSION = "1.2.0";
  const GATEWAY_PHASE5_VERSION = "1.3.0";
  const GATEWAY_PHASE6_VERSION = "1.4.0";

  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
    Object.keys(value).forEach(function freezeChild(key) { deepFreeze(value[key]); });
    return Object.freeze(value);
  }

  function parseSemanticVersion(value) {
    const match = String(value || "").trim().match(/^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/);
    return match ? { major: Number(match[1]), minor: Number(match[2]), patch: Number(match[3]) } : null;
  }

  function isReleaseCompatibleFrom(minimumVersion) {
    const current = parseSemanticVersion(RELEASE_VERSION);
    const minimum = parseSemanticVersion(minimumVersion);
    if (!current || !minimum || current.major !== minimum.major) return false;
    if (current.minor !== minimum.minor) return current.minor > minimum.minor;
    return current.patch >= minimum.patch;
  }

  const moduleVersions = {
    core: PHASE3_VERSION,
    contracts: PHASE10_VERSION,
    schemaRegistry: PHASE10_VERSION,
    authority: PHASE1_VERSION,
    audit: PHASE1_VERSION,
    runtimeCoordination: PHASE2_VERSION,
    softwareSupplyChain: PHASE2_VERSION,
    gatewayClient: PHASE4_VERSION,
    sourceRegistry: PHASE3_VERSION,
    sourceDiscovery: PHASE3_VERSION,
    resourceBudget: PHASE3_VERSION,
    usagePolicy: PHASE3_VERSION,
    acquisitionContract: PHASE4_VERSION,
    adapterRegistry: PHASE4_VERSION,
    sourceRouter: PHASE4_VERSION,
    acquisitionQueue: PHASE4_VERSION,
    phase1Validation: PHASE4_VERSION,
    phase2Validation: PHASE4_VERSION,
    phase3Validation: PHASE4_VERSION,
    phase4Validation: PHASE4_VERSION,
    phase4RealRuntimeValidation: PHASE4_VERSION,
    phase4AndroidValidation: PHASE4_VERSION,
    evidencePersistence: PHASE5_VERSION,
    phase5Validation: PHASE5_VERSION,
    phase5RealRuntimeValidation: PHASE5_VERSION,
    phase5AndroidValidation: PHASE5_VERSION,
    secretGovernance: PHASE6_VERSION,
    externalContentSecurity: PHASE6_VERSION,
    dataLifecycle: PHASE6_VERSION,
    privacyIdentity: PHASE6_VERSION,
    phase6Validation: PHASE6_VERSION,
    phase6RealRuntimeValidation: PHASE6_VERSION,
    phase6AndroidValidation: PHASE6_VERSION,
    temporal: PHASE7_VERSION,
    normalization: PHASE7_VERSION,
    claim: PHASE7_VERSION,
    entity: PHASE7_VERSION,
    phase7Validation: PHASE7_VERSION,
    phase7RealRuntimeValidation: PHASE7_VERSION,
    phase7AndroidValidation: PHASE7_VERSION,
    capabilityRegistry: PHASE8_VERSION,
    capabilityRouting: PHASE8_VERSION,
    lineage: PHASE8_VERSION,
    phase8Validation: PHASE8_VERSION,
    phase8RealRuntimeValidation: PHASE8_VERSION,
    phase8AndroidValidation: PHASE8_VERSION,
    relationGraph: PHASE9_VERSION,
    eventGraph: PHASE9_VERSION,
    impactGraph: PHASE9_VERSION,
    phase9Validation: PHASE9_VERSION,
    phase9RealRuntimeValidation: PHASE9_VERSION,
    phase9AndroidValidation: PHASE9_VERSION,
    reliabilitySignals: PHASE10_VERSION, uncertainty: PHASE10_VERSION, outcome: PHASE10_VERSION,
    phase10Validation: PHASE10_VERSION, phase10RealRuntimeValidation: PHASE10_VERSION, phase10AndroidValidation: PHASE10_VERSION,
    signalDetection: PHASE11_VERSION, hypothesis: PHASE11_VERSION, researchPriority: PHASE11_VERSION, phase11Validation: PHASE11_VERSION, phase11RealRuntimeValidation: PHASE11_VERSION, phase11AndroidValidation: PHASE11_VERSION
  };

  const fileModules = {
    "17_external_intelligence_core.js": "core",
    "17_external_intelligence_contracts.js": "contracts",
    "17_external_intelligence_schema_registry.js": "schemaRegistry",
    "17_external_intelligence_authority.js": "authority",
    "17_external_intelligence_audit.js": "audit",
    "17_external_intelligence_runtime_coordination.js": "runtimeCoordination",
    "17_external_intelligence_software_supply_chain.js": "softwareSupplyChain",
    "17_external_intelligence_gateway_client.js": "gatewayClient",
    "17_external_intelligence_source_registry.js": "sourceRegistry",
    "17_external_intelligence_source_discovery.js": "sourceDiscovery",
    "17_external_intelligence_resource_budget.js": "resourceBudget",
    "17_external_intelligence_usage_policy.js": "usagePolicy",
    "17_external_intelligence_acquisition_contract.js": "acquisitionContract",
    "17_external_intelligence_adapter_registry.js": "adapterRegistry",
    "17_external_intelligence_source_router.js": "sourceRouter",
    "17_external_intelligence_acquisition_queue.js": "acquisitionQueue",
    "17_external_intelligence_phase1_validation.js": "phase1Validation",
    "17_external_intelligence_phase2_validation.js": "phase2Validation",
    "17_external_intelligence_phase3_validation.js": "phase3Validation",
    "17_external_intelligence_phase4_validation.js": "phase4Validation",
    "17_external_intelligence_phase4_real_runtime_validation.js": "phase4RealRuntimeValidation",
    "17_external_intelligence_phase4_android_validation.js": "phase4AndroidValidation",
    "17_external_intelligence_evidence_persistence.js": "evidencePersistence",
    "17_external_intelligence_phase5_validation.js": "phase5Validation",
    "17_external_intelligence_phase5_real_runtime_validation.js": "phase5RealRuntimeValidation",
    "17_external_intelligence_phase5_android_validation.js": "phase5AndroidValidation",
    "17_external_intelligence_secret_governance.js": "secretGovernance",
    "17_external_intelligence_external_content_security.js": "externalContentSecurity",
    "17_external_intelligence_data_lifecycle.js": "dataLifecycle",
    "17_external_intelligence_privacy_identity.js": "privacyIdentity",
    "17_external_intelligence_phase6_validation.js": "phase6Validation",
    "17_external_intelligence_phase6_real_runtime_validation.js": "phase6RealRuntimeValidation",
    "17_external_intelligence_phase6_android_validation.js": "phase6AndroidValidation",
    "17_external_intelligence_temporal.js": "temporal",
    "17_external_intelligence_normalization.js": "normalization",
    "17_external_intelligence_claim.js": "claim",
    "17_external_intelligence_entity.js": "entity",
    "17_external_intelligence_phase7_validation.js": "phase7Validation",
    "17_external_intelligence_phase7_real_runtime_validation.js": "phase7RealRuntimeValidation",
    "17_external_intelligence_phase7_android_validation.js": "phase7AndroidValidation",
    "17_external_intelligence_capability_registry.js": "capabilityRegistry",
    "17_external_intelligence_capability_routing.js": "capabilityRouting",
    "17_external_intelligence_lineage.js": "lineage",
    "17_external_intelligence_phase8_validation.js": "phase8Validation",
    "17_external_intelligence_phase8_real_runtime_validation.js": "phase8RealRuntimeValidation",
    "17_external_intelligence_phase8_android_validation.js": "phase8AndroidValidation",
    "17_external_intelligence_relation_graph.js": "relationGraph",
    "17_external_intelligence_event_graph.js": "eventGraph",
    "17_external_intelligence_impact_graph.js": "impactGraph",
    "17_external_intelligence_phase9_validation.js": "phase9Validation",
    "17_external_intelligence_phase9_real_runtime_validation.js": "phase9RealRuntimeValidation",
    "17_external_intelligence_phase9_android_validation.js": "phase9AndroidValidation",
    "17_external_intelligence_reliability_signals.js": "reliabilitySignals",
    "17_external_intelligence_uncertainty.js": "uncertainty",
    "17_external_intelligence_outcome.js": "outcome",
    "17_external_intelligence_phase10_validation.js": "phase10Validation",
    "17_external_intelligence_phase10_real_runtime_validation.js": "phase10RealRuntimeValidation",
    "17_external_intelligence_phase10_android_validation.js": "phase10AndroidValidation",
    "17_external_intelligence_signal_detection.js": "signalDetection",
    "17_external_intelligence_hypothesis.js": "hypothesis",
    "17_external_intelligence_research_priority.js": "researchPriority",
    "17_external_intelligence_phase11_validation.js": "phase11Validation",
    "17_external_intelligence_phase11_real_runtime_validation.js": "phase11RealRuntimeValidation",
    "17_external_intelligence_phase11_android_validation.js": "phase11AndroidValidation"
  };

  const contractVersions = {
    foundationState: PHASE3_VERSION,
    contractDefinition: PHASE1_VERSION,
    schemaDefinition: PHASE1_VERSION,
    compatibilityProfile: PHASE1_VERSION,
    authorityEnvelope: PHASE1_VERSION,
    auditEvent: PHASE1_VERSION,
    validationResult: PHASE3_VERSION,
    promotionBoundary: PHASE1_VERSION,
    gatewayRuntimeState: PHASE2_VERSION,
    gatewaySessionMetadata: PHASE2_VERSION,
    runtimeCoordinationRecord: PHASE2_VERSION,
    dependencyCandidate: PHASE2_VERSION,
    runtimeProfile: PHASE2_VERSION,
    phase2ValidationResult: PHASE3_VERSION,
    sourceRecord: PHASE3_VERSION,
    sourceDiscoveryRecord: PHASE3_VERSION,
    controlledInspectionRecord: PHASE3_VERSION,
    resourceBudget: PHASE3_VERSION,
    resourceUsageRecord: PHASE3_VERSION,
    usagePolicy: PHASE3_VERSION,
    phase3ValidationResult: PHASE3_VERSION,
    sourceOperationContract: PHASE4_VERSION,
    externalAcquisitionRequest: PHASE4_VERSION,
    externalAcquisitionAttempt: PHASE4_VERSION,
    externalAcquisitionResponse: PHASE4_VERSION,
    externalAcquisitionError: PHASE4_VERSION,
    sourceAdapterDefinition: PHASE4_VERSION,
    sourceRouteDecision: PHASE4_VERSION,
    acquisitionJob: PHASE4_VERSION,
    phase4ValidationResult: PHASE4_VERSION,
    rawEvidenceRecord: PHASE5_VERSION,
    acquisitionEvidenceRecord: PHASE5_VERSION,
    contentObjectMetadata: PHASE5_VERSION,
    processingCheckpoint: PHASE5_VERSION,
    phase5ValidationResult: PHASE5_VERSION,
    secretMetadata: PHASE6_VERSION,
    contentSecurityAssessment: PHASE6_VERSION,
    dataLifecycleRecord: PHASE6_VERSION,
    privacyAssessment: PHASE6_VERSION,
    phase6ValidationResult: PHASE6_VERSION,
    temporalContext: PHASE7_VERSION,
    normalizerDefinition: PHASE7_VERSION,
    normalizedRecord: PHASE7_VERSION,
    claimCandidate: PHASE7_VERSION,
    entityRecord: PHASE7_VERSION,
    entityAliasRecord: PHASE7_VERSION,
    entityIdentifierRecord: PHASE7_VERSION,
    entityMention: PHASE7_VERSION,
    entityResolutionCandidate: PHASE7_VERSION,
    entityMergeSplitCandidate: PHASE7_VERSION,
    phase7ValidationResult: PHASE7_VERSION,
    analyticalCapability: PHASE8_VERSION,
    capabilityPerformanceProfile: PHASE8_VERSION,
    capabilityRoutingCandidate: PHASE8_VERSION,
    analysisExecutionRecord: PHASE8_VERSION,
    independentReviewPlan: PHASE8_VERSION,
    shadowEvaluationRecord: PHASE8_VERSION,
    capabilityFallbackRecord: PHASE8_VERSION,
    snapshotManifest: PHASE8_VERSION,
    transformationRecord: PHASE8_VERSION,
    lineageRecord: PHASE8_VERSION,
    recomputeCandidate: PHASE8_VERSION,
    phase8ValidationResult: PHASE8_VERSION,
    temporalRelationRecord: PHASE9_VERSION, eventRecord: PHASE9_VERSION, eventStateTransition: PHASE9_VERSION, impactEdge: PHASE9_VERSION, impactPath: PHASE9_VERSION, impactObservation: PHASE9_VERSION, historicalAnalogCandidate: PHASE9_VERSION, scenarioCandidate: PHASE9_VERSION, impactOutcomeEvaluationCandidate: PHASE9_VERSION, phase9ValidationResult: PHASE9_VERSION,
    reliabilitySignal: PHASE10_VERSION, evidenceQualitySignal: PHASE10_VERSION, reliabilityCandidate: PHASE10_VERSION, reliabilityInputPackage: PHASE10_VERSION, predictionRecord: PHASE10_VERSION, benchmarkDefinition: PHASE10_VERSION, outcomeRecord: PHASE10_VERSION, outcomeEvaluation: PHASE10_VERSION, phase10ValidationResult: PHASE10_VERSION, baselineRecord: PHASE11_VERSION, signalRecord: PHASE11_VERSION, signalCluster: PHASE11_VERSION, researchQuestion: PHASE11_VERSION, hypothesisRecord: PHASE11_VERSION, researchPriorityRecord: PHASE11_VERSION, phase11ValidationResult: PHASE11_VERSION
  };

  const contractIds = {
    foundationState: "EXTERNAL-010-CONTRACT-FOUNDATION-STATE",
    contractDefinition: "EXTERNAL-010-CONTRACT-DEFINITION",
    schemaDefinition: "EXTERNAL-010-CONTRACT-SCHEMA-DEFINITION",
    compatibilityProfile: "EXTERNAL-010-CONTRACT-COMPATIBILITY-PROFILE",
    authorityEnvelope: "EXTERNAL-010-CONTRACT-AUTHORITY-ENVELOPE",
    auditEvent: "EXTERNAL-010-CONTRACT-AUDIT-EVENT",
    validationResult: "EXTERNAL-010-CONTRACT-VALIDATION-RESULT",
    promotionBoundary: "EXTERNAL-010-CONTRACT-PROMOTION-BOUNDARY",
    gatewayRuntimeState: "EXTERNAL-010-CONTRACT-GATEWAY-RUNTIME-STATE",
    gatewaySessionMetadata: "EXTERNAL-010-CONTRACT-GATEWAY-SESSION-METADATA",
    runtimeCoordinationRecord: "EXTERNAL-010-CONTRACT-RUNTIME-COORDINATION-RECORD",
    dependencyCandidate: "EXTERNAL-010-CONTRACT-DEPENDENCY-CANDIDATE",
    runtimeProfile: "EXTERNAL-010-CONTRACT-RUNTIME-PROFILE",
    phase2ValidationResult: "EXTERNAL-010-CONTRACT-PHASE2-VALIDATION-RESULT",
    sourceRecord: "EXTERNAL-010-CONTRACT-SOURCE-RECORD",
    sourceDiscoveryRecord: "EXTERNAL-010-CONTRACT-SOURCE-DISCOVERY-RECORD",
    controlledInspectionRecord: "EXTERNAL-010-CONTRACT-CONTROLLED-INSPECTION-RECORD",
    resourceBudget: "EXTERNAL-010-CONTRACT-RESOURCE-BUDGET",
    resourceUsageRecord: "EXTERNAL-010-CONTRACT-RESOURCE-USAGE-RECORD",
    usagePolicy: "EXTERNAL-010-CONTRACT-USAGE-POLICY",
    phase3ValidationResult: "EXTERNAL-010-CONTRACT-PHASE3-VALIDATION-RESULT",
    sourceOperationContract: "EXTERNAL-010-CONTRACT-SOURCE-OPERATION",
    externalAcquisitionRequest: "EXTERNAL-010-CONTRACT-ACQUISITION-REQUEST",
    externalAcquisitionAttempt: "EXTERNAL-010-CONTRACT-ACQUISITION-ATTEMPT",
    externalAcquisitionResponse: "EXTERNAL-010-CONTRACT-ACQUISITION-RESPONSE",
    externalAcquisitionError: "EXTERNAL-010-CONTRACT-ACQUISITION-ERROR",
    sourceAdapterDefinition: "EXTERNAL-010-CONTRACT-SOURCE-ADAPTER-DEFINITION",
    sourceRouteDecision: "EXTERNAL-010-CONTRACT-SOURCE-ROUTE-DECISION",
    acquisitionJob: "EXTERNAL-010-CONTRACT-ACQUISITION-JOB",
    phase4ValidationResult: "EXTERNAL-010-CONTRACT-PHASE4-VALIDATION-RESULT",
    rawEvidenceRecord: "EXTERNAL-010-CONTRACT-RAW-EVIDENCE",
    acquisitionEvidenceRecord: "EXTERNAL-010-CONTRACT-ACQUISITION-EVIDENCE",
    contentObjectMetadata: "EXTERNAL-010-CONTRACT-CONTENT-OBJECT",
    processingCheckpoint: "EXTERNAL-010-CONTRACT-PROCESSING-CHECKPOINT",
    phase5ValidationResult: "EXTERNAL-010-CONTRACT-PHASE5-VALIDATION-RESULT",
    secretMetadata: "EXTERNAL-010-CONTRACT-SECRET-METADATA",
    contentSecurityAssessment: "EXTERNAL-010-CONTRACT-CONTENT-SECURITY-ASSESSMENT",
    dataLifecycleRecord: "EXTERNAL-010-CONTRACT-DATA-LIFECYCLE",
    privacyAssessment: "EXTERNAL-010-CONTRACT-PRIVACY-ASSESSMENT",
    phase6ValidationResult: "EXTERNAL-010-CONTRACT-PHASE6-VALIDATION-RESULT",
    temporalContext: "EXTERNAL-010-CONTRACT-TEMPORAL-CONTEXT",
    normalizerDefinition: "EXTERNAL-010-CONTRACT-NORMALIZER-DEFINITION",
    normalizedRecord: "EXTERNAL-010-CONTRACT-NORMALIZED-RECORD",
    claimCandidate: "EXTERNAL-010-CONTRACT-CLAIM-CANDIDATE",
    entityRecord: "EXTERNAL-010-CONTRACT-ENTITY-RECORD",
    entityAliasRecord: "EXTERNAL-010-CONTRACT-ENTITY-ALIAS",
    entityIdentifierRecord: "EXTERNAL-010-CONTRACT-ENTITY-IDENTIFIER",
    entityMention: "EXTERNAL-010-CONTRACT-ENTITY-MENTION",
    entityResolutionCandidate: "EXTERNAL-010-CONTRACT-ENTITY-RESOLUTION-CANDIDATE",
    entityMergeSplitCandidate: "EXTERNAL-010-CONTRACT-ENTITY-MERGE-SPLIT-CANDIDATE",
    phase7ValidationResult: "EXTERNAL-010-CONTRACT-PHASE7-VALIDATION-RESULT",
    analyticalCapability: "EXTERNAL-010-CONTRACT-ANALYTICAL-CAPABILITY",
    capabilityPerformanceProfile: "EXTERNAL-010-CONTRACT-CAPABILITY-PERFORMANCE-PROFILE",
    capabilityRoutingCandidate: "EXTERNAL-010-CONTRACT-CAPABILITY-ROUTING-CANDIDATE",
    analysisExecutionRecord: "EXTERNAL-010-CONTRACT-ANALYSIS-EXECUTION-RECORD",
    independentReviewPlan: "EXTERNAL-010-CONTRACT-INDEPENDENT-REVIEW-PLAN",
    shadowEvaluationRecord: "EXTERNAL-010-CONTRACT-SHADOW-EVALUATION-RECORD",
    capabilityFallbackRecord: "EXTERNAL-010-CONTRACT-CAPABILITY-FALLBACK-RECORD",
    snapshotManifest: "EXTERNAL-010-CONTRACT-SNAPSHOT-MANIFEST",
    transformationRecord: "EXTERNAL-010-CONTRACT-TRANSFORMATION-RECORD",
    lineageRecord: "EXTERNAL-010-CONTRACT-LINEAGE-RECORD",
    recomputeCandidate: "EXTERNAL-010-CONTRACT-RECOMPUTE-CANDIDATE",
    phase8ValidationResult: "EXTERNAL-010-CONTRACT-PHASE8-VALIDATION-RESULT",
    temporalRelationRecord: "EXTERNAL-010-CONTRACT-TEMPORAL-RELATION-RECORD",
    eventRecord: "EXTERNAL-010-CONTRACT-EVENT-RECORD",
    eventStateTransition: "EXTERNAL-010-CONTRACT-EVENT-STATE-TRANSITION",
    impactEdge: "EXTERNAL-010-CONTRACT-IMPACT-EDGE",
    impactPath: "EXTERNAL-010-CONTRACT-IMPACT-PATH",
    impactObservation: "EXTERNAL-010-CONTRACT-IMPACT-OBSERVATION",
    historicalAnalogCandidate: "EXTERNAL-010-CONTRACT-HISTORICAL-ANALOG-CANDIDATE",
    scenarioCandidate: "EXTERNAL-010-CONTRACT-SCENARIO-CANDIDATE",
    impactOutcomeEvaluationCandidate: "EXTERNAL-010-CONTRACT-IMPACT-OUTCOME-EVALUATION-CANDIDATE",
    phase9ValidationResult: "EXTERNAL-010-CONTRACT-PHASE9-VALIDATION-RESULT",
    reliabilitySignal: "EXTERNAL-010-CONTRACT-RELIABILITY-SIGNAL",
    evidenceQualitySignal: "EXTERNAL-010-CONTRACT-EVIDENCE-QUALITY-SIGNAL",
    reliabilityCandidate: "EXTERNAL-010-CONTRACT-RELIABILITY-CANDIDATE",
    reliabilityInputPackage: "EXTERNAL-010-CONTRACT-RELIABILITY-INPUT-PACKAGE",
    predictionRecord: "EXTERNAL-010-CONTRACT-PREDICTION-RECORD",
    benchmarkDefinition: "EXTERNAL-010-CONTRACT-BENCHMARK-DEFINITION",
    outcomeRecord: "EXTERNAL-010-CONTRACT-OUTCOME-RECORD",
    outcomeEvaluation: "EXTERNAL-010-CONTRACT-OUTCOME-EVALUATION",
    phase10ValidationResult: "EXTERNAL-010-CONTRACT-PHASE10-VALIDATION-RESULT",
    baselineRecord: "EXTERNAL-010-CONTRACT-SIGNAL-BASELINE", signalRecord: "EXTERNAL-010-CONTRACT-SIGNAL-RECORD", signalCluster: "EXTERNAL-010-CONTRACT-SIGNAL-CLUSTER", researchQuestion: "EXTERNAL-010-CONTRACT-RESEARCH-QUESTION", hypothesisRecord: "EXTERNAL-010-CONTRACT-HYPOTHESIS-RECORD", researchPriorityRecord: "EXTERNAL-010-CONTRACT-RESEARCH-PRIORITY", phase11ValidationResult: "EXTERNAL-010-CONTRACT-PHASE11-VALIDATION-RESULT"
  };

  const safety = {
    directRepositoryMutationAllowed: false,
    automaticKnowledgePromotionAllowed: false,
    automaticPaidApiActivationAllowed: false,
    automaticSoftwareInstallAllowed: false,
    automaticTradeExecutionAllowed: false,
    automaticAuthorityExpansionAllowed: false,
    authorityBypassAllowed: false,
    externalContentInstructionAuthorityAllowed: false,
    validationEqualsApproval: false,
    localhostAutomaticallyTrusted: false,
    corsEqualsAuthentication: false,
    gatewaySessionEqualsBusinessAuthority: false,
    gatewaySessionTokenPersistenceAllowed: false,
    runtimePackageInstallAllowed: false,
    blindRetryUnknownExecutionAllowed: false,
    remoteGatewayAllowed: false,

    arbitraryUnregisteredSourceAccessAllowed: false,
    automaticSourceActivationAllowed: false,
    automaticPaidSourceActivationAllowed: false,
    automaticSecretBindingAllowed: false,
    automaticProviderSubscriptionAllowed: false,
    sourceIdentityGrantsReliability: false,
    sourceIdentityGrantsAuthority: false,
    externalSourceGrantsEconomicAuthority: false,

    sourceDiscoveryEqualsRegistration: false,
    sourceRegistrationEqualsEnablement: false,
    sourceEnablementEqualsTrust: false,
    sourceEnablementGrantsAllOperations: false,
    sourceDiscoveryGrantsUnlimitedNetworkAuthority: false,
    sourceDiscoveryGrantsSecretAuthority: false,
    sourceDiscoveryGrantsSubscriptionAuthority: false,
    sourceDiscoveryGrantsFinancialAuthority: false,
    searchRankingGrantsSourceTrust: false,
    externalLinkGrantsSourceTrust: false,
    controlledInspectionGrantsActivation: false,
    automaticSubscriptionAllowed: false,
    unknownHighRiskSourceAutoEnableAllowed: false,
    aiSourceDiscoveryGrantsActivationAuthority: false,
    sourceDisableDeletesHistoricalEvidence: false,

    sourceEnabledMeansUnlimitedUsage: false,
    secretAvailableMeansPaidAuthority: false,
    freeSourceMeansUnlimitedUsage: false,
    budgetAvailableMeansMustSpend: false,
    hardBudgetLimitMayBeSilentlyExceeded: false,
    paidRequestMayBypassBudgetCheck: false,
    priorityMayBypassHardLimit: false,
    unknownCostMayBeAssumedZero: false,
    schedulerMayBypassBudgetCheck: false,
    queueMayBypassBudgetCheck: false,
    unusedBudgetMayBeSilentlyReallocated: false,
    budgetProposalGrantsBudgetAuthority: false,
    resourceBudgetGrantsSubscriptionAuthority: false,
    resourceBudgetGrantsFinancialTradingAuthority: false,
    storagePressureGrantsEvidenceDeletionAuthority: false,
    rawEvidenceOverwriteAllowed: false,
    metadataIndexOnlyEvidenceIdentityAllowed: false,
    orphanContentAutomaticDeletionAllowed: false,
    derivedDataMayRewriteRawEvidence: false,
    normalizationReplacesRawEvidence: false,
    normalizationEqualsInterpretation: false,
    entityCandidateEqualsResolvedEntity: false,
    unknownMayBeSilentlyResolved: false,
    ambiguousMayBeSilentlyResolved: false,
    unitConversionEqualsOriginalEvidence: false,
    derivedValueEqualsSourceClaim: false,
    analysisEqualsEvidence: false,
    normalizerUpgradeMayOverwriteHistory: false,
    normalizationFailureInvalidatesRawEvidence: false,
    newestEvidenceAutomaticallyWins: false,
    oldEvidenceAutomaticallyInvalid: false,
    historicalEqualsStale: false,
    freshnessGrantsReliability: false,
    officialSourceAlwaysWins: false,
    acquiredAtEqualsPublishedAt: false,
    futureEvidenceInBacktestAllowed: false,
    unknownTimestampMayBeInvented: false,
    temporalAmbiguityGrantsAutoSelection: false,
    evidenceEqualsClaim: false,
    claimEqualsTruth: false,
    factualClaimEqualsVerifiedFact: false,
    predictionEqualsFact: false,
    publisherEqualsClaimant: false,
    repeatedClaimEqualsIndependentConfirmation: false,
    claimExtractionEqualsKnowledgePromotion: false,
    claimExtractionSuccessEqualsVerification: false,
    highExtractionConfidenceEqualsTruth: false,
    unknownClaimantMayBeSilentlyResolved: false,
    claimExtractorMayOverwriteRawEvidence: false,
    claimExtractorUpgradeMayDeleteHistory: false,
    futureOutcomeMayBeUsedAsPastEvidence: false,
    aiExtractedMeaningEqualsOriginalStatement: false,
    claimCandidateMayGrantToolAuthority: false,
    claimCandidateMayGrantRepositoryAuthority: false,
    entityNameEqualsEntityIdentity: false,
    sameNameEqualsSameEntity: false,
    aliasMatchEqualsExactIdentity: false,
    identifierEqualsPermanentIdentity: false,
    mentionEqualsResolvedEntity: false,
    visualMentionEqualsResolvedEntity: false,
    logoMatchEqualsCanonicalIdentity: false,
    visualSimilarityEqualsIdentity: false,
    eventEqualsRelation: false,
    announcementEqualsCompletion: false,
    planEqualsActualEvent: false,
    claimEqualsEventOccurred: false,
    currentRelationEqualsHistoricalRelation: false,
    relationCandidateEqualsVerifiedRelationship: false,
    aiExtractedRelationEqualsCanonicalRelation: false,
    visualAssociationEqualsBusinessRelationship: false,
    eventOccurrenceEqualsCausation: false,
    relationExistenceEqualsCausalImpact: false,
    ambiguousEntityMayCreateExactRelation: false,
    relationUpdateMayEraseHistoricalState: false,
    eventUpdateMayEraseHistoricalState: false,
    aiCandidateGenerationGrantsCanonicalAuthority: false,
    relationEqualsImpact: false,
    impactEqualsCausation: false,
    correlationEqualsCausation: false,
    temporalProximityEqualsCausation: false,
    eventOccurrenceEqualsOutcomeCause: false,
    historicalPatternEqualsGuaranteedFuture: false,
    historicalSimilarityEqualsSameOutcome: false,
    predictionEqualsOutcome: false,
    aiCausalHypothesisEqualsVerifiedCausalLink: false,
    highImpactScoreEqualsCertainCause: false,
    highSimilarityEqualsCertainOutcome: false,
    marketReactionTimeEqualsBusinessImpactTime: false,
    businessImpactTimeEqualsAccountingRecognitionTime: false,
    futureEvidenceMayBeUsedInHistoricalBacktest: false,
    failedPredictionMayBeSilentlyDeleted: false,
    failedPropagationMayBeSilentlyDeleted: false,
    impactPathGrantsActionAuthority: false,
    automaticImpactModelUpdateAllowed: false,
    visualMatchEqualsAuthenticity: false,
    aiResolutionEqualsCanonicalConfirmation: false,
    visionResolutionEqualsCanonicalConfirmation: false,
    highConfidenceEqualsGuaranteedIdentity: false,
    currentRelationshipEqualsHistoricalRelationship: false,
    entityMergeCandidateEqualsDestructiveMerge: false,
    aiResolutionMayDestructivelyMergeEntity: false,
    unknownEntityMayBeSilentlyResolved: false,
    ambiguousEntityMayBeSilentlyResolved: false,
    externalResolutionMayMutateKnowledgeAutomatically: false,
    evidencePersistenceGrantsKnowledgeAuthority: false,

    modelNameEqualsStableAnalyticalIdentity: false,
    bestOverallModelEqualsBestForEveryTask: false,
    modelAgreementEqualsTruth: false,
    modelCountAgreementEqualsIndependentConfirmation: false,
    aiAnalysisEqualsPrimaryEvidence: false,
    modelCanAnalyzeEqualsDataMayBeSent: false,
    higherCostEqualsHigherValue: false,
    newestModelEqualsBestModel: false,
    historicalWinnerEqualsFutureWinner: false,
    shadowSuccessEqualsAutomaticPromotion: false,
    modelFailureAllowsSilentFallback: false,
    fallbackResultEqualsRequestedModelResult: false,
    highModelPerformanceGrantsActionAuthority: false,
    externalAIOutputGrantsInstructionAuthority: false,
    capabilitySelectionGrantsExecutionAuthority: false,
    capabilityRoutingGrantsBusinessAuthority: false,
    sourceProvenanceEqualsAnalyticalLineage: false,
    auditEqualsLineage: false,
    derivedIntelligenceEqualsPrimaryEvidence: false,
    currentStateEqualsHistoricalInputState: false,
    affectedEqualsInvalid: false,
    inputRevisionAllowsDerivedDeletion: false,
    recomputeRequiredEqualsKnownIncorrect: false,
    realWorldImpactCycleEqualsDerivationCycle: false,
    historicalRecordMayBeSilentlyRewritten: false,
    modelOutputMayLoseOriginalEvidenceLineage: false,
    emergencyMayBypassLineage: false,
    automaticRecomputeAllowed: false,
    lineageRevisionDeletesHistoricalRecord: false,

    technicalAccessEqualsPermission: false,
    publicVisibilityEqualsUnlimitedReuse: false,
    readPermissionGrantsStoragePermission: false,
    readPermissionGrantsRedistributionPermission: false,
    internalAnalysisGrantsCommercialUse: false,
    noProhibitionFoundEqualsPermission: false,
    unknownUsagePolicyEqualsAllowed: false,
    ambiguousUsagePolicyEqualsAllowed: false,
    aiInterpretationEqualsLegalAuthority: false,
    termsLocatedEqualsFullyUnderstood: false,
    parserFailureEqualsNoRestriction: false,
    policyUnavailableEqualsPermission: false,
    freeSourceEqualsOpenLicense: false,
    paidSourceEqualsUnlimitedRights: false,
    derivedDataEqualsUnrestrictedData: false,

    arbitraryExternalRequestAllowed: false,
    browserSecretStorageAllowed: false,
    gatewaySecretExposureAllowed: false,
    automaticPaidApiSubscriptionAllowed: false,
    automaticPurchaseAllowed: false,
    automaticFinancialTransactionAllowed: false,
    externalResponseGrantsAuthority: false,
    gatewayGrantsEconomicAuthority: false,
    adapterDirectInvocationAsNormalFlow: false,
    unregisteredSourceAccessAllowed: false,
    unknownOperationExecutionAllowed: false,
    secretInRequestContractAllowed: false,
    automaticPaidRequestAuthorityAllowed: false,
    requestValidationGrantsExecutionAuthority: false,
    retryCanBypassPolicy: false,
    fallbackCanBypassPolicy: false,
    adapterGrantsSourceAuthority: false,
    adapterMayUseArbitraryUrlByDefault: false,
    adapterMayExposeSecret: false,
    adapterMayAutoPromoteKnowledge: false,
    adapterDeterminesFinalReliability: false,
    adapterMayMutateCanonicalRepository: false,
    adapterMayExecuteFinancialTransaction: false,
    adapterMayIgnoreRetryPolicy: false,
    adapterMayIgnoreSourcePolicy: false,
    unlimitedRetryAllowed: false,
    unlimitedConcurrencyAllowed: false,
    schedulerMayInventResearchGoal: false,
    schedulerMayInventAcquisitionPurpose: false,
    schedulerMayDiscoverSource: false,
    schedulerMayExpandAcquisitionScope: false,
    schedulerMayCreateUnknownSource: false,
    schedulerMayCreateUnknownOperation: false,
    scheduleGrantsPaidAuthority: false,
    scheduleGrantsFinancialAuthority: false,
    queueBypassesSourcePolicy: false,
    queueBypassesSecretPolicy: false,
    queueBypassesBudgetPolicy: false,
    gatewayRestartImpliesJobSuccess: false,
    missedScheduleUnlimitedCatchupAllowed: false,
    backgroundProcessingGrantsRepositoryAuthority: false,
    aiGoalGenerationGrantsExecutionAuthority: false,
    aiGoalGenerationGrantsPaidAuthority: false,
    aiGoalGenerationGrantsFinancialAuthority: false,
    aiGoalGenerationGrantsRepositoryAuthority: false,

    browserSecretStorageAllowed: false,
    repositorySecretStorageAllowed: false,
    memoSecretStorageAllowed: false,
    evidenceSecretStorageAllowed: false,
    secretExportWithProjectAllowed: false,
    secretValueReturnedToBrowserAllowed: false,
    secretInUnifiedRequestAllowed: false,
    secretAvailabilityGrantsPaidAuthority: false,
    secretAvailabilityGrantsFinancialAuthority: false,
    automaticSecretDiscoveryAllowed: false,

    externalContentGrantsInstructionAuthority: false,
    externalContentGrantsToolAuthority: false,
    externalContentGrantsSecretAuthority: false,
    externalContentGrantsRepositoryAuthority: false,
    externalContentGrantsFinancialAuthority: false,
    externalContentGrantsScheduleAuthority: false,
    externalContentMayDirectlyChangePolicy: false,
    externalCodeAutoExecutionAllowed: false,
    sanitizedContentAutomaticallyTrusted: false,
    officialSourceGrantsInstructionAuthority: false,
    highReliabilityGrantsInstructionAuthority: false,

    externalBinaryAutoExecutionAllowed: false,
    externalArchiveAutoExtractAllowed: false,
    unsafeHtmlRenderingAllowed: false,
    unvalidatedMimeTrustAllowed: false,
    unlimitedPayloadSizeAllowed: false,
    unlimitedArchiveExpansionAllowed: false,
    unlimitedArchiveDepthAllowed: false,
    archivePathTraversalAllowed: false,
    parserArbitraryNetworkAccessAllowed: false,
    parserRepositoryWriteAllowed: false,
    parserSecretAccessAllowed: false,
    arbitraryInternalNetworkAccessAllowed: false,
    fileSchemeAccessAllowed: false,
    redirectPolicyBypassAllowed: false,
    externalLocalFileUploadAllowedByDefault: false,
    downloadImpliesInstall: false,
    downloadImpliesExecute: false,
    malwareScanPassImpliesTrusted: false,
    scanUnavailableImpliesClean: false,
    securityUnknownImpliesSafe: false,
    scannerAutoDiscoveryAllowed: false,
    scannerAutoDownloadAllowed: false,
    scannerAutoInstallAllowed: false,
    unknownScannerExecutionAllowed: false,
    scannerIdentityVerificationRequired: true,
    scannerNameAloneGrantsTrust: false,
    scannerCleanResultGrantsExecutionAuthority: false,
    scannerCleanResultGrantsRepositoryAuthority: false,
    scannerCleanResultGrantsFinancialAuthority: false,
    securityPolicyAutoDowngradeAllowed: false,

    mayAcquireEqualsMayStoreLongTerm: false,
    mayStoreEqualsMayExport: false,
    mayAnalyzeEqualsMayTrainModel: false,
    mayCacheEqualsMayArchive: false,
    immutableEqualsStoreForever: false,
    rawRightsEqualsDerivedRights: false,
    canCollectEqualsShouldCollect: false,
    purposeAEqualsPurposeBUsageAuthority: false,
    backupIsPolicyExempt: false,
    policyChangeAllowsDeleteEverything: false,
    retentionExpiredEqualsAlwaysDelete: false,
    knowledgePromotionResetsRights: false,
    aiMaySilentlyDeleteEvidence: false,

    realPersonResolutionDefaultAllowed: false,
    sensitiveAttributeInferenceDefaultAllowed: false,
    crossPlatformIdentityLinkingDefaultAllowed: false,
    reIdentificationDefaultAllowed: false,
    publicVisibilityGrantsUnlimitedProfilingAuthority: false,
    predictiveValueGrantsPrivacyAuthority: false
  };

  const authorityPolicy = {
    defaultDecision: "DENY",
    candidateGrantsAuthority: false,
    validationGrantsAuthority: false,
    approvalEvidenceRequiredForActivation: true,
    ordinaryApprovalOverridesHardDeny: false,
    hardDeniedActions: [
      "DIRECT_REPOSITORY_MUTATION",
      "AUTOMATIC_KNOWLEDGE_PROMOTION",
      "ACTIVATE_PAID_API",
      "INSTALL_SOFTWARE",
      "EXECUTE_TRADE",
      "EXPAND_AUTHORITY",
      "AUTO_SUBSCRIBE_EXTERNAL_SOURCE",
      "AUTO_BIND_EXTERNAL_SECRET"
    ]
  };

  const compatibility = {
    readOldWriteCurrent: true,
    unknownSchemaWriteAllowed: false,
    unknownContractAllowed: false,
    silentSchemaUpgradeAllowed: false,
    projectionRequiresRegisteredAdapter: true,
    minimumBrowserPlatform: "Current Common Web Runtime",
    existingPlatformMutationRequired: false
  };

  const gateway = {
    contractVersion: "1.0.0",
    gatewayVersion: GATEWAY_PHASE6_VERSION,
    defaultBaseUrl: "http://127.0.0.1:43110",
    loopbackOnly: true,
    defaultPort: 43110,
    defaultAllowedOrigins: ["https://aturningpointinhistory.github.io"],
    sessionTokenStorage: "memory-only",
    sessionTtlMs: 300000,
    requestFreshnessMs: 60000,
    customHeadersRequiredForStateChange: true,
    healthEndpoint: "/health",
    sessionEndpoint: "/v1/session",
    revokeEndpoint: "/v1/session/revoke",
    probeEndpoint: "/v1/probe",
    runtimeEndpoint: "/v1/runtime",
    publicAcquisitionEndpoint: "/v1/acquire/public",
    governedAcquisitionEndpoint: "/v1/acquire/governed",
    secretStatusEndpoint: "/v1/secret/status",
    evidencePersistEndpoint: "/v1/evidence/persist",
    evidenceReadEndpoint: "/v1/evidence/read",
    evidenceIntegrityEndpoint: "/v1/evidence/integrity",
    processingCheckpointEndpoint: "/v1/evidence/checkpoint",
    localNetworkAddressSpace: "loopback",
    publicAcquisitionScope: "ACQUIRE_PUBLIC",
    governedAcquisitionScope: "ACQUIRE_EXTERNAL",
    secretMetadataScope: "READ_SECRET_METADATA",
    evidencePersistScope: "PERSIST_EVIDENCE",
    evidenceReadScope: "READ_EVIDENCE",
    governedTargetAllowlistRequired: true
  };

  const supplyChain = {
    runtimeInstallByDefault: false,
    exactVersionPreferred: true,
    integrityHashPreferred: true,
    transitiveInventoryRequiredWhereAvailable: true,
    hardSecurityFailOrdinaryOverrideAllowed: false,
    elevatedExceptionSelfGrantAllowed: false,
    phase2GatewayExternalDependencyCount: 0,
    phase2GatewayDependencyMode: "node-builtins-only"
  };

  const sourceGovernance = {
    registryFirst: true,
    sourceIdentityType: "stable-source-id",
    arbitraryDirectUrlNormalOperation: false,
    sourceTypes: ["PUBLIC_API", "MARKET_DATA", "FINANCIAL_DATA", "NEWS", "RSS", "WEB_PAGE", "SEARCH", "GITHUB", "GOVERNMENT_DATA", "TECHNICAL_DOCUMENTATION", "AI_SERVICE", "DATASET", "OTHER"],
    accessModes: ["BROWSER_DIRECT", "LOCAL_GATEWAY", "AUTO_ROUTE", "DISABLED"],
    authenticationModes: ["NONE", "API_KEY", "BEARER_TOKEN", "OAUTH", "CUSTOM"],
    pricingModes: ["FREE", "FIXED_MONTHLY", "USAGE_BASED", "TIERED", "UNKNOWN"],
    initialAllowedHttpMethods: ["GET"],
    secretValuesStoredInRegistry: false
  };

  const discovery = {
    lifecycle: ["DISCOVERED", "IDENTIFIED", "ASSESSED", "REGISTERED", "ENABLED", "ACTIVE", "REJECTED", "QUARANTINED", "DISABLED", "DEPRECATED", "REVOKED", "UNKNOWN"],
    riskClasses: ["LOW", "MEDIUM", "HIGH", "UNKNOWN"],
    aiMayDiscoverSourceCandidate: true,
    aiMayAssessSourceCandidate: true,
    controlledInspectionAvailable: true,
    controlledInspectionGrantsActivation: false
  };

  const resourceBudget = {
    hierarchy: ["GLOBAL", "CATEGORY", "SOURCE", "GOAL", "PLAN", "REQUEST"],
    resourceDimensions: ["FINANCIAL_COST", "REQUEST_COUNT", "NETWORK_BYTES", "STORAGE_BYTES", "CPU_TIME", "MEMORY", "PROCESSING_TIME", "AI_TOKEN_USAGE", "PROVIDER_QUOTA"],
    softLimitBlocksExecution: false,
    hardLimitBlocksExecution: true,
    aiMayOptimizeResourceUsage: true,
    aiMayProposeAdditionalBudget: true,
    aiMayCompareCostVsValue: true,
    aiMayGenerateResourceAllocationCandidate: true
  };

  const usagePolicy = {
    operations: ["READ", "TEMPORARY_CACHE", "LONG_TERM_STORAGE", "INTERNAL_ANALYSIS", "DERIVED_ANALYSIS", "EXPORT", "FULL_CONTENT_EXPORT", "REDISTRIBUTION", "COMMERCIAL_USE", "MODEL_TRAINING", "INDEXING", "ARCHIVING"],
    states: ["ALLOWED", "ALLOWED_WITH_CONDITIONS", "RESTRICTED", "BLOCKED", "UNKNOWN", "AMBIGUOUS", "REVIEW_REQUIRED"],
    aiMayReadTerms: true,
    aiMayExtractPolicyClauses: true,
    aiMayGenerateUsagePolicyCandidate: true,
    aiMayDetectPolicyChanges: true,
    aiMayGenerateTermsResearchGoal: true,
    aiPolicyInterpretationEqualsLegalAuthority: false,
    unknownDefaultsToAllowed: false
  };

  const acquisition = {
    executionPreferences: ["AUTO", "IMMEDIATE", "BACKGROUND"],
    executionDecisions: ["IMMEDIATE", "QUEUE", "BLOCKED"],
    priorities: ["CRITICAL", "HIGH", "NORMAL", "LOW", "BACKGROUND"],
    jobStatuses: ["QUEUED", "WAITING", "RUNNING", "RETRY_PENDING", "COMPLETED", "FAILED", "BLOCKED", "CANCELLED", "PAUSED", "RECOVERING", "UNKNOWN_EXECUTION_STATE"],
    errorCategories: ["AUTHENTICATION_FAILED", "RATE_LIMITED", "TIMEOUT", "SOURCE_UNAVAILABLE", "TEMPORARY_SOURCE_UNAVAILABLE", "INVALID_REQUEST", "INVALID_RESPONSE", "SCHEMA_MISMATCH", "BLOCKED", "UNKNOWN"],
    defaultTimeoutMs: 15000,
    maxTimeoutMs: 120000,
    maxRetryAttempts: 5,
    concurrencyLimit: 2,
    defaultRetryPolicy: {
      maxAttempts: 3,
      initialDelayMs: 0,
      maxDelayMs: 5000,
      backoffPolicy: "EXPONENTIAL",
      retryableCategories: ["TIMEOUT", "RATE_LIMITED", "SOURCE_UNAVAILABLE", "TEMPORARY_SOURCE_UNAVAILABLE"]
    },
    adapterIds: {
      mock: "EXTERNAL-010-ADAPTER-MOCK-001",
      browserHttpJson: "EXTERNAL-010-ADAPTER-HTTP-JSON-BROWSER-001",
      localGateway: "EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001"
    },
    commonAdapterMethods: ["validateRequest", "acquire", "normalizeResponseMetadata", "extractTemporalMetadata", "sanitize", "buildEvidenceInput"],
    persistentQueueMetadataRequired: true,
    preExecutionRevalidationRequired: true,
    arbitraryUrlProxyAllowed: false,
    gatewayPublicJsonAcquisitionEnabled: true,
    gatewayTargetAllowlistRequired: true
  };

  const persistence = {
    contentHashAlgorithm: "SHA-256",
    contentAddressedStore: true,
    metadataIndex: "SQLITE",
    databaseSchemaVersion: "1.0.0",
    rawContentDefaultStorage: "FILE_STORE",
    storageClasses: ["HOT", "WARM", "COLD", "ARCHIVE"],
    initialStorageClass: "HOT",
    immutableRawEvidence: true,
    acquisitionRecordSeparatedFromContent: true,
    physicalContentDeduplication: true,
    temporaryWriteBeforeCommit: true,
    hashVerificationBeforeMetadataCommit: true,
    atomicRenamePreferred: true,
    metadataIndexIsOnlyEvidenceIdentityCopy: false,
    orphanAutomaticDeletionAllowed: false,
    incrementalProcessingRequired: true,
    checkpointSupported: true,
    projectZipAutoIncludesBulkEvidence: false,
    localGatewayWriterRequired: true,
    browserDirectPersistentStoreAllowed: false,
    androidLocalSqlitePersistenceAvailable: false
  };

  const secretGovernance = {
    secretValueRuntime: "LOCAL_GATEWAY_ONLY",
    browserReferenceOnly: true,
    persistentSecretStorageTechnologyFixed: false,
    defaultProvider: "EPHEMERAL_ENVIRONMENT_REFERENCE",
    metadataFields: ["secretReferenceId", "secretType", "provider", "status", "createdAt", "updatedAt", "expiresAt"],
    statuses: ["ACTIVE", "EXPIRED", "REVOKED", "DISABLED", "MISSING", "UNKNOWN"],
    valuesReturnedToBrowser: false,
    valuesIncludedInEvidence: false,
    valuesIncludedInLogs: false,
    valuesIncludedInProjectZip: false
  };

  const externalContentSecurity = {
    defaultTrustClass: "UNTRUSTED_EXTERNAL",
    defaultPayloadState: "QUARANTINED",
    securityStates: ["QUARANTINED", "UNTRUSTED", "SANITIZED_UNTRUSTED", "REVIEW_REQUIRED", "BLOCKED", "UNKNOWN"],
    rawEvidencePreservedBeforeInterpretation: true,
    sanitizedViewIsDerived: true,
    sanitizedAutomaticallyTrusted: false,
    instructionAuthoritySeparated: true,
    malwareScannerRequiredForTextJson: false,
    unknownScannerRejected: true,
    archiveAutoExtractAllowed: false,
    binaryAutoExecuteAllowed: false,
    parserIsolationRequiredForRiskyPayloads: true
  };

  const dataLifecycle = {
    dataClasses: ["PUBLIC", "ACCOUNT_METADATA", "PERSONAL", "SENSITIVE", "DERIVED", "AGGREGATED", "UNKNOWN"],
    lifecycleStates: ["ACTIVE", "REVIEW_REQUIRED", "RETENTION_EXPIRED", "PRESERVATION_HOLD", "DELETION_CANDIDATE", "TOMBSTONED", "DELETED_BY_POLICY", "UNKNOWN"],
    retentionUnknownMeansUnlimited: false,
    preservationHoldSupported: true,
    automaticRawEvidenceDeletionAllowed: false,
    exportRequiresIndependentPolicyCheck: true,
    modelTrainingRequiresIndependentPolicyCheck: true,
    externalAiTransmissionRequiresIndependentPolicyCheck: true
  };

  const privacy = {
    defaultIdentityMode: "PSEUDONYMOUS_ACCOUNT",
    privacyRiskStates: ["LOW", "MODERATE", "HIGH", "RESTRICTED", "PROHIBITED_BY_POLICY", "UNKNOWN"],
    realPersonResolutionRestricted: true,
    sensitiveAttributeInferenceRestricted: true,
    crossPlatformLinkingCandidateOnly: true,
    reIdentificationRestricted: true,
    dataMinimizationRequired: true
  };

  const temporal = {
    temporalIntents: ["LATEST", "OFFICIAL_EFFECTIVE", "HISTORICAL", "BACKTEST", "AS_OF"],
    freshnessStates: ["FRESH", "STALE", "UNASSESSED", "HISTORICAL_CONTEXT", "UNKNOWN"],
    evidenceTimeFields: ["publishedAt", "availableAt", "effectiveAt", "acquiredAt"],
    historicalModeSupported: true,
    backtestFutureEvidenceGuardRequired: true,
    newestEvidenceAutomaticallyWins: false
  };

  const normalization = {
    immutableRawRequired: true,
    versionedNormalizedLayer: true,
    normalizationStates: ["NORMALIZED", "PARTIAL", "FAILED", "UNKNOWN"],
    resolutionStates: ["UNRESOLVED", "AMBIGUOUS", "PROBABLE", "IDENTIFIER_MATCH", "EXACT", "FAILED", "UNKNOWN"],
    resolutionHookTypes: ["UNIT", "TEMPORAL", "ENTITY"],
    reprocessingPreservesHistory: true,
    derivedDataBoundaryRequired: true
  };

  const claim = {
    candidateOnly: true,
    stableClaimIdRequired: true,
    claimantPublisherSeparationRequired: true,
    atomicClaimRequired: true,
    rawContextReferenceRequired: true,
    extractionVersionRequired: true,
    automaticTruthPromotionAllowed: false,
    automaticKnowledgePromotionAllowed: false
  };

  const entity = {
    stableEntityIdRequired: true,
    aliasIdentifierGraphSupported: true,
    resolutionStates: ["UNRESOLVED", "AMBIGUOUS", "PROBABLE", "IDENTIFIER_MATCH", "EXACT", "UNKNOWN"],
    textMentionSupported: true,
    visualMentionHookSupported: true,
    multimodalResolutionCandidateSupported: true,
    mergeSplitCandidateOnly: true,
    visualSimilarityAutoResolveAllowed: false,
    knowledgeMutationAllowed: false
  };

  const analyticalCapability = {
    capabilityTypes: ["LLM", "VISION_MODEL", "MULTIMODAL_MODEL", "STATISTICAL_MODEL", "TIME_SERIES_MODEL", "RULE_ENGINE", "ALGORITHM", "PYTHON_WORKER", "LOCAL_MODEL", "EXTERNAL_AI_SERVICE", "ENSEMBLE", "HUMAN_ANALYSIS", "UNKNOWN"],
    availabilityStates: ["READY", "DEGRADED", "UNAVAILABLE", "DISABLED", "BLOCKED", "EXPERIMENTAL", "DEPRECATED", "UNKNOWN"],
    roles: ["PRIMARY", "SECONDARY", "SPECIALIST", "REVIEWER", "FALSIFICATION_REVIEWER", "SHADOW", "EXPERIMENTAL", "DEPRECATED", "DISABLED"],
    outputClassifications: ["MODEL_ANALYSIS", "MODEL_DERIVED_CLAIM", "HYPOTHESIS", "PREDICTION", "SUMMARY", "CLASSIFICATION"],
    stableIdentityRequired: true,
    versionedHistoryRequired: true,
    routingCandidateOnly: true,
    independentReviewHook: true,
    shadowEvaluationHook: true,
    outcomePerformanceHook: true,
    automaticPromotionAllowed: false,
    actionAuthorityGrantedByPerformance: false
  };

  const lineage = {
    transformationTypes: ["PARSE", "NORMALIZE", "EXTRACT", "AGGREGATE", "SUMMARIZE", "CLASSIFY", "SCORE", "INFER", "PREDICT", "REVIEW", "FUSE", "BACKTEST", "RECOMPUTE", "OTHER"],
    relationTypes: ["DERIVED_FROM", "NORMALIZED_FROM", "EXTRACTED_FROM", "AGGREGATED_FROM", "SUMMARIZED_FROM", "CLASSIFIED_FROM", "SCORED_FROM", "INFERRED_FROM", "PREDICTED_FROM", "REVIEWED_FROM", "FUSED_FROM", "RECOMPUTED_FROM", "SUPERSEDES", "DEPENDS_ON"],
    lineageStates: ["ACTIVE", "SUPERSEDED", "AFFECTED", "RECOMPUTE_CANDIDATE", "PARTIAL", "FAILED", "UNKNOWN"],
    snapshotBasedReproducibility: true,
    forwardDependencyQuery: true,
    reverseProvenanceQuery: true,
    blastRadiusHook: true,
    recomputeCandidateOnly: true,
    derivationGraphAcyclic: true,
    historicalRewriteAllowed: false
  };

  const relationEvent = {
    relationTypes: [
      "OWNS", "SUBSIDIARY_OF", "CEO_OF", "EMPLOYED_BY", "PARTNERS_WITH", "SUPPLIES_TO",
      "CUSTOMER_OF", "COMPETES_WITH", "INVESTS_IN", "LICENSES_TECHNOLOGY_FROM", "MANUFACTURES",
      "DISTRIBUTES", "MEMBER_OF", "LOCATED_IN", "RELATED_TO"
    ],
    relationStates: ["CANDIDATE", "SUPPORTED", "CONTRADICTED", "ACTIVE", "HISTORICAL", "SUPERSEDED", "DISPUTED", "UNKNOWN"],
    eventTypes: [
      "ACQUISITION", "MERGER", "SPIN_OFF", "PARTNERSHIP", "CONTRACT", "APPOINTMENT", "RESIGNATION",
      "IPO", "DELISTING", "STOCK_SPLIT", "DIVIDEND", "BUYBACK", "EARNINGS_RELEASE", "GUIDANCE_REVISION",
      "PRODUCT_LAUNCH", "FACTORY_OPENING", "FACTORY_SHUTDOWN", "REGULATORY_APPROVAL", "REGULATORY_ACTION",
      "LAWSUIT", "BANKRUPTCY", "DISASTER", "OUTBREAK", "POLICY_CHANGE", "SUPPLY_DISRUPTION", "UNKNOWN"
    ],
    eventStates: [
      "RUMORED", "PROPOSED", "ANNOUNCED", "PLANNED", "SCHEDULED", "REGULATORY_REVIEW", "APPROVED",
      "IN_PROGRESS", "COMPLETED", "CANCELLED", "FAILED", "DISPUTED", "UNKNOWN"
    ],
    eventRelationLinkTypes: ["ESTABLISHES", "ENDS", "UPDATES", "SUPPORTS", "CONTRADICTS", "RELATED_TO"],
    temporalValidityRequired: true,
    versionedHistoryRequired: true,
    historicalAsOfGraphSupported: true,
    graphTraversalHookSupported: true,
    impactAnalysisExtensionHookSupported: true,
    canonicalAutoResolutionAllowed: false,
    relationEqualsCausalImpact: false
  };

  const impactGraph = {
    directions: ["POSITIVE", "NEGATIVE", "MIXED", "CONDITIONAL", "NEUTRAL", "UNKNOWN"],
    causalStates: ["OBSERVED_ASSOCIATION", "CORRELATION", "INFLUENCE_CANDIDATE", "CAUSAL_HYPOTHESIS", "CAUSAL_LINK_SUPPORTED", "CAUSAL_LINK_CONTRADICTED", "INCONCLUSIVE", "UNKNOWN"],
    impactDimensions: [
      "DEMAND", "SUPPLY", "PRICE", "COST", "REVENUE", "PROFIT", "CAPACITY", "EMPLOYMENT", "FINANCING",
      "REGULATION", "SENTIMENT", "MARKET_PRICE", "LIQUIDITY", "TECHNOLOGY", "COMPETITION", "LOGISTICS", "RISK", "UNKNOWN"
    ],
    timeHorizons: ["IMMEDIATE", "SHORT_TERM", "MEDIUM_TERM", "LONG_TERM", "STRUCTURAL", "UNKNOWN"],
    stageStates: ["NOT_OBSERVED", "EARLY_SIGNAL", "PARTIALLY_OBSERVED", "OBSERVED", "CONFIRMED", "CONTRADICTED", "BYPASSED", "FAILED_TO_PROPAGATE", "UNKNOWN"],
    lagUnits: ["MILLISECOND", "SECOND", "MINUTE", "HOUR", "DAY", "WEEK", "MONTH", "YEAR", "UNKNOWN"],
    multiStagePaths: true,
    earliestExpectedLatestLagRequired: true,
    lagDistributionHookSupported: true,
    intermediateObservationTracking: true,
    remainingLagRecalculationHookSupported: true,
    confounderAware: true,
    historicalAnalogDifferenceRequired: true,
    scenarioCandidateHookSupported: true,
    predictionEvaluationHookSupported: true,
    modelVersionRequired: true,
    evidenceLineageRequired: true,
    automaticCausalTruthAllowed: false,
    automaticActionAllowed: false
  };

  const phase9Permissions = {
    aiMayGenerateRelationCandidate: true,
    aiMayGenerateEventCandidate: true,
    observedIntermediateStateMayTriggerRecalculation: true,
    aiMayGenerateCausalHypothesis: true,
    aiMayGenerateHistoricalAnalogCandidate: true,
    aiMayGenerateScenarioCandidate: true,
    candidateGenerationGrantsCanonicalAuthority: false,
    candidateGenerationGrantsActionAuthority: false,
    candidateGenerationGrantsKnowledgeAuthority: false
  };

  const manifest = {
    componentId: "EXTERNAL-010",
    componentName: "External Intelligence Platform",
    namespace: "EXTERNAL010ExternalIntelligence",
    mission: "Evidence-Grounded External Intelligence Platform",
    versionArchitecture: "independent-version-v1",
    release: {
      version: RELEASE_VERSION,
      implementationPhase: "Phase 11 Signal Detection / Competing Hypothesis / Research Priority",
      phase: 11,
      phaseCount: 21,
      designFreezeId: "EXTERNAL-010-DESIGN-FREEZE-1.0.0",
      designFreezeVersion: "1.0.0",
      designFreezePackageId: "EXTERNAL-010-DESIGN-FREEZE-PACKAGE-1.1.0",
      implementationRoadmapId: "EXTERNAL-010-IMPLEMENTATION-ROADMAP-2.1.0",
      decisionRange: "EXTERNAL-010-DECISION-001..054",
      decisionCount: 54,
      architectureStatus: "DESIGN COMPLETE / FROZEN",
      status: "Phase 11 Signal Detection / Competing Hypothesis / Research Priority Implementation"
    },
    moduleVersions: moduleVersions,
    fileModules: fileModules,
    contractVersions: contractVersions,
    contractIds: contractIds,
    safety: safety,
    authorityPolicy: authorityPolicy,
    compatibility: compatibility,
    gateway: gateway,
    supplyChain: supplyChain,
    sourceGovernance: sourceGovernance,
    discovery: discovery,
    resourceBudget: resourceBudget,
    usagePolicy: usagePolicy,
    acquisition: acquisition,
    persistence: persistence,
    secretGovernance: secretGovernance,
    externalContentSecurity: externalContentSecurity,
    dataLifecycle: dataLifecycle,
    privacy: privacy,
    temporal: temporal,
    normalization: normalization,
    claim: claim,
    entity: entity,
    analyticalCapability: analyticalCapability,
    lineage: lineage,
    relationEvent: relationEvent,
    impactGraph: impactGraph,
    phase9Permissions: phase9Permissions,
    implementation: {
      inspectBeforeImplement: true,
      contractFirst: true,
      phase1Complete: true,
      phase2Complete: true,
      phase3Allowed: true,
      phase3Complete: true,
      phase4Allowed: true,
      phase4Complete: true,
      phase5Allowed: true,
      phase5Complete: true,
      phase6Allowed: true,
      phase6Complete: true,
      phase7Allowed: true,
      phase7Complete: true,
      phase8Allowed: true,
      phase8Complete: true,
      phase9Allowed: true,
      phase9Complete: true,
      phase10Allowed: true,
      phase10Complete: true,
      phase11Allowed: true,
      phase11Complete: false,
      phase12Allowed: false,
      releaseAllowed: false,
      androidRealDeviceGateRequired: true,
      pcRealRuntimeGateRequiredWhereApplicable: true
    },
    getModuleVersion: function getModuleVersion(moduleOrFile) {
      const key = fileModules[moduleOrFile] || moduleOrFile;
      return moduleVersions[key] || null;
    },
    getContractVersion: function getContractVersion(contractKeyOrId) {
      if (contractVersions[contractKeyOrId]) return contractVersions[contractKeyOrId];
      const key = Object.keys(contractIds).find(function findKey(candidate) {
        return contractIds[candidate] === contractKeyOrId;
      });
      return key ? contractVersions[key] : null;
    },
    getContractId: function getContractId(contractKey) {
      return contractIds[contractKey] || null;
    },
    isReleaseCompatibleFrom: isReleaseCompatibleFrom
  };

  global.EXTERNAL010VersionManifest = deepFreeze(manifest);
})(typeof window !== "undefined" ? window : globalThis);
