/* ============================================================
   FILE: 17_external_intelligence_outcome.js
   EXTERNAL-010 External Intelligence Platform
   Release: 1.9.1
   Phase 10: Reliability Signals / Uncertainty / Outcome Foundation
   ============================================================ */
(function (global) {
  "use strict";
  const namespace = global.EXTERNAL010ExternalIntelligence;
  const VERSION_MANIFEST = global.EXTERNAL010VersionManifest;
  if (!namespace || !namespace.__internal || !VERSION_MANIFEST) return;
  const internal = namespace.__internal;
  const state = internal.state;
  const MODULE_VERSION = VERSION_MANIFEST.getModuleVersion("outcome");

  const SETTLEMENT=["NOT_YET_OBSERVED","NOT_YET_AVAILABLE","PARTIALLY_OBSERVED","PRELIMINARY","PROVISIONAL","REVISED","FINAL","DISPUTED","UNRESOLVED","UNMEASURABLE","UNKNOWN"];
  function validateRecord(contractKey,schemaId,record){const cv=namespace.validateExternalIntelligenceContract(contractKey,record);const sv=namespace.validateExternalIntelligenceRecord(schemaId,record);return {valid:cv.valid===true&&sv.valid===true,contract:cv,schema:sv};}
  function registerExternalIntelligenceBenchmarkDefinition(input){const x=internal.isPlainObject(input)?input:{};const id=internal.text(x.benchmarkDefinitionId,"");if(!id)return internal.buildResult(false,"EXTERNAL010_BENCHMARK_ID_REQUIRED","Blocked",null);const version=Math.max(1,Number(x.version)||1),key=id+"@"+version;if(state.benchmarkDefinitionVersions.has(key))return internal.buildResult(true,"EXTERNAL010_BENCHMARK_ALREADY_REGISTERED","Ready",{benchmarkDefinition:internal.clone(state.benchmarkDefinitionVersions.get(key))});const rec=internal.deepFreeze({benchmarkDefinitionId:id,version,targetMetric:internal.text(x.targetMetric,""),measurementMethod:internal.text(x.measurementMethod,""),targetWindow:internal.text(x.targetWindow,"")||null,unit:internal.text(x.unit,"")||null,currency:internal.text(x.currency,"")||null,adjustmentMethod:internal.text(x.adjustmentMethod,"")||null,eventCompletionCriteria:internal.text(x.eventCompletionCriteria,"")||null,dataSourcePolicy:internal.text(x.dataSourcePolicy,"")||null,timezone:internal.text(x.timezone,"UTC"),supersedesBenchmarkVersion:x.supersedesBenchmarkVersion||null,createdAt:internal.nowIso(),immutable:true});const validity=validateRecord("benchmarkDefinition","EXTERNAL-010-SCHEMA-BENCHMARK-DEFINITION",rec);if(!validity.valid)return internal.buildResult(false,"EXTERNAL010_BENCHMARK_RECORD_INVALID","Blocked",validity);state.benchmarkDefinitionVersions.set(key,rec);state.benchmarkDefinitions.set(id,rec);internal.touch();return internal.buildResult(true,"EXTERNAL010_BENCHMARK_REGISTERED","Ready",{benchmarkDefinition:internal.clone(rec)});}
  function registerExternalIntelligenceOutcome(input){const x=internal.isPlainObject(input)?input:{};const id=internal.text(x.outcomeId,"");if(!id)return internal.buildResult(false,"EXTERNAL010_OUTCOME_ID_REQUIRED","Blocked",null);const version=Math.max(1,Number(x.version)||1),key=id+"@"+version;if(state.outcomeVersions.has(key))return internal.buildResult(true,"EXTERNAL010_OUTCOME_ALREADY_REGISTERED","Ready",{outcome:internal.clone(state.outcomeVersions.get(key))});const ss=internal.text(x.settlementState,"UNKNOWN").toUpperCase();if(!SETTLEMENT.includes(ss))return internal.buildResult(false,"EXTERNAL010_SETTLEMENT_STATE_INVALID","Blocked",{settlementState:ss});const benchmarkId=internal.text(x.benchmarkDefinitionId,"");if(!benchmarkId||!state.benchmarkDefinitions.has(benchmarkId))return internal.buildResult(false,"EXTERNAL010_BENCHMARK_REQUIRED","Blocked",{benchmarkDefinitionId:benchmarkId});const rec=internal.deepFreeze({outcomeId:id,version,outcomeRecordId:id+"-V"+version,predictionId:internal.text(x.predictionId,"")||null,benchmarkDefinitionId:benchmarkId,outcomeType:internal.text(x.outcomeType,"UNSPECIFIED"),targetEntityId:internal.text(x.targetEntityId,"")||null,targetMetric:internal.text(x.targetMetric,"")||null,observationTime:internal.text(x.observationTime,"")||null,effectiveTime:internal.text(x.effectiveTime,"")||null,settlementState:ss,value:x.value===undefined?null:internal.clone(x.value),unit:internal.text(x.unit,"")||null,currency:internal.text(x.currency,"")||null,supportingEvidenceIds:internal.unique(x.supportingEvidenceIds||[]),sourceRole:internal.text(x.sourceRole,"UNKNOWN"),referenceOutcome:x.referenceOutcome===true,supersedesOutcomeRecordId:internal.text(x.supersedesOutcomeRecordId,"")||null,absoluteTruthClaimed:false,historyOverwritePerformed:false,createdAt:internal.nowIso(),immutable:true});const validity=validateRecord("outcomeRecord","EXTERNAL-010-SCHEMA-OUTCOME-RECORD",rec);if(!validity.valid)return internal.buildResult(false,"EXTERNAL010_OUTCOME_RECORD_INVALID","Blocked",validity);state.outcomeVersions.set(key,rec);state.outcomeRecords.set(id,rec);internal.touch();return internal.buildResult(true,"EXTERNAL010_OUTCOME_REGISTERED","Ready",{outcome:internal.clone(rec)});}
  function listExternalIntelligenceOutcomeHistory(id){return Array.from(state.outcomeVersions.values()).filter(r=>r.outcomeId===id).sort((a,b)=>a.version-b.version).map(internal.clone);}
  function recordExternalIntelligenceOutcomeEvaluation(input){const x=internal.isPlainObject(input)?input:{};const prediction=state.predictionRecords.get(internal.text(x.predictionId,""));const outcome=state.outcomeVersions.get(internal.text(x.outcomeId,"")+"@"+Math.max(1,Number(x.outcomeVersion)||1));if(!prediction||!outcome)return internal.buildResult(false,"EXTERNAL010_EVALUATION_REFERENCES_REQUIRED","Blocked",null);const id=internal.text(x.evaluationId,internal.nextId("EXTERNAL-010-OUTCOME-EVALUATION"));const rec=internal.deepFreeze({evaluationId:id,predictionRecordId:prediction.predictionRecordId,referenceOutcomeRecordId:outcome.outcomeRecordId,benchmarkDefinitionId:outcome.benchmarkDefinitionId,evaluationState:internal.text(x.evaluationState,"RECORDED"),calibrationState:internal.text(x.calibrationState,"UNASSESSED"),truthAuthorityGranted:false,automaticActionPerformed:false,createdAt:internal.nowIso(),immutable:true});const validity=validateRecord("outcomeEvaluation","EXTERNAL-010-SCHEMA-OUTCOME-EVALUATION",rec);if(!validity.valid)return internal.buildResult(false,"EXTERNAL010_OUTCOME_EVALUATION_INVALID","Blocked",validity);state.outcomeEvaluations.set(id,rec);internal.touch();return internal.buildResult(true,"EXTERNAL010_OUTCOME_EVALUATION_RECORDED","Ready",{evaluation:internal.clone(rec)});}
  Object.assign(namespace.api,{registerExternalIntelligenceBenchmarkDefinition,registerExternalIntelligenceOutcome,listExternalIntelligenceOutcomeHistory,recordExternalIntelligenceOutcomeEvaluation,getExternalIntelligenceOutcome:function(id){const r=state.outcomeRecords.get(internal.text(id,""));return r?internal.clone(r):null;}});Object.assign(namespace,namespace.api);
  namespace.modules.outcome={id:"EXTERNAL-010-OUTCOME",version:MODULE_VERSION,status:"Ready",phase:10,decisions:["031"],versionedOutcome:true,noGroundTruthAssumption:true,loadedAt:internal.nowIso()};
})(typeof window !== "undefined" ? window : globalThis);
