(function(global){"use strict";const namespace=global.EXTERNAL010ExternalIntelligence,VM=global.EXTERNAL010VersionManifest;if(!namespace||!namespace.__internal||!VM)return;const internal=namespace.__internal,state=internal.state;const MODULE_VERSION=VM.getModuleVersion("marketIdentity");
const PHASE17_DEFS=[
["marketInstrument","EXTERNAL-010-CONTRACT-MARKET-INSTRUMENT","EXTERNAL-010-SCHEMA-MARKET-INSTRUMENT",["instrumentId","venueId","symbol","assetType","tradableInstrumentEqualsCompanyEntity","immutable"]],
["marketBar","EXTERNAL-010-CONTRACT-MARKET-BAR","EXTERNAL-010-SCHEMA-MARKET-BAR",["barId","version","instrumentId","open","high","low","close","volume","seriesKind","gapState","finalizationState","missingBarEqualsUnchangedPrice","immutable"]],
["technicalIndicatorResult","EXTERNAL-010-CONTRACT-TECHNICAL-INDICATOR-RESULT","EXTERNAL-010-SCHEMA-TECHNICAL-INDICATOR-RESULT",["indicatorResultId","algorithmId","algorithmVersion","parameters","inputSeriesId","values","reproducible","tradingAuthorityGranted","immutable"]],
["technicalSignalCandidate","EXTERNAL-010-CONTRACT-TECHNICAL-SIGNAL-CANDIDATE","EXTERNAL-010-SCHEMA-TECHNICAL-SIGNAL-CANDIDATE",["technicalSignalCandidateId","indicatorResultId","candidateOnly","tradingDecision","orderCreated","tradingAuthorityGranted","immutable"]],
["pythonWorkerCapability","EXTERNAL-010-CONTRACT-PYTHON-WORKER-CAPABILITY","EXTERNAL-010-SCHEMA-PYTHON-WORKER-CAPABILITY",["workerId","workerVersion","capabilities","optional","executionAuthorityGranted","tradingAuthorityGranted","paidApiAuthorityGranted","immutable"]]
];
function initializePhase17Definitions(){const results=[];PHASE17_DEFS.forEach(function(d){if(typeof namespace.registerExternalIntelligenceContract==="function")results.push(namespace.registerExternalIntelligenceContract({contractId:d[1],key:d[0],name:d[0]+" Contract",version:MODULE_VERSION,immutable:true,fields:d[3].map(function(n){return{name:n,required:true};}),source:"phase17"}));if(typeof namespace.registerExternalIntelligenceSchema==="function")results.push(namespace.registerExternalIntelligenceSchema({schemaId:d[2],name:d[0]+" Schema",version:MODULE_VERSION,type:"object",required:d[3],properties:Object.fromEntries(d[3].map(function(n){return[n,{}];})),additionalProperties:true,immutable:true,owner:"EXTERNAL-010",source:"phase17"}));});return results;} initializePhase17Definitions();["marketInstruments","marketVenues","marketSessions","marketRuleProfiles"].forEach(k=>{if(!(state[k] instanceof Map))state[k]=new Map();});
function norm(v){return internal.text(v,"").trim().toUpperCase();}
function registerVenue(x){x=internal.isPlainObject(x)?x:{};const venueId=norm(x.venueId);if(!venueId)return internal.buildResult(false,"EXTERNAL010_MARKET_VENUE_ID_REQUIRED","Blocked",null);const r=internal.deepFreeze({venueId,venueName:internal.text(x.venueName,venueId),mic: norm(x.mic)||null,countryCode:norm(x.countryCode)||null,timeZone:internal.text(x.timeZone,"UTC"),immutable:true,createdAt:internal.nowIso()});state.marketVenues.set(venueId,r);return internal.buildResult(true,"EXTERNAL010_MARKET_VENUE_REGISTERED","Ready",{venue:internal.clone(r)});}
function registerInstrument(x){x=internal.isPlainObject(x)?x:{};const venueId=norm(x.venueId),symbol=norm(x.symbol),assetType=norm(x.assetType||"EQUITY");if(!venueId||!symbol||!state.marketVenues.has(venueId))return internal.buildResult(false,"EXTERNAL010_MARKET_INSTRUMENT_IDENTITY_INVALID","Blocked",{venueId,symbol});const instrumentId=internal.text(x.instrumentId,"")||("EXTERNAL-010-INSTRUMENT-"+venueId+"-"+symbol);const r=internal.deepFreeze({instrumentId,venueId,symbol,assetType,currency:norm(x.currency||"USD"),entityId:internal.text(x.entityId,"")||null,tradableInstrumentEqualsCompanyEntity:false,immutable:true,createdAt:internal.nowIso()});state.marketInstruments.set(instrumentId,r);return internal.buildResult(true,"EXTERNAL010_MARKET_INSTRUMENT_REGISTERED","Ready",{instrument:internal.clone(r)});}
function registerSession(x){x=internal.isPlainObject(x)?x:{};const venueId=norm(x.venueId);if(!state.marketVenues.has(venueId))return internal.buildResult(false,"EXTERNAL010_MARKET_SESSION_VENUE_REQUIRED","Blocked",null);const sessionId=internal.text(x.sessionId,"")||internal.nextId("EXTERNAL-010-MARKET-SESSION");const r=internal.deepFreeze({sessionId,venueId,sessionType:norm(x.sessionType||"REGULAR"),opensAt:internal.text(x.opensAt,""),closesAt:internal.text(x.closesAt,""),timeZone:internal.text(x.timeZone,state.marketVenues.get(venueId).timeZone),immutable:true});state.marketSessions.set(sessionId,r);return internal.buildResult(true,"EXTERNAL010_MARKET_SESSION_REGISTERED","Ready",{session:internal.clone(r)});}
function registerRuleProfile(x){x=internal.isPlainObject(x)?x:{};const profileId=internal.text(x.marketRuleProfileId,"")||internal.nextId("EXTERNAL-010-MARKET-RULE");const r=internal.deepFreeze({marketRuleProfileId:profileId,venueId:norm(x.venueId)||null,tickSize:Number(x.tickSize)||null,priceAdjustmentPolicy:internal.text(x.priceAdjustmentPolicy,"EXPLICIT_ONLY"),sessionPolicy:internal.text(x.sessionPolicy,"VENUE_DEFINED"),immutable:true});state.marketRuleProfiles.set(profileId,r);return internal.buildResult(true,"EXTERNAL010_MARKET_RULE_PROFILE_REGISTERED","Ready",{marketRuleProfile:internal.clone(r)});}
Object.assign(namespace.api,{initializeExternalIntelligencePhase17Definitions:initializePhase17Definitions,registerExternalIntelligenceMarketVenue:registerVenue,registerExternalIntelligenceMarketInstrument:registerInstrument,registerExternalIntelligenceMarketSession:registerSession,registerExternalIntelligenceMarketRuleProfile:registerRuleProfile,getExternalIntelligenceMarketInstrument:id=>state.marketInstruments.has(id)?internal.clone(state.marketInstruments.get(id)):null});Object.assign(namespace,namespace.api);namespace.modules.marketIdentity={id:"EXTERNAL-010-MARKET-IDENTITY",version:MODULE_VERSION,phase:17,decisions:["047"],status:"Ready",companyEntityEqualsTradableInstrument:false};})(typeof window!=="undefined"?window:globalThis);