/* ============================================================
   FILE: 17_external_intelligence_phase6_real_runtime_validation.js
   EXTERNAL-010 External Intelligence Platform
   Release: 1.5.0 / Gateway 1.4.0
   Phase 06 PC Real Runtime Validation
   Reference-only Secret -> Gateway Injection -> Redaction -> Security/Lifecycle/Privacy
   ============================================================ */
(function(global){
  "use strict";
  const namespace=global.EXTERNAL010ExternalIntelligence;
  const VERSION_MANIFEST=global.EXTERNAL010VersionManifest;
  if(!namespace||!namespace.__internal||!VERSION_MANIFEST){console.warn("EXTERNAL-010 Phase 06 PC validation blocked: dependencies missing.");return;}
  const internal=namespace.__internal,state=internal.state,MODULE_VERSION=VERSION_MANIFEST.getModuleVersion("phase6RealRuntimeValidation"),PURPOSE="phase6-pc-real-runtime";
  function collector(){const checks=[];return{checks,check(name,passed,detail,group,severity){checks.push({name,passed:passed===true,detail:detail==null?"":(typeof detail==="string"?detail:internal.stableStringify(detail)),group:group||"PC Real Runtime",severity:severity||"Critical"});}};}
  function summarize(checks){const passed=checks.filter(x=>x.passed).length,failed=checks.length-passed,criticalFailed=checks.filter(x=>!x.passed&&x.severity==="Critical").length;return{passed,failed,total:checks.length,criticalFailed,health:checks.length?Math.round(passed/checks.length*1000)/10:0};}
  async function sha256Hex(text){const bytes=new TextEncoder().encode(String(text||""));const digest=await global.crypto.subtle.digest("SHA-256",bytes);return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("");}
  async function grantAuthority(action,type,id,owned,purpose){const candidate=namespace.createExternalIntelligenceAuthorityEnvelopeCandidate({action,target:{type,id},purpose:purpose||PURPOSE,scope:{domain:"EXTERNAL-010",operation:action}});if(!candidate.ok)return{ok:false,candidate};owned.push(candidate.data.envelope.authorityEnvelopeId);const activated=await namespace.activateExternalIntelligenceAuthorityEnvelope(candidate.data.envelope.authorityEnvelopeId,{validationOnly:true});return{ok:activated.ok===true,activated,envelopeId:candidate.data.envelope.authorityEnvelopeId};}
  async function setupAuthenticatedSource(sourceId,endpoint,budgetId,owned){
    const operationId="READ",adapterId=VERSION_MANIFEST.acquisition.adapterIds.localGateway,secretReferenceId="SECRET-PHASE6-TEST";
    const regAuth=await grantAuthority("REGISTER_EXTERNAL_SOURCE","source",sourceId,owned);if(!regAuth.ok)return{ok:false,stage:"register-authority",result:regAuth};
    const registered=await namespace.registerExternalIntelligenceSource({sourceId,sourceName:"Phase 06 PC Protected Source",sourceType:"PUBLIC_API",provider:"EXTERNAL-010 Phase 06 Controlled Fixture",accessMode:"LOCAL_GATEWAY",adapterId,endpointPolicy:{canonicalHost:endpoint.canonicalHost,endpointReference:endpoint.endpointReference,allowRedirects:false},authenticationMode:"BEARER_TOKEN",secretReferenceId,allowedOperations:[operationId],allowedMethods:["GET"],pricingMode:"FREE",purpose:PURPOSE});
    if(!registered.ok)return{ok:false,stage:"register",result:registered};
    const policyCandidate=namespace.createExternalIntelligenceUsagePolicyCandidate({sourceId,policyVersion:"phase6-pc-1",policyEvidenceIds:["PHASE6-PC-CONTROLLED-FIXTURE-POLICY"],policyCompleteness:"COMPLETE",interpretationConfidence:"HIGH",rights:{READ:{state:"ALLOWED",confidence:"HIGH",evidenceIds:["PHASE6-PC-CONTROLLED-FIXTURE-POLICY"]}}});
    if(!policyCandidate.ok)return{ok:false,stage:"policy-candidate",result:policyCandidate};
    const policyAuth=await grantAuthority("ACTIVATE_USAGE_POLICY","usage-policy",policyCandidate.data.usagePolicy.usagePolicyId,owned);if(!policyAuth.ok)return{ok:false,stage:"policy-authority",result:policyAuth};
    const policyActive=await namespace.activateExternalIntelligenceUsagePolicy({usagePolicyId:policyCandidate.data.usagePolicy.usagePolicyId,purpose:PURPOSE});if(!policyActive.ok)return{ok:false,stage:"policy-activate",result:policyActive};
    const enableAuth=await grantAuthority("ENABLE_EXTERNAL_SOURCE","source",sourceId,owned);if(!enableAuth.ok)return{ok:false,stage:"enable-authority",result:enableAuth};
    const enabled=await namespace.enableExternalIntelligenceSource({sourceId,operations:[operationId],purpose:PURPOSE});if(!enabled.ok)return{ok:false,stage:"enable",result:enabled};
    const activateAuth=await grantAuthority("ACTIVATE_EXTERNAL_SOURCE","source",sourceId,owned);if(!activateAuth.ok)return{ok:false,stage:"activate-authority",result:activateAuth};
    const activated=await namespace.activateExternalIntelligenceSource({sourceId,purpose:PURPOSE});if(!activated.ok)return{ok:false,stage:"activate",result:activated};
    const operationContractId="EXTERNAL-010-OP-"+sourceId.replace(/^SOURCE-/,"")+"-READ";
    const opAuth=await grantAuthority("REGISTER_SOURCE_OPERATION_CONTRACT","source-operation",operationContractId,owned,"phase4-operation-contract");if(!opAuth.ok)return{ok:false,stage:"operation-authority",result:opAuth};
    const operation=await namespace.registerExternalIntelligenceSourceOperationContract({operationContractId,sourceId,operationId,adapterId,method:"GET",endpoint,parameterPolicy:{required:[],optional:[],allowUnknown:false,maxParameterCount:4},timeoutPolicy:{timeoutMs:5000},retryPolicy:{maxAttempts:1,initialDelayMs:0,maxDelayMs:0,backoffPolicy:"NONE",retryableCategories:["TIMEOUT","SOURCE_UNAVAILABLE"]},responseMode:"JSON",executionHints:{backgroundPreferred:false,expectedResponseSize:"SMALL",longRunning:false,batch:false},estimatedUsage:{REQUEST_COUNT:1,NETWORK_BYTES:8192,PROCESSING_TIME:5000}});
    if(!operation.ok)return{ok:false,stage:"operation",result:operation};
    const request=namespace.createExternalIntelligenceAcquisitionRequest({sourceId,operationId,parameters:{},priority:"NORMAL",executionPreference:"IMMEDIATE",purpose:PURPOSE,requestedBy:"Project Owner PC Real Runtime Validation",correlationId:"PHASE6-PC-REAL-RUNTIME",idempotencyKey:"PHASE6-PC-"+Date.now()+"-"+Math.random(),budgetIds:[budgetId],acquisitionPlanId:"PHASE6-PC-PLAN",researchGoalId:"PHASE6-PC-GOAL"});
    if(!request.ok)return{ok:false,stage:"request",result:request};
    const execAuth=await grantAuthority("EXECUTE_EXTERNAL_ACQUISITION","external-acquisition",request.data.request.requestId,owned);if(!execAuth.ok)return{ok:false,stage:"execute-authority",result:execAuth};
    return{ok:true,request:request.data.request,source:namespace.getExternalIntelligenceSource(sourceId),operation:operation.data.operationContract};
  }

  async function runExternalIntelligencePhase6PcRealRuntimeValidation(input){
    const settings=internal.isPlainObject(input)?input:{},gatewayBaseUrl=internal.text(settings.gatewayBaseUrl,VERSION_MANIFEST.gateway.defaultBaseUrl).replace(/\/+$/,""),fixtureBaseUrl=internal.text(settings.fixtureBaseUrl,"http://127.0.0.1:43130").replace(/\/+$/,""),c=collector(),check=c.check,owned=[];let phase6=null,execution=null,persisted=null,security=null;
    try{
      check("Release Version is Phase 06 compatible or later",VERSION_MANIFEST.isReleaseCompatibleFrom("1.5.0"),VERSION_MANIFEST.release.version,"Foundation");
      check("Gateway compatibility version is 1.4.0",VERSION_MANIFEST.gateway.gatewayVersion==="1.4.0",VERSION_MANIFEST.gateway.gatewayVersion,"Foundation");
      const init=await namespace.initializeExternalIntelligenceFoundation();check("Phase 06 foundation initializes for PC real runtime",init&&init.ok===true,init&&init.code,"Foundation");
      phase6=await namespace.runExternalIntelligencePhase6Validation();check("Phase 06 regression remains PASS",phase6.failed===0&&phase6.health===100&&phase6.phase6Complete===true,{passed:phase6.passed,failed:phase6.failed,total:phase6.total},"Regression");
      const configured=namespace.configureExternalIntelligenceGatewayClient({baseUrl:gatewayBaseUrl});check("Gateway client remains loopback-bound",configured.ok===true&&/^http:\/\/(?:127\.0\.0\.1|localhost)(?::\d+)?$/i.test(configured.data.baseUrl),configured.data||configured.code,"Gateway");
      const health=await namespace.getExternalIntelligenceGatewayHealth();check("Real Gateway health is READY at 1.4.0",health.ok===true&&health.data.health&&health.data.health.gatewayVersion==="1.4.0"&&health.data.health.loopbackOnly===true,health.data||health.code,"Gateway");
      const ownerApproval=namespace.setExternalIntelligenceAuthorityApprovalAdapter({adapterId:"EXTERNAL-010-PHASE6-PC-OWNER-APPROVAL",requiresExplicitOwnerInteraction:true,async verifyApproval(){return{approved:true,actorType:"Project Owner",interactionEvidenceId:"PHASE6-PC-OWNER-INTERACTION"};}});check("Project Owner validation approval adapter configured",ownerApproval.ok===true,ownerApproval.data||ownerApproval.code,"Authority");
      const secretMeta=namespace.registerExternalIntelligenceSecretMetadata({secretReferenceId:"SECRET-PHASE6-TEST",secretType:"BEARER_TOKEN",provider:"LOCAL_GATEWAY",status:"ACTIVE"});check("Browser registers Secret reference metadata only",secretMeta.ok===true&&secretMeta.data.secretValueStored===false,secretMeta.data||secretMeta.code,"Secret Governance");
      const session=await namespace.openExternalIntelligenceGatewaySession({requestedScope:["PROBE","READ_RUNTIME","ACQUIRE_EXTERNAL","READ_SECRET_METADATA","PERSIST_EVIDENCE","READ_EVIDENCE"]});check("Gateway session contains Phase 06 scopes without exposing provider Secret",session.ok===true&&session.data.session.scope.includes("ACQUIRE_EXTERNAL")&&session.data.session.scope.includes("READ_SECRET_METADATA")&&session.data.sessionTokenPersisted===false&&session.data.tokenReturnedToCaller===false,session.data||session.code,"Gateway Security");
      const status=await namespace.getExternalIntelligenceGatewaySecretMetadataStatus({secretReferenceId:"SECRET-PHASE6-TEST",secretType:"BEARER_TOKEN"});check("Gateway Secret status returns metadata only",status.ok===true&&status.data.secretValueReturned===false&&status.data.secretMetadata&&status.data.secretMetadata.valueExposed===false,status.data||status.code,"Secret Governance");
      const bridge=namespace.enableExternalIntelligenceGatewayAcquisitionBridge();check("Governed Gateway acquisition bridge is enabled",bridge.ok===true&&bridge.data.arbitraryUrlProxyEnabled===false,bridge.data||bridge.code,"Gateway");
      const pbridge=namespace.enableExternalIntelligenceGatewayEvidencePersistenceBridge();check("Gateway Evidence persistence bridge remains enabled",pbridge.ok===true,pbridge.data||pbridge.code,"Persistence");
      const persistAuth=await grantAuthority("PERSIST_EXTERNAL_EVIDENCE","external-evidence-persistence","*",owned),readAuth=await grantAuthority("READ_EXTERNAL_EVIDENCE","external-evidence","*",owned);check("Evidence persistence/read authority is explicitly scoped",persistAuth.ok&&readAuth.ok,{persist:persistAuth.ok,read:readAuth.ok},"Authority");
      const budgetCandidate=namespace.createExternalIntelligenceResourceBudgetCandidate({scopeType:"GLOBAL",scopeId:"EXTERNAL-010",currency:"JPY",period:{type:"PHASE6_PC_REAL_RUNTIME"},limits:{REQUEST_COUNT:{softLimit:10,hardLimit:20},NETWORK_BYTES:{softLimit:1000000,hardLimit:2000000},PROCESSING_TIME:{softLimit:60000,hardLimit:120000},FINANCIAL_COST:{softLimit:0,hardLimit:0}}});check("Zero-financial-cost PC security budget candidate created",budgetCandidate.ok===true,budgetCandidate.data||budgetCandidate.code,"Budget");
      const budgetId=budgetCandidate.ok?budgetCandidate.data.budget.budgetId:null;if(budgetId){const ba=await grantAuthority("ACTIVATE_RESOURCE_BUDGET","resource-budget",budgetId,owned);const active=ba.ok?await namespace.activateExternalIntelligenceResourceBudget({budgetId,purpose:PURPOSE}):ba;check("PC security budget activated",ba.ok===true&&active.ok===true,{authority:ba.ok,active:active.ok},"Budget");}
      const fixture=new URL(fixtureBaseUrl),sourceId="SOURCE-PHASE6-PC-PROTECTED-"+Date.now().toString(36).toUpperCase();
      const setup=await setupAuthenticatedSource(sourceId,{exactUrl:fixtureBaseUrl+"/protected",canonicalHost:fixture.hostname,endpointReference:"phase6-protected"},budgetId,owned);check("Authenticated governed source is prepared using Secret reference only",setup.ok===true&&setup.source&&setup.source.secretReferenceId==="SECRET-PHASE6-TEST"&&setup.source.authenticationMode==="BEARER_TOKEN",setup,"Governed Acquisition");
      execution=setup.ok?await namespace.executeExternalIntelligenceAcquisition({requestId:setup.request.requestId}):null;
      check("Gateway injects provider Secret and performs authenticated real HTTP",Boolean(execution&&execution.ok===true&&execution.data.response.payload&&execution.data.response.payload.authenticated===true),execution&&(execution.data||execution.code),"Governed Acquisition");
      const response=execution&&execution.ok?execution.data.response:null;
      check("Provider Secret echo is redacted before Browser receives response",Boolean(response&&response.payload&&response.payload.secretEcho==="[REDACTED]"&&typeof response.evidenceInput.rawText==="string"&&response.evidenceInput.rawText.indexOf("[REDACTED]")>=0),response&&{payload:response.payload,rawText:response.evidenceInput.rawText},"Secret Redaction");
      check("Browser response retains Secret reference but never Secret value field",Boolean(response&&response.evidenceInput&&!Object.prototype.hasOwnProperty.call(response.evidenceInput,"secretValue")&&!Object.prototype.hasOwnProperty.call(response,"secretValue")),response&&response.evidenceInput,"Secret Redaction");
      security=response?namespace.classifyExternalIntelligenceContent({rawText:response.evidenceInput.rawText,evidenceId:response.responseId,sourceId:sourceId}):null;
      check("Real provider hostile text is classified as untrusted",Boolean(security&&security.ok===true&&security.data.assessment.trustClass==="UNTRUSTED_EXTERNAL"&&security.data.assessment.signals.includes("PROMPT_INJECTION")&&security.data.assessment.signals.includes("SECRET_REQUEST")&&security.data.assessment.signals.includes("TOOL_REQUEST")),security&&(security.data||security.code),"External Content Security");
      check("Hostile provider text grants no instruction/tool/secret authority",Boolean(security&&security.ok===true&&security.data.assessment.instructionAuthorityGranted===false&&security.data.assessment.toolAuthorityGranted===false&&security.data.assessment.secretAuthorityGranted===false),security&&security.data.assessment,"Authority Boundary");
      persisted=response?await namespace.persistExternalIntelligenceAcquisitionEvidence({response,purpose:PURPOSE}):null;
      check("Redacted governed acquisition persists as immutable Evidence",Boolean(persisted&&persisted.ok===true&&persisted.data.acquisitionEvidence.immutable===true&&persisted.data.rawEvidence.immutable===true),persisted&&{code:persisted.code,status:persisted.status,data:persisted.data,error:persisted.error||null},"Persistence");
      const redactedRawHash=response?await sha256Hex(response.evidenceInput.rawText):null;check("Persisted physical Evidence hash matches the already-redacted raw HTTP body",Boolean(persisted&&persisted.ok===true&&redactedRawHash&&persisted.data.contentObject.contentHash===redactedRawHash&&!Object.prototype.hasOwnProperty.call(persisted.data.acquisitionEvidence,"secretValue")),{expectedRedactedRawHash:redactedRawHash,persistedContentHash:persisted&&persisted.ok&&persisted.data.contentObject.contentHash||null},"Secret Redaction");
      const lifecycle=persisted&&persisted.ok?namespace.createExternalIntelligenceDataLifecycleRecord({subjectType:"EVIDENCE",subjectId:persisted.data.acquisitionEvidence.evidenceId,sourceId, dataClass:"PUBLIC",purposeId:PURPOSE,policyVersion:"phase6-pc-1",lifecycleState:"ACTIVE"}):null;check("Persisted Evidence receives purpose-bound lifecycle metadata",Boolean(lifecycle&&lifecycle.ok===true&&lifecycle.data.lifecycle.purposeId===PURPOSE),lifecycle&&(lifecycle.data||lifecycle.code),"Data Lifecycle");
      const privacy=namespace.assessExternalIntelligencePrivacy({subjectId:"ACCOUNT-PHASE6-PC",purposeId:PURPOSE,crossPlatformLinkRequested:true,dataMinimized:true});check("PC privacy assessment remains pseudonymous and candidate-only",privacy.ok===true&&privacy.data.privacyAssessment.identityMode==="PSEUDONYMOUS_ACCOUNT"&&privacy.data.privacyAssessment.crossPlatformLinkConfirmed===false,privacy.data||privacy.code,"Privacy");
      const audit=await namespace.verifyExternalIntelligenceAuditChain();check("Audit chain remains valid after PC Phase 06 security flow",audit.valid===true,{valid:audit.valid,eventCount:audit.eventCount},"Audit");
      check("Automatic Repository/Knowledge/financial authority remains disabled",VERSION_MANIFEST.safety.directRepositoryMutationAllowed===false&&VERSION_MANIFEST.safety.automaticKnowledgePromotionAllowed===false&&VERSION_MANIFEST.safety.automaticPaidApiActivationAllowed===false&&VERSION_MANIFEST.safety.automaticTradeExecutionAllowed===false,VERSION_MANIFEST.safety,"Safety");
    }catch(error){check("Phase 06 PC real runtime completes without exception",false,{message:error&&error.message||String(error),stack:error&&error.stack||null},"Validation");}
    finally{owned.forEach(id=>namespace.revokeExternalIntelligenceAuthorityEnvelope(id,"Phase 06 PC validation completed"));namespace.setExternalIntelligenceAuthorityApprovalAdapter(null);if(typeof namespace.disableExternalIntelligenceGatewayAcquisitionBridge==="function")namespace.disableExternalIntelligenceGatewayAcquisitionBridge();try{await namespace.revokeExternalIntelligenceGatewaySession();}catch(_){}}
    const s=summarize(c.checks),gate=s.failed===0&&s.criticalFailed===0;
    const result={id:internal.nextId("EXTERNAL-010-PHASE6-PC-REAL-RUNTIME"),componentId:"EXTERNAL-010",version:VERSION_MANIFEST.release.version,gatewayVersion:VERSION_MANIFEST.gateway.gatewayVersion,implementationPhase:VERSION_MANIFEST.release.implementationPhase,passed:s.passed,failed:s.failed,total:s.total,health:s.health,criticalFailed:s.criticalFailed,status:gate?"EXTERNAL-010 Phase 06 PC Real Runtime Validation PASS":"EXTERNAL-010 Phase 06 PC Real Runtime Validation FAIL",releaseAllowed:gate,phase6PcRealRuntimeComplete:gate,phase6FinalGateReady:false,secretGovernance:{referenceOnly:true,gatewayResolved:gate,secretValueReturnedToBrowser:false},contentSecurity:{untrustedExternal:Boolean(security&&security.ok===true),instructionAuthorityGranted:false},regression:phase6?{passed:phase6.passed,failed:phase6.failed,total:phase6.total,health:phase6.health,status:phase6.status}:null,checks:c.checks,validatedAt:internal.nowIso()};
    state.latestPhase6PcRealRuntimeValidation=internal.deepFreeze(internal.clone(result));namespace.modules.phase6RealRuntimeValidation.status=gate?"Passed":"Failed";internal.touch();return internal.clone(result);
  }
  function getLatestExternalIntelligencePhase6PcRealRuntimeValidation(){return state.latestPhase6PcRealRuntimeValidation?internal.clone(state.latestPhase6PcRealRuntimeValidation):null;}
  Object.assign(namespace.api,{runExternalIntelligencePhase6PcRealRuntimeValidation,getLatestExternalIntelligencePhase6PcRealRuntimeValidation});Object.assign(namespace,namespace.api);
  namespace.modules.phase6RealRuntimeValidation={id:"EXTERNAL-010-PHASE6-PC-REAL-RUNTIME-VALIDATION",version:MODULE_VERSION,status:"Loaded",phase:6,decisions:["012","017","018","041","050"],realAuthenticatedHttp:true,secretValueBrowserExposureAllowed:false,loadedAt:internal.nowIso()};
  global.runExternalIntelligencePhase6PcRealRuntimeValidation=runExternalIntelligencePhase6PcRealRuntimeValidation;
})(typeof window!=="undefined"?window:globalThis);
