/* ============================================================
   FILE: 17_external_intelligence_phase10_validation.js
   EXTERNAL-010 External Intelligence Platform
   Release: 1.9.1
   Phase 10: Reliability Signals / Uncertainty / Outcome Foundation
   ============================================================ */
(function (global) {
  "use strict";
  const namespace = global.EXTERNAL010ExternalIntelligence;
  const VERSION_MANIFEST = global.EXTERNAL010VersionManifest;
  if (!namespace || !namespace.__internal || !VERSION_MANIFEST) return;
  const internal = namespace.__internal;
  const state = internal.state;
  const MODULE_VERSION = VERSION_MANIFEST.getModuleVersion("phase10Validation");

  async function runExternalIntelligencePhase10Validation(){const checks=[];const add=(name,passed,detail,group)=>checks.push({name,passed:passed===true,detail:detail==null?"":(typeof detail==="string"?detail:internal.stableStringify(detail)),group:group||"Phase 10",severity:"Critical"});
    add("Release Version is Phase 10 compatible or later",VERSION_MANIFEST.isReleaseCompatibleFrom("1.9.0"),VERSION_MANIFEST.release.version,"Foundation"); add("Implementation Phase is Phase 10",VERSION_MANIFEST.release.phase===10,VERSION_MANIFEST.release.implementationPhase,"Foundation"); add("Phase 10 primary Decisions are 010 / 030 / 031",internal.stableStringify(namespace.modules.phase10Validation.decisions)===internal.stableStringify(["010","030","031"]),namespace.modules.phase10Validation.decisions,"Foundation"); add("Gateway remains unchanged at 1.4.0",VERSION_MANIFEST.gateway.gatewayVersion==="1.4.0",VERSION_MANIFEST.gateway.gatewayVersion,"Boundary");
    const init=await namespace.initializeExternalIntelligenceFoundation(); add("Foundation initializes",init&&init.ok===true,init&&init.code,"Initialization"); const p9=await namespace.runExternalIntelligencePhase9Validation(); add("Phase 09 regression remains PASS",p9.failed===0&&p9.health===100,{passed:p9.passed,failed:p9.failed,total:p9.total},"Regression");
    const rs=namespace.recordExternalIntelligenceReliabilitySignal({sourceId:"SOURCE-PHASE10-A",observationWindow:"P30D",requestCount:100,successCount:97,timeoutCount:2,schemaFailureCount:1,averageLatencyMs:420,freshnessState:"FRESH"}); add("Operational reliability signal is recorded without factual reliability judgment",rs.ok&&rs.data.reliabilitySignal.operationalReliabilityOnly&&rs.data.reliabilitySignal.factualReliabilityDetermined===false&&rs.data.reliabilitySignal.reliabilityScore===null,rs.data,"Reliability");
    const q=namespace.recordExternalIntelligenceEvidenceQualitySignal({evidenceId:"EVIDENCE-PHASE10-A",sourceId:"SOURCE-PHASE10-A",sourceRole:"OFFICIAL",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true}); add("Evidence quality remains signal input, not authority score",q.ok&&q.data.evidenceQualitySignal.authorityScore===null&&q.data.evidenceQualitySignal.truthConfirmed===false,q.data,"Reliability");
    const cc=namespace.recordExternalIntelligenceContradictionCandidate({candidateId:"CONTRADICTION-PHASE10-1",subjectRef:"ENTITY-PHASE10",field:"revenue",period:"2026Q2",evidenceIds:["EVIDENCE-PHASE10-A","EVIDENCE-PHASE10-B"]}); add("Contradiction is preserved without automatic winner",cc.ok&&cc.data.candidate.conflictWinner===null&&cc.data.candidate.automaticResolutionPerformed===false,cc.data,"Contradiction");
    const invented=namespace.registerExternalIntelligencePrediction({predictionId:"PRED-PHASE10-BLOCK",probabilityState:"NOT_ESTIMATED",probability:0.8}); add("Invented probability is blocked",invented.ok===false&&invented.code==="EXTERNAL010_INVENTED_PROBABILITY_BLOCKED",invented.code,"Uncertainty");
    const pred=namespace.registerExternalIntelligencePrediction({predictionId:"PRED-PHASE10-1",version:1,predictionType:"DIRECTIONAL",targetTime:"2027-01-01T00:00:00Z",probabilityState:"RANGE",probability:null,estimateConfidence:"LOW",evidenceStrength:"LIMITED",historicalSampleCount:12,predictionInterval:{min:0.35,max:0.55},uncertaintyFactors:["SAMPLE_SIZE","SOURCE_CONFLICT"],modelId:"MODEL-PHASE10",modelVersion:"1.0.0",evidenceIds:["EVIDENCE-PHASE10-A"]}); add("Prediction snapshot records uncertainty and model identity",pred.ok&&pred.data.prediction.modelId==="MODEL-PHASE10"&&pred.data.prediction.uncertaintyFactors.length===2&&pred.data.prediction.probabilityInvented===false,pred.data,"Prediction");
    const b=namespace.registerExternalIntelligenceBenchmarkDefinition({benchmarkDefinitionId:"BENCH-PHASE10-1",version:1,targetMetric:"REVENUE",measurementMethod:"OFFICIAL_FILING",targetWindow:"FY2026",unit:"JPY",timezone:"Asia/Tokyo"}); add("Benchmark definition is versioned before settlement",b.ok&&b.data.benchmarkDefinition.version===1,b.data,"Outcome");
    const o1=namespace.registerExternalIntelligenceOutcome({outcomeId:"OUTCOME-PHASE10-1",version:1,predictionId:"PRED-PHASE10-1",benchmarkDefinitionId:"BENCH-PHASE10-1",outcomeType:"NUMERIC",targetMetric:"REVENUE",settlementState:"PRELIMINARY",value:100,supportingEvidenceIds:["EVIDENCE-PHASE10-OUTCOME-V1"],sourceRole:"PRIMARY_OFFICIAL"}); const o2=namespace.registerExternalIntelligenceOutcome({outcomeId:"OUTCOME-PHASE10-1",version:2,predictionId:"PRED-PHASE10-1",benchmarkDefinitionId:"BENCH-PHASE10-1",outcomeType:"NUMERIC",targetMetric:"REVENUE",settlementState:"FINAL",value:101,supportingEvidenceIds:["EVIDENCE-PHASE10-OUTCOME-V2"],sourceRole:"REGULATORY_FILING",supersedesOutcomeRecordId:"OUTCOME-PHASE10-1-V1",referenceOutcome:true}); const hist=namespace.listExternalIntelligenceOutcomeHistory("OUTCOME-PHASE10-1"); add("Outcome revision preserves history",o1.ok&&o2.ok&&hist.length===2&&hist[0].settlementState==="PRELIMINARY"&&hist[1].settlementState==="FINAL",hist,"Outcome"); add("Reference Outcome does not claim absolute truth",o2.ok&&o2.data.outcome.absoluteTruthClaimed===false,o2.data,"Outcome Boundary");
    const ev=namespace.recordExternalIntelligenceOutcomeEvaluation({predictionId:"PRED-PHASE10-1",outcomeId:"OUTCOME-PHASE10-1",outcomeVersion:2,evaluationState:"RECORDED"}); add("Prediction connects reproducibly to explicit Outcome version",ev.ok&&ev.data.evaluation.predictionRecordId==="PRED-PHASE10-1-V1"&&ev.data.evaluation.referenceOutcomeRecordId==="OUTCOME-PHASE10-1-V2",ev.data,"Evaluation"); const pkg=namespace.getExternalIntelligenceReliabilityInputPackage(); add("EXTERNAL-020 reliability input contract keeps final authority external",pkg.finalReliabilityAuthority==="EXTERNAL-020"&&pkg.contractValid===true,pkg,"Boundary");
    const phase10Contracts=["reliabilitySignal","evidenceQualitySignal","reliabilityCandidate","reliabilityInputPackage","predictionRecord","benchmarkDefinition","outcomeRecord","outcomeEvaluation","phase10ValidationResult"]; add("Phase 10 contracts are registered",phase10Contracts.every(k=>Boolean(namespace.getExternalIntelligenceContract(k))),phase10Contracts,"Contract");
    const phase10Schemas=["EXTERNAL-010-SCHEMA-RELIABILITY-SIGNAL","EXTERNAL-010-SCHEMA-EVIDENCE-QUALITY-SIGNAL","EXTERNAL-010-SCHEMA-RELIABILITY-CANDIDATE","EXTERNAL-010-SCHEMA-RELIABILITY-INPUT-PACKAGE","EXTERNAL-010-SCHEMA-PREDICTION-RECORD","EXTERNAL-010-SCHEMA-BENCHMARK-DEFINITION","EXTERNAL-010-SCHEMA-OUTCOME-RECORD","EXTERNAL-010-SCHEMA-OUTCOME-EVALUATION","EXTERNAL-010-SCHEMA-PHASE10-VALIDATION-RESULT"]; add("Phase 10 schemas are registered",phase10Schemas.every(id=>Boolean(namespace.getExternalIntelligenceSchema(id))),phase10Schemas,"Schema");
    const predCv=namespace.validateExternalIntelligenceContract("predictionRecord",pred.data.prediction),predSv=namespace.validateExternalIntelligenceRecord("EXTERNAL-010-SCHEMA-PREDICTION-RECORD",pred.data.prediction); add("Prediction validates against contract and schema",predCv.valid===true&&predSv.valid===true,{contract:predCv.valid,schema:predSv.valid},"Contract/Schema");
    const badPred=internal.clone(pred.data.prediction); delete badPred.probabilityState; const badCv=namespace.validateExternalIntelligenceContract("predictionRecord",badPred),badSv=namespace.validateExternalIntelligenceRecord("EXTERNAL-010-SCHEMA-PREDICTION-RECORD",badPred); add("Malformed Prediction is rejected by contract and schema",badCv.valid===false&&badSv.valid===false,{contract:badCv.valid,schema:badSv.valid},"Negative Validation");
    const badOutcome=internal.clone(o2.data.outcome); badOutcome.absoluteTruthClaimed=true; const badOutcomeCv=namespace.validateExternalIntelligenceContract("outcomeRecord",badOutcome),badOutcomeSv=namespace.validateExternalIntelligenceRecord("EXTERNAL-010-SCHEMA-OUTCOME-RECORD",badOutcome); add("Outcome absolute-truth authority violation is rejected",badOutcomeCv.valid===false&&badOutcomeSv.valid===false,{contract:badOutcomeCv.valid,schema:badOutcomeSv.valid},"Negative Validation");
    const snapshot=namespace.getExternalIntelligencePrediction("PRED-PHASE10-1"); add("Prediction readback snapshot is reproducible",snapshot&&internal.stableStringify(snapshot)===internal.stableStringify(pred.data.prediction),snapshot,"Readback");
    const outcomeReadback=namespace.getExternalIntelligenceOutcome("OUTCOME-PHASE10-1"); add("Latest Outcome readback preserves explicit version",outcomeReadback&&outcomeReadback.outcomeRecordId==="OUTCOME-PHASE10-1-V2"&&namespace.listExternalIntelligenceOutcomeHistory("OUTCOME-PHASE10-1").length===2,outcomeReadback,"Readback");
    const passed=checks.filter(x=>x.passed).length,failed=checks.length-passed,criticalFailed=failed; const result={id:internal.nextId("EXTERNAL-010-PHASE10-VALIDATION"),componentId:"EXTERNAL-010",version:VERSION_MANIFEST.release.version,gatewayVersion:VERSION_MANIFEST.gateway.gatewayVersion,implementationPhase:VERSION_MANIFEST.release.implementationPhase,decisionCoverage:54,passed,failed,total:checks.length,health:checks.length?Number((passed/checks.length*100).toFixed(1)):0,criticalFailed,status:failed===0?"EXTERNAL-010 Phase 10 Validation PASS":"EXTERNAL-010 Phase 10 Validation FAIL",releaseAllowed:failed===0,phase10Complete:failed===0,phase11Allowed:failed===0,checks,validatedAt:internal.nowIso(),immutable:true}; state.latestPhase10Validation=internal.deepFreeze(internal.clone(result)); return internal.clone(result);}
  Object.assign(namespace.api,{runExternalIntelligencePhase10Validation,getLatestExternalIntelligencePhase10Validation:function(){return state.latestPhase10Validation?internal.clone(state.latestPhase10Validation):null;}});Object.assign(namespace,namespace.api); namespace.modules.phase10Validation={id:"EXTERNAL-010-PHASE10-VALIDATION",version:MODULE_VERSION,status:"Ready",phase:10,decisions:["010","030","031"],loadedAt:internal.nowIso()}; global.runExternalIntelligencePhase10Validation=runExternalIntelligencePhase10Validation;
})(typeof window !== "undefined" ? window : globalThis);
