/* EXTERNAL-010 Phase 14 Knowledge Boundary v1.13.0 */
(function(global){"use strict";const n=global.EXTERNAL010ExternalIntelligence,m=global.EXTERNAL010VersionManifest;if(!n||!n.__internal||!m)return;const i=n.__internal,s=i.state,v=m.getModuleVersion("knowledgeBoundary");
if(!(s.externalKnowledgeCandidates instanceof Map))s.externalKnowledgeCandidates=new Map();if(!(s.knowledgePromotionBoundaryRecords instanceof Map))s.knowledgePromotionBoundaryRecords=new Map();
const VALIDATION=["UNVALIDATED","VALID","INVALID","INCONCLUSIVE","UNKNOWN"],PROMOTION=["NOT_EVALUATED","EVALUATED","CANDIDATE","VALIDATED","REJECTED","PROMOTED","SUPERSEDED"];
function valid(k,id,r){const c=n.validateExternalIntelligenceContract(k,r),q=n.validateExternalIntelligenceRecord(id,r);return{valid:c.valid===true&&q.valid===true,contract:c,schema:q};}
function createExternalIntelligenceKnowledgeCandidate(input){const x=i.isPlainObject(input)?input:{},refs=i.unique(x.sourceEvidenceIds||[]);if(!refs.length)return i.buildResult(false,"EXTERNAL010_PHASE14_KNOWLEDGE_CANDIDATE_EVIDENCE_REQUIRED","Blocked",null);const validationState=i.text(x.validationState,"UNVALIDATED").toUpperCase(),promotionState=i.text(x.promotionState,"CANDIDATE").toUpperCase();if(!VALIDATION.includes(validationState)||!PROMOTION.includes(promotionState))return i.buildResult(false,"EXTERNAL010_PHASE14_KNOWLEDGE_CANDIDATE_STATE_INVALID","Blocked",{validationState,promotionState});const r=i.deepFreeze({candidateId:i.text(x.candidateId,i.nextId("EXTERNAL-010-KNOWLEDGE-CANDIDATE")),candidateType:i.text(x.candidateType,"EXTERNAL_CLAIM").toUpperCase(),claim:i.text(x.claim,""),sourceEvidenceIds:refs,createdAt:i.nowIso(),createdBy:i.text(x.createdBy,"AI_OR_OWNER"),reliabilityAssessmentId:i.text(x.reliabilityAssessmentId,"")||null,freshnessState:i.text(x.freshnessState,"UNKNOWN").toUpperCase(),contradictionState:i.text(x.contradictionState,"UNASSESSED").toUpperCase(),validationState,promotionState,knowledgeIdentityAssigned:false,promotionAuthorityGranted:false,canonicalKnowledgeMutationPerformed:false,immutable:true});if(!r.claim)return i.buildResult(false,"EXTERNAL010_PHASE14_KNOWLEDGE_CANDIDATE_CLAIM_REQUIRED","Blocked",null);const z=valid("knowledgeCandidate","EXTERNAL-010-SCHEMA-KNOWLEDGE-CANDIDATE",r);if(!z.valid)return i.buildResult(false,"EXTERNAL010_PHASE14_KNOWLEDGE_CANDIDATE_INVALID","Blocked",z);s.externalKnowledgeCandidates.set(r.candidateId,r);refs.forEach(function(ref){if(typeof n.createExternalIntelligenceLineageRecord==="function")n.createExternalIntelligenceLineageRecord({inputReferenceId:ref,outputReferenceId:r.candidateId,relationType:"DERIVED_FROM",lineageState:"ACTIVE"});});i.touch();return i.buildResult(true,"EXTERNAL010_PHASE14_KNOWLEDGE_CANDIDATE_CREATED","Candidate",{knowledgeCandidate:i.clone(r)});}
function evaluateExternalIntelligenceKnowledgePromotionBoundary(input){const x=i.isPlainObject(input)?input:{},id=i.text(x.candidateId,""),c=s.externalKnowledgeCandidates.get(id);if(!c)return i.buildResult(false,"EXTERNAL010_PHASE14_KNOWLEDGE_CANDIDATE_NOT_FOUND","Blocked",{candidateId:id||null});const validationState=i.text(x.validationState,c.validationState).toUpperCase(),authorityState=i.text(x.authorityState,"NOT_GRANTED").toUpperCase();const r=i.deepFreeze({promotionBoundaryId:i.nextId("EXTERNAL-010-KNOWLEDGE-PROMOTION-BOUNDARY"),candidateId:id,validationState,authorityState,promotionState:c.promotionState,automaticPromotionAllowed:false,validationPassEqualsPromotion:false,reliabilityHighGrantsAutomaticPromotion:false,knowledgeWritePerformed:false,canonicalKnowledgeMutationPerformed:false,requiresExternalKnowledgePromotionService:true,createdAt:i.nowIso(),immutable:true});const z=valid("knowledgePromotionBoundary","EXTERNAL-010-SCHEMA-KNOWLEDGE-PROMOTION-BOUNDARY",r);if(!z.valid)return i.buildResult(false,"EXTERNAL010_PHASE14_KNOWLEDGE_PROMOTION_BOUNDARY_INVALID","Blocked",z);s.knowledgePromotionBoundaryRecords.set(r.promotionBoundaryId,r);i.touch();return i.buildResult(true,"EXTERNAL010_PHASE14_KNOWLEDGE_PROMOTION_BOUNDARY_EVALUATED","Requires External Promotion Service",{boundary:i.clone(r),promotionPerformed:false,authorityEffect:"none"});}
function getExternalIntelligenceKnowledgeCandidate(id){const r=s.externalKnowledgeCandidates.get(i.text(id,""));return r?i.clone(r):null;}function listExternalIntelligenceKnowledgeCandidates(){return Array.from(s.externalKnowledgeCandidates.values()).map(i.clone);}
Object.assign(n.api,{createExternalIntelligenceKnowledgeCandidate,evaluateExternalIntelligenceKnowledgePromotionBoundary,getExternalIntelligenceKnowledgeCandidate,listExternalIntelligenceKnowledgeCandidates});Object.assign(n,n.api);n.modules.knowledgeBoundary={id:"EXTERNAL-010-KNOWLEDGE-BOUNDARY",version:v,status:"Ready",phase:14,decisions:["021","043"],automaticPromotionAllowed:false,canonicalKnowledgeMutationImplemented:false,loadedAt:i.nowIso()};})(typeof window!=="undefined"?window:globalThis);
