/* ============================================================
   FILE: 19_trust_evidence_phase2_validation.js
   EXTERNAL-020 Phase 2 Functional / Safety Validation
   ============================================================ */
(function(global){
  "use strict";
  const namespace=global.EXTERNAL020TrustEvidence,P2=global.EXTERNAL020Phase2VersionManifest;if(!namespace||!namespace.__internal||!P2)return;
  const i=namespace.__internal,s=i.state;
  function runExternal020Phase2Validation(){
    const checks=[];function check(name,passed,detail,group,severity){checks.push({name:name,passed:Boolean(passed),detail:i.clone(detail),group:group||"Functional",severity:severity||"Critical"});}
    const base=typeof global.runExternal020Phase1Validation==="function"?global.runExternal020Phase1Validation():null;check("Frozen Phase 1 functional foundation remains PASS",base&&base.failed===0&&base.criticalFailed===0&&base.phase1ImplementationComplete===true,base,"Regression","Critical");
    const inputA=namespace.readExternal010ReliabilityInput();check("EXTERNAL-010 Reliability Input remains read-only",inputA.ok===true&&inputA.data.inputPackage.readOnly===true&&inputA.data.inputPackage.rawEvidenceMutationPerformed===false,inputA,"Integration","Critical");const pkgA=inputA.ok?inputA.data.inputPackage:null;
    const srcCtxA=namespace.createExternal020EvaluationContext({subjectType:"SOURCE",subjectRef:"SRC-PHASE2",domain:"MARKET",task:"PRICE_DATA_REVIEW",purpose:"PHASE2_VALIDATION",timeHorizon:"CURRENT",sourceRefs:["SRC-PHASE2"],evidenceRefs:["EVIDENCE-P2-A","EVIDENCE-P2-B"],inputPackageId:pkgA&&pkgA.inputPackageId});
    const srcEvA=namespace.createExternal020ReliabilityEvaluationCandidate({contextId:srcCtxA.ok?srcCtxA.data.context.contextId:"",inputPackageId:pkgA&&pkgA.inputPackageId,evaluationState:"UNRESOLVED",explanation:"Phase 2 source profile validation"});
    const sourceProfile=namespace.createExternal020ReliabilityProfile({evaluationId:srcEvA.ok?srcEvA.data.evaluation.evaluationId:""});check("REQ-020-003 SOURCE Reliability Profile can be created",sourceProfile.ok===true&&sourceProfile.data.profile.subjectType==="SOURCE",sourceProfile,"Reliability","Critical");
    const claimCtx=namespace.createExternal020EvaluationContext({subjectType:"CLAIM",subjectRef:"CLAIM-PHASE2",domain:"MARKET",task:"PRICE_DATA_REVIEW",purpose:"PHASE2_VALIDATION",timeHorizon:"CURRENT",sourceRefs:["SRC-PHASE2"],evidenceRefs:["EVIDENCE-P2-A","EVIDENCE-P2-B"],inputPackageId:pkgA&&pkgA.inputPackageId});
    const claimEv=namespace.createExternal020ReliabilityEvaluationCandidate({contextId:claimCtx.ok?claimCtx.data.context.contextId:"",inputPackageId:pkgA&&pkgA.inputPackageId,evaluationState:"UNRESOLVED",explanation:"Phase 2 claim profile validation"});
    const claimProfile=namespace.createExternal020ReliabilityProfile({evaluationId:claimEv.ok?claimEv.data.evaluation.evaluationId:""});check("REQ-020-003 SOURCE and CLAIM profiles remain separate",claimProfile.ok===true&&sourceProfile.ok===true&&claimProfile.data.profile.profileId!==sourceProfile.data.profile.profileId&&claimProfile.data.profile.subjectType==="CLAIM",{source:sourceProfile.data&&sourceProfile.data.profile,claim:claimProfile.data&&claimProfile.data.profile},"Reliability","Critical");
    const srcCtxB=namespace.createExternal020EvaluationContext({subjectType:"SOURCE",subjectRef:"SRC-PHASE2",domain:"NEWS",task:"BREAKING_NEWS_REVIEW",purpose:"PHASE2_VALIDATION",timeHorizon:"SHORT",sourceRefs:["SRC-PHASE2"],evidenceRefs:["EVIDENCE-P2-A"],inputPackageId:pkgA&&pkgA.inputPackageId});
    const srcEvB=namespace.createExternal020ReliabilityEvaluationCandidate({contextId:srcCtxB.ok?srcCtxB.data.context.contextId:"",inputPackageId:pkgA&&pkgA.inputPackageId,evaluationState:"ASSESSABLE",explanation:"Different context profile"});const sourceProfileB=namespace.createExternal020ReliabilityProfile({evaluationId:srcEvB.ok?srcEvB.data.evaluation.evaluationId:""});check("REQ-020-004 Same Source can have separate Domain / Task profiles",sourceProfileB.ok===true&&sourceProfile.ok===true&&sourceProfileB.data.profile.profileId!==sourceProfile.data.profile.profileId&&sourceProfileB.data.profile.contextIdentity!==sourceProfile.data.profile.contextIdentity,{market:sourceProfile.data&&sourceProfile.data.profile.contextIdentity,news:sourceProfileB.data&&sourceProfileB.data.profile.contextIdentity},"Reliability","Critical");
    const dims=sourceProfile.ok?sourceProfile.data.profile.dimensions:null;check("REQ-020-005 Multi-dimensional assessments remain separate",dims&&P2.reliabilityDimensions.every(function(k){return Object.prototype.hasOwnProperty.call(dims,k);}),dims,"Reliability","Critical");check("REQ-020-005 No universal numerical Reliability score is generated",sourceProfile.ok&&sourceProfile.data.profile.reliabilityScore===null&&sourceProfile.data.profile.authorityScore===null&&P2.safety.universalTrustScoreImplemented===false,sourceProfile.data&&sourceProfile.data.profile,"Safety","Critical");
    const ind=srcEvA.ok?namespace.assessExternal020IndependentConfirmation({evaluationId:srcEvA.data.evaluation.evaluationId}):null;check("REQ-020-007 Independence assessment is explicit",ind&&ind.ok===true&&P2.independenceStates.includes(ind.data.assessment.state),ind,"Reliability","Critical");check("REQ-020-007 UNKNOWN independence is not treated as verified",ind&&ind.ok===true&&ind.data.assessment.unknownTreatedAsIndependent===false&&ind.data.assessment.dependencyInferred===false,ind,"Safety","Critical");
    const pkg2=i.deepFreeze(Object.assign({},i.clone(pkgA||{}),{inputPackageId:i.nextId("EXTERNAL020-INPUT-PHASE2-REV"),confirmationCandidates:(pkgA&&pkgA.confirmationCandidates?i.clone(pkgA.confirmationCandidates):[]).concat([{candidateId:"CONF-P2-INDEPENDENT",candidateType:"CONFIRMATION",subjectRef:"SRC-PHASE2",evidenceIds:["EVIDENCE-P2-A","EVIDENCE-P2-C"],independenceVerified:true,conflictWinner:null,truthConfirmed:false,automaticResolutionPerformed:false,duplicateEqualsIndependentConfirmation:false,finalReliabilityAuthority:"EXTERNAL-020"}]),capturedAt:i.nowIso(),immutable:true}));s.inputPackages.set(pkg2.inputPackageId,pkg2);
    const revCtx=namespace.createExternal020EvaluationContext({subjectType:"SOURCE",subjectRef:"SRC-PHASE2",domain:"MARKET",task:"PRICE_DATA_REVIEW",purpose:"PHASE2_VALIDATION",timeHorizon:"CURRENT",sourceRefs:["SRC-PHASE2"],evidenceRefs:["EVIDENCE-P2-A","EVIDENCE-P2-B","EVIDENCE-P2-C"],inputPackageId:pkg2.inputPackageId});const revEv=namespace.createExternal020ReliabilityEvaluationCandidate({contextId:revCtx.ok?revCtx.data.context.contextId:"",inputPackageId:pkg2.inputPackageId,evaluationState:"ASSESSABLE",explanation:"New independent confirmation added"});const revised=namespace.reviseExternal020ReliabilityProfile({profileId:sourceProfile.ok?sourceProfile.data.profile.profileId:"",evaluationId:revEv.ok?revEv.data.evaluation.evaluationId:"",revisionReason:"NEW_INDEPENDENT_CONFIRMATION"});check("REQ-020-009 Profile can be revised append-only",revised.ok===true&&revised.data.profile.revisionNumber===2&&revised.data.profile.previousVersionRef===revised.data.previousProfile.profileId+"@"+revised.data.previousProfile.profileVersion,revised,"Revision","Critical");
    const hist=revised.ok?namespace.listExternal020ReliabilityProfileHistory(revised.data.profile.profileId):[];check("REQ-020-009 Previous version remains retrievable and marked SUPERSEDED",hist.length===2&&hist[0].historyState==="SUPERSEDED"&&hist[1].historyState==="CURRENT"&&hist[0].profileVersion!==hist[1].profileVersion,hist,"Revision","Critical");check("Revision lineage preserves prior version reference",revised.ok&&revised.data.profile.supersedesVersionRef===revised.data.profile.previousVersionRef,revised.data&&revised.data.profile,"Lineage","Major");check("Contradiction references survive revision",revised.ok&&Array.isArray(revised.data.profile.contradictionRefs),revised.data&&revised.data.profile,"Reliability","Major");check("Missing information remains explicit across revision",revised.ok&&Array.isArray(revised.data.profile.missingInformation),revised.data&&revised.data.profile,"Reliability","Major");
    const mismatch=namespace.reviseExternal020ReliabilityProfile({profileId:sourceProfile.ok?sourceProfile.data.profile.profileId:"",evaluationId:claimEv.ok?claimEv.data.evaluation.evaluationId:"",revisionReason:"INVALID_SUBJECT_REUSE"});check("SOURCE Profile cannot be silently revised with CLAIM evaluation",mismatch.ok===false&&mismatch.code==="EXTERNAL020_PROFILE_CONTEXT_IDENTITY_MISMATCH",mismatch,"Negative","Critical");
    const coverage=namespace.getExternal020Decision001Coverage();check("Decision 001 traceability reaches 16/18 without false completion",coverage.totalDecisionRequirements===18&&coverage.decisionRequirementsFullyImplemented===16&&coverage.allDecisionRequirementsComplete===false&&coverage.remainingRequirementIds.length===2&&coverage.remainingRequirementIds.includes("REQ-020-008")&&coverage.remainingRequirementIds.includes("REQ-020-015"),coverage,"Traceability","Critical");
    const latest=revised.ok?revised.data.profile:null;check("Reliability Profile grants no Truth / Knowledge / action authority",latest&&latest.truthConfirmed===false&&latest.knowledgePromotionPerformed===false&&latest.actionAuthorityGranted===false&&latest.canonicalRepositoryMutationPerformed===false,latest,"Authority","Critical");check("Phase 2 remains local-only with no paid API or external transmission",latest&&latest.externalTransmissionPerformed===false&&latest.paidApiExecutionPerformed===false&&P2.safety.externalAiReliabilityReasoningImplemented===false,latest,"Safety","Critical");check("IDE-170 Confidence remains untouched",latest&&latest.ide170ConfidenceOverwritten===false&&P2.safety.ide170ConfidenceOverwriteAllowed===false,latest,"Safety","Critical");check("Historical Outcome and External AI remain deferred",P2.safety.historicalOutcomeGroundedEvaluationImplemented===false&&P2.safety.externalAiReliabilityReasoningImplemented===false,P2.safety,"Scope","Critical");check("Validation does not equal Project Owner approval",global.EXTERNAL020VersionManifest&&global.EXTERNAL020VersionManifest.safety.validationEqualsApproval===false,{validationEqualsApproval:false},"Authority","Critical");
    const failed=checks.filter(function(c){return !c.passed;}),criticalFailed=failed.filter(function(c){return c.severity==="Critical";}).length;const record=i.deepFreeze({validationId:i.nextId("EXTERNAL020-PHASE2-VALIDATION"),componentId:P2.componentId,decisionId:P2.decisionId,version:P2.version,phase:2,passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed:criticalFailed,phase2ImplementationComplete:failed.length===0,phase2TechnicalGateReady:failed.length===0,decision001RequirementsComplete:coverage.decisionRequirementsFullyImplemented,decision001RequirementsTotal:coverage.totalDecisionRequirements,decision001Complete:false,releaseAllowed:false,projectOwnerAcceptanceRequired:true,validationIsApproval:false,canonicalMutationPerformed:false,externalTransmissionPerformed:false,paidApiExecutionPerformed:false,historicalOutcomeGroundedEvaluationPerformed:false,externalAiReliabilityReasoningPerformed:false,checks:checks,validatedAt:i.nowIso(),immutable:true});s.validations.set(record.validationId,record);s.latestValidationId=record.validationId;i.touch();return i.clone(record);
  }
  Object.assign(namespace.api,{runExternal020Phase2Validation});Object.assign(namespace,namespace.api);namespace.modules.phase2Validation={id:"EXTERNAL-020-PHASE2-VALIDATION",version:P2.version,status:"Ready",releaseAllowed:false,validationIsApproval:false,loadedAt:i.nowIso()};global.runExternal020Phase2Validation=runExternal020Phase2Validation;
})(typeof window!=="undefined"?window:globalThis);
