/* ============================================================
   FILE: 19_trust_evidence_external_ai_reasoning.js
   EXTERNAL-020 Phase 4 / Provider Output Candidate Boundary
   ============================================================ */
(function(global){
  "use strict";
  const namespace=global.EXTERNAL020TrustEvidence,P4=global.EXTERNAL020Phase4VersionManifest;if(!namespace||!namespace.__internal||!P4)return;
  const i=namespace.__internal;
  function extractText(payload){const response=i.isPlainObject(payload)?payload:{},parts=[];(Array.isArray(response.output)?response.output:[]).forEach(function(item){(item&&Array.isArray(item.content)?item.content:[]).forEach(function(entry){if(entry&&typeof entry.text==="string")parts.push(entry.text);});});return parts.join("\n").trim();}
  function buildExternal020ExternalAiReasoningCandidate(input){const x=i.isPlainObject(input)?input:{};if(x.outputClassification!=="AI_RELIABILITY_REASONING_CANDIDATE_ONLY")return i.buildResult(false,"EXTERNAL020_PHASE4_REASONING_OUTPUT_CLASSIFICATION_REQUIRED","Blocked",{profileRevisionPerformed:false,knowledgePromotionPerformed:false});const payload=i.isPlainObject(x.rawProviderPayload)?x.rawProviderPayload:{};const text=i.text(x.outputText,extractText(payload));const candidate=i.deepFreeze({reasoningCandidateId:i.nextId("EXTERNAL020-PHASE4-REASONING-CANDIDATE"),requestId:i.text(x.requestId,""),contextPackageId:i.text(x.contextPackageId,""),contextHash:i.text(x.contextHash,""),providerResponseId:i.text(x.providerResponseId,"")||null,modelReported:i.text(x.modelReported,"")||null,outputText:text,outputClassification:"AI_RELIABILITY_REASONING_CANDIDATE_ONLY",reliabilityAssessmentProposalOnly:true,truthConfirmed:false,conflictWinner:null,automaticConflictResolutionPerformed:false,reliabilityScore:null,authorityScore:null,profileRevisionCandidateOnly:true,profileRevisionPerformed:false,knowledgePromotionPerformed:false,actionAuthorityGranted:false,tradingAuthorityGranted:false,financialAuthorityGranted:false,businessAuthorityGranted:false,canonicalRepositoryMutationPerformed:false,ide170ConfidenceOverwritten:false,providerNetworkCallPerformed:x.providerNetworkCallPerformed===true,externalTransmissionPerformed:x.externalTransmissionPerformed===true,paidApiExecutionPerformed:x.paidApiExecutionPerformed===true,usageReconciliation:i.clone(x.usageReconciliation||null),createdAt:i.nowIso(),immutable:true});return i.buildResult(true,"EXTERNAL020_PHASE4_REASONING_CANDIDATE_NORMALIZED","Candidate",{reasoningCandidate:candidate});}
  Object.assign(namespace.api,{buildExternal020ExternalAiReasoningCandidate});Object.assign(namespace,namespace.api);namespace.modules.phase4ExternalAiReasoning={id:"EXTERNAL-020-PHASE4-EXTERNAL-AI-REASONING",version:P4.version,status:"Ready",proposalOnly:true,loadedAt:i.nowIso()};
})(typeof window!=="undefined"?window:globalThis);
