/* ============================================================
   FILE: 19_trust_evidence_phase4_validation.js
   EXTERNAL-020 Phase 4 / Functional + Governance Validation
   NOTE: This validator MUST NOT execute a provider network call.
   ============================================================ */
(function(global){
  "use strict";
  const namespace=global.EXTERNAL020TrustEvidence,P4=global.EXTERNAL020Phase4VersionManifest;if(!namespace||!namespace.__internal||!P4)return;const i=namespace.__internal,s=i.state;
  async function runExternal020Phase4Validation(){const checks=[];function check(name,passed,detail,group,severity){checks.push({name:name,passed:passed===true,detail:i.clone(detail==null?null:detail),group:group||"Functional",severity:severity||"Critical"});}
    const p3=typeof namespace.runExternal020Phase3Validation==="function"?await namespace.runExternal020Phase3Validation():null;check("Frozen Phase 3 functional foundation remains PASS",Boolean(p3&&p3.failed===0&&p3.criticalFailed===0&&p3.decision001RequirementsComplete===17),p3&&{validationId:p3.validationId,version:p3.version,passed:p3.passed,failed:p3.failed,decision001RequirementsComplete:p3.decision001RequirementsComplete},"Regression","Critical");
    const readiness=namespace.inspectExternal020ExternalAiGovernanceReadiness();check("REQ-020-015 reuses EXTERNAL-010 OpenAI governance and final readiness",readiness.external010Available===true&&readiness.openAIFinalValidated===true&&readiness.sourceReady===true&&readiness.operationReady===true&&readiness.usagePolicyReady===true&&readiness.secretReferenceReady===true&&readiness.readiness==="EXTERNAL020_EXTERNAL_AI_READY",readiness,"Integration","Critical");
    check("No second Provider / Secret / Budget / Gateway engine is created",readiness.secondProviderEngineCreated===false&&readiness.secondSecretStoreCreated===false&&readiness.secondBudgetEngineCreated===false&&readiness.secondGatewayCreated===false,readiness,"Architecture","Critical");
    const policy=namespace.getExternal020ExternalAiContextPolicy();check("External AI context is bounded and explicit-evidence only",policy.maxEvidenceItems===8&&policy.maxTotalEvidenceChars===12000&&policy.maxPromptChars===18000&&policy.repositoryWideAutomaticTransmissionAllowed===false&&policy.explicitProjectOwnerTransmissionApprovalRequired===true,policy,"Context","Critical");
    const ctx=await namespace.buildExternal020ExternalAiContextPackage({question:"Assess the reliability implications without deciding truth.",evidenceItems:[{evidenceId:"P4-E1",evidenceType:"RELIABILITY_PROFILE",sourceRef:"EXTERNAL020-PROFILE-TEST",excerpt:"Profile remains context-specific with reliabilityScore null."},{evidenceId:"P4-E2",evidenceType:"HISTORICAL_ASSESSMENT",sourceRef:"EXTERNAL020-HISTORICAL-TEST",excerpt:"Historical grounding state is OUTCOME_GROUNDED but truthConfirmed remains false."}]});check("Bounded context package can be built without transmission",ctx&&ctx.ok===true&&ctx.data.contextPackage.evidenceItemCount===2&&ctx.data.contextPackage.externalTransmissionPerformed===false&&ctx.data.contextPackage.secretValueIncluded===false,ctx,"Context","Critical");
    const secretBlocked=await namespace.buildExternal020ExternalAiContextPackage({question:"Assess",evidenceItems:[{evidenceId:"P4-SECRET",evidenceType:"EVIDENCE",excerpt:"api_key='sk-12345678901234567890'"}]});check("Secret-like evidence is blocked before provider preparation",secretBlocked&&secretBlocked.ok===false&&secretBlocked.data.errors.some(function(x){return String(x).indexOf("SECRET_LIKE_VALUE_IN_EVIDENCE")===0;}),secretBlocked,"Negative","Critical");
    const prepared=await namespace.prepareExternal020ExternalAiReliabilityReasoning({question:"Assess reliability and preserve uncertainty.",evidenceItems:[{evidenceId:"P4-E1",evidenceType:"RELIABILITY_PROFILE",excerpt:"Context-specific profile; no universal score."}],model:"gpt-5.6-luna"});check("Provider request preparation reuses bounded USD budget and EXTERNAL-010 request preparation",prepared&&prepared.ok===true&&prepared.data.requestCandidate&&prepared.data.requestCandidate.sourceId==="SOURCE-OPENAI"&&prepared.data.requestCandidate.operationId==="INTERNAL_ANALYSIS"&&prepared.data.requestCandidate.body&&prepared.data.requestCandidate.body.store===false&&prepared.data.providerNetworkCallPerformed===false&&prepared.data.externalTransmissionPerformed===false,prepared,"Integration","Critical");
    const body=prepared&&prepared.data&&prepared.data.requestCandidate&&prepared.data.requestCandidate.body||{};check("Provider request keeps store=false and no tool/file/web/computer capability",body.store===false&&!Object.prototype.hasOwnProperty.call(body,"tools")&&!Object.prototype.hasOwnProperty.call(body,"files")&&!Object.prototype.hasOwnProperty.call(body,"web_search")&&!Object.prototype.hasOwnProperty.call(body,"computer_use")&&readiness.toolsAllowed===false&&readiness.filesAllowed===false&&readiness.webSearchAllowed===false&&readiness.computerUseAllowed===false,{bodyKeys:Object.keys(body),readiness:readiness},"Safety","Critical");
    const denied=await namespace.executeExternal020ExternalAiReliabilityReasoning({question:"Assess",evidenceItems:[{evidenceId:"P4-E1",evidenceType:"EVIDENCE",excerpt:"Evidence"}]});check("Provider execution is blocked without explicit Project Owner external-transmission approval",denied&&denied.ok===false&&denied.code==="EXTERNAL020_PHASE4_EXTERNAL_TRANSMISSION_PROJECT_OWNER_APPROVAL_REQUIRED"&&denied.data.providerNetworkCallPerformed===false&&denied.data.externalTransmissionPerformed===false,denied,"Authority","Critical");
    const normalized=namespace.buildExternal020ExternalAiReasoningCandidate({requestId:"P4-REQ",contextPackageId:"P4-CTX",contextHash:"P4-HASH",providerResponseId:"resp_fixture",modelReported:"gpt-5.6-luna",outputClassification:"AI_RELIABILITY_REASONING_CANDIDATE_ONLY",rawProviderPayload:{output:[{content:[{text:"Evidence supports a candidate assessment; truth remains unresolved."}]}]},providerNetworkCallPerformed:true,externalTransmissionPerformed:true,paidApiExecutionPerformed:true,usageReconciliation:{reconciled:true}});check("Provider output normalizes only as a non-authoritative reliability reasoning candidate",normalized&&normalized.ok===true&&normalized.data.reasoningCandidate.outputClassification==="AI_RELIABILITY_REASONING_CANDIDATE_ONLY"&&normalized.data.reasoningCandidate.truthConfirmed===false&&normalized.data.reasoningCandidate.reliabilityScore===null&&normalized.data.reasoningCandidate.authorityScore===null,normalized,"Reasoning","Critical");
    const rc=normalized&&normalized.data.reasoningCandidate||{};check("External AI output cannot auto-resolve conflicts, revise Profile, promote Knowledge, or grant authority",rc.automaticConflictResolutionPerformed===false&&rc.profileRevisionPerformed===false&&rc.knowledgePromotionPerformed===false&&rc.actionAuthorityGranted===false&&rc.tradingAuthorityGranted===false&&rc.financialAuthorityGranted===false&&rc.businessAuthorityGranted===false&&rc.canonicalRepositoryMutationPerformed===false,rc,"Authority","Critical");
    check("IDE-170 Confidence remains untouched",rc.ide170ConfidenceOverwritten===false&&P4.safety.ide170ConfidenceOverwriteAllowed===false,rc,"Safety","Critical");
    check("Validation performs no provider network call, external transmission, or paid API execution",P4.safety.validationMayExecuteProviderNetworkCall===false&&P4.safety.validationMayTransmitExternally===false&&P4.safety.validationMayConsumePaidApi===false,{providerNetworkCallPerformed:false,externalTransmissionPerformed:false,paidApiExecutionPerformed:false},"Safety","Critical");
    check("External AI reuse does not enable universal Trust Score or global source ranking",P4.safety.universalTrustScoreImplemented===false&&P4.safety.permanentGlobalSourceRankingImplemented===false,P4.safety,"Safety","Critical");
    const p3Coverage=typeof namespace.getExternal020Phase3Decision001Coverage==="function"?namespace.getExternal020Phase3Decision001Coverage():null;check("Backward compatibility keeps Frozen Phase 3 coverage at 17/18",p3Coverage&&p3Coverage.decisionRequirementsFullyImplemented===17&&p3Coverage.allDecisionRequirementsComplete===false&&p3Coverage.remainingRequirementIds.length===1&&p3Coverage.remainingRequirementIds[0]==="REQ-020-015",p3Coverage,"Regression","Critical");
    const coverage=namespace.getExternal020Phase4Decision001Coverage();check("Decision 001 traceability reaches 18/18 only through REQ-020-015 implementation",coverage.totalDecisionRequirements===18&&coverage.decisionRequirementsFullyImplemented===18&&coverage.allDecisionRequirementsComplete===true&&coverage.remainingRequirementIds.length===0,coverage,"Traceability","Critical");
    check("Decision 001 completion does not equal Project Owner acceptance or release",coverage.allDecisionRequirementsComplete===true&&P4.status==="IMPLEMENTATION_PHASE4_CANDIDATE",{decisionComplete:true,projectOwnerAcceptanceRequired:true,releaseAllowed:false},"Authority","Critical");
    check("External AI reasoning output does not equal Truth",P4.safety.externalAiReliabilityReasoningImplemented===true&&P4.safety.providerOutputMayConfirmTruth===false&&P4.safety.reliabilityEqualsTruth===false,P4.safety,"Authority","Critical");
    check("External AI reasoning output does not equal action authority",P4.safety.providerOutputMayGrantActionAuthority===false&&P4.safety.reliabilityEqualsActionAuthority===false&&P4.safety.selfGrantedAuthorityAllowed===false,P4.safety,"Authority","Critical");
    check("Validation does not equal Project Owner approval",global.EXTERNAL020VersionManifest&&global.EXTERNAL020VersionManifest.safety.validationEqualsApproval===false,{validationEqualsApproval:false},"Authority","Critical");
    const failed=checks.filter(function(c){return !c.passed;}),criticalFailed=failed.filter(function(c){return c.severity==="Critical";}).length;const record=i.deepFreeze({validationId:i.nextId("EXTERNAL020-PHASE4-VALIDATION"),componentId:P4.componentId,decisionId:P4.decisionId,version:P4.version,phase:4,passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed:criticalFailed,phase4ImplementationComplete:failed.length===0,phase4TechnicalGateReady:failed.length===0,decision001RequirementsComplete:coverage.decisionRequirementsFullyImplemented,decision001RequirementsTotal:coverage.totalDecisionRequirements,decision001Complete:coverage.allDecisionRequirementsComplete===true,releaseAllowed:false,projectOwnerAcceptanceRequired:true,validationIsApproval:false,canonicalMutationPerformed:false,externalTransmissionPerformed:false,providerNetworkCallPerformed:false,paidApiExecutionPerformed:false,historicalOutcomeGroundedEvaluationPerformed:true,externalAiReliabilityReasoningImplemented:true,externalAiReliabilityReasoningPerformed:false,checks:checks,validatedAt:i.nowIso(),immutable:true});s.validations.set(record.validationId,record);s.latestValidationId=record.validationId;i.touch();return i.clone(record);
  }
  Object.assign(namespace.api,{runExternal020Phase4Validation});Object.assign(namespace,namespace.api);namespace.modules.phase4Validation={id:"EXTERNAL-020-PHASE4-VALIDATION",version:P4.version,status:"Ready",releaseAllowed:false,validationIsApproval:false,loadedAt:i.nowIso()};global.runExternal020Phase4Validation=runExternal020Phase4Validation;
})(typeof window!=="undefined"?window:globalThis);
