/* ============================================================
   FILE: 19_trust_evidence_phase3_validation.js
   EXTERNAL-020 Phase 3 Functional Validation
   ============================================================ */
(function(global){
  "use strict";
  const namespace=global.EXTERNAL020TrustEvidence,P3=global.EXTERNAL020Phase3VersionManifest;if(!namespace||!namespace.__internal||!P3)return;
  const i=namespace.__internal,s=i.state;
  function runExternal020Phase3Validation(){
    const checks=[];function check(name,passed,detail,group,severity){checks.push({name:name,passed:Boolean(passed),detail:i.clone(detail),group:group||"Functional",severity:severity||"Critical"});}
    const p2=typeof global.runExternal020Phase2Validation==="function"?global.runExternal020Phase2Validation():null;check("Frozen Phase 2 functional foundation remains PASS",p2&&p2.failed===0&&p2.criticalFailed===0&&p2.passed===21,p2,"Regression","Critical");
    const dep=namespace.getExternal020HistoricalOutcomeDependencyStatus();check("REQ-020-008 EXTERNAL-010 historical inputs are available through public read APIs",dep.allRequiredPublicReadApisAvailable===true&&dep.writeApiRequired===false&&dep.internalStateAccessAllowed===false,dep,"Integration","Critical");
    const capture=namespace.captureExternal020HistoricalOutcomeInputs({predictionId:"EXTERNAL020-PHASE3-NO-DATA-PREDICTION",outcomeId:"EXTERNAL020-PHASE3-NO-DATA-OUTCOME",capabilityId:"EXTERNAL020-PHASE3-NO-DATA-CAPABILITY"});check("Historical input capture is read-only and invokes no EXTERNAL-010 write API",capture.ok===true&&capture.data.historicalInputPackage.readOnly===true&&capture.data.historicalInputPackage.external010WriteApiInvoked===false&&capture.data.historicalInputPackage.internalStateAccessPerformed===false,capture,"Safety","Critical");
    const emptySnap=capture.ok?capture.data.historicalInputPackage:{predictionHistory:[],outcomeHistory:[],capabilityPerformanceProfiles:[]};const emptyEval=namespace.evaluateExternal020HistoricalOutcomeSnapshot({profile:null,historicalInputPackage:emptySnap});check("Missing historical outcomes produce INSUFFICIENT_HISTORY without invented score",emptyEval.historicalGroundingState==="INSUFFICIENT_HISTORY"&&emptyEval.historicalAccuracyScore===null&&emptyEval.reliabilityScore===null&&emptyEval.truthConfirmed===false,emptyEval,"Negative","Critical");
    const finalFixture={predictionHistory:[{predictionId:"P-HIST-1",version:1,evidenceIds:["EVIDENCE-PRED-1"],probabilityState:"QUALITATIVE",canonicalTruthConfirmed:false}],outcomeHistory:[{outcomeId:"O-HIST-1",version:1,predictionId:"P-HIST-1",settlementState:"FINAL",supportingEvidenceIds:["EVIDENCE-OUTCOME-1"],absoluteTruthClaimed:false}],capabilityPerformanceProfiles:[{performanceProfileId:"PERF-HIST-1",capabilityId:"CAP-HIST-1",taskType:"PRICE_DATA_REVIEW",domain:"MARKET",horizon:"CURRENT",outcomeGrounded:true,evaluationEvidenceRefs:["EVIDENCE-PERF-1"],performanceGrantsActionAuthority:false}]};
    const profileFixture={domain:"MARKET",task:"PRICE_DATA_REVIEW",timeHorizon:"CURRENT"};const finalEval=namespace.evaluateExternal020HistoricalOutcomeSnapshot({profile:profileFixture,historicalInputPackage:finalFixture});check("FINAL historical Outcome can produce OUTCOME_GROUNDED assessment",finalEval.historicalGroundingState==="OUTCOME_GROUNDED"&&finalEval.finalSettlementObserved===true&&finalEval.outcomeHistoryCount===1,finalEval,"Reliability","Critical");
    check("Historical grounding preserves evidence references",finalEval.historicalEvidenceRefs.includes("EVIDENCE-PRED-1")&&finalEval.historicalEvidenceRefs.includes("EVIDENCE-OUTCOME-1")&&finalEval.historicalEvidenceRefs.includes("EVIDENCE-PERF-1"),finalEval.historicalEvidenceRefs,"Lineage","Major");
    check("Outcome-grounded Capability Performance remains context-scoped evidence, not authority",finalEval.outcomeGroundedPerformanceProfileCount===1&&finalEval.contextMatchingOutcomeGroundedPerformanceProfileCount===1&&finalEval.actionAuthorityGranted===false,finalEval,"Authority","Critical");
    check("Prediction and Outcome are not automatically converted into an accuracy score",finalEval.predictionOutcomeMatchComputed===false&&finalEval.historicalAccuracyScore===null&&finalEval.calibrationScore===null&&finalEval.reliabilityScore===null,finalEval,"Safety","Critical");
    const conflictFixture={predictionHistory:finalFixture.predictionHistory,outcomeHistory:[{outcomeId:"O-HIST-CONFLICT",version:1,predictionId:"P-HIST-1",settlementState:"DISPUTED",supportingEvidenceIds:["EVIDENCE-CONFLICT-A","EVIDENCE-CONFLICT-B"]}],capabilityPerformanceProfiles:[]};const conflictEval=namespace.evaluateExternal020HistoricalOutcomeSnapshot({profile:profileFixture,historicalInputPackage:conflictFixture});check("DISPUTED historical Outcome remains CONFLICTED_HISTORY with no winner",conflictEval.historicalGroundingState==="CONFLICTED_HISTORY"&&conflictEval.conflictWinner===null&&conflictEval.automaticConflictResolutionPerformed===false&&conflictEval.truthConfirmed===false,conflictEval,"Negative","Critical");
    const partialFixture={predictionHistory:finalFixture.predictionHistory,outcomeHistory:[{outcomeId:"O-HIST-PARTIAL",version:1,predictionId:"P-HIST-1",settlementState:"PROVISIONAL",supportingEvidenceIds:["EVIDENCE-PARTIAL"]}],capabilityPerformanceProfiles:[]};const partialEval=namespace.evaluateExternal020HistoricalOutcomeSnapshot({profile:profileFixture,historicalInputPackage:partialFixture});check("PROVISIONAL historical Outcome remains PARTIALLY_GROUNDED",partialEval.historicalGroundingState==="PARTIALLY_GROUNDED"&&partialEval.truthConfirmed===false,partialEval,"Reliability","Major");
    const p=typeof namespace.findExternal020ReliabilityProfile==="function"?namespace.findExternal020ReliabilityProfile({subjectType:"SOURCE",subjectRef:"SRC-PHASE2",domain:"MARKET",task:"PRICE_DATA_REVIEW",purpose:"PHASE2_VALIDATION",timeHorizon:"CURRENT"}):null;const before=p&&typeof namespace.listExternal020ReliabilityProfileHistory==="function"?namespace.listExternal020ReliabilityProfileHistory(p.profileId).length:0;
    const assessment=p?namespace.createExternal020HistoricalOutcomeAssessment({profileId:p.profileId,predictionId:"EXTERNAL020-PHASE3-NO-DATA-PREDICTION",outcomeId:"EXTERNAL020-PHASE3-NO-DATA-OUTCOME",capabilityId:"EXTERNAL020-PHASE3-NO-DATA-CAPABILITY",explanation:"Phase 3 read-only integration validation"}):null;check("Historical Outcome Assessment can be linked to an existing Reliability Profile",assessment&&assessment.ok===true&&assessment.data.assessment.profileId===p.profileId&&assessment.data.assessment.profileVersionRef===p.profileId+"@"+p.profileVersion,assessment,"Integration","Critical");
    check("Historical assessment is append-only evidence and does not automatically revise Profile",assessment&&assessment.ok===true&&assessment.data.assessment.automaticProfileRevisionPerformed===false&&assessment.data.assessment.profileRevisionCandidateOnly===true,assessment&&assessment.data.assessment,"Revision","Critical");
    const after=p&&typeof namespace.listExternal020ReliabilityProfileHistory==="function"?namespace.listExternal020ReliabilityProfileHistory(p.profileId).length:0;check("Existing Reliability Profile history is unchanged by Historical assessment",Boolean(p)&&before===after,{before:before,after:after},"Revision","Critical");
    check("Historical assessment grants no Truth / Knowledge / action authority",assessment&&assessment.ok===true&&assessment.data.assessment.truthConfirmed===false&&assessment.data.assessment.knowledgePromotionPerformed===false&&assessment.data.assessment.actionAuthorityGranted===false,assessment&&assessment.data.assessment,"Authority","Critical");
    check("Phase 3 performs no Raw Evidence or Canonical Repository mutation",assessment&&assessment.ok===true&&assessment.data.assessment.rawEvidenceMutationPerformed===false&&assessment.data.assessment.canonicalRepositoryMutationPerformed===false,assessment&&assessment.data.assessment,"Safety","Critical");
    check("Phase 3 remains local-only with no paid API or external transmission",assessment&&assessment.ok===true&&assessment.data.assessment.externalTransmissionPerformed===false&&assessment.data.assessment.paidApiExecutionPerformed===false,assessment&&assessment.data.assessment,"Safety","Critical");
    check("IDE-170 Confidence remains untouched",assessment&&assessment.ok===true&&assessment.data.assessment.ide170ConfidenceOverwritten===false&&P3.safety.ide170ConfidenceOverwriteAllowed===false,assessment&&assessment.data.assessment,"Safety","Critical");
    check("External AI Reliability Reasoning remains deferred",P3.safety.externalAiReliabilityReasoningImplemented===false&&P3.deferredAfterPhase3.length===1&&P3.deferredAfterPhase3[0]==="REQ-020-015",P3,"Scope","Critical");
    const coverage=namespace.getExternal020Phase3Decision001Coverage();check("Decision 001 traceability reaches 17/18 without false completion",coverage.totalDecisionRequirements===18&&coverage.decisionRequirementsFullyImplemented===17&&coverage.allDecisionRequirementsComplete===false&&coverage.remainingRequirementIds.length===1&&coverage.remainingRequirementIds[0]==="REQ-020-015",coverage,"Traceability","Critical");
    check("Historical Outcome grounding does not equal automatic Truth",P3.safety.historicalOutcomeGroundedEvaluationImplemented===true&&P3.safety.truthConfirmationAllowed===false&&P3.safety.predictionOutcomeMatchAutomaticallyComputed===false,P3.safety,"Authority","Critical");
    check("Validation does not equal Project Owner approval",global.EXTERNAL020VersionManifest&&global.EXTERNAL020VersionManifest.safety.validationEqualsApproval===false,{validationEqualsApproval:false},"Authority","Critical");
    const failed=checks.filter(function(c){return !c.passed;}),criticalFailed=failed.filter(function(c){return c.severity==="Critical";}).length;const record=i.deepFreeze({validationId:i.nextId("EXTERNAL020-PHASE3-VALIDATION"),componentId:P3.componentId,decisionId:P3.decisionId,version:P3.version,phase:3,passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed:criticalFailed,phase3ImplementationComplete:failed.length===0,phase3TechnicalGateReady:failed.length===0,decision001RequirementsComplete:coverage.decisionRequirementsFullyImplemented,decision001RequirementsTotal:coverage.totalDecisionRequirements,decision001Complete:false,releaseAllowed:false,projectOwnerAcceptanceRequired:true,validationIsApproval:false,canonicalMutationPerformed:false,externalTransmissionPerformed:false,paidApiExecutionPerformed:false,historicalOutcomeGroundedEvaluationPerformed:true,externalAiReliabilityReasoningPerformed:false,checks:checks,validatedAt:i.nowIso(),immutable:true});s.validations.set(record.validationId,record);s.latestValidationId=record.validationId;i.touch();return i.clone(record);
  }
  Object.assign(namespace.api,{runExternal020Phase3Validation});Object.assign(namespace,namespace.api);namespace.modules.phase3Validation={id:"EXTERNAL-020-PHASE3-VALIDATION",version:P3.version,status:"Ready",releaseAllowed:false,validationIsApproval:false,loadedAt:i.nowIso()};global.runExternal020Phase3Validation=runExternal020Phase3Validation;
})(typeof window!=="undefined"?window:globalThis);
