"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const root=__dirname,checks=[];const check=(name,passed,detail,severity="Critical")=>checks.push({name,passed:Boolean(passed),detail,severity});
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");const norm=s=>String(s||"").split("#")[0].split("?")[0].replace(/^\.\//,"");
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o={};Object.keys(v).sort().forEach(k=>o[k]=stable(v[k]));return o;}return v;}
const manifest=JSON.parse(fs.readFileSync(path.join(root,"00_script_manifest.json"),"utf8"));const projectInfo=JSON.parse(fs.readFileSync(path.join(root,"project_info.json"),"utf8"));const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const p1Files=["19_trust_evidence_version_manifest.js","19_trust_evidence_core.js","19_trust_evidence_external010_adapter.js","19_trust_evidence_evaluation_context.js","19_trust_evidence_lineage.js","19_trust_evidence_evaluation_candidate.js","19_trust_evidence_traceability.js","19_trust_evidence_phase1_validation.js","19_trust_evidence_phase1_android_validation.js"];
const p1Hashes={
"19_trust_evidence_version_manifest.js":"10898623acf40e6f4e0281479ffc49c5bb5ab9ce4dec072e7efbed87f894a1bc","19_trust_evidence_core.js":"5ff77d1cf7c8de9a6448dfe4eb57f973904c3f25ea45a28f2216a93ab770ac64","19_trust_evidence_external010_adapter.js":"c4189beae60b4927167ebf48c0ddb4829b0aaa3b831f2088cec79eea6e84523b","19_trust_evidence_evaluation_context.js":"013366c99b74ed230a8c4887563d61136b60af42e591b62ae66eebf1132bbdde","19_trust_evidence_lineage.js":"174724e6b5919d53cd578dbee5204e89a47e29994e9d4378fd0fce7af70b0381","19_trust_evidence_evaluation_candidate.js":"ed712a0aa92930fe73031f842d7711db9eb5d2d514ed09759dbe3b14d23b1cf3","19_trust_evidence_traceability.js":"67bdead2a46535e178427a58dd3c5c0cee7eb09435f5e2590e9b7b03559c383a","19_trust_evidence_phase1_validation.js":"4a1ab2cee6936434e78419f3c228193b4582ce8761e0f57f7c894b5c2ea9949b","19_trust_evidence_phase1_android_validation.js":"0ddbc0481241e54b1116ece571324cbee5a86a62df267b6ab79b8478604e82b1"};
const p2Files=["19_trust_evidence_phase2_version_manifest.js","19_trust_evidence_dimensions.js","19_trust_evidence_independence.js","19_trust_evidence_reliability_profile.js","19_trust_evidence_reliability_revision.js","19_trust_evidence_phase2_traceability.js","19_trust_evidence_phase2_validation.js"];
let hashPass=0,cachePass=0,missing=[];for(const src of manifest.scripts){const f=norm(src),p=path.join(root,f),h=manifest.hashes&&manifest.hashes[f];if(!fs.existsSync(p)||!h){missing.push(f);continue;}const b=fs.readFileSync(p),actual=sha(b);if(actual===h.sha256&&b.length===h.byteSize)hashPass++;const m=String(src).match(/[?&]h=([a-f0-9]+)/i);if(m&&m[1]===h.cacheKey&&h.cacheKey===h.sha256.slice(0,12))cachePass++;}
check("All manifest script hashes and byte sizes match",hashPass===manifest.scripts.length&&missing.length===0,{verified:hashPass,total:manifest.scripts.length,missing});
check("All manifest cache keys match",cachePass===manifest.scripts.length,{verified:cachePass,total:manifest.scripts.length});
const setPayload=manifest.scripts.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n"),computedSetHash=sha(Buffer.from(setPayload));check("Script Set Hash verifies",computedSetHash===manifest.scriptSetHash,{computed:computedSetHash,stored:manifest.scriptSetHash});
const copy=JSON.parse(JSON.stringify(manifest));delete copy.manifestHash;delete copy.updatedAt;const computedManifestHash=sha(Buffer.from(JSON.stringify(stable(copy))));check("Manifest Hash verifies",computedManifestHash===manifest.manifestHash,{computed:computedManifestHash,stored:manifest.manifestHash});
const meta=(index.match(/<meta name="ai-pro-script-manifest-hash" content="([a-f0-9]{64})"/)||[])[1]||"";check("index manifest hash marker matches",meta===manifest.manifestHash,{index:meta,manifest:manifest.manifestHash});
const indexScripts=[];const re=/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi;let mm;while((mm=re.exec(index)))if(/^\.\//.test(mm[1])&&/\.js(?:\?|$)/i.test(mm[1]))indexScripts.push(mm[1]);check("index script sequence matches manifest",JSON.stringify(indexScripts)===JSON.stringify(manifest.scripts),{indexCount:indexScripts.length,manifestCount:manifest.scripts.length});
check("Phase 2 files are all present",p2Files.every(f=>manifest.scripts.some(src=>norm(src)===f)),p2Files);
const pos=p2Files.map(f=>manifest.scripts.findIndex(src=>norm(src)===f)),p1Last=manifest.scripts.findIndex(src=>norm(src)==="19_trust_evidence_phase1_android_validation.js"),initPos=manifest.scripts.findIndex(src=>norm(src)==="99_init.js");check("Phase 2 scripts load contiguously after Frozen Phase 1 and before 99_init",pos.every((p,idx)=>p>=0&&(idx===0?p===p1Last+1:p===pos[idx-1]+1))&&pos[pos.length-1]<initPos,{p1Last,pos,initPos});
check("Frozen Phase 1 script bytes are unchanged",p1Files.every(f=>manifest.hashes[f]&&manifest.hashes[f].sha256===p1Hashes[f]),p1Files.map(f=>({file:f,expected:p1Hashes[f],actual:manifest.hashes[f]&&manifest.hashes[f].sha256})));
const parentScripts=manifest.scripts.filter(src=>!/^19_trust_evidence_/.test(norm(src)));const parentPayload=parentScripts.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");const parentSetHash=sha(Buffer.from(parentPayload));check("Canonical 0023 parent script set remains byte/order identical",parentScripts.length===462&&parentSetHash==="d3121eb588b7c7b332cb86ef66f82fe2f2ecd77bd1be029143ff578f2d0514a3",{parentScriptCount:parentScripts.length,parentScriptSetHash:parentSetHash});
check("project_info identity matches Phase 2 candidate",Number(projectInfo.scriptManifestCount)===manifest.scripts.length&&projectInfo.scriptManifestHash===manifest.manifestHash&&projectInfo.scriptSetHash===manifest.scriptSetHash&&projectInfo.external020Phase1Status==="PROJECT_OWNER_ACCEPTED_FROZEN"&&projectInfo.external020Phase2Version==="0.2.0"&&projectInfo.external020Phase2Status==="IMPLEMENTATION_PHASE2_CANDIDATE",{count:projectInfo.scriptManifestCount,phase1Status:projectInfo.external020Phase1Status,phase2Version:projectInfo.external020Phase2Version,phase2Status:projectInfo.external020Phase2Status});
const saved=new Set(projectInfo.savedFiles||[]);check("project_info savedFiles covers every manifest script",manifest.scripts.every(src=>saved.has(norm(src))),{savedCount:saved.size,manifestCount:manifest.scripts.length});
check("Candidate does not claim release or full Decision completion",projectInfo.releaseAllowed===false&&projectInfo.projectOwnerRevalidationRequired===true&&projectInfo.external020Decision001RequirementsImplementedCandidateCount===16&&projectInfo.external020Decision001Complete===false,{releaseAllowed:projectInfo.releaseAllowed,implemented:projectInfo.external020Decision001RequirementsImplementedCandidateCount,decisionComplete:projectInfo.external020Decision001Complete});

global.IDE170Intelligence={getStatus:()=>({componentId:"IDE-170",status:"Ready"})};global.IDE180KnowledgeNavigator={getStatus:()=>({componentId:"IDE-180",status:"Ready"})};
const sourcePkg={operationalSignals:[{reliabilitySignalId:"RS-P2",sourceId:"SRC-PHASE2",observationWindow:"7D",requestCount:10,successCount:9,timeoutCount:1,schemaFailureCount:0,averageLatencyMs:100,freshnessState:"FRESH",correctionObserved:false,operationalReliabilityOnly:true,factualReliabilityDetermined:false,reliabilityScore:null,authorityScore:null,finalReliabilityAuthority:"EXTERNAL-020"}],evidenceQualitySignals:[{qualitySignalId:"EQ-P2-A",evidenceId:"EVIDENCE-P2-A",sourceId:"SRC-PHASE2",sourceRole:"PRIMARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true,qualityScore:null,authorityScore:null,truthConfirmed:false,finalReliabilityAuthority:"EXTERNAL-020"},{qualitySignalId:"EQ-P2-B",evidenceId:"EVIDENCE-P2-B",sourceId:"SRC-PHASE2",sourceRole:"SECONDARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true,qualityScore:null,authorityScore:null,truthConfirmed:false,finalReliabilityAuthority:"EXTERNAL-020"}],contradictionCandidates:[{candidateId:"CON-P2",candidateType:"CONTRADICTION",subjectRef:"SRC-PHASE2",evidenceIds:["EVIDENCE-P2-A","EVIDENCE-P2-B"],independenceVerified:false,conflictWinner:null,truthConfirmed:false,automaticResolutionPerformed:false,duplicateEqualsIndependentConfirmation:false,finalReliabilityAuthority:"EXTERNAL-020"}],confirmationCandidates:[{candidateId:"CONF-P2",candidateType:"CONFIRMATION",subjectRef:"SRC-PHASE2",evidenceIds:["EVIDENCE-P2-A","EVIDENCE-P2-B"],independenceVerified:false,conflictWinner:null,truthConfirmed:false,automaticResolutionPerformed:false,duplicateEqualsIndependentConfirmation:false,finalReliabilityAuthority:"EXTERNAL-020"}],finalReliabilityAuthority:"EXTERNAL-020",generatedAt:new Date().toISOString(),contractValid:true};
global.EXTERNAL010ExternalIntelligence={getExternalIntelligenceReliabilityInputPackage:()=>JSON.parse(JSON.stringify(sourcePkg))};
for(const f of p1Files.concat(p2Files))require(path.join(root,f));
const p1=global.runExternal020Phase1Validation();check("Frozen Phase 1 functional validation remains PASS",p1&&p1.failed===0&&p1.criticalFailed===0&&p1.phase1ImplementationComplete===true,p1);
const p2=global.runExternal020Phase2Validation();check("Phase 2 functional validation passes",p2&&p2.failed===0&&p2.criticalFailed===0&&p2.phase2ImplementationComplete===true&&p2.decision001RequirementsComplete===16,p2);
check("Phase 2 grants no approval / release / mutation / external execution",p2&&p2.releaseAllowed===false&&p2.projectOwnerAcceptanceRequired===true&&p2.validationIsApproval===false&&p2.canonicalMutationPerformed===false&&p2.externalTransmissionPerformed===false&&p2.paidApiExecutionPerformed===false,p2);
const coverage=global.EXTERNAL020TrustEvidence.getExternal020Decision001Coverage();check("Decision 001 is 16/18 after Phase 2 and remains incomplete",coverage.decisionRequirementsFullyImplemented===16&&coverage.allDecisionRequirementsComplete===false&&JSON.stringify(coverage.remainingRequirementIds.sort())===JSON.stringify(["REQ-020-008","REQ-020-015"].sort()),coverage);
check("Historical Outcome and External AI remain deferred",global.EXTERNAL020Phase2VersionManifest.safety.historicalOutcomeGroundedEvaluationImplemented===false&&global.EXTERNAL020Phase2VersionManifest.safety.externalAiReliabilityReasoningImplemented===false,global.EXTERNAL020Phase2VersionManifest.safety);
const failed=checks.filter(x=>!x.passed),criticalFailed=failed.filter(x=>x.severity==="Critical").length;const report={id:"EXTERNAL-020-PHASE2-STATIC-FUNCTIONAL-VALIDATION",decisionId:"EXTERNAL-020-DECISION-001",candidateVersion:"0.2.0",passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed,scriptCount:manifest.scripts.length,manifestHash:manifest.manifestHash,scriptSetHash:manifest.scriptSetHash,frozenPhase1SourceVerified:true,canonical0023ParentVerified:true,decision001RequirementsComplete:16,decision001RequirementsTotal:18,releaseAllowed:false,validationIsApproval:false,canonicalMutationPerformed:false,externalTransmissionPerformed:false,paidApiExecutionPerformed:false,checks};console.log(JSON.stringify(report,null,2));process.exitCode=failed.length?1:0;
