"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const root=__dirname,checks=[];const check=(name,passed,detail,severity="Critical")=>checks.push({name,passed:Boolean(passed),detail,severity});
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");const norm=s=>String(s||"").split("#")[0].split("?")[0].replace(/^\.\//,"");
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o={};Object.keys(v).sort().forEach(k=>o[k]=stable(v[k]));return o;}return v;}
const manifest=JSON.parse(fs.readFileSync(path.join(root,"00_script_manifest.json"),"utf8"));const projectInfo=JSON.parse(fs.readFileSync(path.join(root,"project_info.json"),"utf8"));const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const phase4Files=["19_trust_evidence_phase4_version_manifest.js","19_trust_evidence_external_ai_context_policy.js","19_trust_evidence_external_ai_governance_adapter.js","19_trust_evidence_external_ai_reasoning.js","19_trust_evidence_phase4_traceability.js","19_trust_evidence_phase4_validation.js"];
let verified=0,cache=0,missing=[];for(const src of manifest.scripts){const f=norm(src),p=path.join(root,f),h=manifest.hashes&&manifest.hashes[f];if(!fs.existsSync(p)||!h){missing.push(f);continue;}const b=fs.readFileSync(p),actual=sha(b);if(actual===h.sha256&&b.length===h.byteSize)verified++;const m=String(src).match(/[?&]h=([a-f0-9]+)/i);if(m&&m[1]===h.cacheKey&&h.cacheKey===h.sha256.slice(0,12))cache++;}
check("All 491 manifest script hashes and byte sizes match",verified===manifest.scripts.length&&manifest.scripts.length===491&&missing.length===0,{verified,total:manifest.scripts.length,missing});
check("All manifest cache keys match",cache===manifest.scripts.length,{verified:cache,total:manifest.scripts.length});
const payload=manifest.scripts.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");check("Script Set Hash verifies",sha(Buffer.from(payload))===manifest.scriptSetHash,{computed:sha(Buffer.from(payload)),stored:manifest.scriptSetHash});
const cp=JSON.parse(JSON.stringify(manifest));delete cp.manifestHash;delete cp.updatedAt;const mh=sha(Buffer.from(JSON.stringify(stable(cp))));check("Manifest Hash verifies",mh===manifest.manifestHash,{computed:mh,stored:manifest.manifestHash});
const meta=(index.match(/<meta name="ai-pro-script-manifest-hash" content="([a-f0-9]{64})"/)||[])[1]||"";check("index manifest hash marker matches",meta===manifest.manifestHash,{index:meta,manifest:manifest.manifestHash});
const seq=[];const re=/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi;let mm;while((mm=re.exec(index)))if(/^\.\//.test(mm[1])&&/\.js(?:\?|$)/i.test(mm[1]))seq.push(mm[1]);check("index script sequence matches manifest",JSON.stringify(seq)===JSON.stringify(manifest.scripts),{indexCount:seq.length,manifestCount:manifest.scripts.length});
const parent=manifest.scripts.filter(src=>!phase4Files.includes(norm(src)));const parentPayload=parent.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");check("Frozen Phase 3 v0.3.1 parent remains byte/order identical",parent.length===485&&sha(Buffer.from(parentPayload))==="69ea6a918db8a26702a0b3cfaffe0002d3247ac468a25ee485905fab247d7954",{parentCount:parent.length,parentHash:sha(Buffer.from(parentPayload))});
const canonical=manifest.scripts.filter(src=>!/^19_trust_evidence_/.test(norm(src)));const canonicalPayload=canonical.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");check("Canonical 0023 parent remains byte/order identical",canonical.length===462&&sha(Buffer.from(canonicalPayload))==="d3121eb588b7c7b332cb86ef66f82fe2f2ecd77bd1be029143ff578f2d0514a3",{parentCount:canonical.length,parentHash:sha(Buffer.from(canonicalPayload))});
check("project_info identity matches Phase 4 v0.4.1 hotfix candidate",projectInfo.scriptManifestCount===491&&projectInfo.scriptManifestHash===manifest.manifestHash&&projectInfo.scriptSetHash===manifest.scriptSetHash&&projectInfo.external020Phase4Version==="0.4.1"&&projectInfo.external020Phase4ValidationRerunIdempotencyFixed===true&&projectInfo.releaseAllowed===false,{phase4Version:projectInfo.external020Phase4Version,hotfix:projectInfo.external020Phase4HotfixId,releaseAllowed:projectInfo.releaseAllowed});

global.document={};global.IDE170Intelligence={};global.IDE180KnowledgeNavigator={};let submitCalls=0,authorityCalls=0;
const sourcePkg={contractId:"EXTERNAL-010-CONTRACT-RELIABILITY-INPUT-PACKAGE",operationalSignals:[{reliabilitySignalId:"RS-P4",sourceId:"SRC-PHASE2",requestCount:10,successCount:9,timeoutCount:1,schemaFailureCount:0,freshnessState:"FRESH"}],evidenceQualitySignals:[{qualitySignalId:"QS-P4-A",evidenceId:"EVIDENCE-P2-A",sourceId:"SRC-PHASE2",sourceRole:"PRIMARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true},{qualitySignalId:"QS-P4-B",evidenceId:"EVIDENCE-P2-B",sourceId:"SRC-PHASE2",sourceRole:"SECONDARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true}],contradictionCandidates:[],confirmationCandidates:[],finalReliabilityAuthority:"EXTERNAL-020",generatedAt:new Date().toISOString(),contractValid:true};
global.EXTERNAL010ExternalIntelligence={
 getExternalIntelligenceReliabilityInputPackage:()=>JSON.parse(JSON.stringify(sourcePkg)),getExternalIntelligencePrediction:()=>null,listExternalIntelligencePredictionHistory:()=>[],getExternalIntelligenceOutcome:()=>null,listExternalIntelligenceOutcomeHistory:()=>[],listExternalIntelligenceCapabilityPerformanceProfiles:()=>[],
 getOpenAIFinalValidation:()=>({passed:true,state:"FINAL_VALIDATED",readiness:"OPENAI_API_INTEGRATION_READY"}),getOpenAIProviderIntegrationProfile:()=>({provider:"OPENAI",storeRequiredValue:false,initialCapability:{tools:false,files:false,webSearch:false,computerUse:false},noPerRequestHumanApprovalInsideApprovedScope:true}),getExternalIntelligenceSource:()=>({sourceId:"SOURCE-OPENAI",lifecycleState:"ACTIVE",enabled:true,secretReferenceId:"SECRET-OPENAI-LEGACY",paidActivationPolicy:{budgetIds:["BUDGET-P4"],perRequestHardCapUsd:0.05,currency:"USD"}}),getExternalIntelligenceSourceOperationContract:()=>({enabled:true,method:"POST",bodyPolicy:{fixedFields:{store:false}}}),checkExternalIntelligenceUsagePolicy:()=>({ok:true,data:{allowed:true}}),validateExternalIntelligenceSecretReference:()=>({ok:true,data:{secretValueReturned:false}}),
 prepareOpenAIResponsesRequest:(input)=>({ok:true,code:"STUB_PREPARED",data:{requestCandidate:{sourceId:"SOURCE-OPENAI",operationId:"INTERNAL_ANALYSIS",body:input.body,budgetIds:input.budgetIds,estimatedUsage:{FINANCIAL_COST:0.001},retryPolicy:{maxAttempts:1},timeoutPolicy:{timeoutMs:60000}},costEstimate:{maximumEstimatedCostUsd:0.001,estimatedUsage:{FINANCIAL_COST:0.001}}}}),
 setExternalIntelligenceAuthorityApprovalAdapter:()=>{authorityCalls++;return {ok:true};},createExternalIntelligenceAuthorityEnvelopeCandidate:()=>{authorityCalls++;return {ok:true,data:{envelope:{authorityEnvelopeId:"AUTH-STUB"}}};},activateExternalIntelligenceAuthorityEnvelope:async()=>{authorityCalls++;return {ok:true};},revokeExternalIntelligenceAuthorityEnvelope:()=>{authorityCalls++;return {ok:true};},submitExternalIntelligenceAcquisition:async()=>{submitCalls++;throw new Error("Provider execution must not run in validation");}
};
const runtimeFiles=manifest.scripts.map(norm).filter(f=>/^19_trust_evidence_/.test(f));for(const f of runtimeFiles)require(path.join(root,f));
check("Phase 4 Version Manifest reports v0.4.1 hotfix metadata",global.EXTERNAL020Phase4VersionManifest&&global.EXTERNAL020Phase4VersionManifest.version==="0.4.1"&&global.EXTERNAL020Phase4VersionManifest.hotfix&&global.EXTERNAL020Phase4VersionManifest.hotfix.isolatedRegressionState===true,global.EXTERNAL020Phase4VersionManifest);
(async()=>{
 const dirty=await global.runExternal020Phase3Validation();check("Fixture intentionally dirties Frozen Phase 3 state before Phase 4",dirty&&dirty.failed===0&&dirty.decision001RequirementsComplete===17,dirty);
 const ns=global.EXTERNAL020TrustEvidence,st=ns.__internal.state;const profileCountBefore=st.reliabilityProfiles.size,historySeriesBefore=st.reliabilityProfileSeries.size;
 const r1=await global.runExternal020Phase4Validation();
 check("Phase 4 first run passes 20/20 on dirty caller state",r1&&r1.passed===20&&r1.failed===0&&r1.criticalFailed===0&&r1.phase4TechnicalGateReady===true,r1);
 check("Phase 4 isolated regression restores caller Reliability Profile state",st.reliabilityProfiles.size===profileCountBefore&&st.reliabilityProfileSeries.size===historySeriesBefore,{profileCountBefore,profileCountAfter:st.reliabilityProfiles.size,historySeriesBefore,historySeriesAfter:st.reliabilityProfileSeries.size});
 const r2=await global.runExternal020Phase4Validation();
 check("Phase 4 repeated run in same session passes 20/20",r2&&r2.passed===20&&r2.failed===0&&r2.criticalFailed===0&&r2.phase4TechnicalGateReady===true,r2);
 check("Repeated Phase 4 validation invokes no provider execution or execution authority",submitCalls===0&&authorityCalls===0,{submitCalls,authorityCalls});
 const failed=checks.filter(c=>!c.passed),criticalFailed=failed.filter(c=>c.severity==="Critical").length;const report={id:"EXTERNAL-020-PHASE4-V0.4.1-RERUN-IDEMPOTENCY-HOTFIX",candidateVersion:"0.4.1",passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed,scriptCount:manifest.scripts.length,manifestHash:manifest.manifestHash,scriptSetHash:manifest.scriptSetHash,frozenPhase3ParentVerified:true,canonical0023ParentVerified:true,rerunIdempotencyVerified:r1.failed===0&&r2.failed===0,providerExecutionCallsDuringValidation:submitCalls,authorityActivationCallsDuringValidation:authorityCalls,releaseAllowed:false,checks};console.log(JSON.stringify(report,null,2));process.exitCode=failed.length?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
