"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const root=__dirname,checks=[];const check=(name,passed,detail,severity="Critical")=>checks.push({name,passed:Boolean(passed),detail,severity});
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");const norm=s=>String(s||"").split("#")[0].split("?")[0].replace(/^\.\//,"");
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o={};Object.keys(v).sort().forEach(k=>o[k]=stable(v[k]));return o;}return v;}
const manifest=JSON.parse(fs.readFileSync(path.join(root,"00_script_manifest.json"),"utf8"));const projectInfo=JSON.parse(fs.readFileSync(path.join(root,"project_info.json"),"utf8"));const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
let verified=0,cache=0,missing=[];for(const src of manifest.scripts){const f=norm(src),p=path.join(root,f),h=manifest.hashes&&manifest.hashes[f];if(!fs.existsSync(p)||!h){missing.push(f);continue;}const b=fs.readFileSync(p),actual=sha(b);if(actual===h.sha256&&b.length===h.byteSize)verified++;const m=String(src).match(/[?&]h=([a-f0-9]+)/i);if(m&&m[1]===h.cacheKey&&h.cacheKey===h.sha256.slice(0,12))cache++;}
check("All 492 manifest script hashes and byte sizes match",verified===manifest.scripts.length&&manifest.scripts.length===492&&missing.length===0,{verified,total:manifest.scripts.length,missing});
check("All manifest cache keys match",cache===manifest.scripts.length,{verified:cache,total:manifest.scripts.length});
const payload=manifest.scripts.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");check("Script Set Hash verifies",sha(Buffer.from(payload))===manifest.scriptSetHash,{computed:sha(Buffer.from(payload)),stored:manifest.scriptSetHash});
const cp=JSON.parse(JSON.stringify(manifest));delete cp.manifestHash;delete cp.updatedAt;const mh=sha(Buffer.from(JSON.stringify(stable(cp))));check("Manifest Hash verifies",mh===manifest.manifestHash,{computed:mh,stored:manifest.manifestHash});
const meta=(index.match(/<meta name="ai-pro-script-manifest-hash" content="([a-f0-9]{64})"/)||[])[1]||"";check("index manifest hash marker matches",meta===manifest.manifestHash,{index:meta,manifest:manifest.manifestHash});
const seq=[];const re=/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi;let mm;while((mm=re.exec(index)))if(/^\.\//.test(mm[1])&&/\.js(?:\?|$)/i.test(mm[1]))seq.push(mm[1]);check("index script sequence matches manifest",JSON.stringify(seq)===JSON.stringify(manifest.scripts),{indexCount:seq.length,manifestCount:manifest.scripts.length});
const androidPos=manifest.scripts.findIndex(s=>norm(s)==="19_trust_evidence_phase4_android_validation.js"),initPos=manifest.scripts.findIndex(s=>norm(s)==="99_init.js"),p4ValPos=manifest.scripts.findIndex(s=>norm(s)==="19_trust_evidence_phase4_validation.js");check("Phase 4 Android validator loads after Phase 4 validation and before 99_init",androidPos===p4ValPos+1&&initPos===androidPos+1,{p4ValPos,androidPos,initPos});
const parentPhase3=manifest.scripts.filter(src=>!/^19_trust_evidence_phase4_/.test(norm(src))&&!/^19_trust_evidence_external_ai_/.test(norm(src)));
const parentPayload=parentPhase3.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");check("Frozen Phase 3 v0.3.1 parent remains byte/order identical",parentPhase3.length===485&&sha(Buffer.from(parentPayload))==="69ea6a918db8a26702a0b3cfaffe0002d3247ac468a25ee485905fab247d7954",{parentCount:parentPhase3.length,parentHash:sha(Buffer.from(parentPayload))});
const canonical=manifest.scripts.filter(src=>!/^19_trust_evidence_/.test(norm(src)));const canonicalPayload=canonical.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");check("Canonical 0023 parent remains byte/order identical",canonical.length===462&&sha(Buffer.from(canonicalPayload))==="d3121eb588b7c7b332cb86ef66f82fe2f2ecd77bd1be029143ff578f2d0514a3",{parentCount:canonical.length,parentHash:sha(Buffer.from(canonicalPayload))});
const coreHashes={
"19_trust_evidence_external_ai_context_policy.js":"1efff08269221d56c76fb49e02e8288d13f54bc929daaab0d1839db78ad54b7d",
"19_trust_evidence_external_ai_governance_adapter.js":"035fc0ce6b4b4c14291b8517d70de08e049a3b60a14c7f6ee65671d13e49df0a",
"19_trust_evidence_external_ai_reasoning.js":"c95a011401b3ff2f584c726d5f2534b3776218a8c7279892603161f0b74dc9f9",
"19_trust_evidence_phase4_traceability.js":"cf74c4da2b8748ceb4064aa8d8800fda1d77d04a3833b4c60d22214a7783959d",
"19_trust_evidence_phase4_validation.js":"11314e18626d8b5e8518bfda708aabd31fe763cd5343f3c6c828ab40468e32fe"
};let coreOk=true;for(const [f,h] of Object.entries(coreHashes))coreOk=coreOk&&sha(fs.readFileSync(path.join(root,f)))===h;check("Phase 4 v0.4.2 functional core remains byte-identical",coreOk,coreHashes);
check("project_info identity matches Phase 4 v0.4.3 Android candidate",projectInfo.scriptManifestCount===492&&projectInfo.scriptManifestHash===manifest.manifestHash&&projectInfo.scriptSetHash===manifest.scriptSetHash&&projectInfo.external020Phase4Version==="0.4.3"&&projectInfo.external020Phase4AndroidValidationImplemented===true&&projectInfo.external020Phase4AndroidValidationFunction==="runExternal020Phase4AndroidValidation"&&projectInfo.releaseAllowed===false,{phase4Version:projectInfo.external020Phase4Version,androidImplemented:projectInfo.external020Phase4AndroidValidationImplemented,releaseAllowed:projectInfo.releaseAllowed});

global.document={};Object.defineProperty(global,"navigator",{value:{userAgent:"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Mobile Safari/537.36"},configurable:true});global.IDE170Intelligence={};global.IDE180KnowledgeNavigator={};let submitCalls=0,authorityCalls=0;
const sourcePkg={contractId:"EXTERNAL-010-CONTRACT-RELIABILITY-INPUT-PACKAGE",operationalSignals:[{reliabilitySignalId:"RS-P4A",sourceId:"SRC-PHASE2",requestCount:10,successCount:9,timeoutCount:1,schemaFailureCount:0,freshnessState:"FRESH"}],evidenceQualitySignals:[{qualitySignalId:"QS-P4A-A",evidenceId:"EVIDENCE-P2-A",sourceId:"SRC-PHASE2",sourceRole:"PRIMARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true},{qualitySignalId:"QS-P4A-B",evidenceId:"EVIDENCE-P2-B",sourceId:"SRC-PHASE2",sourceRole:"SECONDARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true}],contradictionCandidates:[],confirmationCandidates:[],finalReliabilityAuthority:"EXTERNAL-020",generatedAt:new Date().toISOString(),contractValid:true};
let liveReady=false;global.EXTERNAL010ExternalIntelligence={
 getExternalIntelligenceReliabilityInputPackage:()=>JSON.parse(JSON.stringify(sourcePkg)),getExternalIntelligencePrediction:()=>null,listExternalIntelligencePredictionHistory:()=>[],getExternalIntelligenceOutcome:()=>null,listExternalIntelligenceOutcomeHistory:()=>[],listExternalIntelligenceCapabilityPerformanceProfiles:()=>[],
 getOpenAIFinalValidation:()=>liveReady?({passed:true,state:"FINAL_VALIDATED",readiness:"OPENAI_API_INTEGRATION_READY"}):null,getOpenAIProviderIntegrationProfile:()=>({provider:"OPENAI",storeRequiredValue:false,initialCapability:{tools:false,files:false,webSearch:false,computerUse:false},noPerRequestHumanApprovalInsideApprovedScope:true}),
 getExternalIntelligenceSource:()=>liveReady?({sourceId:"SOURCE-OPENAI",lifecycleState:"ACTIVE",enabled:true,secretReferenceId:"SECRET-OPENAI-LEGACY",paidActivationPolicy:{budgetIds:["BUDGET-P4"],perRequestHardCapUsd:0.05,currency:"USD"}}):null,getExternalIntelligenceSourceOperationContract:()=>liveReady?({enabled:true,method:"POST",bodyPolicy:{fixedFields:{store:false}}}):null,checkExternalIntelligenceUsagePolicy:()=>liveReady?({ok:true,data:{allowed:true}}):({ok:false,code:"NOT_ACTIVE"}),validateExternalIntelligenceSecretReference:()=>liveReady?({ok:true,data:{secretValueReturned:false}}):({ok:false,code:"NOT_CONFIGURED"}),
 prepareOpenAIResponsesRequest:(input)=>({ok:true,code:"STUB_PREPARED",data:{requestCandidate:{sourceId:"SOURCE-OPENAI",operationId:"INTERNAL_ANALYSIS",body:input.body,budgetIds:input.budgetIds,estimatedUsage:{FINANCIAL_COST:0.001},retryPolicy:{maxAttempts:1},timeoutPolicy:{timeoutMs:60000}},costEstimate:{maximumEstimatedCostUsd:0.001,estimatedUsage:{FINANCIAL_COST:0.001}}}}),
 setExternalIntelligenceAuthorityApprovalAdapter:()=>{authorityCalls++;return {ok:true};},createExternalIntelligenceAuthorityEnvelopeCandidate:()=>{authorityCalls++;return {ok:true,data:{envelope:{authorityEnvelopeId:"AUTH-STUB"}}};},activateExternalIntelligenceAuthorityEnvelope:async()=>{authorityCalls++;return {ok:true};},revokeExternalIntelligenceAuthorityEnvelope:()=>{authorityCalls++;return {ok:true};},submitExternalIntelligenceAcquisition:async()=>{submitCalls++;throw new Error("Provider execution must not run in Android validation");}
};
const runtimeFiles=manifest.scripts.map(norm).filter(f=>/^19_trust_evidence_/.test(f));for(const f of runtimeFiles)require(path.join(root,f));
check("Phase 4 Version Manifest reports v0.4.3 Android validation metadata",global.EXTERNAL020Phase4VersionManifest&&global.EXTERNAL020Phase4VersionManifest.version==="0.4.3"&&global.EXTERNAL020Phase4VersionManifest.androidValidation&&global.EXTERNAL020Phase4VersionManifest.androidValidation.implemented===true&&global.EXTERNAL020Phase4VersionManifest.androidValidation.providerExecutionAllowed===false,global.EXTERNAL020Phase4VersionManifest);
(async()=>{const p4=await global.runExternal020Phase4Validation();check("Phase 4 functional fixture remains 20/20 PASS",p4&&p4.passed===20&&p4.failed===0&&p4.criticalFailed===0&&p4.phase4TechnicalGateReady===true&&p4.decision001RequirementsComplete===18,p4);const a1=await global.runExternal020Phase4AndroidValidation();check("Android real-device fixture passes 21/21 when LIVE provider is NOT READY and fail-closed",a1&&a1.passed===21&&a1.failed===0&&a1.criticalFailed===0&&a1.phase4AndroidRealDeviceComplete===true&&a1.phase4ProjectOwnerGateReady===true&&a1.decision001Complete===true,a1);const a2=await global.runExternal020Phase4AndroidValidation();check("Same-session Android rerun remains 21/21 PASS",a2&&a2.passed===21&&a2.failed===0&&a2.criticalFailed===0,a2);check("Android validation invokes no provider execution or authority activation",submitCalls===0&&authorityCalls===0,{submitCalls,authorityCalls});const failed=checks.filter(c=>!c.passed),criticalFailed=failed.filter(c=>c.severity==="Critical").length;const report={id:"EXTERNAL-020-PHASE4-V0.4.3-ANDROID-VALIDATION-CANDIDATE",candidateVersion:"0.4.3",passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed,scriptCount:manifest.scripts.length,manifestHash:manifest.manifestHash,scriptSetHash:manifest.scriptSetHash,androidFixture:{passed:a1&&a1.passed,total:a1&&a1.total,health:a1&&a1.health},decision001RequirementsComplete:a1&&a1.decision001RequirementsComplete,decision001Complete:a1&&a1.decision001Complete,releaseAllowed:false,checks};console.log(JSON.stringify(report,null,2));process.exitCode=failed.length?1:0;})().catch(e=>{console.error(e&&e.stack||e);process.exitCode=1;});
