"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto");
const root=__dirname,checks=[];
const check=(name,passed,detail,severity="Critical")=>checks.push({name,passed:Boolean(passed),detail,severity});
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");
const norm=s=>String(s||"").split("#")[0].split("?")[0].replace(/^\.\//,"");
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o={};Object.keys(v).sort().forEach(k=>o[k]=stable(v[k]));return o;}return v;}
const manifest=JSON.parse(fs.readFileSync(path.join(root,"00_script_manifest.json"),"utf8"));
const projectInfo=JSON.parse(fs.readFileSync(path.join(root,"project_info.json"),"utf8"));
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const p1Files=["19_trust_evidence_version_manifest.js","19_trust_evidence_core.js","19_trust_evidence_external010_adapter.js","19_trust_evidence_evaluation_context.js","19_trust_evidence_lineage.js","19_trust_evidence_evaluation_candidate.js","19_trust_evidence_traceability.js","19_trust_evidence_phase1_validation.js","19_trust_evidence_phase1_android_validation.js"];
const p1Hashes={
"19_trust_evidence_version_manifest.js":"10898623acf40e6f4e0281479ffc49c5bb5ab9ce4dec072e7efbed87f894a1bc","19_trust_evidence_core.js":"5ff77d1cf7c8de9a6448dfe4eb57f973904c3f25ea45a28f2216a93ab770ac64","19_trust_evidence_external010_adapter.js":"c4189beae60b4927167ebf48c0ddb4829b0aaa3b831f2088cec79eea6e84523b","19_trust_evidence_evaluation_context.js":"013366c99b74ed230a8c4887563d61136b60af42e591b62ae66eebf1132bbdde","19_trust_evidence_lineage.js":"174724e6b5919d53cd578dbee5204e89a47e29994e9d4378fd0fce7af70b0381","19_trust_evidence_evaluation_candidate.js":"ed712a0aa92930fe73031f842d7711db9eb5d2d514ed09759dbe3b14d23b1cf3","19_trust_evidence_traceability.js":"67bdead2a46535e178427a58dd3c5c0cee7eb09435f5e2590e9b7b03559c383a","19_trust_evidence_phase1_validation.js":"4a1ab2cee6936434e78419f3c228193b4582ce8761e0f57f7c894b5c2ea9949b","19_trust_evidence_phase1_android_validation.js":"0ddbc0481241e54b1116ece571324cbee5a86a62df267b6ab79b8478604e82b1"};
const p2Unchanged={
"19_trust_evidence_dimensions.js":"2cd6aeeadfd4ae379814df6156279f8bb55192546d7c3dbd92a20f0acbb9c487",
"19_trust_evidence_independence.js":"b636883052277cb628c9e09ecdfb84c3f807900ff0489156cead83b85ff596f4",
"19_trust_evidence_reliability_profile.js":"0f5f2e848eeb78fedb2e3366d51602642c177a30cd3913cd025b75159e6ff98f",
"19_trust_evidence_reliability_revision.js":"5111d0cb2c0b300c7fbeb794fc609c483e8b5eb41d60a722189d40ebc7a720f4",
"19_trust_evidence_phase2_traceability.js":"ee6a877e9e9e02a0358686d9eacc02f864d1bdeab23fca8e31ba674515dc7a83",
"19_trust_evidence_phase2_validation.js":"62f641d60ec18104e624f752de24ce9f69372cc99fe29867386cf145610f9c6f"};
const p2Files=["19_trust_evidence_phase2_version_manifest.js",...Object.keys(p2Unchanged),"19_trust_evidence_phase2_android_validation.js"];
let verified=0,cache=0,missing=[];
for(const src of manifest.scripts){const f=norm(src),p=path.join(root,f),h=manifest.hashes&&manifest.hashes[f];if(!fs.existsSync(p)||!h){missing.push(f);continue;}const b=fs.readFileSync(p),actual=sha(b);if(actual===h.sha256&&b.length===h.byteSize)verified++;const m=String(src).match(/[?&]h=([a-f0-9]+)/i);if(m&&m[1]===h.cacheKey&&h.cacheKey===h.sha256.slice(0,12))cache++;}
check("All 479 manifest script hashes and byte sizes match",verified===manifest.scripts.length&&manifest.scripts.length===479&&missing.length===0,{verified,total:manifest.scripts.length,missing});
check("All manifest cache keys match",cache===manifest.scripts.length,{verified:cache,total:manifest.scripts.length});
const payload=manifest.scripts.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");
check("Script Set Hash verifies",sha(Buffer.from(payload))===manifest.scriptSetHash,{computed:sha(Buffer.from(payload)),stored:manifest.scriptSetHash});
const cp=JSON.parse(JSON.stringify(manifest));delete cp.manifestHash;delete cp.updatedAt;const mh=sha(Buffer.from(JSON.stringify(stable(cp))));
check("Manifest Hash verifies",mh===manifest.manifestHash,{computed:mh,stored:manifest.manifestHash});
const meta=(index.match(/<meta name="ai-pro-script-manifest-hash" content="([a-f0-9]{64})"/)||[])[1]||"";
check("index manifest hash marker matches",meta===manifest.manifestHash,{index:meta,manifest:manifest.manifestHash});
const seq=[];const re=/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi;let mm;while((mm=re.exec(index)))if(/^\.\//.test(mm[1])&&/\.js(?:\?|$)/i.test(mm[1]))seq.push(mm[1]);
check("index script sequence matches manifest",JSON.stringify(seq)===JSON.stringify(manifest.scripts),{indexCount:seq.length,manifestCount:manifest.scripts.length});
check("Frozen Phase 1 script bytes remain unchanged",p1Files.every(f=>manifest.hashes[f]&&manifest.hashes[f].sha256===p1Hashes[f]),p1Files.map(f=>({file:f,expected:p1Hashes[f],actual:manifest.hashes[f]&&manifest.hashes[f].sha256})));
check("Phase 2 v0.2.0 core logic files remain unchanged",Object.entries(p2Unchanged).every(([f,h])=>manifest.hashes[f]&&manifest.hashes[f].sha256===h),Object.entries(p2Unchanged).map(([f,h])=>({file:f,expected:h,actual:manifest.hashes[f]&&manifest.hashes[f].sha256})));
check("Phase 2 Android validator is present before 99_init",manifest.scripts.findIndex(x=>norm(x)==="19_trust_evidence_phase2_android_validation.js")>manifest.scripts.findIndex(x=>norm(x)==="19_trust_evidence_phase2_validation.js")&&manifest.scripts.findIndex(x=>norm(x)==="19_trust_evidence_phase2_android_validation.js")<manifest.scripts.findIndex(x=>norm(x)==="99_init.js"),{androidPos:manifest.scripts.findIndex(x=>norm(x)==="19_trust_evidence_phase2_android_validation.js"),initPos:manifest.scripts.findIndex(x=>norm(x)==="99_init.js")});
const parent=manifest.scripts.filter(src=>!/^19_trust_evidence_/.test(norm(src)));const parentPayload=parent.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");
check("Canonical 0023 parent script set remains byte/order identical",parent.length===462&&sha(Buffer.from(parentPayload))==="d3121eb588b7c7b332cb86ef66f82fe2f2ecd77bd1be029143ff578f2d0514a3",{parentScriptCount:parent.length,parentScriptSetHash:sha(Buffer.from(parentPayload))});
check("project_info identity matches v0.2.1 Android validation candidate",projectInfo.scriptManifestCount===479&&projectInfo.scriptManifestHash===manifest.manifestHash&&projectInfo.scriptSetHash===manifest.scriptSetHash&&projectInfo.external020Phase2Version==="0.2.1"&&projectInfo.external020Phase2AndroidValidationImplemented===true&&projectInfo.releaseAllowed===false,{count:projectInfo.scriptManifestCount,phase2Version:projectInfo.external020Phase2Version,status:projectInfo.external020Phase2Status,releaseAllowed:projectInfo.releaseAllowed});
const saved=new Set(projectInfo.savedFiles||[]);check("project_info savedFiles covers every manifest script",manifest.scripts.every(src=>saved.has(norm(src))),{savedCount:saved.size,manifestCount:manifest.scripts.length});

// Runtime fixture
Object.defineProperty(global,"navigator",{value:{userAgent:"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 Chrome/152.0.0.0 Mobile Safari/537.36"},configurable:true});
global.document={};global.IDE170Intelligence={};global.IDE180KnowledgeNavigator={};
const sourcePkg={contractId:"EXTERNAL-010-CONTRACT-RELIABILITY-INPUT-PACKAGE",operationalSignals:[{reliabilitySignalId:"RS-P2-V021",sourceId:"SRC-PHASE2",requestCount:10,successCount:9,timeoutCount:1,schemaFailureCount:0,freshnessState:"FRESH"}],evidenceQualitySignals:[{qualitySignalId:"QS-P2-V021-A",evidenceId:"EVIDENCE-P2-A",sourceId:"SRC-PHASE2",sourceRole:"PRIMARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true},{qualitySignalId:"QS-P2-V021-B",evidenceId:"EVIDENCE-P2-B",sourceId:"SRC-PHASE2",sourceRole:"SECONDARY",contentPresent:true,schemaValid:true,timestampPresent:true,sourceIdentityResolved:true,contentHashVerified:true,provenanceComplete:true,temporalMetadataComplete:true}],contradictionCandidates:[{candidateId:"CONTRA-P2-V021",candidateType:"CONTRADICTION",subjectRef:"SRC-PHASE2",evidenceIds:["EVIDENCE-P2-A","EVIDENCE-P2-B"],independenceVerified:false,conflictWinner:null,truthConfirmed:false,automaticResolutionPerformed:false,finalReliabilityAuthority:"EXTERNAL-020"}],confirmationCandidates:[{candidateId:"CONF-P2-V021",candidateType:"CONFIRMATION",subjectRef:"SRC-PHASE2",evidenceIds:["EVIDENCE-P2-A","EVIDENCE-P2-B"],independenceVerified:false,conflictWinner:null,truthConfirmed:false,automaticResolutionPerformed:false,duplicateEqualsIndependentConfirmation:false,finalReliabilityAuthority:"EXTERNAL-020"}],finalReliabilityAuthority:"EXTERNAL-020",generatedAt:new Date().toISOString(),contractValid:true};
global.EXTERNAL010ExternalIntelligence={getExternalIntelligenceReliabilityInputPackage:()=>JSON.parse(JSON.stringify(sourcePkg))};
for(const f of p1Files.concat(p2Files))require(path.join(root,f));
check("Phase 2 Version Manifest reports v0.2.1",global.EXTERNAL020Phase2VersionManifest&&global.EXTERNAL020Phase2VersionManifest.version==="0.2.1"&&global.EXTERNAL020Phase2VersionManifest.status==="IMPLEMENTATION_PHASE2_ANDROID_VALIDATION_CANDIDATE",global.EXTERNAL020Phase2VersionManifest);
const android=global.runExternal020Phase2AndroidValidation();check("Phase 2 functional prerequisite and Android validation fixture pass",android&&android.failed===0&&android.criticalFailed===0&&android.phase2AndroidRealDeviceComplete===true&&android.phase2ProjectOwnerGateReady===true&&android.checks&&android.checks[0]&&android.checks[0].passed===true&&android.checks[0].detail&&android.checks[0].detail.passed===21,android);
check("Android validation remains non-approving and side-effect free",android&&android.releaseAllowed===false&&android.projectOwnerAcceptanceRequired===true&&android.validationIsApproval===false&&android.canonicalMutationPerformed===false&&android.externalTransmissionPerformed===false&&android.paidApiExecutionPerformed===false,android);
const coverage=global.EXTERNAL020TrustEvidence.getExternal020Decision001Coverage();check("Decision 001 remains 16/18",coverage.decisionRequirementsFullyImplemented===16&&coverage.allDecisionRequirementsComplete===false&&coverage.remainingRequirementIds.includes("REQ-020-008")&&coverage.remainingRequirementIds.includes("REQ-020-015"),coverage);
const failed=checks.filter(c=>!c.passed),criticalFailed=failed.filter(c=>c.severity==="Critical").length;const report={id:"EXTERNAL-020-PHASE2-V0.2.1-STATIC-FUNCTIONAL-ANDROID-VALIDATION",decisionId:"EXTERNAL-020-DECISION-001",candidateVersion:"0.2.1",passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed,scriptCount:manifest.scripts.length,manifestHash:manifest.manifestHash,scriptSetHash:manifest.scriptSetHash,frozenPhase1SourceVerified:true,phase2CoreLogicUnchanged:true,canonical0023ParentVerified:true,decision001RequirementsComplete:16,decision001RequirementsTotal:18,releaseAllowed:false,validationIsApproval:false,canonicalMutationPerformed:false,externalTransmissionPerformed:false,paidApiExecutionPerformed:false,checks};console.log(JSON.stringify(report,null,2));process.exitCode=failed.length?1:0;
