"use strict";
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),cp=require("node:child_process");
const root=__dirname,checks=[];
const check=(name,passed,detail,severity="Critical")=>checks.push({name,passed:Boolean(passed),detail,severity});
const sha=b=>crypto.createHash("sha256").update(b).digest("hex");
const norm=s=>String(s||"").split("#")[0].split("?")[0].replace(/^\.\//,"");
function stable(v){if(Array.isArray(v))return v.map(stable);if(v&&typeof v==="object"){const o={};Object.keys(v).sort().forEach(k=>o[k]=stable(v[k]));return o;}return v;}
const manifest=JSON.parse(fs.readFileSync(path.join(root,"00_script_manifest.json"),"utf8"));
const projectInfo=JSON.parse(fs.readFileSync(path.join(root,"project_info.json"),"utf8"));
const index=fs.readFileSync(path.join(root,"index.html"),"utf8");
const phase1Frozen={
"18_self_development_version_manifest.js":"85212e46389a1bf1c9893bfaa49e9f4dc93cb805bb83554689483298cf325022",
"18_self_development_core.js":"1fefbfc970a5e3f13bce1bb9543855e3a55319d777298690b1695c3163ed63a3",
"18_self_development_baseline_identity.js":"576aa7144410da8db0577aedca49be28252a7cf39ad6108c798b5828600db829",
"18_self_development_adapter.js":"dff9273d523476ddbf37badc697dec0f59b65320acc81e2ccad2145421f0e03d",
"18_self_development_candidate.js":"06f466cd13aaadd4229729269d5b3b950839d1fb6e35b8741f78b37d3c594733",
"18_self_development_traceability.js":"754a62f36c5eee2c15f924a8d823d324a5e2a97bc44fcbca5d29489db571a913",
"18_self_development_dashboard.js":"7758b20bd1b13dc692a392e690b383099ab5ea7b00f65932112fba1d14641afb",
"18_self_development_phase1_validation.js":"1fa2cd44bb5f58781000ec848e884a741dd2c6764beabc0359b13325dc36d381"};
const phase2Frozen={
"18_self_development_phase2_version_manifest.js":"9b0258a884ff594a206a0082d8c9f79fc3214fb1329a5f7cc9ef6dab7dcfec31",
"18_self_development_phase2_persistence.js":"0e3345c19b5f509c39e5e0e1cc2945137ba58eefb889b717a674bfa2d47214e2",
"18_self_development_phase2_repository_inspection.js":"36d3978a14ead7eb5102c52dcf4c7de4f1fa9c7aa4679821c377820f02b90dc6",
"18_self_development_phase2_evidence_integrity.js":"1410b7dc790d42fb294ee9d6ded37c03d4f9346f173f30f5b129b61213c350cb",
"18_self_development_phase2_candidate_detection.js":"193792deb51be6db9e907d8776437be12c1489ba3042d1d05a444d83a9f90644",
"18_self_development_phase2_validation_contract.js":"38e857798a4d90e227a6efa3c2d98c6603af84d751ef5382e7b4fb1eaaaaa3b9",
"18_self_development_phase2_external_ai_readiness.js":"37ceccf085f2ef9e7afbc21f499f8e98ce181e61ab3e53f7b1ebe10d7200c14f",
"18_self_development_phase2_traceability.js":"df11be6da8894ad5ed700ab1bd3d768184f32e34dd4c91a8d8d9be17f5aa9cff",
"18_self_development_phase2_dashboard.js":"c285b011134d76876d51e14eb6b5b08664eeb7fb61beca869eeb50dacfbb06a2",
"18_self_development_phase2_validation.js":"e93ef6865fa8ebf0ec7f867729a429963f8986cbf22470dc3f496cfe821ed64e"};
const phase3Frozen={
"18_self_development_phase3_version_manifest.js":"978ec2f927ed2d4b8af5bca9bd5b8b52e5a6b0ccf03641433f619f40a22a68ef",
"18_self_development_phase3_approval_policy.js":"a6e8d143c991f7870076302856836775c80cb06e526334a9f9815a7f6f277b88",
"18_self_development_phase3_approval_bridge.js":"427515981fa9b33f358fa9ffddfc14f0e08914a889d45f324d40779bb5b6461d",
"18_self_development_phase3_patch_fixture.js":"9447d79d5facd66947cb46eb42f520525b1a529e8f4f87a134714a5d4041e592",
"18_self_development_phase3_patch_adapter.js":"7a04db50900b9683486dff08bfaacd11ba6cde3cba85d9a35ee8a6f036646ab8",
"18_self_development_phase3_independent_validation.js":"b5131110c5f02c3b451520b4973b5d241c030583f368cd0835035672858e0a7e",
"18_self_development_phase3_traceability.js":"f646a9df3c6741867ee98fe55b94c5701a1616f962dca8df30d95e19d2747340",
"18_self_development_phase3_dashboard.js":"826e5fd1716b7571496dc6f966292583c3d00dabab23bb41e511dc97e12f8259",
"18_self_development_phase3_validation.js":"27d4c1bbfb78e5ca4811291e50f58ca2ae20e2a4581b856a754f82bc6c21a478"};
const p1=Object.keys(phase1Frozen),p2=Object.keys(phase2Frozen),p3=Object.keys(phase3Frozen);
const p4=["18_self_development_phase4_version_manifest.js","18_self_development_phase4_adoption_policy.js","18_self_development_phase4_repository_bridge.js","18_self_development_phase4_reflection_preflight.js","18_self_development_phase4_recovery_contract.js","18_self_development_phase4_audit_lineage.js","18_self_development_phase4_traceability.js","18_self_development_phase4_dashboard.js","18_self_development_phase4_validation.js"];
let hp=0,cpk=0,missing=[];
for(const src of manifest.scripts){const f=norm(src),fp=path.join(root,f),h=manifest.hashes&&manifest.hashes[f];if(!fs.existsSync(fp)||!h){missing.push(f);continue;}const b=fs.readFileSync(fp),a=sha(b);if(a===h.sha256&&b.length===h.byteSize)hp++;const m=String(src).match(/[?&]h=([a-f0-9]+)/i);if(m&&m[1]===h.cacheKey&&h.cacheKey===h.sha256.slice(0,12))cpk++;}
check("All manifest script hashes and byte sizes match",hp===manifest.scripts.length&&missing.length===0,{verified:hp,total:manifest.scripts.length,missing});
check("All manifest cache keys match",cpk===manifest.scripts.length,{verified:cpk,total:manifest.scripts.length});
const setPayload=manifest.scripts.map(src=>{const f=norm(src);return `${f}:${manifest.hashes[f].sha256}`;}).join("\n");const setHash=sha(Buffer.from(setPayload));check("Script Set Hash verifies",setHash===manifest.scriptSetHash,{computed:setHash,stored:manifest.scriptSetHash});
const copy=JSON.parse(JSON.stringify(manifest));delete copy.manifestHash;delete copy.updatedAt;const mh=sha(Buffer.from(JSON.stringify(stable(copy))));check("Manifest Hash verifies",mh===manifest.manifestHash,{computed:mh,stored:manifest.manifestHash});
const meta=(index.match(/<meta name="ai-pro-script-manifest-hash" content="([a-f0-9]{64})"/)||[])[1]||"";check("index manifest hash marker matches",meta===manifest.manifestHash,{index:meta,manifest:manifest.manifestHash});
const idx=[];const re=/<script\s+[^>]*src=["']([^"']+)["'][^>]*><\/script>/gi;let mm;while((mm=re.exec(index)))if(/^\.\//.test(mm[1])&&/\.js(?:\?|$)/i.test(mm[1]))idx.push(mm[1]);check("index script sequence matches manifest",JSON.stringify(idx)===JSON.stringify(manifest.scripts),{indexCount:idx.length,manifestCount:manifest.scripts.length});
check("All Decision 058 Phase 4 scripts are present",p4.every(f=>manifest.scripts.some(src=>norm(src)===f)),p4);
const p4pos=p4.map(f=>manifest.scripts.findIndex(src=>norm(src)===f)),p3end=manifest.scripts.findIndex(src=>norm(src)==="18_self_development_phase3_validation.js"),init=manifest.scripts.findIndex(src=>norm(src)==="99_init.js");check("Phase 4 scripts load additively after frozen Phase 3 and before 99_init",p4pos.every((p,n)=>p>=0&&(n===0?p===p3end+1:p===p4pos[n-1]+1))&&p4pos[p4pos.length-1]<init,{phase3End:p3end,positions:p4pos,initPos:init});
for(const [label,map] of [["Phase 1",phase1Frozen],["Phase 2",phase2Frozen],["Phase 3",phase3Frozen]]){const rows=Object.keys(map).map(f=>({file:f,expected:map[f],actual:sha(fs.readFileSync(path.join(root,f)))}));check(`${label} Accepted/Frozen source remains byte-identical`,rows.every(x=>x.expected===x.actual),rows);}
check("project_info identity matches current manifest",projectInfo.scriptManifestVersion===manifest.version&&projectInfo.applicationReleaseVersion===manifest.applicationReleaseVersion&&Number(projectInfo.scriptManifestCount)===manifest.scripts.length&&projectInfo.scriptManifestHash===manifest.manifestHash&&projectInfo.scriptSetHash===manifest.scriptSetHash,{projectInfo:{count:projectInfo.scriptManifestCount,manifestHash:projectInfo.scriptManifestHash,scriptSetHash:projectInfo.scriptSetHash},manifest:{count:manifest.scripts.length,manifestHash:manifest.manifestHash,scriptSetHash:manifest.scriptSetHash}});
const saved=new Set(projectInfo.savedFiles||[]);check("project_info savedFiles covers every manifest script",manifest.scripts.every(src=>saved.has(norm(src))),{savedCount:saved.size,manifestCount:manifest.scripts.length});
check("Phase 4 candidate metadata preserves accepted parents and no release",projectInfo.releaseStatus==="SELF_DEVELOPMENT_058_PHASE4_CANDIDATE"&&projectInfo.releaseAllowed===false&&projectInfo.projectOwnerRevalidationRequired===true&&projectInfo.decision058Phase1Status==="PROJECT_OWNER_ACCEPTED_FROZEN"&&projectInfo.decision058Phase2Status==="PROJECT_OWNER_ACCEPTED_FROZEN"&&projectInfo.decision058Phase3Status==="PROJECT_OWNER_ACCEPTED_FROZEN"&&projectInfo.decision058CanonicalMutationImplemented===false&&projectInfo.decision058ValidationIsApproval===false,{releaseStatus:projectInfo.releaseStatus,p1:projectInfo.decision058Phase1Status,p2:projectInfo.decision058Phase2Status,p3:projectInfo.decision058Phase3Status,canonicalMutation:projectInfo.decision058CanonicalMutationImplemented});
const pol=fs.readFileSync(path.join(root,"18_self_development_phase4_adoption_policy.js"),"utf8");check("Future REPOSITORY-010 relaxation map names policy keys and engine refs",/tokenTtlMinutes/.test(pol)&&/tokenConsumptionMode/.test(pol)&&/13_local_first_repository_acceptance_token\.js/.test(pol)&&/13_local_first_repository_controlled_transaction\.js/.test(pol)&&/Policy change alone never bypasses REPOSITORY-010 enforcement/.test(pol),"relaxation-map-present");
const accept=fs.readFileSync(path.join(root,"13_local_first_repository_acceptance_token.js"),"utf8"),tx=fs.readFileSync(path.join(root,"13_local_first_repository_controlled_transaction.js"),"utf8"),closure=fs.readFileSync(path.join(root,"13_local_first_repository_reflection_closure.js"),"utf8"),promotion=fs.readFileSync(path.join(root,"13_local_first_repository_baseline_promotion.js"),"utf8");
check("REPOSITORY-010 current acceptance engine matches 15min / Project Owner / one-time map",/TOKEN_TTL_MS\s*=\s*15\s*\*\s*60\s*\*\s*1000/.test(accept)&&/ACCEPTED_BY\s*=\s*"Project Owner"/.test(accept)&&/tokenOneTimeUseRequired:\s*true/.test(accept),"Project Owner / 15min / one-time enforced");
check("REPOSITORY-010 controlled transaction enforces backup / token consume / rollback mechanics",/function createBackupsAndJournal/.test(tx)&&/function consumeToken/.test(tx)&&/function rollbackTransaction/.test(tx)&&/await createBackupsAndJournal\(transaction, context\)/.test(tx)&&/await consumeToken\(transaction, context\)/.test(tx),"controlled transaction safety mechanics present");
check("REPOSITORY-010 exposes V5 closure and explicit non-automatic baseline promotion",/function deriveReflectionIntegrityClosure/.test(closure)&&/function promoteCanonicalBaseline/.test(promotion)&&/projectOwnerExplicitActionRequired:\s*true/.test(promotion)&&/automaticPromotionAllowed:\s*false/.test(promotion),"V5 + explicit promotion boundary present");
const openaiHashes={"17_external_intelligence_openai_provider_integration.js":"0107b4838b2bef35daa8e700a4be47766738948f351620903a20323dc8dcb891","17_external_intelligence_openai_provider_ui.js":"1ee0d94d7d5d3786ee13a68989acdb74b3813dd7d9482fbd8d153f555cebdd87"};const of=Object.keys(openaiHashes).map(f=>({file:f,expected:openaiHashes[f],actual:sha(fs.readFileSync(path.join(root,f)))}));check("OpenAI v0.3.11 provider source remains byte-identical",of.every(x=>x.expected===x.actual),of);
let oa=null;try{oa=JSON.parse(cp.execFileSync(process.execPath,[path.join(root,"validate_openai_final_validation_gate_v0311.cjs")],{encoding:"utf8"}));}catch(e){try{oa=JSON.parse(String(e.stdout||""));}catch(_){oa={failed:1,error:e.message};}}check("OpenAI v0.3.11 Final Validation Gate remains 23/23 PASS",oa&&oa.passed===23&&oa.failed===0&&oa.total===23&&oa.health===100&&oa.criticalFailed===0,{passed:oa&&oa.passed,failed:oa&&oa.failed,total:oa&&oa.total,health:oa&&oa.health,criticalFailed:oa&&oa.criticalFailed});
const storage=new Map();global.localStorage={getItem:k=>storage.has(k)?storage.get(k):null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};
global.IDE140DevelopmentAnalytics={getDevelopmentAnalyticsStatus:()=>({id:"IDE-140",status:"Completed"})};global.IDE170Intelligence={getStatus:()=>({componentId:"IDE-170",status:"Ready"}),getRepositorySnapshotStatus:()=>({status:"Ready",snapshotCount:0})};
global.IDE190DevelopmentAutomation={getStatus:()=>({componentId:"IDE-190",status:"Ready"}),getSafetyStatus:()=>({directRepositoryMutationAllowed:false}),validateAutomationApproval:()=>({valid:false,status:"Invalid",approval:null,approvalState:null,reasons:["Approval Not Found"]}),getAutomationApprovalStatus:()=>({approval:null,approvalState:null})};
global.IDE150AutoRefactoring={generateSelfDevelopmentPatchCandidate:()=>({generated:true,verified:false,reason:"validation-fixture-adapter"})};
global.REPOSITORY010LocalFirstRepository={getStatus:()=>({componentId:"REPOSITORY-010",status:"Ready"}),getSafetyStatus:()=>({directRepositoryMutationAllowed:false,uncontrolledPersistentMutationAllowed:false}),issueManualAcceptanceToken:async()=>{throw new Error("must-not-be-called")},validateAcceptanceToken:async()=>({valid:false}),getAcceptanceTokenStatus:()=>({token:null}),executeControlledTransactionTrial:async()=>{throw new Error("must-not-be-called")},listPendingControlledTransactionRecoveries:async()=>[],recoverControlledTransactionTrial:async()=>{throw new Error("must-not-be-called")},getControlledTransactionStatus:()=>({status:"Ready"}),deriveReflectionIntegrityClosure:async()=>({ok:false}),createBaselinePromotionCandidate:async()=>({ok:false}),promoteCanonicalBaseline:async()=>{throw new Error("must-not-be-called")},getBaselinePromotionStatus:()=>({status:"Ready"})};
global.EXTERNAL010ExternalIntelligence={getExternalIntelligenceFoundationState:()=>({componentId:"EXTERNAL-010",version:"1.20.1",initialized:true,safety:{directRepositoryMutationAllowed:false}}),getOpenAIFinalValidation:()=>({passed:true,state:"FINAL_VALIDATED",readiness:"OPENAI_API_INTEGRATION_READY",providerNetworkCallPerformed:false})};global.getExternalIntelligenceFoundationState=global.EXTERNAL010ExternalIntelligence.getExternalIntelligenceFoundationState;
global.registerDevelopmentDashboardModule=()=>({registered:true});global.registerDevelopmentStatus=()=>({registered:true});global.registerIdeComponent=()=>({registered:true});global.getProjectFileCategory=f=>f.endsWith(".js")?"js":f.endsWith(".json")?"json":f.endsWith(".html")?"html":f.endsWith(".css")?"css":"other";
const inspect=[...p1,...p2,...p3,...p4,"01_project_manager.js","17_external_intelligence_core.js","17_external_intelligence_openai_provider_integration.js"].map(f=>({path:f,fileName:f,code:fs.readFileSync(path.join(root,f),"utf8")}));global.getProjectFiles=()=>inspect.map(x=>({...x}));
for(const f of p1)require(path.join(root,f));for(const f of p2)require(path.join(root,f));for(const f of p3)require(path.join(root,f));for(const f of p4)require(path.join(root,f));
global.__SELFDEV058_PHASE3_VALIDATION_MANIFEST=manifest;global.__SELFDEV058_PHASE3_VALIDATION_PROJECT_INFO=projectInfo;
(async()=>{
 const p2r=await global.runSelfDevelopment058Phase2Validation({manifest,projectInfo});check("Phase 2 Accepted/Frozen runtime regression remains 18/18 PASS",p2r&&p2r.passed===18&&p2r.failed===0&&p2r.total===18&&p2r.health===100&&p2r.criticalFailed===0,{passed:p2r&&p2r.passed,failed:p2r&&p2r.failed,total:p2r&&p2r.total,health:p2r&&p2r.health,criticalFailed:p2r&&p2r.criticalFailed});
 const p3r=await global.runSelfDevelopment058Phase3Validation();check("Phase 3 Accepted/Frozen runtime regression remains 16/16 PASS",p3r&&p3r.passed===16&&p3r.failed===0&&p3r.total===16&&p3r.health===100&&p3r.criticalFailed===0,{passed:p3r&&p3r.passed,failed:p3r&&p3r.failed,total:p3r&&p3r.total,health:p3r&&p3r.health,criticalFailed:p3r&&p3r.criticalFailed});
 const r=await global.runSelfDevelopment058Phase4Validation();check("Phase 4 runtime validation passes",r&&r.passed===17&&r.failed===0&&r.total===17&&r.health===100&&r.criticalFailed===0&&r.phase4ImplementationComplete===true&&r.phase4TechnicalGateReady===true,{passed:r&&r.passed,failed:r&&r.failed,total:r&&r.total,health:r&&r.health,criticalFailed:r&&r.criticalFailed});
 check("Phase 4 validation performs no token issue / reflection / rollback / promotion / mutation",r&&r.repository010AcceptanceTokenIssued===false&&r.controlledTransactionExecuted===false&&r.persistentReflectionPerformed===false&&r.rollbackExecuted===false&&r.baselinePromotionPerformed===false&&r.canonicalMutationPerformed===false&&r.validationIsApproval===false,{token:r&&r.repository010AcceptanceTokenIssued,transaction:r&&r.controlledTransactionExecuted,reflection:r&&r.persistentReflectionPerformed,rollback:r&&r.rollbackExecuted,promotion:r&&r.baselinePromotionPerformed,mutation:r&&r.canonicalMutationPerformed});
 const coverage=global.SELFDEVELOPMENT058Environment.getSelfDevelopmentPhase4Coverage();check("18 Decision requirements remain tracked without false completion",coverage.totalDecisionRequirements===18&&coverage.phase4ScopeComplete===true&&coverage.fullyImplementedDecisionRequirements===14&&coverage.allDecisionRequirementsComplete===false&&coverage.falseFullDecisionCompletionClaimed===false,coverage);
 const guide=global.SELFDEVELOPMENT058Environment.getSelfDevelopmentPhase4RelaxationGuide();check("Phase 4 relaxation guide is discoverable from one Decision-058 entry point",guide.file==="18_self_development_phase4_adoption_policy.js"&&guide.engineMigrationRequired===true&&guide.changeEntryPoints.includes("tokenTtlMinutes")&&guide.changeEntryPoints.includes("tokenConsumptionMode"),guide);
 const h=global.SELFDEVELOPMENT058Phase4VersionManifest.hardBoundaries;check("Phase 4 hard boundaries are fixed",h.selfApprovalAllowed===false&&h.acceptanceTokenEqualsMutationAuthority===false&&h.canonicalRepositoryMutationAllowed===false&&h.tokenIssueAllowedInPhase4Validation===false&&h.controlledTransactionExecutionAllowedInPhase4Validation===false&&h.persistentReflectionAllowedInPhase4===false&&h.actualRollbackExecutionAllowedInPhase4Validation===false&&h.baselinePromotionAllowedInPhase4===false,h);
 const failed=checks.filter(x=>!x.passed),criticalFailed=failed.filter(x=>x.severity==="Critical").length;const report={id:"SELF-DEVELOPMENT-058-PHASE4-STATIC-FUNCTIONAL-VALIDATION",decisionId:"EXTERNAL-010-DECISION-058",candidateVersion:"0.4.0",passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed,scriptCount:manifest.scripts.length,manifestHash:manifest.manifestHash,scriptSetHash:manifest.scriptSetHash,phase1FrozenSourceVerified:true,phase2FrozenSourceVerified:true,phase3FrozenSourceVerified:true,releaseAllowed:false,validationIsApproval:false,adoptionAuthorizationGranted:false,repository010AcceptanceTokenIssued:false,controlledTransactionExecuted:false,persistentReflectionPerformed:false,rollbackExecuted:false,baselinePromotionPerformed:false,canonicalMutationPerformed:false,checks};console.log(JSON.stringify(report,null,2));process.exitCode=failed.length?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
