"use strict";
const fs=require("node:fs"),vm=require("node:vm"),path=require("node:path");
const checks=[];const check=(name,passed,detail)=>checks.push({name,passed:Boolean(passed),detail});
function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function stable(v){if(v===null||typeof v!=="object")return JSON.stringify(v);if(Array.isArray(v))return "["+v.map(stable).join(",")+"]";return "{"+Object.keys(v).sort().map(k=>JSON.stringify(k)+":"+stable(v[k])).join(",")+"}";}
let seq=0,commitCalls=0,auditCalls=0,providerCalls=0;
let source={sourceId:"SOURCE-OPENAI",sourceName:"OpenAI Responses API",sourceType:"AI_SERVICE",provider:"OPENAI",category:"AI_PROVIDER",accessMode:"LOCAL_GATEWAY",adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",authenticationMode:"BEARER_TOKEN",secretReferenceId:"SECRET-OPENAI-LEGACY",allowedOperations:["INTERNAL_ANALYSIS"],allowedMethods:["POST"],pricingMode:"USAGE_BASED",costCurrency:"USD",enabled:true,lifecycleState:"ACTIVE",version:3,identityState:"VERIFIED",reliabilityState:"UNASSESSED",authorityGranted:false,paidActivationPolicy:{authorityAction:"ACTIVATE_GOVERNED_PAID_SOURCE",budgetIds:["BUDGET-OPENAI"],perRequestHardCapUsd:0.01,currency:"USD",noPerRequestHumanApprovalInsideApprovedScope:true,automaticBudgetExpansionAllowed:false},realApiTestValidation:{passed:true,requestId:"REQ-REAL-1",responseId:"RESP-1",providerResponseId:"resp_test",providerRequestId:"req_test",modelRequested:"gpt-5.6-luna",modelReported:"gpt-5.6-luna",budgetIds:["BUDGET-OPENAI"],estimatedMaximumCostUsd:0.0000876,actualUsage:{AI_TOKEN_USAGE:16,FINANCIAL_COST:0.0000082},outputMatchedExpected:true,fixedTestInputOnly:true,projectDataTransmitted:false,store:false,toolsEnabled:false,streamingEnabled:false,retryMaxAttempts:1,secretValueReturned:false,completedAt:new Date().toISOString()},immutable:true};
const op={operationContractId:"EXTERNAL-010-OP-OPENAI-INTERNAL-ANALYSIS",sourceId:"SOURCE-OPENAI",operationId:"INTERNAL_ANALYSIS",adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",method:"POST",endpoint:{exactUrl:"https://api.openai.com/v1/responses",canonicalHost:"api.openai.com",endpointReference:"OPENAI-RESPONSES-V1"},bodyPolicy:{mode:"JSON",fixedFields:{store:false},allowUnknown:false},retryPolicy:{maxAttempts:1},enabled:true};
let budget={budgetId:"BUDGET-OPENAI",scopeType:"SOURCE",scopeId:"SOURCE-OPENAI",currency:"USD",limits:{FINANCIAL_COST:{softLimit:3,hardLimit:5}},consumed:{FINANCIAL_COST:0.0000082},state:"ACTIVE",version:3};
const policy={usagePolicyId:"POLICY-OPENAI",sourceId:"SOURCE-OPENAI",status:"ACTIVE",rights:{INTERNAL_ANALYSIS:{state:"ALLOWED_WITH_CONDITIONS",conditions:["TEST"],confidence:"MEDIUM"}}};
let usageRecords=[{usageRecordId:"USAGE-1",operationId:"INTERNAL_ANALYSIS",budgetIds:["BUDGET-OPENAI"],sourceId:"SOURCE-OPENAI",estimatedUsage:{FINANCIAL_COST:0.0000876,REQUEST_COUNT:1,AI_TOKEN_USAGE:118},actualUsage:{FINANCIAL_COST:0.0000082,REQUEST_COUNT:1,AI_TOKEN_USAGE:16},reconciled:true,reconciliationState:"PROVIDER_USAGE_RECONCILED",createdAt:new Date().toISOString(),immutable:true}];
let gateway={baseUrl:"http://127.0.0.1:43110",healthState:"READY",session:{gatewaySessionId:"S1",state:"ACTIVE",expiresAt:new Date(Date.now()+60000).toISOString()},sessionTokenPresentInMemory:true,sessionTokenPersisted:false,acquisitionBridgeEnabled:true,lastError:null,lastCheckedAt:new Date().toISOString()};
const internal={state:{},isPlainObject:v=>Boolean(v&&typeof v==='object'&&!Array.isArray(v)),text:(v,f='')=>String(v==null?f:v),clone,stableStringify:stable,nowIso:()=>new Date().toISOString(),unique:v=>Array.from(new Set(Array.isArray(v)?v:[])),deepFreeze:v=>v,nextId:p=>`${p}-TEST-${++seq}`,buildResult:(ok,code,status,data,error)=>({ok,code,status,data:data==null?null:data,error:error||null}),commitExternalIntelligenceSourceVersion:(id,patch)=>{if(id!=="SOURCE-OPENAI")return null;commitCalls++;source={...source,...clone(patch),version:(source.version||1)+1,updatedAt:new Date().toISOString()};return clone(source);}};
const ns={api:{},modules:{},__internal:internal,
 getExternalIntelligenceSource:id=>id==="SOURCE-OPENAI"?clone(source):null,
 getExternalIntelligenceSourceOperationContract:(sid,oid)=>sid==="SOURCE-OPENAI"&&oid==="INTERNAL_ANALYSIS"?clone(op):null,
 validateExternalIntelligenceSecretReference:input=>input&&input.secretReferenceId==="SECRET-OPENAI-LEGACY"?{ok:true,code:"EXTERNAL010_SECRET_REFERENCE_ACTIVE",data:{secretMetadata:{secretReferenceId:"SECRET-OPENAI-LEGACY",status:"ACTIVE"},secretValueReturned:false,paidAuthorityGranted:false,financialAuthorityGranted:false}}:{ok:false,code:"MISSING",data:{secretValueReturned:false}},
 getExternalIntelligenceSecretMetadata:id=>id==="SECRET-OPENAI-LEGACY"?{secretReferenceId:id,secretType:"BEARER_TOKEN",provider:"OPENAI",status:"ACTIVE"}:null,
 listExternalIntelligenceSecretMetadata:()=>[{secretReferenceId:"SECRET-OPENAI-LEGACY",secretType:"BEARER_TOKEN",provider:"OPENAI",status:"ACTIVE"}],
 getActiveExternalIntelligenceUsagePolicyForSource:id=>id==="SOURCE-OPENAI"?clone(policy):null,
 checkExternalIntelligenceUsagePolicy:input=>input.sourceId==="SOURCE-OPENAI"&&input.operation==="INTERNAL_ANALYSIS"?{ok:true,code:"EXTERNAL010_USAGE_POLICY_OPERATION_ALLOWED",data:{usagePolicyId:policy.usagePolicyId,allowed:true,right:clone(policy.rights.INTERNAL_ANALYSIS),policyCompleteness:"PARTIAL",legalAuthorityGranted:false}}:{ok:false,code:"BLOCKED"},
 getExternalIntelligenceResourceBudget:id=>id===budget.budgetId?clone(budget):null,
 listExternalIntelligenceResourceBudgets:()=>[clone(budget)],
 listExternalIntelligenceResourceUsageRecords:()=>clone(usageRecords),
 getExternalIntelligenceGatewayClientState:()=>clone(gateway),
 appendExternalIntelligenceAuditEvent:async()=>{auditCalls++;return {ok:true};}
};
const elements={externalOpenAISecretReference:{value:"SECRET-OPENAI-LEGACY"},externalOpenAIModel:{value:"gpt-5.6-luna"},externalOpenAIMaxOutput:{value:"100"},externalOpenAIPerRequestCap:{value:"0.01"},externalOpenAIBudget:{value:"BUDGET-OPENAI"},externalOpenAIBudgetSoftLimit:{value:"3"},externalOpenAIBudgetHardLimit:{value:"5"},externalOpenAIImpact:{textContent:""}};
const store=new Map();store.set("EXTERNAL010_OPENAI_UI_DRAFT_V1",JSON.stringify({model:"gpt-5.6-luna",maxOutputTokens:"100",perRequestHardCapUsd:"0.01",budgetId:"BUDGET-OPENAI",budgetCandidateId:"",budgetSoftLimitUsd:"3",budgetHardLimitUsd:"5",usagePolicyCandidateId:"",secretReferenceId:"SECRET-OPENAI-LEGACY"}));
const manifest={release:{version:"1.20.1"},authorityPolicy:{hardDeniedActions:["DIRECT_REPOSITORY_MUTATION","AUTOMATIC_KNOWLEDGE_PROMOTION","ACTIVATE_PAID_API","EXECUTE_TRADE"]},getModuleVersion:()=>"0.3.11"};
const context={window:null,globalThis:null,EXTERNAL010ExternalIntelligence:ns,EXTERNAL010VersionManifest:manifest,TextEncoder,document:{getElementById:id=>elements[id]||null,querySelector:()=>({open:false}),createElement:()=>({style:{},innerHTML:"",id:""}),body:{appendChild:()=>{}}},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v))},externalConsoleRefresh:()=>{},confirm:()=>true,setTimeout,clearTimeout,Date,console};context.window=context;context.globalThis=context;vm.createContext(context);
for(const f of ["17_external_intelligence_openai_provider_integration.js","17_external_intelligence_openai_provider_ui.js"]){vm.runInContext(fs.readFileSync(path.join(__dirname,f),"utf8"),context,{filename:f});}
(async()=>{
 const htmlBefore=ns.renderOpenAIProviderIntegrationPanelHtml();
 check("STEP 8 exposes review and Project Owner finalization controls",htmlBefore.includes("Final Validation内容を確認")&&htmlBefore.includes("Project OwnerとしてFinal Validation確定"),"controls-present");
 const beforeCommit=commitCalls,beforeAudit=auditCalls;
 const review=context.externalOpenAIReviewFinalValidation();
 check("Final Validation review is PASS and mutation/network free",review.ok===true&&review.code==="EXTERNAL010_OPENAI_FINAL_VALIDATION_REVIEW_READY"&&review.data&&review.data.failed===0&&review.data.total===12&&commitCalls===beforeCommit&&auditCalls===beforeAudit&&providerCalls===0,review);
 check("Final review validates ACTIVE Source and governed Local Gateway",review.data.checks.some(c=>c.name.includes("Source is ACTIVE")&&c.passed),review.data.checks);
 check("Final review validates Secret Reference without exposing value",review.data.checks.some(c=>c.name.includes("Secret Reference")&&c.passed&&c.detail&&c.detail.secretValueReturned===false),review.data.checks);
 check("Final review validates fixed POST /v1/responses and store=false",review.data.checks.some(c=>c.name.includes("Operation Contract")&&c.passed&&c.detail&&c.detail.store===false&&c.detail.retryMaxAttempts===1),review.data.checks);
 check("Final review validates Usage Policy without legal-authority escalation",review.data.checks.some(c=>c.name.includes("Usage Policy")&&c.passed&&c.detail&&c.detail.legalAuthorityGranted===false),review.data.checks);
 check("Final review validates Active USD Budget below hard limit",review.data.checks.some(c=>c.name.includes("USD Budgets")&&c.passed),review.data.checks);
 check("Final review validates Real API Test and reconciled usage",review.data.checks.some(c=>c.name.includes("Real API Test passed")&&c.passed)&&review.data.checks.some(c=>c.name.includes("Provider Usage")&&c.passed&&c.detail.actualTokens===16&&c.detail.actualCostUsd===0.0000082),review.data.checks);
 check("Final review validates Gateway Bridge READY",review.data.checks.some(c=>c.name.includes("Gateway runtime")&&c.passed&&c.detail.acquisitionBridgeEnabled===true),review.data.checks);
 check("Final review preserves critical Hard Denies",review.data.checks.some(c=>c.name.includes("Hard Denies")&&c.passed),review.data.checks);
 check("Final review explicitly has no provider call, authority expansion, repository mutation, or Validation=Approval",review.data.providerNetworkCallPerformed===false&&review.data.realApiRequestPerformed===false&&review.data.authorityExpansionPerformed===false&&review.data.directRepositoryMutationPerformed===false&&review.data.validationEqualsApproval===false,review.data);
 const untrusted=await context.externalOpenAIApproveFinalValidation({isTrusted:false});
 check("Programmatic/untrusted Final Validation is rejected",untrusted.ok===false&&untrusted.code==="EXTERNAL010_TRUSTED_PROJECT_OWNER_UI_INTERACTION_REQUIRED"&&commitCalls===beforeCommit,untrusted);
 const direct=await ns.finalizeOpenAIApiIntegrationWithProjectOwnerConfirmation({projectOwnerConfirmed:true,ownerInteractionTrusted:false,interactionEvidenceId:"TEST"});
 check("Integration gate independently requires trusted Project Owner interaction",direct.ok===false&&direct.code==="EXTERNAL010_OPENAI_FINAL_VALIDATION_PROJECT_OWNER_INTERACTION_REQUIRED"&&commitCalls===beforeCommit,direct);
 const result=await context.externalOpenAIApproveFinalValidation({isTrusted:true});
 check("Trusted Project Owner records FINAL_VALIDATED once",result.ok===true&&result.code==="EXTERNAL010_OPENAI_API_INTEGRATION_FINAL_VALIDATED"&&commitCalls===beforeCommit+1&&source.openAIFinalValidation&&source.openAIFinalValidation.passed===true&&source.openAIFinalValidation.state==="FINAL_VALIDATED",result);
 check("Final record marks OpenAI API Integration READY",source.openAIFinalValidation.readiness==="OPENAI_API_INTEGRATION_READY"&&result.data.nextRequiredAction==="OPENAI_API_INTEGRATION_READY",source.openAIFinalValidation);
 check("Finalization performs no new provider network call or paid request",result.data.providerNetworkCallPerformed===false&&result.data.realApiRequestPerformed===false&&providerCalls===0,result.data);
 check("Finalization does not expand authority, budget, or repository mutation",result.data.authorityExpansionPerformed===false&&result.data.directRepositoryMutationPerformed===false&&result.data.validationEqualsApproval===false&&source.openAIFinalValidation.automaticBudgetExpansionPerformed===false&&source.openAIFinalValidation.automaticRechargePerformed===false,result.data);
 check("Audit event is recorded for final validation",auditCalls===beforeAudit+1,auditCalls);
 const workflow=ns.getOpenAISetupWorkflowState();
 check("Stepper marks STEP 8 complete and reports Integration Ready",workflow.currentStep===8&&workflow.completed[8]===true&&workflow.finalValidationComplete===true&&workflow.nextAction==="OpenAI API Integration Ready",workflow);
 const htmlAfter=ns.renderOpenAIProviderIntegrationPanelHtml();
 check("UI shows STEP 8 complete and FINAL VALIDATED state",htmlAfter.includes("✅ STEP 8 · Final Validation · 完了")&&htmlAfter.includes("FINAL_VALIDATED")&&htmlAfter.includes("FINAL VALIDATED"),"step8-final");
 const second=ns.buildOpenAIFinalValidationReview();
 check("Repeated final review is idempotent",second.ok===true&&second.code==="EXTERNAL010_OPENAI_FINAL_VALIDATION_ALREADY_PASSED"&&commitCalls===beforeCommit+1,second);
 // fail-closed scenario after reset in a separate logical probe
 const saved=source.openAIFinalValidation; delete source.openAIFinalValidation; const savedGateway=clone(gateway); gateway={...gateway,acquisitionBridgeEnabled:false};
 const blocked=ns.buildOpenAIFinalValidationReview();
 check("Final Validation fails closed when Gateway Bridge is unavailable",blocked.ok===false&&blocked.code==="EXTERNAL010_OPENAI_FINAL_VALIDATION_REVIEW_BLOCKED"&&blocked.data.failed>0&&blocked.data.checks.some(c=>c.name.includes("Gateway runtime")&&!c.passed),blocked);
 gateway=savedGateway;source.openAIFinalValidation=saved;
 check("Generic ACTIVATE_PAID_API / EXECUTE_TRADE / Repository hard denies remain preserved",manifest.authorityPolicy.hardDeniedActions.includes("ACTIVATE_PAID_API")&&manifest.authorityPolicy.hardDeniedActions.includes("EXECUTE_TRADE")&&manifest.authorityPolicy.hardDeniedActions.includes("DIRECT_REPOSITORY_MUTATION"),manifest.authorityPolicy.hardDeniedActions);
 const failed=checks.filter(x=>!x.passed);const out={id:"OPENAI-API-INTEGRATION-FINAL-VALIDATION-GATE",candidateVersion:"0.3.11",decisionIds:["EXTERNAL-010-DECISION-055","EXTERNAL-010-DECISION-056"],passed:checks.length-failed.length,failed:failed.length,total:checks.length,health:Math.round((checks.length-failed.length)/checks.length*100),criticalFailed:failed.length,realProviderNetworkCallPerformed:false,checks};console.log(JSON.stringify(out,null,2));process.exitCode=failed.length?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
