@echo off
setlocal
set "EXTERNAL010_ALLOWED_ORIGINS=https://aturningpointinhistory.github.io,http://localhost:8000,http://127.0.0.1:8000"
set "EXTERNAL010_ACQUISITION_ALLOWED_HOSTS=127.0.0.1"
set "EXTERNAL010_ALLOW_HTTP_ACQUISITION=true"
set "EXTERNAL010_EVIDENCE_STORAGE_ROOT=%TEMP%\AI_Prompt_OS\EXTERNAL010\phase5_pc_runtime"
if not exist "%EXTERNAL010_EVIDENCE_STORAGE_ROOT%" mkdir "%EXTERNAL010_EVIDENCE_STORAGE_ROOT%"
start "EXTERNAL-010 Phase5 Fixture" cmd /k "set EXTERNAL010_ALLOWED_ORIGINS=%EXTERNAL010_ALLOWED_ORIGINS%&& set EXTERNAL010_ACQUISITION_ALLOWED_HOSTS=%EXTERNAL010_ACQUISITION_ALLOWED_HOSTS%&& set EXTERNAL010_ALLOW_HTTP_ACQUISITION=%EXTERNAL010_ALLOW_HTTP_ACQUISITION%&& node phase4_fixture.cjs"
start "EXTERNAL-010 Phase5 Gateway" cmd /k "set EXTERNAL010_ALLOWED_ORIGINS=%EXTERNAL010_ALLOWED_ORIGINS%&& set EXTERNAL010_ACQUISITION_ALLOWED_HOSTS=%EXTERNAL010_ACQUISITION_ALLOWED_HOSTS%&& set EXTERNAL010_ALLOW_HTTP_ACQUISITION=%EXTERNAL010_ALLOW_HTTP_ACQUISITION%&& set EXTERNAL010_EVIDENCE_STORAGE_ROOT=%EXTERNAL010_EVIDENCE_STORAGE_ROOT%&& node gateway.cjs"
echo Phase 05 PC runtime services started.
echo Fixture: http://127.0.0.1:43120
echo Gateway: http://127.0.0.1:43110
echo Evidence store: %EXTERNAL010_EVIDENCE_STORAGE_ROOT%
endlocal
