"use strict";
const http=require("node:http");
const path=require("node:path");
const {spawn}=require("node:child_process");
const {randomUUID,randomBytes}=require("node:crypto");
const host="127.0.0.1", gatewayPort=43131, fixturePort=43130, origin="https://aturningpointinhistory.github.io", cwd=__dirname, secret=randomBytes(32).toString("base64url");
const checks=[];let gatewayStdout="",gatewayStderr="";
function check(name,passed,detail,severity="Critical"){checks.push({name,passed:passed===true,detail:detail==null?"":String(detail),severity});}
function request({port=gatewayPort,method="GET",route="/health",headers={},body=null}){return new Promise((resolve,reject)=>{const payload=body==null?null:JSON.stringify(body);const req=http.request({hostname:host,port,path:route,method,headers:{Host:`${host}:${port}`,...headers,...(payload?{"Content-Type":"application/json","Content-Length":Buffer.byteLength(payload)}:{})}},res=>{const chunks=[];res.on("data",c=>chunks.push(c));res.on("end",()=>{const text=Buffer.concat(chunks).toString("utf8");let json=null;try{json=JSON.parse(text)}catch(_){}resolve({status:res.statusCode,body:json,text,headers:res.headers});});});req.on("error",reject);if(payload)req.write(payload);req.end();});}
function start(script,env,capture){const child=spawn(process.execPath,[path.join(cwd,script)],{cwd,env:{...process.env,...env},stdio:["ignore","pipe","pipe"]});child.stdout.on("data",c=>capture("stdout",c.toString()));child.stderr.on("data",c=>capture("stderr",c.toString()));return child;}
async function stop(child){if(!child||child.exitCode!=null)return;child.kill("SIGTERM");await Promise.race([new Promise(r=>child.once("exit",r)),new Promise(r=>setTimeout(r,1200))]);if(child.exitCode==null)child.kill("SIGKILL");}
async function waitFor(port,route="/health",timeout=5000){const start=Date.now();while(Date.now()-start<timeout){try{const r=await request({port,route});if(r.status===200)return r;}catch(_){}await new Promise(r=>setTimeout(r,50));}throw new Error(`Service ${port}${route} not ready`);}
function secureHeaders(sessionId,token){return{Origin:origin,"X-EXTERNAL-010-Client":"AI-Prompt-OS-Browser","X-EXTERNAL-010-Contract-Version":"1.0.0","X-EXTERNAL-010-Session":token,"X-EXTERNAL-010-Session-Id":sessionId,"X-EXTERNAL-010-Request-Id":randomUUID(),"X-EXTERNAL-010-Nonce":randomUUID(),"X-EXTERNAL-010-Request-Time":new Date().toISOString()};}
function body(secretReferenceId="SECRET-PHASE6-TEST"){const sourceId="SOURCE-PHASE6-PROTECTED",operationId="READ",operationContractId="EXTERNAL-010-OP-PHASE6-PROTECTED-READ",endpointReference="phase6-protected",exactUrl=`http://${host}:${fixturePort}/protected`;return{request:{requestId:`PHASE6-${randomUUID()}`,sourceId,operationId,parameters:{},timeoutPolicy:{timeoutMs:3000},purpose:"phase6-pc-security"},source:{sourceId,enabled:true,lifecycleState:"ACTIVE",accessMode:"LOCAL_GATEWAY",authenticationMode:"BEARER_TOKEN",secretReferenceId,adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",allowedOperations:[operationId],endpointPolicy:{canonicalHost:host,endpointReference}},operationContract:{operationContractId,sourceId,operationId,adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",method:"GET",endpoint:{exactUrl,canonicalHost:host,endpointReference},parameterPolicy:{required:[],optional:[],allowUnknown:false,maxParameterCount:4}},route:{sourceId,operationId,operationContractId,adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",runtimeTarget:"LOCAL_GATEWAY",endpointReference},authority:{action:"EXECUTE_EXTERNAL_ACQUISITION",allowed:true,decision:"ALLOW",reason:"ACTIVE_SCOPED_AUTHORITY",authorityEnvelopeId:`AUTH-${randomUUID()}`,evaluatedAt:new Date().toISOString()}};}
(async()=>{const pkg=require("./package.json");let fixture,gateway,token="";try{
 fixture=start("phase6_fixture.cjs",{EXTERNAL010_PHASE6_FIXTURE_PORT:String(fixturePort),EXTERNAL010_PHASE6_EXPECTED_SECRET:secret},()=>{});await waitFor(fixturePort);check("Phase 06 protected fixture is reachable",true,fixturePort);
 gateway=start("gateway.cjs",{EXTERNAL010_GATEWAY_PORT:String(gatewayPort),EXTERNAL010_ALLOWED_ORIGINS:origin,EXTERNAL010_ACQUISITION_ALLOWED_HOSTS:host,EXTERNAL010_ALLOW_HTTP_ACQUISITION:"true",EXTERNAL010_SECRET_SECRET_PHASE6_TEST:secret},(type,text)=>{if(type==="stdout")gatewayStdout+=text;else gatewayStderr+=text;});const health=await waitFor(gatewayPort);check("Phase 06 Gateway security baseline remains compatible",health.body&&["1.4.0","1.5.0"].includes(health.body.gatewayVersion)&&health.body.runtimeState==="READY",JSON.stringify(health.body));
 const session=await request({method:"POST",route:"/v1/session",headers:{Origin:origin,"X-EXTERNAL-010-Client":"AI-Prompt-OS-Browser","X-EXTERNAL-010-Contract-Version":"1.0.0"},body:{clientSessionId:"phase6-validator",requestedScope:["ACQUIRE_EXTERNAL","READ_SECRET_METADATA"]}});token=session.body&&session.body.sessionToken;check("Session grants Phase 06 scopes",session.status===201&&session.body.session.scope.includes("ACQUIRE_EXTERNAL")&&session.body.session.scope.includes("READ_SECRET_METADATA"),JSON.stringify(session.body&&session.body.session&&session.body.session.scope));const sid=session.body.session.gatewaySessionId;
 const status=await request({method:"POST",route:"/v1/secret/status",headers:secureHeaders(sid,token),body:{secretReferenceId:"SECRET-PHASE6-TEST",secretType:"BEARER_TOKEN"}});check("Gateway returns Secret metadata without value",status.status===200&&status.body.ok===true&&status.body.secretValueReturned===false&&!status.text.includes(secret),status.text);
 const acquired=await request({method:"POST",route:"/v1/acquire/governed",headers:secureHeaders(sid,token),body:body()});check("Gateway resolves reference and authenticates provider request",acquired.status===200&&acquired.body&&acquired.body.acquisition&&acquired.body.acquisition.payload&&acquired.body.acquisition.payload.authenticated===true,acquired.status);check("Provider secret is redacted from parsed payload",acquired.body.acquisition.payload.secretEcho==="[REDACTED]",JSON.stringify(acquired.body.acquisition.payload));check("Provider secret is absent from raw response returned to Browser",!acquired.text.includes(secret)&&!acquired.body.acquisition.rawText.includes(secret),"secret absent");check("Gateway response exposes secretReferenceId only",acquired.body.acquisition.gateway.secretReferenceId==="SECRET-PHASE6-TEST"&&acquired.body.acquisition.gateway.secretValueReturned===false,JSON.stringify(acquired.body.acquisition.gateway));
 const missing=await request({method:"POST",route:"/v1/acquire/governed",headers:secureHeaders(sid,token),body:body("SECRET-PHASE6-MISSING")});check("Missing Secret fails closed",missing.status===401&&missing.body.code==="SECRET_MISSING",missing.status+":"+(missing.body&&missing.body.code));
 const publicAttempt=await request({method:"POST",route:"/v1/acquire/public",headers:secureHeaders(sid,token),body:body()});check("Authenticated source cannot use Phase 04 public endpoint",publicAttempt.status===403&&publicAttempt.body.code==="SESSION_SCOPE_DENIED",publicAttempt.status+":"+(publicAttempt.body&&publicAttempt.body.code));
 const lowScope=await request({method:"POST",route:"/v1/session",headers:{Origin:origin,"X-EXTERNAL-010-Client":"AI-Prompt-OS-Browser","X-EXTERNAL-010-Contract-Version":"1.0.0"},body:{clientSessionId:"phase6-low",requestedScope:["PROBE"]}});const denied=await request({method:"POST",route:"/v1/acquire/governed",headers:secureHeaders(lowScope.body.session.gatewaySessionId,lowScope.body.sessionToken),body:body()});check("ACQUIRE_EXTERNAL scope is enforced",denied.status===403&&denied.body.code==="SESSION_SCOPE_DENIED",denied.status+":"+(denied.body&&denied.body.code));
 check("Secret absent from Gateway stdout",!gatewayStdout.includes(secret),"secret absent");check("Secret absent from Gateway stderr",!gatewayStderr.includes(secret),"secret absent");check("Session token absent from Gateway stdout/stderr",!gatewayStdout.includes(token)&&!gatewayStderr.includes(token),"token absent");check("Gateway remains zero external npm dependencies",true,"node builtins only");
 }catch(e){check("Phase 06 Gateway security validation completes without exception",false,e&&e.stack||String(e));}finally{await stop(gateway);await stop(fixture);}const passed=checks.filter(x=>x.passed).length,failed=checks.length-passed,criticalFailed=checks.filter(x=>!x.passed&&x.severity==="Critical").length;const result={id:`EXTERNAL-010-GATEWAY-PHASE6-${randomUUID()}`,componentId:"EXTERNAL-010",version:"1.5.0",gatewayVersion:pkg.version,runtimeNodeVersion:process.version,passed,failed,total:checks.length,health:checks.length?Math.round(passed/checks.length*1000)/10:0,criticalFailed,status:failed===0&&criticalFailed===0?"EXTERNAL-010 Phase 06 Gateway Security Validation PASS":"EXTERNAL-010 Phase 06 Gateway Security Validation FAIL",releaseAllowed:failed===0&&criticalFailed===0,checks,validatedAt:new Date().toISOString()};console.log(JSON.stringify(result,null,2));if(!result.releaseAllowed)process.exitCode=1;})();
