"use strict";

const http = require("node:http");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawn } = require("node:child_process");
const { createHash, randomUUID } = require("node:crypto");

const gatewayPort = 43128;
const fixturePort = 43127;
const host = "127.0.0.1";
const origin = "http://127.0.0.1:8000";
const cwd = __dirname;
const pkg = JSON.parse(fs.readFileSync(path.join(cwd,"package.json"),"utf8"));
const storageRoot = fs.mkdtempSync(path.join(os.tmpdir(), "external010-phase5-"));
const checks = [];
let gatewayStdout = ""; let gatewayStderr = ""; let fixtureStdout = ""; let fixtureStderr = "";

function check(name, passed, detail, severity = "Critical") { checks.push({ name, passed: passed === true, detail: detail == null ? "" : String(detail), severity }); }
function request({ port = gatewayPort, method = "GET", route = "/health", headers = {}, body = null }) {
  return new Promise((resolve, reject) => {
    const payload = body == null ? null : JSON.stringify(body);
    const req = http.request({ hostname: host, port, path: route, method, headers: { Host: `${host}:${port}`, ...headers, ...(payload ? { "Content-Type": "application/json", "Content-Length": Buffer.byteLength(payload) } : {}) } }, (res) => {
      const chunks=[]; res.on("data",c=>chunks.push(c)); res.on("end",()=>{ const text=Buffer.concat(chunks).toString("utf8"); let json=null; try{json=JSON.parse(text)}catch(_){} resolve({status:res.statusCode,headers:res.headers,body:json,text}); });
    });
    req.on("error",reject); if(payload) req.write(payload); req.end();
  });
}
function start(script, env, capture) { const child=spawn(process.execPath,[path.join(cwd,script)],{cwd,env:{...process.env,...env},stdio:["ignore","pipe","pipe"]}); child.stdout.on("data",c=>capture("stdout",c.toString())); child.stderr.on("data",c=>capture("stderr",c.toString())); return child; }
async function stop(child) { if(!child||child.exitCode!=null)return; child.kill("SIGTERM"); await Promise.race([new Promise(r=>child.once("exit",r)),new Promise(r=>setTimeout(r,1500))]); if(child.exitCode==null) child.kill("SIGKILL"); await new Promise(r=>setTimeout(r,100)); }
async function waitFor(port,route,timeout=6000){const startAt=Date.now();while(Date.now()-startAt<timeout){try{const r=await request({port,route});if(r.status===200)return r}catch(_){}await new Promise(r=>setTimeout(r,50));}throw new Error(`Service ${port}${route} not ready`)}
function sessionHeaders(sessionId, token, requestId = randomUUID(), nonce = randomUUID()) { return { Origin:origin,"X-EXTERNAL-010-Client":"AI-Prompt-OS-Browser","X-EXTERNAL-010-Contract-Version":"1.0.0","X-EXTERNAL-010-Session":token,"X-EXTERNAL-010-Session-Id":sessionId,"X-EXTERNAL-010-Request-Id":requestId,"X-EXTERNAL-010-Nonce":nonce,"X-EXTERNAL-010-Request-Time":new Date().toISOString() }; }
function upperId(prefix){return `${prefix}-${randomUUID().toUpperCase()}`}
function sha256(text){return createHash("sha256").update(String(text)).digest("hex")}
function acquisitionBody(exactUrl){const sourceId="SOURCE-PHASE5-PC-GATEWAY";const operationId="READ";const operationContractId="EXTERNAL-010-OP-PHASE5-PC-GATEWAY-READ";const endpointReference="phase5-pc-gateway-json";const url=new URL(exactUrl);return{request:{requestId:upperId("EXTERNAL-010-PC"),sourceId,operationId,parameters:{query:"phase5-persistence"},timeoutPolicy:{timeoutMs:3000},purpose:"phase5-pc-real-runtime"},source:{sourceId,enabled:true,lifecycleState:"ACTIVE",accessMode:"LOCAL_GATEWAY",authenticationMode:"NONE",adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",allowedOperations:[operationId],endpointPolicy:{canonicalHost:url.hostname,endpointReference}},operationContract:{operationContractId,sourceId,operationId,adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",method:"GET",endpoint:{exactUrl,canonicalHost:url.hostname,endpointReference},parameterPolicy:{required:[],optional:["query"],allowUnknown:false,maxParameterCount:8}},route:{routeId:upperId("EXTERNAL-010-ROUTE"),sourceId,sourceVersion:1,operationId,operationContractId,adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",adapterVersion:"1.0.0",accessMode:"LOCAL_GATEWAY",runtimeTarget:"LOCAL_GATEWAY",endpointReference},attempt:{attemptId:upperId("EXTERNAL-010-ATTEMPT")},authority:{action:"EXECUTE_EXTERNAL_ACQUISITION",allowed:true,decision:"ALLOW",reason:"ACTIVE_SCOPED_AUTHORITY",authorityEnvelopeId:upperId("AUTH"),evaluatedAt:new Date().toISOString()}}}
async function openSession(scopes){const r=await request({method:"POST",route:"/v1/session",headers:{Origin:origin,"X-EXTERNAL-010-Client":"AI-Prompt-OS-Browser","X-EXTERNAL-010-Contract-Version":"1.0.0"},body:{clientSessionId:"phase5-validator",requestedScope:scopes}}); if(r.status!==201) throw new Error(`SESSION_FAILED:${r.status}`); return {id:r.body.session.gatewaySessionId,token:r.body.sessionToken,scope:r.body.session.scope};}
function persistenceBody(acq,index){const rawText=String(acq.rawText||JSON.stringify(acq.payload));const hash=sha256(rawText);const now=acq.temporalMetadata&&acq.temporalMetadata.observedAt||new Date().toISOString();const evidenceId=upperId("EXTERNAL-010-EVIDENCE");const rawEvidenceId=upperId("EXTERNAL-010-RAW");const base={evidenceId,requestId:`PHASE5-PERSIST-${index}`,sourceId:"SOURCE-PHASE5-PC-GATEWAY",sourceVersion:1,operationId:"READ",adapterId:"EXTERNAL-010-ADAPTER-LOCAL-GATEWAY-001",adapterVersion:"1.0.0",accessMode:"LOCAL_GATEWAY",acquiredAt:now,publishedAt:null,status:"ACQUIRED",contentHash:hash,contentType:acq.contentType||"application/json",rawEvidenceId,attemptCount:1,correlationId:"PHASE5-PC",acquisitionPlanId:"PHASE5-PLAN",researchGoalId:"PHASE5-GOAL",responseId:upperId("RESPONSE"),attemptId:upperId("ATTEMPT"),routeId:upperId("ROUTE"),runtimeVersion:"1.4.0",gatewayVersion:pkg.version,schemaVersion:"1.0.0",recordVersion:1,createdAt:new Date().toISOString(),immutable:true};const recordHash=sha256(JSON.stringify(Object.keys(base).sort().reduce((o,k)=>(o[k]=base[k],o),{})));return{acquisitionEvidence:{...base,recordHash},rawEvidence:{rawEvidenceId,contentId:`EXTERNAL-010-CONTENT-SHA256-${hash}`,contentHash:hash,contentType:base.contentType,sizeBytes:Buffer.byteLength(rawText),rawDataReference:null,storageClass:"HOT",acquiredAt:now,publishedAt:null,sourceId:base.sourceId,requestId:base.requestId,acquisitionStatus:"ACQUIRED",schemaVersion:"1.0.0",createdAt:new Date().toISOString(),immutable:true},contentObject:{contentId:`EXTERNAL-010-CONTENT-SHA256-${hash}`,contentHash:hash,storageClass:"HOT",storageProvider:"UNPERSISTED",storageReference:null,sizeBytes:Buffer.byteLength(rawText),contentType:base.contentType,integrityState:"HASHED",createdAt:new Date().toISOString(),immutable:true},rawText,authority:{action:"PERSIST_EXTERNAL_EVIDENCE",allowed:true,decision:"ALLOW",reason:"ACTIVE_SCOPED_AUTHORITY",authorityEnvelopeId:upperId("AUTH-PERSIST"),evaluatedAt:new Date().toISOString()}}}

async function main(){let fixture;let gateway;let firstEvidenceId=null;let firstHash=null;try{
  check("Gateway package version is compatible with Phase 05 baseline",["1.3.0","1.4.0","1.5.0"].includes(pkg.version),pkg.version);check("Gateway remains zero external npm dependencies",Object.keys(pkg.dependencies||{}).length===0&&Object.keys(pkg.devDependencies||{}).length===0,JSON.stringify({dependencies:pkg.dependencies,devDependencies:pkg.devDependencies}));check("Node runtime provides built-in SQLite",(()=>{try{return typeof require("node:sqlite").DatabaseSync==="function"}catch(_){return false}})(),process.version);
  fixture=start("phase4_fixture.cjs",{EXTERNAL010_PHASE4_FIXTURE_PORT:String(fixturePort)},(t,x)=>{if(t==="stdout")fixtureStdout+=x;else fixtureStderr+=x}); await waitFor(fixturePort,"/health"); check("Real HTTP fixture is reachable",true,`http://${host}:${fixturePort}`);
  const gatewayEnv={EXTERNAL010_GATEWAY_PORT:String(gatewayPort),EXTERNAL010_ALLOWED_ORIGINS:origin,EXTERNAL010_ACQUISITION_ALLOWED_HOSTS:host,EXTERNAL010_ALLOW_HTTP_ACQUISITION:"true",EXTERNAL010_EVIDENCE_STORAGE_ROOT:storageRoot};
  gateway=start("gateway.cjs",gatewayEnv,(t,x)=>{if(t==="stdout")gatewayStdout+=x;else gatewayStderr+=x}); const health=await waitFor(gatewayPort,"/health"); check("Phase 05 Gateway runtime is READY",health.body&&["1.3.0","1.4.0","1.5.0"].includes(health.body.gatewayVersion)&&health.body.runtimeState==="READY",JSON.stringify(health.body));
  let session=await openSession(["ACQUIRE_PUBLIC","PERSIST_EVIDENCE","READ_EVIDENCE"]);check("Session scopes include acquisition/persist/read separately",["ACQUIRE_PUBLIC","PERSIST_EVIDENCE","READ_EVIDENCE"].every(x=>session.scope.includes(x)),JSON.stringify(session.scope));
  const acquired=await request({method:"POST",route:"/v1/acquire/public",headers:sessionHeaders(session.id,session.token),body:acquisitionBody(`http://${host}:${fixturePort}/gateway-json`)});check("Gateway acquires real HTTP content before persistence",acquired.status===200&&acquired.body&&acquired.body.acquisition&&typeof acquired.body.acquisition.rawText==="string",JSON.stringify(acquired.body&&acquired.body.acquisition&&{status:acquired.body.acquisition.status,responseSize:acquired.body.acquisition.responseSize}));
  const p1body=persistenceBody(acquired.body.acquisition,1);firstHash=p1body.acquisitionEvidence.contentHash;const p1=await request({method:"POST",route:"/v1/evidence/persist",headers:sessionHeaders(session.id,session.token),body:p1body});check("First Evidence persistence commits Content + Raw + Acquisition metadata",p1.status===201&&p1.body&&p1.body.persistence&&p1.body.persistence.contentCreated===true,JSON.stringify(p1.body));firstEvidenceId=p1.body.persistence.acquisitionEvidence.evidenceId;
  check("Raw content is stored by SHA-256 identity",p1.body.persistence.contentObject.contentHash===firstHash&&p1.body.persistence.contentObject.storageReference.includes(firstHash),JSON.stringify(p1.body.persistence.contentObject));
  check("SQLite is the metadata index",p1.body.persistence.metadataIndex==="SQLITE",p1.body.persistence.metadataIndex);
  check("Persistence grants no repository mutation or knowledge promotion",p1.body.persistence.canonicalRepositoryMutationPerformed===false&&p1.body.persistence.knowledgePromotionPerformed===false,JSON.stringify(p1.body.persistence));
  const p2body=persistenceBody(acquired.body.acquisition,2);const p2=await request({method:"POST",route:"/v1/evidence/persist",headers:sessionHeaders(session.id,session.token),body:p2body});check("Same content creates second Evidence identity",p2.status===201&&p2.body.persistence.acquisitionEvidence.evidenceId!==firstEvidenceId,p2.body&&p2.body.persistence&&p2.body.persistence.acquisitionEvidence.evidenceId);check("Same content is physically deduplicated",p2.body.persistence.contentCreated===false&&p2.body.persistence.physicalContentDeduplicated===true&&p2.body.persistence.contentObject.contentHash===firstHash,JSON.stringify(p2.body.persistence));
  const readAuthority={action:"READ_EXTERNAL_EVIDENCE",allowed:true,decision:"ALLOW",reason:"ACTIVE_SCOPED_AUTHORITY",authorityEnvelopeId:upperId("AUTH-READ"),evaluatedAt:new Date().toISOString()};const read1=await request({method:"POST",route:"/v1/evidence/read",headers:sessionHeaders(session.id,session.token),body:{evidenceId:firstEvidenceId,verifyHash:true,authority:readAuthority}});check("Evidence readback verifies stored content hash",read1.status===200&&read1.body.evidence.integrityState==="VERIFIED"&&read1.body.evidence.contentAvailable===true,JSON.stringify(read1.body));
  const cp={checkpointId:upperId("EXTERNAL-010-PROCESSING-CHECKPOINT"),contentHash:firstHash,processorId:"PHASE5-VALIDATOR",processorVersion:"1.0.0",parameterHash:"",processingState:"COMPLETED",resumeCursor:{item:1},supersedesCheckpointId:null,createdAt:new Date().toISOString(),immutable:true};const cpRes=await request({method:"POST",route:"/v1/evidence/checkpoint",headers:sessionHeaders(session.id,session.token),body:{checkpoint:cp,authority:{action:"PERSIST_EXTERNAL_PROCESSING_STATE",allowed:true,decision:"ALLOW",reason:"ACTIVE_SCOPED_AUTHORITY",authorityEnvelopeId:upperId("AUTH-CP"),evaluatedAt:new Date().toISOString()}}});check("Incremental processing checkpoint persists",cpRes.status===201&&cpRes.body&&cpRes.body.ok===true,JSON.stringify(cpRes.body));
  const scan=await request({method:"POST",route:"/v1/evidence/integrity",headers:sessionHeaders(session.id,session.token),body:{authority:readAuthority}});check("Integrity scan has no missing/corrupted content",scan.status===200&&scan.body.integrity.valid===true&&scan.body.integrity.missing.length===0&&scan.body.integrity.corrupted.length===0,JSON.stringify(scan.body));check("Integrity scan does not auto-delete orphans",scan.body.integrity.orphanAutomaticDeletionPerformed===false,JSON.stringify(scan.body.integrity));check("Physical content count is 1 while Evidence count is 2",scan.body.integrity.counts.contentObjectCount===1&&scan.body.integrity.counts.acquisitionEvidenceCount===2,JSON.stringify(scan.body.integrity.counts));
  const manifestDir=path.join(storageRoot,"evidence");check("Recovery-side Evidence manifests exist outside SQLite",fs.readdirSync(manifestDir).filter(x=>x.endsWith(".json")).length===2,fs.readdirSync(manifestDir).join(","));
  await stop(gateway);gateway=null;
  gateway=start("gateway.cjs",gatewayEnv,(t,x)=>{if(t==="stdout")gatewayStdout+=x;else gatewayStderr+=x});await waitFor(gatewayPort,"/health");session=await openSession(["READ_EVIDENCE"]);const reread=await request({method:"POST",route:"/v1/evidence/read",headers:sessionHeaders(session.id,session.token),body:{evidenceId:firstEvidenceId,verifyHash:true,authority:readAuthority}});check("Evidence survives Gateway restart and new session",reread.status===200&&reread.body.evidence.acquisitionEvidence.evidenceId===firstEvidenceId&&reread.body.evidence.integrityState==="VERIFIED",JSON.stringify(reread.body));
  check("Session token is absent from Gateway stdout/stderr",!gatewayStdout.includes(session.token)&&!gatewayStderr.includes(session.token),"token absent");
  check("SQLite database file exists after restart",fs.existsSync(path.join(storageRoot,"metadata.sqlite")),path.join(storageRoot,"metadata.sqlite"));
}catch(error){check("Phase 05 PC persistence validation completes without exception",false,error&&error.stack||String(error));}finally{await stop(gateway);await stop(fixture);try{fs.rmSync(storageRoot,{recursive:true,force:true})}catch(_){}}
  const passed=checks.filter(x=>x.passed).length;const failed=checks.length-passed;const criticalFailed=checks.filter(x=>!x.passed&&x.severity==="Critical").length;const result={id:upperId("EXTERNAL-010-GATEWAY-PHASE5-VALIDATION"),componentId:"EXTERNAL-010",version:"1.4.0",gatewayVersion:pkg.version,runtimeNodeVersion:process.version,passed,failed,total:checks.length,health:checks.length?Math.round((passed/checks.length)*1000)/10:0,criticalFailed,status:failed===0&&criticalFailed===0?"EXTERNAL-010 Phase 05 PC Persistence Validation PASS":"EXTERNAL-010 Phase 05 PC Persistence Validation FAIL",releaseAllowed:failed===0&&criticalFailed===0,phase5PersistenceComplete:failed===0&&criticalFailed===0,checks,validatedAt:new Date().toISOString()};console.log(JSON.stringify(result,null,2));process.exitCode=result.releaseAllowed?0:1;
}
main();
